### ISSUE TITLE
Broken image - not displayed in the topic

### ISSUE THREAD

**Issue by OfficeGSX** [MicrosoftDocs/OfficeDocs-Enterprise#1]
Topic below contains incorrect link to an image and this is not displayed in the topic properly. Please update the link to the image.

Topic: https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/sharepoint-server-2013-disaster-recovery-in-microsoft-azure.md

**Broken Image:**
![image](https://user-images.githubusercontent.com/16706698/35263798-7e924690-001a-11e8-8155-953df41e93fd.png)

Thanks,
Moravia

**Comment by denisebmsft** [comment]
I think this is now fixed.

**Comment by denisebmsft** [comment]
please let deniseb know if anything else is needed
