### ISSUE TITLE
Cannot open Word files in Desktop Word

### ISSUE THREAD

**Issue by sngoz** [MicrosoftDocs/OfficeDocs-Enterprise#103]
I cannot open Word files in desktop Word. 

When I select Edit in Word for a Word document, Desktop Word opens with the toolbar, and below the toolbar is a empty grey background, then in front of Desktop Word a small dialog box appears with the homepage of the site in it, then when I click on the x to close this dialog, nothing happens and I still see Desktop Word with the empty grey background.

The same thing happens with Excel files and desktop Excel. I have no issues with files in SharePoint Online, or on-premise without Azure AD authentication. OOS viewing and editing is fine, but staff not being able to use Excel/Word/PowerPoint to view and edit files is a major issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication#feedback)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by sngoz** [comment]
The PowerShell below from https://sharepoint.stackexchange.com/questions/228085/sharepoint-2016-with-fba-credential-prompts-when-opening-office-documents/231296#231296 has possibly fixed the issue. I will test more thoroughly in the next couple of days.

$sts = Get-SPSecurityTokenServiceConfig
$sts.SuppressModernAuthForOfficeClients = $True
$sts.update()
iisreset

What are the implications of setting SuppressModernAuthForOfficeClients to True, and also can this be set for at the web application level just for one web application?

**Comment by kaevans** [comment]
The Get-SPSecurityTokenServiceConfig setting is at the STS level, not at the web application level, so this is a farm-wide setting as there is only one STS per farm. The STS processes the incoming SOAP messages from trusted identity providers. You can have multiple zones for a web application where users accessing from one zone use federated auth claims (such as in this article with AAD) and users accessing from another zone use Windows claims. It is also possible for a single zone to serve both audiences.
