### ISSUE TITLE
Kind Reminder: Set-ExecutionPolicy Unrestricted before trying Connect-MsolService

### ISSUE THREAD

**Issue by zhouqinp** [MicrosoftDocs/OfficeDocs-Enterprise#104]
After I successfully installed MSOnline with Install-Module MSOnline command, I faced error when I try connecting MsolService. It reads 'The 'Connect-MsolService' command was found in the module 'MSOnline', but the module could not be loaded. For more information, run
'Import-Module MSOnline'.' Then I tried Import-Module MSOnline, but it also failed because 'Errors occurred while loading the format data file'.

Thanks to https://i.stack.imgur.com/0YgOT.png, I realized that I had't set the execution policy. Please kindly add this reminder: 'Use Set-ExecutionPolicy Unrestricted command before trying Connect-MsolService command'.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-gb/office365/enterprise/powershell/connect-to-office-365-powershell)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
I just tried this on a brand new virtual machine and I was able to install and execute Connect-MsolService without having to set the Execution policy (which was set to its default of RemoteSigned). Perhaps there is another reason why you got this error.
