### ISSUE TITLE
Instructions and link text for installing the .NET Framework 3.5 on desktops refer to Win8/8.1 but not Win10

### ISSUE THREAD

**Issue by scraping-infinity** [MicrosoftDocs/OfficeDocs-Enterprise#105]
The section here with instructions on installing .NET 3.5 for desktop systems calls out Windows 8 and 8.1, but makes no mention of Windows 10.  The title of the linked article is "Install the .NET Framework 3.5 on Windows 10, Windows 8.1, and Windows 8".  The title and link text used in this article should be updated to include Windows 10.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@scraping-infinity, The article now contains a link to the instructions for Windows 10. Thanks for letting us know.

**Comment by scraping-infinity** [comment]
Just for the record:  The added link is exactly the same as the link that's already there with the incorrect title and link text.

**Comment by JoeDavies-MSFT** [comment]
@scraping-infinity  This has been corrected. Sorry for the overlook. Thanks again for letting me know. :)
