### ISSUE TITLE
On down the road

### ISSUE THREAD

**Issue by ashunt677** [MicrosoftDocs/OfficeDocs-Enterprise#106]
I mostly got this tutorial working in my dev/test, could never get Azure to verify with my 365 tenant:
![image](https://user-images.githubusercontent.com/39784734/43040419-0706dfb0-8d09-11e8-80de-4c1261443eba.png)

Although the O365 --> GoDaddy domain integration was seamless:
![image](https://user-images.githubusercontent.com/39784734/43040453-df487956-8d09-11e8-9d38-a1faeeaace53.png)

This is an excerpt from the MS Press book I'm following, Exam Ref 70-346: Managing Office 365 identities and Requirements:
![image](https://user-images.githubusercontent.com/39784734/43040405-a32801fe-8d08-11e8-9c9d-e8c9d7d93fd6.png)
I didn't purchase a certificate, already had the domain

I hate to move on without the previous task completed 100% but time is not on my side, I have 12 days left until my 2 months of O365 trial run out, although I'm thinking of keeping 1/5 of the E5 accounts if I can. Since I don't plan on quitting my job, shunning my wife and eating meth for breakfast, I realistically have about 15 hours left of study time.

So my question is, what parts of the O365 dev/Test should I spend the remaining time going through before I'm out of E5's? I would appreciate any feedback, I realize this is an open ended question and depends on a lot of things. I already use ATP in production as well as eDiscovery and Cloud App Security including Phish Hunter, so I'm skipping those.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a0b3f11-8f84-f015-82db-5f0d049e1a76
* Version Independent ID: 949d1ec8-4335-4827-83d7-3f67bb9a26fa
* Content: [Federated identity for your Office 365 dev/test environment](https://docs.microsoft.com/en-us/office365/enterprise/federated-identity-for-your-office-365-dev-test-environment)
* Content Source: [Enterprise/federated-identity-for-your-office-365-dev-test-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/federated-identity-for-your-office-365-dev-test-environment.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@ashunt677 Sorry to hear about your problems completing this test lab configuration. This guide is in the process of being revised to include a synchronized domain name and a purchased third-party certificate for a better test experience. I will comment here when it is complete so perhaps you can try again with a new E5 trial subscription.
