### ISSUE TITLE
MSDN 

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Enterprise#110]
Why does MSDN not include Office 365 E5 and Dynamics 365?  The MSDN enterprise level subscription would be perfect for building this, but it only include E3 level.  Please make it E5 and add D365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 596c812b-a25a-e573-825b-debe0af35fd8
* Version Independent ID: 1669980c-0c80-ae7c-3bc3-6bfcc64fe924
* Content: [Cloud adoption Test Lab Guides (TLGs)](https://docs.microsoft.com/en-us/office365/enterprise/cloud-adoption-test-lab-guides-tlgs)
* Content Source: [Enterprise/cloud-adoption-test-lab-guides-tlgs.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/cloud-adoption-test-lab-guides-tlgs.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@danmyhre The best I can do is pass your request along to the folks who run the MSDN subscription program. You might also send your request through MSDN subscription support at https://www.visualstudio.com/subscriptions/support/. Thanks
