### ISSUE TITLE
Incorrect examples

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/OfficeDocs-Enterprise#111]
Ahem, can you folks please test your code examples before putting them in official documentation. The entire "Specific Office 365 services for users from all licensing plans" section doesn't make any sense. First, you are getting all the SKUs for the tenant, and not checking which individual SKUs a given user is assigned. Second, there is no single serviceplan that you can disable across "all licensing plans" - each of the different SKUs has different sets of plans, and specifying invalid values will break the whole script. For example, here's what will happen if I try to disable the "TEAMS1" service using the examples for that section.

Here's the license variable:
$O365Licences

ExtensionData AccountSkuId                                         DisabledServicePlans
------------- ------------                                         --------------------
              Microsoft.Online.Administration.AccountSkuIdentifier {TEAMS1}

Here's one of the SKUs that dont contain "TEAMS1":

$O365Licences.AccountSkuId

ExtensionData AccountName SkuPartNumber
------------- ----------- -------------
              michev      MCOPSTN2

Here's what happens when the Set-MsolUserLicense cmdlet runs with the incorrectly prepared variable (as there is no "TEAMS1" service in the MCOPSTN2 SKU:

Set-MsolUserLicense -UserPrincipalName shared@michev.info -LicenseOptions $O365Licences
Set-MsolUserLicense : Unable to assign this license because the license options are invalid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add5965d-008c-f030-45df-653ce3e9a1b3
* Version Independent ID: 6646ad46-d40d-fee3-5ca1-3272d3b3e4fb
* Content: [Disable access to services with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/disable-access-to-services-with-office-365-powershell)
* Content Source: [Enterprise/powershell/disable-access-to-services-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/disable-access-to-services-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@michevnew Looking into this now, Sorry for the inconvenience.

**Comment by JoeDavies-MSFT** [comment]
@michevnew You are correct. The section makes some big assumptions about each licensing plan being assigned to the user account(s) and that the service is supported by all of them. I have removed the offending section and added text to use the remaining procedures multiple times for multiple licensing plans. Sorry again for your inconvenience. Thanks for letting us know about this so we could correct it.
