### ISSUE TITLE
Script with filter by license ($acctSKU="<AccountSkuId>") isn't workin.

### ISSUE THREAD

**Issue by OlegKP** [MicrosoftDocs/OfficeDocs-Enterprise#112]
If user have enable additional license with pack, script is not apply. 
$acctSKU="&lt;AccountSkuId&gt;"
$AllLicensed = Get-MsolUser -All | Where {$_.isLicensed -eq $true -and $_.licenses[0].AccountSku.SkuPartNumber -eq ($acctSKU).Substring($acctSKU.IndexOf(":")+1, $acctSKU.Length-$acctSKU.IndexOf(":")-1)}
$AllLicensed | ForEach {Set-MsolUserLicense -UserPrincipalName $_.UserPrincipalName -LicenseOptions $LO}

If use $LO filter for one user, no issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add5965d-008c-f030-45df-653ce3e9a1b3
* Version Independent ID: 6646ad46-d40d-fee3-5ca1-3272d3b3e4fb
* Content: [Disable access to services with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/disable-access-to-services-with-office-365-powershell)
* Content Source: [Enterprise/powershell/disable-access-to-services-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/disable-access-to-services-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@OlegKP I have removed the section with the code block until it can be rewritten to support multiple licenses. Time frame is to be determined. Sorry for the inconvenience.

**Comment by Dottn** [comment]
The line to get all licensed users fails if a user has several licenses assigned, and the license with the relevant $acctSKU is not in $_.licenses[0].

This modification of worked for me.

$acctSKU="<AccountSkuId>"

$AllLicensed = Get-MsolUser -All | Where-Object {$_.isLicensed -eq $true} | Where-Object { foreach ($license in $_.licenses) {$license.AccountSku.SkuPartNumber -eq ($acctSKU).Substring($acctSKU.IndexOf(":")+1, $acctSKU.Length-$acctSKU.IndexOf(":")-1)}}

$AllLicensed | ForEach {Set-MsolUserLicense -UserPrincipalName $_.UserPrincipalName -LicenseOptions $LO}
