### ISSUE TITLE
Multiple Licenses Example

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Enterprise#114]
Please add an example of how you deal with users that have multiple licenses assigned.  It is possible that some services are included in multiple licenses.  For example, SharePoint online and Office Online is included in both ENTERPRISEPACK and DYN365_ENTERPRISE_PLAN1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f403603f-e17b-8b5b-cbd8-8e4c6f4e1728
* Version Independent ID: a93a3de1-25d3-4f7a-3e3e-3a6f25f88b75
* Content: [View account license and service details with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-account-license-and-service-details-with-office-365-powershell)
* Content Source: [Enterprise/powershell/view-account-license-and-service-details-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/view-account-license-and-service-details-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@danmyhre The article has been updated. See the last section and code block.
