### ISSUE TITLE
Examples Missing Array Index

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Enterprise#115]
Some of the examples are missing the array index on the "Licenses" property

Get-MsolUser | Where-Object {$_.isLicensed -eq $true -and $_.Licenses.ServiceStatus[4].ProvisioningStatus -eq "Disabled"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f403603f-e17b-8b5b-cbd8-8e4c6f4e1728
* Version Independent ID: a93a3de1-25d3-4f7a-3e3e-3a6f25f88b75
* Content: [View account license and service details with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-account-license-and-service-details-with-office-365-powershell)
* Content Source: [Enterprise/powershell/view-account-license-and-service-details-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/view-account-license-and-service-details-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@danmyhre The "long version" section with the incorrect examples has been removed. Thanks for letting us know.

**Comment by c016smith** [comment]
Oh, it looks like this is the same issue I just reported, I apologize. Still there's not a correction of how that should be. 
My query is the same as mentioned by @danmyhre but I'm using:
Get-MsolUser -All | where {$.isLicensed -eq $true -and $.Licenses[8].ServiceStatus[6].ProvisioningStatus -eq "Success"}

This is the result I get:
Cannot index into a null array.
At line:1 char:28
+ ... ll | where {$_.isLicensed -eq $true -and $_Licenses[8].ServicesStatus ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
