### ISSUE TITLE
Trial license from Microsoft.com to conduct pilot for EA customer

### ISSUE THREAD

**Issue by Vrolir** [MicrosoftDocs/OfficeDocs-Enterprise#117]
We are intrested in Office 365 E3 and would like to conduct a small Pilot.

Can we create a tenant via the Microsoft website for this purpose and if the pilot is succesfull link this tenant to our Enterprise Agreement and buy production licenses under that agreement?

I know we could ask our LSP to provision a Tenant for us, but  we would like to speed up the process.

So in a compact form; can we link a Office 365 Tenant created via the Microsoft website to a enterprise agreement?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdf56d0-5b7a-f0df-86c2-14ce1c067514
* Version Independent ID: 76a8737d-8f21-56ae-93f5-5d7942813484
* Content: [Subscriptions, licenses, accounts, and tenants for Microsoft's cloud offerings](https://docs.microsoft.com/en-us/office365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings)
* Content Source: [Enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Vrolir Please contact your local account team for this licensing question.
