### ISSUE TITLE
Does Azure AD for SharePoint Server Authentication work with Cloud Hybrid Search?

### ISSUE THREAD

**Issue by sngoz** [MicrosoftDocs/OfficeDocs-Enterprise#119]
Cloud Hybrid Search ( https://docs.microsoft.com/en-us/sharepoint/hybrid/configure-cloud-hybrid-searchroadmap ) is a great feature. Does Azure AD for SharePoint Server Authentication work with it? TY.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
@sngoz - As of right now, cloud hybrid search does not support SAML claims providers, it requires NTLM or Windows claims.

**Comment by sngoz** [comment]
@kaevans - Thank you.

Can SharePoint Online be crawled by an on-premise Search Service Application and search work with security trimming, when Azure AD for SharePoint Server Authentication is used?

Also are there plans to include support for SAML claims providers in cloud hybrid search in the roadmap?

**Comment by kaevans** [comment]
No it cannot be used to search and provide security trimming out of box. You could look into on-premises search extensibility to see if this can be built. 

To provide feedback on this scenario, post to Uservoice. https://office365.uservoice.com/
