### ISSUE TITLE
Step 7 double check

### ISSUE THREAD

**Issue by stevep4** [MicrosoftDocs/OfficeDocs-Enterprise#12]
Hi... I just wanted to check... on step 7 I see a different Azure AD page when I click Sign in, but maybe that's company branding... I get a login.microsoftonline.com page (yours seems to be a personalised domain), but it all seems to work fine. However, in the last screenshot you get a nice email address at the top right, I get a federated type username displayed, which is a bit yuck. Did I do something wrong?

Also... is it possible to bring group info through as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication | Microsoft Docs](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
@stevep4 yes, the difference is that the image shown is a federated domain using ADFS. Your experience may differ depending whether you are using a federated domain or a synchronized domain. It also varies based on your company branding settings in AAD and if you have enabled the Keep Me Signed In (KMSI) feature in your company branding settings in AAD.

Group info (role claims) is out of scope for this article. The Azure AD token will not include role claims for the user, you would need to create a custom role provider that does lookups to Graph. See the end of the article for a sample custom claims provider that provides similar functionality.

**Comment by balajimadgundi** [comment]
Getting error on step #6, 3rd line saying Get-PoliciesAssignedToServicePrincipal is not recognized as command name or script etc. "$saml2policyid = Get-PoliciesAssignedToServicePrincipal -servicePrincipalId $objectid | ?{$_.displayName -EQ "TokenIssuancePolicy"} | select objectId"

**Comment by kaevans** [comment]
@balajimadgundi please make sure you have followed the directions to download and execute the Initialize.ps1 and MSGraphTokenLifetimePolicy.psm1 files. 

> This article refers to code samples for interacting with Azure Active Directory Graph. You can download the code samples [here](https://github.com/kaevans/spsaml11/tree/master/scripts).

**Comment by guptas-abhishek** [comment]
Hi Kaevans.....  Unfortunately I am also stuck here ... Went through the steps but the command  on row number 3 
$saml2policyid = Get-PoliciesAssignedToServicePrincipal -servicePrincipalId $objectid | ?{$_.displayName -EQ "TokenIssuancePolicy"} | select objectId
gives the below error

"Get-PoliciesAssignedToServicePrincipal : The term
'Get-PoliciesAssignedToServicePrincipal' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:18
+ $saml2policyid = Get-PoliciesAssignedToServicePrincipal -servicePrincipalId
$obj ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-PoliciesAssignedToServicePr
   incipal:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException"

Any idea on this please?

**Comment by guptas-abhishek** [comment]
Just to add,  I tried looking on the initialize.ps1 which contains a command for importing ActiveDirectoryAuthenticationLibrary

"Import-ActiveDirectoryAuthenticationLibrary"
When  I run initialize.ps1, it doesn't throws any errors but if  I try to run the above command separately, it gives following error.
Import-ActiveDirectoryAuthenticationLibrary : The term
'Import-ActiveDirectoryAuthenticationLibrary' is not recognized as the name of
a cmdlet, function, script file, or operable program. Check the spelling of
the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ Import-ActiveDirectoryAuthenticationLibrary
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Import-ActiveDi...ticationLibra
   ry:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException 

probably both can be somehow linked.. ???

**Comment by stevep4** [comment]
@guptas-abhishek... did you run Import-Module (path)\MSGraphTokenLifetimePolicy.psm1 first? Import-ActiveDirectoryAuthenticationLibrary won't work until you have.

**Comment by kaevans** [comment]
You must run:

`Import-Module <file path of Initialize.ps1>`

This is shown in the PowerShell example. Running that import-module step will, in turn, load the dependent module.

**Comment by balajimadgundi** [comment]
@kaevans - I did run Import-Module <file path of Initialize.ps1> but it is not loading the dependent module(MSGraphTokenLifetimePolicy.psm1) hence people are getting errors.

After I explicitly ran the Import-Module <file path of MSGraphTokenLifetimePolicy.psm1>,  the whole script block executed withour errors.

**Comment by denisebmsft** [comment]
Thanks to Kirk Evans for his diligent monitoring and response to incoming questions and comments.

**Comment by guptas-abhishek** [comment]
any idea /suggestions on my issue please?

**Comment by kaevans** [comment]
Original issue was @stevep4 and this should be closed. If there are additional issues, please open a new issue so that it can be tracked separately.

**Comment by guptas-abhishek** [comment]
Sure, Have raised my issue seperately...
