### ISSUE TITLE
Recent page changes appear to have hidden the references to IE

### ISSUE THREAD

**Issue by mzappy** [MicrosoftDocs/OfficeDocs-Enterprise#121]
It appears this page format was updated recently (today?), which removed significant, descriptive text.

One such area was the specific notations regarding the need to add certain URL's into the IE Trusted Sites settings for our user's workstation browsers.

Getting requests for supportive documentation and would greatly appreciate such information being made available again

**Comment by denisebmsft** [comment]
@mzappy can you clarify which article(s) don't have the descriptive text you're looking for?

**Comment by mzappy** [comment]
https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2

Thank you, Denise for your time and assist with this request.

Mike Zappacosta
Microsoft Cloud Platform Engineer
Exelon IT Cloud & Infrastructure

**Comment by JoeDavies-MSFT** [comment]
@mzappy You can find this information in a new article here: https://docs.microsoft.com/office365/enterprise/additional-office365-ip-addresses-and-urls
