### ISSUE TITLE
Office 2010

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Enterprise#122]
Looks like the Office 2010 apps such as word and excel have been updated to support modern auth for SharePoint Online.  Can you add the details to this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059ed9a7-ea75-0fa3-e246-4ad1f1b0c5bc
* Version Independent ID: d7598f96-3158-09ee-024a-6175599718cd
* Content: [How modern authentication works for Office 2013 and Office 2016 client apps](https://docs.microsoft.com/en-us/office365/enterprise/modern-auth-for-office-2013-and-2016?redirectSourcePath=%252fen-us%252farticle%252fHow-modern-authentication-works-for-Office-2013-and-Office-2016-client-apps-e4c45989-4b1a-462e-a81b-2a13191cf517)
* Content Source: [Enterprise/modern-auth-for-office-2013-and-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/modern-auth-for-office-2013-and-2016.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by denisebmsft** [comment]
@danmyhre, thank you for the feedback.  We're looking into this.

**Comment by AndreaBarr** [comment]
@danmyhre Thank you for this feedback

I am getting this over to the Enterprise team for investigation and update.

I was able to get this into the backlog for the Enterprise team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by denisebmsft** [comment]
@danmyhre thank you for the feedback, and @AndreaBarr thank you for your help. Turns out Office 2010 is not currently supported with Office 365, including SharePoint Online, so for now, we aren't going to add that.
