### ISSUE TITLE
aVP Global Strategic Alliances

### ISSUE THREAD

**Issue by ErinRomeo** [MicrosoftDocs/OfficeDocs-Enterprise#123]
Can we see an example of the content needed in the "web link to the solution that you are looking to qualify in this program"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e449ab57-b1c0-6ca5-7e77-a587eb7390a9
* Version Independent ID: 53932091-b65c-c7d8-1927-97afa11d1cf6
* Content: [Office 365 Networking Partner Program](https://docs.microsoft.com/en-us/office365/enterprise/office-365-networking-partner-program)
* Content Source: [Enterprise/office-365-networking-partner-program.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-networking-partner-program.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
This field is referring to a URL that points to a product or solution that you are trying to certify, such as the URL to a product page of a firewall, proxy server, or other type of network edge device.
