### ISSUE TITLE
Use of nested AD groups

### ISSUE THREAD

**Issue by bernardlam** [MicrosoftDocs/OfficeDocs-Enterprise#124]
I was under the impression that deeply nested AD/AAD groups may cause unexpected behaviour in permissioning. may want to call this out in the doc and provide more specific guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1364a35f-148d-20e2-620e-1999290c74c8
* Version Independent ID: 2b1ce492-f795-20fc-9b49-1960b4e95baf
* Content: [Design an isolated SharePoint Online team site](https://docs.microsoft.com/en-us/office365/enterprise/design-an-isolated-sharepoint-online-team-site)
* Content Source: [Enterprise/design-an-isolated-sharepoint-online-team-site.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/design-an-isolated-sharepoint-online-team-site.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@bernardlam I am investigating. Thanks.

**Comment by JoeDavies-MSFT** [comment]
@bernardlam Using Azure AD groups as members of SharePoint groups in the manner described in this article works fine. There are no Microsoft support issues related to this. Thanks.

**Comment by bernardlam** [comment]
Hi Joe, I realize it's supported but not necessarily recommended.  I dug up some old notes and found this verbiage:

- we do not recommend the following items when you manage AD DS groups […] Adding security groups that contain nested security groups, contacts, or distribution lists.

- security groups that have deep nested structure might break SharePoint sites

source: https://docs.microsoft.com/en-us/sharepoint/sites/overview-of-security-groups-in-sharepoint-server

**Comment by JoeDavies-MSFT** [comment]
@bernardlam Your link refers to a best practice for Active Directory Domain Services (AD DS) and SharePoint 2016. The article is for Azure AD and SharePoint Online, with only one level of nesting.

**Comment by bernardlam** [comment]
HI Joe, it was also my understanding that one level of nesting is OK. Would it make sense to be more explicit in the article to say we're only recommending one level of nesting (or state that we don't recommend deep nesting)?

**Comment by JoeDavies-MSFT** [comment]
@bernardlam Based on my internal Microsoft research, there are no issues with nesting groups beyond a single level of nesting for Azure AD groups and SharePoint Online. A statement recommending against its use would not be appropriate.
