### ISSUE TITLE
Information about user profile synchronisation mechanism

### ISSUE THREAD

**Issue by Codefearingguy** [MicrosoftDocs/OfficeDocs-Enterprise#126]
Will the OOTB user profile sync mechanism work here? Or should we implement custom profile sync mechanism. Please add some information regarding the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
See https://blogs.msdn.microsoft.com/kaevans/2013/05/23/sharepoint-2013-user-profile-sync-for-claims-users/.
