### ISSUE TITLE
Step 5: Set the permissions for a lot of users

### ISSUE THREAD

**Issue by brianmaurer** [MicrosoftDocs/OfficeDocs-Enterprise#13]
Is it possible to give permissions to Azure AD groups rather than users? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication | Microsoft Docs](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
Not by default. Role claims are not part of the SAML post. This would likely require a custom claims provider, which is out of scope for this article. A new pull request has been added that provides additional information on a custom claims provider (https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/15). 

Recommend to close.
