### ISSUE TITLE
Intune Endpoints are missing from api

### ISSUE THREAD

**Issue by chwilfing** [MicrosoftDocs/OfficeDocs-Enterprise#135]
The intune list is not part of this full list. - intune list is https://docs.microsoft.com/en-us/intune/network-bandwidth-use 
As far as i see - also api does not return the list of intune IP Addresses.

BG Christoph

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
@chwilfing thank you for the feedback! We're looking into this.

**Comment by AndreaBarr** [comment]
@chwilfing Thank you for this feedback. 

I am getting this Intune list issue over to the Enterprise team so we can get this addressed and updated. 

I was able to get this into the backlog for the Enterprise team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@chwilfing Yes, you are correct. This list does not at this time include the Intune endpoints. It it primarily for Office 365.

**Comment by chwilfing** [comment]
Does that mean it will not be part of the api?

Is there a way to get that information from an api? are there any changes?

**Comment by triplanedave** [comment]
I haven't seen that Intune IP's are programmatically available via API.  But, the O365 IP's are documented on https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges
Or you can use the web service to stay up to date - https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service.  I'll keep looking for the Intune IP's and see if we have that info available too.

**Comment by triplanedave** [comment]
https://docs.microsoft.com/en-us/intune/network-bandwidth-use

**Comment by JoeDavies-MSFT** [comment]
@chwilfing Inclusion of Intune endpoints into the Web Services at this time is TBD. I will comment here when more details become available.
