### ISSUE TITLE
Bug in Session Timeouts

### ISSUE THREAD

**Issue by robertpauljensen** [MicrosoftDocs/OfficeDocs-Enterprise#137]
If I login and start reading a document for even just 1m I get forced to log out with a notice saying the session timed out. This happens on every computer I use. It makes 365 unusable for me since I need longer than 60 secs to read and respond to documents. This could be because I am logged in to an older session. If this is the case it should session me out sooner and not wait until after I read the document. I believe this is a bad coding decision that is meant to make things easier but actually makes things more annoying. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1570de51-50b1-d4cc-c1c7-832b3242ccb3
* Version Independent ID: f5250f91-0a48-20cf-8e2c-e2dc347edd88
* Content: [Session timeouts for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/session-timeouts)
* Content Source: [Enterprise/session-timeouts.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/session-timeouts.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by denisebmsft** [comment]
@robertpauljensen, thank you for the feedback. Have you reached out to your organization's Office 365 Admin to see what's going on?

**Comment by AndreaBarr** [comment]
@robertpauljensen Thank you for the feedback.

I want to make sure this forced logout issue is addressed ASAP for you. Support will be able to take this issue to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
