### ISSUE TITLE
Need PowerShell command reference

### ISSUE THREAD

**Issue by dialedin2014** [MicrosoftDocs/OfficeDocs-Enterprise#138]
Please provide a link to documentation for all the PowerShell commands used to manage Skype for Business Online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f318af5-7da8-daec-d038-7bca3d4cabf8
* Version Independent ID: 7cb9bf9d-5b01-7cbd-fa54-cb9847b61fc2
* Content: [Manage Skype for Business Online with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell)
* Content Source: [Enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
@dialedin2014 thank you for the feedback. Link added.
