### ISSUE TITLE
Pros とConsがProと詐欺となっています。

### ISSUE THREAD

**Issue by sasukeh** [MicrosoftDocs/OfficeDocs-Enterprise#139]
[フィードバックをこちらに入力してください]
ProsとConsは日本語でメリットとデメリットという訳になるかと思いますが、
現状このドキュメントでは、Proと詐欺という正しくない訳になっております。
修正をしていただけないでしょうか？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7249c9c4-ab9c-c731-aeb0-6065965f518a
* Version Independent ID: 804199c9-6487-5fdb-f5e8-aaab252c4704
* Content: [SharePoint Server 2007 のサポート終了ロードマップ](https://docs.microsoft.com/ja-jp/office365/enterprise/sharepoint-2007-end-of-support)
* Content Source: [Enterprise/sharepoint-2007-end-of-support.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/sharepoint-2007-end-of-support.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
Per Bing Translator, the feedback is this:

I think that pros and cons will be a translation of merit and disadvantage in Japanese,
In this document, pro and fraud are not correct. Could you please fix it?

We will definitely look into this. Thank you @sasukeh for the feedback.

我々は間違いなくこれに見ていきます。ご意見 @sasukeh ありがとうございます。

**Comment by denisebmsft** [comment]
@sasukeh we are working on this. It should be fixed soon.


我々はこれに取り組んでいます。それはすぐに修正する必要があります。

**Comment by denisebmsft** [comment]
@sasukeh the updated content is live now. 

更新されたコンテンツは現在ライブです。他にご不明な点がございましたらお知らせください。再度のご意見ありがとうございます!
