### ISSUE TITLE
Access denied on Site Collection

### ISSUE THREAD

**Issue by michelef71** [MicrosoftDocs/OfficeDocs-Enterprise#14]
hi , I'm trying to configure SharePoint 2013, I have added the Azure AD Auth provider and I'm able to add the Azure guest users from the people picker , but when I try to browse in the site collection i receive "this site hasn't been shared with you".
using "Check permissions" I can see that the guest user is allowed to enter on the site collection.
What can i Check?
Thank you
Michele

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication | Microsoft Docs](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
Ensure that you are choosing the "Name" claim and providing the value exactly as it appears. I have added a new pull request that adds information about a custom claims provider (https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/15).

**Comment by denisebmsft** [comment]
Thanks, Kirk, for the help. And thank you, Michelef71, for the feedback!
