### ISSUE TITLE
Missing mapping for group

### ISSUE THREAD

**Issue by shahartamari** [MicrosoftDocs/OfficeDocs-Enterprise#140]
The PowerShell script to add TrustedIdenityTokenIssuer is missing the id claim for Group.  The result will be that as-is, groups will not be visible in the people picker.  To fix this you need to add
`$map1 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" -IncomingClaimTypeDisplayName "Group" -SameAsIncoming`

and change the last line of the script to reference the additional mapping
`$ap = New-SPTrustedIdentityTokenIssuer -Name "AzureAD" -Description "SharePoint secured by Azure AD" -realm $realm -ImportTrustCertificate $cert -ClaimsMappings $map,$map1,$map2,$map3 -SignInUrl $wsfedurl -IdentifierClaim "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name" `

**Comment by denisebmsft** [comment]
@shahartamari does your feedback pertain to this article: https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication?

**Comment by shahartamari** [comment]
Yes

Shahar Tamari

**Comment by kaevans** [comment]
Duplicate issue. See #109
