### ISSUE TITLE
typo in SharePoint Online link in the left nav

### ISSUE THREAD

**Issue by dplotnikov** [MicrosoftDocs/OfficeDocs-Enterprise#141]
now you have https://docs.microsoft.com/en-us/sharepoint/sharepoint-online.md but it should be https://docs.microsoft.com/en-us/sharepoint/sharepoint-online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf76353d-e095-c8a4-cf9e-4bafee7b688c
* Version Independent ID: 52df9c4a-3a3d-2305-bf00-5184d940bcd3
* Content: [Deployment planning checklist for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/deployment-planning-checklist)
* Content Source: [Enterprise/deployment-planning-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/deployment-planning-checklist.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by denisebmsft** [comment]
Thank you @dplotnikov for the feedback. We've fixed the link.
