### ISSUE TITLE
Issue in getting the Signin Page after Step 6

### ISSUE THREAD

**Issue by guptas-abhishek** [MicrosoftDocs/OfficeDocs-Enterprise#142]
Hi ,  I had followed your guidelines and have successfully changed the authentication mechanism from ACS to Azure AD in few environments in the past, but recently in one of the environment  I am facing the problems.

After creating the TrustedIdentifier Token and executing the scripts of enabling SAML 1.1 to my Enterprise application,  when  I try to browse the site,  i am not getting the landing page rather getting a blank screen. In ULS logs,  I can see that IsAuthenticated comes as false
Have tried to delete the Enterprise application and also recreating the TruststedIdentifier Token but no luck.

As part of investigation, when  I tried to test my SAML from enterprise application itself, it worked fine but not having any clue now as in what might be stopping this.

Any suggestions please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by guptas-abhishek** [comment]
The Page when tried to browse comes with the following URL -- https://*******.com/_trust/?ReturnUrl=%2f_layouts%2f15%2fAuthenticate.aspx%3fSource%3d%252F&Source=%2F

**Comment by denisebmsft** [comment]
@guptas-abhishek thank you for the feedback. We're looking into this.
