### ISSUE TITLE
Hybrid Search does not support SAML based authentication

### ISSUE THREAD

**Issue by AussieDavo** [MicrosoftDocs/OfficeDocs-Enterprise#144]
There is a limitation in Hybrid Search where any objects with SAML based permissions submitted to SharePoint Online Search index are security trimmed. 

This causes these SharePoint objects to be unsearchable when authenticating with AzureAD.

Reference (Hybrid Search supports Windows Claims only): https://blogs.msdn.microsoft.com/spses/2016/07/19/sharepoint-2016-hybrid-search-stuff-you-should-know-about-cloud-ssa/ 

Please vote to to make this a priority for the Microsoft product development team: https://sharepoint.uservoice.com/forums/282887-sharepoint-hybrid-or-migration-to-office365/suggestions/20037220-support-hybrid-search-on-premise-with-a-saml-authe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
@AussieDavo thank you for the feedback on the product. As you noted, the correct place for that feedback is via UserVoice.
