### ISSUE TITLE
URL "*.o365weve.com" is missing from the XML list "https://support.content.office.net/en-us/static/O365IPAddresses.xml"

### ISSUE THREAD

**Issue by d-kovacevic** [MicrosoftDocs/OfficeDocs-Enterprise#151]
Hello Team,

Based on the article "Office 365 URLs and IP address ranges" (URL is bellow) URL "*.o365weve.com" should be included in the Office365 XML list "https://support.content.office.net/en-us/static/O365IPAddresses.xml" but currently is missing.

https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252fen-us%252farticle%252foffice-365-urls-and-ip-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2

Could you please help us with this.

Thanks,
Dusan Kovacevic

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252fen-us%252farticle%252foffice-365-urls-and-ip-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by AndreaBarr** [comment]
@d-kovacevic Thank you for this feedback

I agree it should be in that list. 

I was able to get this into the backlog for the Enterprise team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@d-kovacevic As of 10/2, the XML files are no longer being maintained and do not reflect the changes for the October update. Please use the JSON formatted list going forward, which now includes o365weve.com.
