### ISSUE TITLE
Broken link on left hand navigation - Choose between MDM and Intune

### ISSUE THREAD

**Issue by markaldridge** [MicrosoftDocs/OfficeDocs-Enterprise#152]
The link to Choose between MDM and Intune directs to an incorrect URL.
Currently it links to https://docs.microsoft.com/en-us/SecurityCompliance/choose-between-mdm-and-intune.md
I assume it's meant to link to this page.
https://docs.microsoft.com/en-us/office365/securitycompliance/choose-between-mdm-and-intune

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdf56d0-5b7a-f0df-86c2-14ce1c067514
* Version Independent ID: 76a8737d-8f21-56ae-93f5-5d7942813484
* Content: [Subscriptions, licenses, accounts, and tenants for Microsoft's cloud offerings](https://docs.microsoft.com/en-us/office365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings)
* Content Source: [Enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
@markaldridge and @AndreaBarr I believe this is fixed. Thank you so much for your feedback and help.
