### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by TomAafloen** [MicrosoftDocs/OfficeDocs-Enterprise#156]
The link "Implementing password hash synchronization with Azure AD Connect sync" points to "https://docs.microsoft.com/en-us/azure/active-directory/active-directory-aadconnectsync-implement-password-synchronization", which gives a "404 - Page not found" error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 093db571-11e5-adc8-8826-3485e79ccbec
* Version Independent ID: 0c7bd2ea-f4cf-bd2a-56ef-d5f57786c5be
* Content: [Fixing problems with directory synchronization for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/fix-problems-with-directory-synchronization?redirectSourcePath=%252farticle%252fFixing-problems-with-directory-synchronization-for-Office-365-79c43023-5a47-45ae-8068-d8a26eee6bc2)
* Content Source: [Enterprise/fix-problems-with-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/fix-problems-with-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by AndreaBarr** [comment]
@TomAafloen Thank you for this feedback

I will make sure this link get fixed. 

I was able to get this into the backlog for the Enterprise team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by robmazz** [comment]
This link has been updated and fixed - thanks for reporting.
