### ISSUE TITLE
Multiple Providers on web app

### ISSUE THREAD

**Issue by sav169** [MicrosoftDocs/OfficeDocs-Enterprise#157]
I have a question. I want to use Azure AD as an authentication provider along with Windows Claims (NTLM) and with Forms authentication on the same web application for the following reasons
1) Windows NTLM auth (For Crawling purpose)
2) Forms authentication (Existing forms external users)
3) Azure AD auth provider (For authenticating with Azure AD which allows us to use MFA)
Is it possible to have the above working ? Currently we use NTLM and Forms with a custom login page. In the article above in step 4, I need to replace my custom login page with "/_trust/".
I have been able to successfully configure Azure AD provider on my Dev following above steps but I cant seem to use forms. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by AndreaBarr** [comment]
@sav169 Thank you for this feedback

I want to make sure you get this addressed promptly. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by sav169** [comment]
I opened a ticket with O365 support but they closed it saying its a on-prem issue.
The question that I would like to be addressed is step 4 in this article. For the sign-in page, can we use it with a custom login page ? as the article says we have to use "/_trust/".
If we have to use forms authentication also, then we cannot put "/_trust/"

**Comment by AndreaBarr** [comment]
@sav169 I don't have an answer for you so let me get this over the Enterprise team so we can get the appropriate answers. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by sav169** [comment]
Thanks for taking this to the Enterprise team. I would eagerly wait to hear back on this.

**Comment by MSFTTracyP** [comment]
@sav169 Starting from the top, this is a single web-app with FBA configured in the web.config, yes? Also, please tell me what are your Zone URLs for SharePoint Server? It also seems like if you use NTLM + the trusted Azure AD IdP without using FBA, this works, correct? When you add back, Forms-Based Authentication, then any use of any Zone URL results in the pop of the FBA prompt for credentials, yes or no? I know it seems roundabout, but please answer all my questions in a reply.

I also would like to apologize for what happened to you with support (that you weren't routed somewhere else for a ticket). I'm currently looking into why that happened. Please keep in touch, and let's see if this is a quick question the documentation can give you a definitive answer on, or, if you need a Support Engineer, how to get you to the right place. 

Thank you for your patience!

**Comment by MSFTTracyP** [comment]
@sav69, So there are some configuration problems here. Firstly, you're trying to use one zone (think of this as an authentication method boundary) for all these different things. It would be far more consistent to use a zone per authentication method. For example, NTLM and crawl on Default Zone, FBA on the Intranet Zone, et cetera. This is a detailed configuration, so I'm going to direct you to SharePoint Server Support (rather than online). This is a 'callback' model, so there are a couple of hoops (apologies for that) but starting out, you need to go here: 
![image](https://user-images.githubusercontent.com/33558605/51212318-0f907b00-18cd-11e9-9818-71e49237fe4c.png) and follow through the prompts to log your SharePoint authentication issue.
