### ISSUE TITLE
Multi geo and tenant sync settIngs

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/OfficeDocs-Enterprise#158]
Clearly call out if SPO tenant sync settings can be different in multi geo ??  Ie allow ODFB Mac sync 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f3a2c9-0399-218d-cf9a-eb0f16fcbbb0
* Version Independent ID: da6ada6e-ce41-f772-74b8-144cf540d423
* Content: [Multi-Geo Capabilities in OneDrive and SharePoint Online in Office 365](https://docs.microsoft.com/en-gb/office365/enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365)
* Content Source: [Enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by AndreaBarr** [comment]
@bakerm00 Thank you for this feedback

I agree these sync settings should be clerified. 

I was able to get this into the backlog for the Enterprise team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
