### ISSUE TITLE
Error on Stepd 6 - AcquireToken" with "4" argument(s)

### ISSUE THREAD

**Issue by guptas-abhishek** [MicrosoftDocs/OfficeDocs-Enterprise#16]
Hi,  I am stuck in step no 6 

Executed the Import-Module (path)\MSGraphTokenLifetimePolicy.psm1 and Import-ActiveDirectoryAuthenticationLibrary command which worked like a charm but when running the main script "$saml2policyid = Get-PoliciesAssignedToServicePrincipal -servicePrincipalId $objectid | ?{$_.displayName -EQ "TokenIssuancePolicy"} | select objectId", it gave me an error....

Is there something more i need to do... Code output is below

PS Z:\cgas\Abhi> Import-ActiveDirectoryAuthenticationLibrary
Active Directory Authentication Library Nuget doesn't exist. Downloading now ..

nuget.exe not found. Downloading from http://www.nuget.org/nuget.exe ...
Loading ADAL Assemblies ...
True
PS Z:\cgas\Abhi> $saml2policyid = Get-PoliciesAssignedToServicePrincipal -servicePrincipalId $objectid | ?{$_.displayName -EQ "TokenIssuancePolicy"} | select objectId
GetPoliciesAssignedToEntityUrl: Using graph endpoint: https://graph.windows.net
entity: servicePrincipals entityId: *******
Exception calling "AcquireToken" with "4" argument(s): "Unable to cast object
of type
'Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.InteractiveWebUI' to
type 'Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.IWebUI'."
At C:\Program Files\WindowsPowerShell\Modules\MSGraphTokenLifetimePolicy\MSGrap
hTokenLifetimePolicy.psm1:52 char:3

$Global:authenticationResult =
$authContext.AcquireToken($resourceAppIdURI, $c ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication | Microsoft Docs](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
I created a new pull request (https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/15) with more explicit directions. 

1. Open an elevated command prompt 
2. Change directory to the folder containing the Initialize.ps1 and MSGraphTokenLifetimePolicy.psm1 files.
3. Execute the command `Import-Module Initialize.ps1`

Hope this helps.

**Comment by denisebmsft** [comment]
Thank you, Guptas-Abhishek for the feedback, and thank you, Kirk Evans, for the help.
