### ISSUE TITLE
Teams fails to join meetings with "oops you've been disconnected"

### ISSUE THREAD

**Issue by lachlann562** [MicrosoftDocs/OfficeDocs-Enterprise#166]
After several weeks of investigation on my own and with microsoft support, we identified that the reason meeting were dropping (but not other calls) is that there was a problem with port mapping. the resolution was to setup a port forwarding rule on the router to my computer.
Audio ports: UDP 50000-50019
Video ports: UDP 50020-50039
App sharing ports: UDP 50040-50059

support case # was 11072418

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by AndreaBarr** [comment]
@lachlann562 Thank you so much for sharing this information

I'll make sure we get this information added to the docs.

I was able to get this into the backlog for the Enterprise team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by JohnGGeo** [comment]
@lachlann562 The above ports were listed under Default Optional Notes: Needed when there are users are hosted both in Skype for Business on premises and online (Hybrid). No changes should be required for docs.
