### ISSUE TITLE
ClientSideAssets

### ISSUE THREAD

**Issue by Lady-MCSE** [MicrosoftDocs/OfficeDocs-Enterprise#167]
Another more recent article seems to suggest that "clientsideassets" is also a default public origin. 
 It is not mentioned in this article.  Reference -  https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2836d55d-6874-f366-60c2-e3043dd5547e
* Version Independent ID: 3c84c811-52bc-872e-48cf-54ecc2a9d7de
* Content: [Use the Office 365 content delivery network with SharePoint Online](https://docs.microsoft.com/en-us/office365/enterprise/use-office-365-cdn-with-spo#determine-where-you-want-to-store-your-assets)
* Content Source: [Enterprise/use-office-365-cdn-with-spo.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/use-office-365-cdn-with-spo.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@Lady-MCSE Thank you for this feedback

I agree we need to clarify "clientsideassets". I'm going to get this over to the Enterprise team for investigation and clarification. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MSFTTracyP** [comment]
Clientsideassets is a default public origin that was added in Dec of 2017 so that, if you had a public CDN before that time, you wouldn't see the entry automatically added, but if you created afterward, you'd see this change automatically.
