### ISSUE TITLE
Powershell parameters typo

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/OfficeDocs-Enterprise#169]
There is a typ in powershell parameter commands,
instead: Select-Object -TenantId
should be: Select-Object TenantId

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c34e3138-8c1d-0a14-f730-416c9767cf24
* Version Independent ID: 2c01a8e7-0b6f-e44d-2e4c-bab9c0f5beda
* Content: [Manage Office 365 tenants with Windows PowerShell for Delegated Access Permissions (DAP) partners](https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-office-365-tenants-with-windows-powershell-for-delegated-access-permissio)
* Content Source: [Enterprise/powershell/manage-office-365-tenants-with-windows-powershell-for-delegated-access-permissio.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/manage-office-365-tenants-with-windows-powershell-for-delegated-access-permissio.md)
* Service: **o365-administration**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by AndreaBarr** [comment]
@hkusulja Thank you for finding this

I will get this over to the Enterprise team so we can fix this typo. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
