### ISSUE TITLE
Does not work for Office 365 Germany

### ISSUE THREAD

**Issue by Comde-IT** [MicrosoftDocs/OfficeDocs-Enterprise#173]
Step 2 does not work for account under Office 365 Germany. I can connect to Exchange by changing the server adress, but that option is missing here. Please add the info or name an alternative.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by AndreaBarr** [comment]
@Comde-IT Thank you for this information.

I will get this over to the Enterprise team so we can get the instructions for the Germany 365 accounts updated. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@Comde-IT  I added tips to both step 2 sections with a link to a separate article that contains the instructions to connect to Office 365 Germany. Thanks for your feedback.
