### ISSUE TITLE
Line 125 explination

### ISSUE THREAD

**Issue by pavelrozenberg** [MicrosoftDocs/OfficeDocs-Enterprise#174]
It seems that this row is for CRLs.
Why does it have www.microsoft.com included?
Also why does it require port 443?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by AndreaBarr** [comment]
@pavelrozenberg Thank you for this feedback. 

I don't have the answers for this but I'll get this over to the Enterprise team so we can get answers for you. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@pavelrozenberg I have forwarded your question to the product team owners, who will reopen this issue when they provide an answer.
