### ISSUE TITLE
Where to go to enable Multi-Geo support?

### ISSUE THREAD

**Issue by adammodlin** [MicrosoftDocs/OfficeDocs-Enterprise#175]
It's mentioned above "Microsoft needs to configure your Exchange Online tenant for Multi-Geo support. This one-time configuration process is triggered after you order Multi-Geo and the licenses show up in our tenant." but there is no link or direction on how to enable this for your tenant. Am I missing that information or is it not on the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85937c83-35db-0882-e226-a4f2f732de73
* Version Independent ID: ac0b646b-0fbf-eb24-6768-07cfcd51076b
* Content: [Multi-Geo Capabilities in Exchange Online](https://docs.microsoft.com/en-us/office365/enterprise/multi-geo-capabilities-in-exchange-online)
* Content Source: [Enterprise/multi-geo-capabilities-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/multi-geo-capabilities-in-exchange-online.md)
* Service: **o365-solutions**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@adammodlin I added the following sentence: To order Multi-Geo, contact your Microsoft representative. For more information, see https://aka.ms/Multi-Geo.

Thanks for the feedback.
