### ISSUE TITLE
Skype for Business and Microsoft Teams ID #12

### ISSUE THREAD

**Issue by cowitkow** [MicrosoftDocs/OfficeDocs-Enterprise#177]
dev.teams.microsoft.com is an Azure CDN. Routing this via PAC against ExpressRoute will not work, as ER block CDNs (https://docs.microsoft.com/en-us/azure/expressroute/expressroute-faqs). Needs to be excluded in particular for ER customers for AppStudio to work in Teams

**Comment by cowitkow** [comment]
This is for the general URLs and IPs article for O365 (https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges) in relation to https://icm.ad.msft.net/imp/v3/incidents/details/79728857/home. Teams PG confirmed the limitations after a back and forth with the ExpressRoute folks.

**Comment by JoeDavies-MSFT** [comment]
@cowitkow Closing this to resolve this issue within Microsoft.
