### ISSUE TITLE
Error in Set-PolicyToServicePrincipal - (Step 6)

### ISSUE THREAD

**Issue by Smith-richard** [MicrosoftDocs/OfficeDocs-Enterprise#18]
Great article mate.... Getting a nasty error while executing command of#6 -> 
set-PolicyToServicePrincipal.

Invoke-RestMethod : {"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"The URI
'https://graph.windows.net//myorganization/policies/**********?api-version=1.61-internal' is
not valid since it is not based on 'https://graph.windows.net/myorganization/'."}}}

Any thoughts/advice ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication | Microsoft Docs](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
The "-internal" in the URL indicates you are using an early version of the script that has since been corrected. Please go to the repo containing the script (https://github.com/kaevans/spsaml11/blob/master/scripts/) and get the latest version.

**Comment by Smith-richard** [comment]
TA kaevans... but the latest version is giving me a new error 
"Request_MultipleObjectsWithSameKeyValue","message":{"lang":"en","value":"Request contains property changes that would result in property-uniqueness violation(s)."

**Comment by kaevans** [comment]
There can only be one TokenIssuancePolicy for the service principal. It's important to run the previous command that removes the existing SAML 2.0 policy. 

`Import-Module <file path of Initialize.ps1> 
$objectid = "<Application Object ID from Table 1>"
$saml2policyid = Get-PoliciesAssignedToServicePrincipal -servicePrincipalId $objectid | ?{$_.displayName -EQ "TokenIssuancePolicy"} | select objectId
Remove-PolicyFromServicePrincipal -policyId $saml2policyid -servicePrincipalId $objectid`

**Comment by denisebmsft** [comment]
Thanks, Kirk!

**Comment by SashaSidorenko** [comment]
Hi There,
Using 
Import-Module ".\Initialize.ps1"
$objectid = "d8ee32be-3510-4222-a214-71b4b58be62e"
$saml2policyid = Get-PoliciesAssignedToServicePrincipal -servicePrincipalId $objectid | ?{$_.displayName -EQ "TokenIssuancePolicy"} | select objectId
Remove-PolicyFromServicePrincipal -policyId $saml2policyid -servicePrincipalId $objectid

receiving an error:
Importing Module: .\MSGraphTokenLifetimePolicy.psm1
Loading ADAL Assemblies ...
True
GetPoliciesAssignedToEntityUrl: Using graph endpoint: https://graph.windows.net entity: servicePrincipals entityId: d8ee32be-3510-4222-a214-71b4b58be62e
HTTP GET https://graph.windows.net/myorganization/servicePrincipals/d8ee32be-3510-4222-a214-71b4b58be62e/policies?api-version=1.6
AssignPolicyToEntity: Using graph endpoint: https://graph.windows.net entity: servicePrincipals entityId: d8ee32be-3510-4222-a214-71b4b58be62e
HTTP DELETE https://graph.windows.net/myorganization/servicePrincipals/d8ee32be-3510-4222-a214-71b4b58be62e/$links/policies/@{objectId=41cf3e00-e3dd-4943-99ca-ed2ccee90178}?api-version=1.6
Invoke-RestMethod : {"odata.error":{"code":"Request_UnsupportedQuery","message":{"lang":"en","value":"Unsupported referenced-object resource identifier for link property 'policies'."}}}
At C:\Program Files\WindowsPowerShell\Modules\MSGraphTokenLifetimePolicy\MSGraphTokenLifetimePolicy.psm1:339 char:15
+     $result = Invoke-RestMethod @parameters
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

it's worked previously for other enterprise application

**Comment by denisebmsft** [comment]
Thank you for the feedback, SashaSidorenko. We are looking into this.

**Comment by AlN3t** [comment]
Having the same issue as SashaSidorenko. even tried to replace manually the policy id but same error.
Any ideas anyone?

**Comment by kaevans** [comment]
The code works as written, re-verified in my environment. Unsure what might be specific to your environment. The PowerShell simply wraps REST API calls to the AzureAD Graph. You can see the specific calls in the article [Microsoft Graph operations on policy](https://msdn.microsoft.com/en-us/library/azure/ad/graph/api/policy-operations#create-a-policy). You can use the same URLs that are output from the PowerShell commands and go to the [AzureAD Graph Explorer](https://graphexplorer.azurewebsites.net/) to re-issue the commands. For instance:

```
https://graph.windows.net/myorganization/servicePrincipals/YOUR_APPLICATION_ID_HERE/policies
```

That command would list the policies, allowing you to see if there is an existing SAML 2.0 policy or even an existing SAML 1.1 policy.

**Comment by AlN3t** [comment]
Thanks Kaevans. Managed to make it work. must have been a typo on my side.

**Comment by AlN3t** [comment]
Hi guys,
For the user to access sharepoint, it seems like it needs at least full read access to the wrong site collection.

Is there a way to handle permissions in Sharepoint where you want to break permission inheritance and assign different permission level to different user?

Thanks,
Alain

**Comment by kaevans** [comment]
@AlN3t - please refer to a forum such as [SharePoint Stack Exchange](https://sharepoint.stackexchange.com/) for this guidance. Issues here are specific to the accuracy of the associated article and not for general product help. 

SharePoint has long had a concept of breaking permissions and querying effective permissions, however that is outside the scope of this article.

@denisebmsft Recommend to close this issue.

**Comment by RoyKimYYZ** [comment]
Thanks for the tip. I resolved by hardcoding the $saml2policyid value as such: Remove-PolicyFromServicePrincipal -policyId "4327fe90-c06f-454e-9539-4c06c235740f" -servicePrincipalId $objectid
