### ISSUE TITLE
"Office 365 authentication and identity" Content missing which is suppose to be as per https://docs.microsoft.com/en-us/office365/enterprise/hybrid-modern-auth-overview

### ISSUE THREAD

**Issue by NeeranjanShettar** [MicrosoftDocs/OfficeDocs-Enterprise#180]
"Office 365 authentication and identity" Content missing which is suppose to be as per https://docs.microsoft.com/en-us/office365/enterprise/hybrid-modern-auth-overview

Have it checked and update accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by AndreaBarr** [comment]
@NeeranjanShettar Thank you for this feedback

I will make sure to get this over to the Enterprise team for investigation. 

 The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@NeeranjanShettar A fix to the original article at https://docs.microsoft.com/en-us/office365/enterprise/hybrid-modern-auth-overview is in progress.

**Comment by NeeranjanShettar** [comment]
Thanks, Joe.. How about for this article where "Office 365 authentication and identity" Content missing which is suppose to be as per https://docs.microsoft.com/en-us/office365/enterprise/hybrid-modern-auth-overview ? is it something Enterprise team are going to modify the statement in the original article ?

Thanks in advance.

**Comment by NeeranjanShettar** [comment]
Is there any update ?

**Comment by JoeDavies-MSFT** [comment]
@NeeranjanShettar Sorry for the delay. The article has been updated to point to the new rows in the "Office 365 URLs and IP address ranges." Thanks for letting us know.

**Comment by NeeranjanShettar** [comment]
Excellent, really appreciated.
