### ISSUE TITLE
IP address for secure.aadcdn.microsoftonline-p.com

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/OfficeDocs-Enterprise#181]
I have a customer who would like to know if IP address is static and its range to add to NSG in Azure - where/how can I get information? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252fen-us%252farticle%252foffice-365-urls-and-ip-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2#microsoft-365-common-and-office-online)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by AndreaBarr** [comment]
@kazshi Thank you for this feedback

I am not sure where the information for NSG in Azure is. Let me get this over to the Enterprise team so we can get some answers for you. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@kazshi I have forwarded your question to the product team owners, who will reopen this issue when they provide an answer.

**Comment by kazshi** [comment]
@JoeDavies-MSFT Do you mind if I reopen this to track the issue (since I have no way to track this issue other than here)?  or Would you please tell me whom I should contact for the issue?  Thanks

**Comment by kazshi** [comment]
Closing since I got information. Thanks.
