### ISSUE TITLE
Improving Italian translation

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/OfficeDocs-Enterprise#182]
Is there any way to suggest improvements for the automated translation into Italian language for this page or to manually fix it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by AndreaBarr** [comment]
@LuigiBruno Thank you for this feedback

I am not sure what the best way to suggest improvements for the Italian language automated translation. Let me get this over to the Enterprise team so this can be handled appropriately. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by LuigiBruno** [comment]
@AndreaBarr Thank you.

**Comment by denisebmsft** [comment]
@LuigiBruno thank you for the feedback. Our localization team is looking into this.
