### ISSUE TITLE
Grammer mistake

### ISSUE THREAD

**Issue by chaitraliraut105** [MicrosoftDocs/OfficeDocs-Enterprise#183]
please correct this grammar error "users' passwords "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0157c20-f401-82c5-eede-67c6505a688d
* Version Independent ID: 02e0575c-193a-3610-5496-e9076d51df3f
* Content: [Understanding Office 365 identity and Azure Active Directory](https://docs.microsoft.com/en-us/office365/enterprise/about-office-365-identity)
* Content Source: [Enterprise/about-office-365-identity.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/about-office-365-identity.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by AndreaBarr** [comment]
@chaitraliraut105 Thank you for this feedback

I created a pull request to fix that grammar. It's now waiting to be reviewed and merged. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
