### ISSUE TITLE
Need Info on Traffic Direction (Source(s) / Destination(s))

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Enterprise#184]
This information used to include what source / destinations go along with these IP address ranges and URL's.  For example, the "Exchange Online" IP address ranges...:

Some of these are required to be allowed to connect inbound to customers' external-facing Exchange servers.  Then, some of these are required to be allowed for customers' users to connect outbound to them.  These two requirements are completely separate, however in this documentation they are just lumped together with no distinction whatsoever.

When I go an look at the Web Service feed for Worldwide endpoints (https://endpoints.office.com/endpoints/worldwide?clientrequestid=b10c5ed1-bad1-445f-b386-b919946339a7), the same list is repeated numerous times, each with a separate set of Ports and required'ness level, but no indication of what on-premises endpoints (users, servers, etc.) are involved and what direction.

So since there is no direction, is it safe to say that customers should open bidrectionally to all of the IP ranges / URL's, to every single system in their on-premises environment?  I'm sure the answer is 'no', so case and point, there needs to be clear and concise information about this stuff on this page.

PS.  What is an Exchange Online 'POP migration'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@JeremyTBradshaw I have forwarded your question to the product team owners, who will reopen this issue when they provide an answer.
