### ISSUE TITLE
Missing information for SharePoint Hybrid Site feature traffic 

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-Enterprise#193]
When SharePoint Hybrid Site feature is enabled SP farm is sending POST requests to a service located in the OneDrive sites namespace. (https://GUID-my.sharepoint.com/_vti_bin/client.svc/ProcessQuery). This information is missing from the documentation - to allow traffic from SP farm we would need information which service on local SP farm is posting the request, what exactly URL is beind used (looks like the URL is specific for each customer so it would be good to have Information how to find this URL) 

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/pl-pl/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2#sharepoint-online-and-onedrive-for-business)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by AndreaBarr** [comment]
@Larryngolog Thank you for this feedback

We apricate you pointing out where we can improve the documentation. I will get this information over to the Enterprise team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@Larryngolog I have forwarded your question to the product team owners, who will reopen this issue when they provide an answer.
