### ISSUE TITLE
Modern Authentication - Supported Clients?

### ISSUE THREAD

**Issue by dcaddick** [MicrosoftDocs/OfficeDocs-Enterprise#195]
Hi,

Just leaving this as macOS & iOS without any reference to version numbers is a bit simplistic.
There is a reasonable expectation that in most docuemtation there are specific "System PreReqs" called out.

Just like this other reference:
https://www.microsoft.com/en-us/microsoft-365/blog/2015/11/19/updated-office-365-modern-authentication-public-preview/ but again it was last edited over 12 months ago?

Is there another resource where this is spelt out clearly?

Thanks in advance 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c554e4c6-b078-134a-dd27-43310c93aa45
* Version Independent ID: a55042c0-f1f4-5750-5a03-fe9fad687367
* Content: [Office 365 Client App Support - Modern Authentication](https://docs.microsoft.com/en-us/office365/enterprise/office-365-client-support-modern-authentication)
* Content Source: [Enterprise/office-365-client-support-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-client-support-modern-authentication.md)
* Service: **office 365 administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by AndreaBarr** [comment]
@dcaddick Thank you for this feedback

I am not sure if there is another resource where this is split out. Let me get this over to the Enterprise team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by robmazz** [comment]
@dcaddick - thanks for your patience with this issue. I've been in discussions with some of our internal teams about how to include some versioning information to help with your valid concerns. We're trying to work through some different options and addressing some other internal factors. I'll post an update when the topic is updated.

**Comment by robmazz** [comment]
@dcaddick - I've updated the Client Support section to call out support for the latest versions of the clients. I'll continue to investigate a better way to also address the Platform section. The short answer now is that the Modern Auth platform requirements are the same as the platform requirements for Office 365 (https://products.office.com/en-us/office-system-requirements).
