### ISSUE TITLE
federation required - or not?

### ISSUE THREAD

**Issue by gnerd** [MicrosoftDocs/OfficeDocs-Enterprise#196]
The article states "◦Your SIP domain is added as a Federated domain in Office 365" - later you state "◦Your identity configurations are any of the types supported by AAD Connect (such as password hash sync, pass-through authentication, on-premises STS supported by Office 365, et cetera.)" so is federation requried or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626caf29-7e88-0b56-2013-5c5b7c2a5917
* Version Independent ID: 2376192f-793d-0166-46c7-870cd0c41abb
* Content: [Hybrid Modern Authentication overview and prerequisites for using it with on-premises Skype for Business and Exchange servers](https://docs.microsoft.com/en-us/office365/enterprise/hybrid-modern-auth-overview)
* Content Source: [Enterprise/hybrid-modern-auth-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/hybrid-modern-auth-overview.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by AndreaBarr** [comment]
@gnerd Thank you for this feedback

I am not sure if federation is required or not. Let me get this over to the Enterprise team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by mqunbar** [comment]
If we don't meet the pre-requisites for our on prem Sfb and Exchange environment.. do we have no option to take advantage of the modern auth capabilities of exchange online? We want to enable modern auth so we can protect our accounts with Azure MFA

**Comment by MSFTTracyP** [comment]
AAD Connect can handle either ADFS Federation is part of a standard Skype for Business hybrid allowing for federated users as you'd see when using AAD Connect to sync accounts.

**Comment by gnerd** [comment]
My argument is that "Your SIP domain is added as a Federated domain in Office 365" - what you really mean is a verified domain.  a Federated domain implies this is offloading authentication to your on-premises AD.    Or you mean "Your SIP domain is added as a Federated domain in SKYPE"  - right now its confusing.
