### ISSUE TITLE
Need exact version numbers

### ISSUE THREAD

**Issue by randallrking** [MicrosoftDocs/OfficeDocs-Enterprise#197]
[Enter feedback here]
As a previous user commented, I would like to know specific version numbers of the software where Modern Authentication was added. For instance, was it in Office 2016 for Mac from the initial launch, or was it added in a specific version later (e.g. 15.30)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c554e4c6-b078-134a-dd27-43310c93aa45
* Version Independent ID: a55042c0-f1f4-5750-5a03-fe9fad687367
* Content: [Office 365 Client App Support - Modern Authentication](https://docs.microsoft.com/en-us/office365/enterprise/office-365-client-support-modern-authentication)
* Content Source: [Enterprise/office-365-client-support-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-client-support-modern-authentication.md)
* Service: **office 365 administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by AndreaBarr** [comment]
@randallrking Thank you for this inquiry. 

I don't have the version numbers so let me get this request over to the Enterprise team. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by randallrking** [comment]
I’m not sure how Android was brought into the picture.

For macOS, it can be any version upon which Microsoft Office will run. Microsoft has supported different versions of macOS for Office over the years. I can’t see how your question is relevant to my question. At some point in Microsoft Office for Mac, modern authentication (ADAL) was added. I’d like to know when. That question seems irrelevant to what version of macOS I or any of my customers that I’m supporting have.

**Comment by robmazz** [comment]
@randallrking and @rstamp - thanks for your patience with this issue. I've been in discussions with some of our internal teams about how to include some versioning information to help with your valid concerns. We're trying to work through some different options and addressing some other internal factors. I'll post an update when the topic is updated.

**Comment by sethmiller-millersystems** [comment]
Any updates?

**Comment by robmazz** [comment]
@randallrking, @rstamp, @sethmiller-millersystems - thanks so much for the patience. I've updated the Client Support section to call out support for the latest versions of the clients. I'll also continue to investigate a better way to also address the Platform section. The short answer now is that the Modern Auth platform requirements are the same as the platform requirements for Office 365 (https://products.office.com/en-us/office-system-requirements). The latest version for the platforms is what we're supporting, providing information for previous versions (or when and at what point a version was supported) isn't on our support roadmap for this area.
