### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by v-MarioMigliacio** [MicrosoftDocs/OfficeDocs-Enterprise#199]
Hey, just a heads up - there are a LOT of 404 broken links on this page. Googled a couple of them and found them, but I think this is a great page- just needs some care!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 093db571-11e5-adc8-8826-3485e79ccbec
* Version Independent ID: 0c7bd2ea-f4cf-bd2a-56ef-d5f57786c5be
* Content: [Fixing problems with directory synchronization for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/fix-problems-with-directory-synchronization?redirectSourcePath=%252fen-us%252farticle%252ffixing-problems-with-directory-synchronization-for-office-365-79c43023-5a47-45ae-8068-d8a26eee6bc2)
* Content Source: [Enterprise/fix-problems-with-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/fix-problems-with-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by AndreaBarr** [comment]
@v-MarioMigliacio Thank you for pointing this out

I will get this broken links information over to the Enterprise team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by robmazz** [comment]
@v-MarioMigliacio - thanks for catching these broken links, the topic has been updated and the broken links are fixed. And please remember to Bing instead of Google! :)
