### ISSUE TITLE
Replacing ACS on existing Sharepoint Azure Extranet

### ISSUE THREAD

**Issue by ryankirchner** [MicrosoftDocs/OfficeDocs-Enterprise#20]
Kirk - We are attempting to cut over an existing Azure enterprise application using SharePoint 2013 (using ACS) to a new enterprise application using this documentation. I am in the process of creating the new enterprise application in Step 3. Our existing Sharepoint site is public facing at a URL of https://www.site.com. Do I need to delete this enterprise application before I create the new one? The new one needs to have the same URL, so deleting the old one would make sense. Also, since the ACS tools are no longer available I am fearful that if this new method you describe in the documentation does not work for whatever reason I will not be able to restore our old site. Thoughts?

**Comment by kaevans** [comment]
Migrating from ACS to AzureAD and migrating users is out of scope for this document. In theory (I haven't tested), you set the realm in AAD the same as you did in ACS. Then you should only need to update the existing SPTrustedIdentityProvider to set the properties for the reply URL and update the cert similar to the steps at the end of the article, assuming the claims mapping remains the same. There should be no need to delete the SharePoint Web Application.

**Comment by ryankirchner** [comment]
Do you recommend wiping out my Azure/ACS settings (keeping my SharePoint web app as-is) and then building out a new enterprise application to point to my old SharePoint site? I imagine I will need to redo permissions on each site? Thanks, I'm having a hard time planning how I can accomplish this.

**Comment by kaevans** [comment]
The only part that matters is the SPTrustedIdentityTokenIssuer in SharePoint as it is the thing that decides which service (AAD or ACS) to go to based on the login URL and the signing certificate. I'd leave the existing settings in AAD and ACS as-is. Follow the doc to create a new application registration, but make sure to use the same realm string value as you did previously with ACS. Download the new signing certificate and add to SharePoint as shown in the doc. Then update (don't delete and replace) the SPTrustedIdentityTokenIssuer with the new logon URL and certificate. The user identity should remain the same, no need to change permissions or anything. By using the same SPTrustedIdentityTokenIssuer, the user identifier in the database remains unchanged:

i:0#.c|myacsregistration|someone@example.com

If, instead, you created a new SPTrustedIdentityTokenIssuer according to the article, it would look like:

i:0#.c|azuread|someone@example.com

By reusing the same SPTrustedIdentityTokenIssuer, the string isn't changed. If we create a new one, the string is changed and the user identities in the database won't match.
 
If, by some unfortunate reason, you deleted the SPTrustedIdentityTokenIssuer, you could create a new one and migrate the users using the Move-SPUser command in a script similar to what is in the following blog post:

https://blogs.msdn.microsoft.com/sambetts/2014/09/03/how-to-migrate-sharepoint-users-to-adfs/ 

Hope this helps!

**Comment by ryankirchner** [comment]
Thanks for the response. I will give it a shot to see what happens. I really appreciate your help with this.
