### ISSUE TITLE
Guidance on when to install AzureADPreview modules

### ISSUE THREAD

**Issue by westerdaled** [MicrosoftDocs/OfficeDocs-Enterprise#201]
I am refreshing some Developer laptop installation documentation for a colleague. Previously, I ran  Install-Module -Name AzureADPreview  however, I wonder this is only appropriate If I need the (latest) support for graph API xyz . Can you please advise?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by AndreaBarr** [comment]
@westerdaled Thank you for this inquiry

I am not sure on the answer to this. Let me get this over to the Enterprise team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@westerdaled Please ask this same question as a comment on this page: https://www.powershellgallery.com/packages/AzureADPreview/2.0.2.5. The product team for the Azure AD Preview PowerShell module should be able to answer your question. Thanks
