### ISSUE TITLE
TraceTCP link not working

### ISSUE THREAD

**Issue by jopgommans** [MicrosoftDocs/OfficeDocs-Enterprise#206]
It seems the TraceTCP link is not functioning, might be good to look into that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45822051-b802-c3da-01c2-88abb5482ca2
* Version Independent ID: 3b6670b0-6eb8-9ab1-fd3d-02c833d2cdbc
* Content: [Office 365 performance tuning using baselines and performance history](https://docs.microsoft.com/en-us/office365/enterprise/performance-tuning-using-baselines-and-history)
* Content Source: [Enterprise/performance-tuning-using-baselines-and-history.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/performance-tuning-using-baselines-and-history.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by JoeDavies-MSFT** [comment]
@jopgommans This link has been corrected and updated. Thanks for letting us know.
