### ISSUE TITLE
More tips, not just on migration

### ISSUE THREAD

**Issue by jopgommans** [MicrosoftDocs/OfficeDocs-Enterprise#207]
The essence of this article is great, and adding tips to improve speeds is a great approach. I notice that most of the Exchange Online are related to migration however. I would suggest adding some general tips such as:
- Look into mailbox caching and choose the appropriate options (caching period, shared mailbox caching yes/no)
- Verify that the DNS lookup for outlook.office.com enters the MS-datacenter at a logical entry location (for example in NL ams-1x-1.microsoft.com)
- Prevent outlook data from passing over a VPN connection (to a central office) before going over the internet
- Make sure mailbox data adheres to the limitations on folder- and item amounts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b4f786-65a8-d5ae-d9dc-038df47be0b2
* Version Independent ID: ff95b05d-9153-0b3d-c212-3a117bc0dfad
* Content: [Tune Exchange Online performance](https://docs.microsoft.com/en-us/office365/enterprise/tune-exchange-online-performance)
* Content Source: [Enterprise/tune-exchange-online-performance.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/tune-exchange-online-performance.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@jopgommans Thank you for these suggestions. 

I am going to get this over to the Enterprise team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MSFTTracyP** [comment]
I'm updating the documentation now. This article is specific to migration, it's true, but I made a general section that should remind admins about these points. Thank you for your feedback, @jopgommans!
