### ISSUE TITLE
Windows Azure Active Directory Module for Windows PowerShell (64-bit version)

### ISSUE THREAD

**Issue by StewartSiegel33472** [MicrosoftDocs/OfficeDocs-Enterprise#21]
When you click on that link it states that it is retired, and therefore you cannot install that module.

Documentation needs to be updated to install it through PowerShell.

The cmdlets are:
Install-Module Azure and Install-Module AzureRM 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c551eb1-7ac5-cb02-cd1b-d67ca3886d85
* Version Independent ID: fb690e2e-420e-f697-60f2-39520283d385
* Content: [Connect to all Office 365 services in a single Windows PowerShell window](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window)
* Content Source: [Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
StewartSiegel33472, I updated the instructions to install the module from the PowerShell command prompt with the Install-Module MSOnline command.

**Comment by SwapnilSwarajIT** [comment]
https://docs.microsoft.com/en-us/previous-versions/azure/jj151815(v=azure.100)#install-the-azure-ad-module

I think above link also require update as it redirect to same page.
