### ISSUE TITLE
This article appears to have been superseded?

### ISSUE THREAD

**Issue by stevep4** [MicrosoftDocs/OfficeDocs-Enterprise#211]
The following article:

https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sharepoint-on-premises-tutorial

appears to supersede this article... it describes virtually the same scenario, without the need to create a non-gallery app and play with powershell... there is an enterprise app now pre-built to take out all the hard work... and it's free (the solution in this article isn't free).

Maybe there could be a big link at the top of the article to let people know to go to the other one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sharepoint-on-premises-tutorial is an older article, in fact. 'Using Azure AD for SharePoint Server Authentication' is the most comprehensive article.

**Comment by AndreaBarr** [comment]
@stevep4 Did what Tracy provided resolve this issue?

**Comment by stevep4** [comment]
I respectfully disagree that this article is the more comprehensive.

If you follow this article without realising the other one exists, then you are left thinking you need to create a non-gallery app, which is an Azure AD Premium only thing.

If you're on Azure AD Basic, like most Education users might be, then you're left thinking you are not able to use this SAML 1.1 feature (without spending a lot of money).

That's the position I found myself in, so ended up using a different solution. Now I realise I could have used a "free" gallery application, but it is too late as I have already moved to production and don't want to convert all my users to federated users in SharePoint.

The other article achieves exactly the same, but with much less technical interaction, just using a solution that is pre-built.

I strongly feel that this article should at least reference the other article, or mention that there is a prebuilt gallery app that could be used rather than creating a non-gallery app.

**Comment by MSFTTracyP** [comment]
Hm. Steve. The last time I saw https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sharepoint-on-premises-tutorial, it included information that used the ACS (which is not going to work, long term for customers) but I'm not seeing that now and it's been updated, so you have a good point here. Let me see what I can do (if anything). I'll look into this.

**Comment by harbars** [comment]
yup, the second article was updated in August and no longer requires the use of ACS. the use of the Gallery is certainly something that should be promoted. Not that doing it without the gallery config isn't valid, but as mentioned above requires AD premium (in this scenario just to translate a saml token)

**Comment by mypil** [comment]
@MSFTTracyP - Do you have any updates on this? Thank you.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@stevep4 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
