### ISSUE TITLE
Missing IPs for Teams

### ISSUE THREAD

**Issue by mrik23** [MicrosoftDocs/OfficeDocs-Enterprise#212]
Looking at the traffic during meeting or call in Teams, and I see most of the traffic being on IP like 52.113. and 52.114. which are not listed at all here. And I check even from the JSON on web service, it's missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#skype-for-business-online-and-microsoft-teams)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mrik23** [comment]
OK sorry these IPs are withing 52.112.0.0/14.

However I'm seeing traffic to 40.70.46.15 which doesn't fall in any given range.

**Comment by JoeDavies-MSFT** [comment]
@mrik23 I have forwarded your feedback to the product team that maintains the list of IP addresses for Teams. They will incorporate your request as needed into the next update. Thanks for letting us know.
