### ISSUE TITLE
Office 365 Roadmap link dead

### ISSUE THREAD

**Issue by Forcide** [MicrosoftDocs/OfficeDocs-Enterprise#213]
The link to the Office 365 Roadmap is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b49fa8b-3555-bab8-6a91-417af55f6b5c
* Version Independent ID: ed87643c-8ee0-f937-8b2c-975d0be7bf7c
* Content: [Manage Office 365 Groups with PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/manage-office-365-groups-with-powershell?redirectSourcePath=%2farticle%2faeb669aa-1770-4537-9de2-a82ac11b0540)
* Content Source: [Enterprise/manage-office-365-groups-with-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/manage-office-365-groups-with-powershell.md)
* Service: **o365-administration**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by AndreaBarr** [comment]
@Forcide Thank you for pointing this out

I will get this link information to the Enterprise team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dianef77** [comment]
No repro.  Just tested the link and it worked for me.
