### ISSUE TITLE
I believe there are updates to both Regions and workloads 

### ISSUE THREAD

**Issue by Ramonin** [MicrosoftDocs/OfficeDocs-Enterprise#214]
Please update this article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f3a2c9-0399-218d-cf9a-eb0f16fcbbb0
* Version Independent ID: da6ada6e-ce41-f772-74b8-144cf540d423
* Content: [Multi-Geo Capabilities in OneDrive and SharePoint Online in Office 365](https://docs.microsoft.com/en-us/office365/enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365#multi-geo-status-and-availability)
* Content Source: [Enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by AndreaBarr** [comment]
@Ramonin Thank you for pointing this out

I will get this information about the updates to the Enterprise team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MikePlumleyMSFT** [comment]
New updates published to multi-geo content today.
