### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by matthewjlevy** [MicrosoftDocs/OfficeDocs-Enterprise#216]
Hi Joe and the documentation team, this a great series of articles and I had seen the TLG PowerPoint from your CAAB about a year ago, however, the link in all the docs in this series to http://aka.ms/catlgstack take me to an empty or non-existent OneDrive location. Can you confirm the link please?

PS: Great show with you, Brenda Carter and "theCloudArchitects" https://thearchitects.cloud/2018/11/02/episode-19-unsung-heroes/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 596c812b-a25a-e573-825b-debe0af35fd8
* Version Independent ID: 1669980c-0c80-ae7c-3bc3-6bfcc64fe924
* Content: [Test Office 365 with Cloud adoption Test Lab Guides (TLGs)](https://docs.microsoft.com/en-za/office365/enterprise/cloud-adoption-test-lab-guides-tlgs)
* Content Source: [Enterprise/cloud-adoption-test-lab-guides-tlgs.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/cloud-adoption-test-lab-guides-tlgs.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@matthewjlevy The link has been corrected and updated. Thanks for letting us know about the broken link and the kudos on the content and the Cloud Architects podcast. :)

**Comment by matthewjlevy** [comment]
That "One" TLG stack is a thing of beauty!

**Comment by JoeDavies-MSFT** [comment]
@matthewjlevy Thanks! The "One that rules them all!" :)
