### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by sathiathirumal** [MicrosoftDocs/OfficeDocs-Enterprise#219]
The link for text "Microsoft Cloud Identity for Enterprise Architects" is broken.
It points to https://go.microsoft.com/fwlink/p/?LinkId=828642 which leads to a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919dff18-2ca8-ded4-7b64-be7b05657dfe
* Version Independent ID: d211dc9d-f8a9-1c94-4956-c4fe97cddff3
* Content: [Azure integration with Office 365](https://docs.microsoft.com/en-us/office365/enterprise/azure-integration)
* Content Source: [Enterprise/azure-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/azure-integration.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by AndreaBarr** [comment]
@sathiathirumal Thank you for pointing this out

I will get this broken link information over to the Enterprise writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by robmazz** [comment]
@sathiathirumal - Thanks for the feedback, this link has been fixed and updated.
