### ISSUE TITLE
Step 6 permissions issue

### ISSUE THREAD

**Issue by ryankirchner** [MicrosoftDocs/OfficeDocs-Enterprise#22]
I am trying to run the scripts in step 6 as an administrator of both Azure and SharePoint.  I am getting an error in Powershell(see below).  Do I need to do anything regarding access to the graph API? What steps would I need to do?  I just ran the following script per the documentation:

Import-Module MSOnline
Connect-MsolService
Add-PSSnapin Microsoft.SharePoint.Powershell
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

Import-Module <path to Initialize.ps1>
Import-ActiveDirectoryAuthenticationLibrary

$objectid = <my object id>
$saml2policyid = Get-PoliciesAssignedToServicePrincipal -servicePrincipalId $objectid | ?{$_.displayName -EQ "TokenIssuancePolicy"} | select objectId
Remove-PolicyFromServicePrincipal -policyId $saml2policyid -servicePrincipalId $objectid
$policy = Add-TokenIssuancePolicy -DisplayName SPSAML11 -SigningAlgorithm "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" -TokenResponseSigningPolicy TokenOnly -SamlTokenVersion "1.1"
Set-PolicyToServicePrincipal -policyId $policy.objectId -servicePrincipalId $objectid

and here is the output and error:

Importing Module: C:\graph\scripts\MSGraphTokenLifetimePolicy.psm1
Loading ADAL Assemblies ...
True
Loading ADAL Assemblies ...
True
GetPoliciesAssignedToEntityUrl: Using graph endpoint: https://graph.windows.net 
entity: servicePrincipals entityId: 092b3a1a-1ce7-4de1-85a6-f962f649bc57
HTTP GET https://graph.windows.net/myorganization/servicePrincipals/092b3a1a-1ce
7-4de1-85a6-f962f649bc57/policies?api-version=1.6
AssignPolicyToEntity: Using graph endpoint: https://graph.windows.net entity: se
rvicePrincipals entityId: 092b3a1a-1ce7-4de1-85a6-f962f649bc57
HTTP DELETE https://graph.windows.net/myorganization/servicePrincipals/092b3a1a-
1ce7-4de1-85a6-f962f649bc57/$links/policies/@{objectId=16f07fcd-3fb2-481e-8587-3
e7afc3f696b}?api-version=1.6

Invoke-RestMethod : {"odata.error":{"code":"Authorization_RequestDenied","messa
ge":{"lang":"en","value":"Insufficient privileges to complete the 
operation."}}}
At C:\graph\scripts\MSGraphTokenLifetimePolicy.psm1:339 char:15
+     $result = Invoke-RestMethod @parameters
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt 
   pWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe 
   ll.Commands.InvokeRestMethodCommand

**Comment by kaevans** [comment]
The easiest way to troubleshoot this issue is to use the [AAD Graph Explorer](https://graphexplorer.azurewebsites.net/) to attempt to re-issue the commands as shown in the output. This should help troubleshoot what's happening. It looks like the permission was denied on the DELETE operation. You can use the Graph Explorer to run the GET command to see what's currently assigned. If it is the SAML 2.0 policy, then it needs to be deleted before assigning the new policy.

**Comment by ryankirchner** [comment]
Thanks for the quick response. I guess I have more research to do to figure out how to use the Graph API. When I run the GET command I get this response (see below). It looks like SamlTokenVersion is 2.0.  

{
    "odata.metadata": "https://graph.windows.net/myorganization/$metadata#directoryObjects",
    "value": [
        {
            "odata.type": "Microsoft.DirectoryServices.Policy",
            "objectType": "Policy",
            "objectId": "16f07fcd-3fb2-481e-8587-3e7afc3f696b",
            "deletionTimestamp": null,
            "alternativeIdentifier": null,
            "definition": [
                "{\r\n  \"TokenIssuancePolicy\": {\r\n    \"Version\": 1,\r\n    \"SigningAlgorithm\": \"http://www.w3.org/2001/04/xmldsig-more#rsa-sha256\",\r\n    \"TokenResponseSigningPolicy\": \"TokenOnly\",\r\n    \"SamlTokenVersion\": \"2.0\"\r\n  }\r\n}"
            ],
            "displayName": "TokenIssuancePolicy",
            "isTenantDefault": false,
            "keyCredentials": [],
            "type": "TokenIssuancePolicy"
        }
    ]
}


So I need to delete this policy? Doesn't this snippet already delete and then re-add it? If it is breaking because I can't delete the policy then what do I need to do to fix it?  I'm running it as an admin. Now I'm really confused. 

$objectid = "092b3a1a-1ce7-4de1-85a6-f962f649bc57"
$saml2policyid = Get-PoliciesAssignedToServicePrincipal -servicePrincipalId $objectid | ?{$_.displayName -EQ "TokenIssuancePolicy"} | select objectId
**Remove-PolicyFromServicePrincipal -policyId $saml2policyid -servicePrincipalId $objectid**
$policy = Add-TokenIssuancePolicy -DisplayName SPSAML11 -SigningAlgorithm "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" -TokenResponseSigningPolicy TokenOnly -SamlTokenVersion "1.1"
Set-PolicyToServicePrincipal -policyId $policy.objectId -servicePrincipalId $objectid

**Comment by kaevans** [comment]
1. Go to AAD Graph Explorer
2. Login (top right corner)
3. Change the HTTP verb in the top left drop-down to DELETE
4. Enter this into the text box:

https://graph.windows.net/myorganization/servicePrincipals/092b3a1a-
1ce7-4de1-85a6-f962f649bc57/$links/policies/@{objectId=16f07fcd-3fb2-481e-8587-3
e7afc3f696b}

I expect that you will get the same error, but hopefully with a descriptive error message.

**Comment by ryankirchner** [comment]
This is all it gives me:


{
    "odata.error": {
        "code": "Authorization_RequestDenied",
        "message": {
            "lang": "en",
            "value": "Insufficient privileges to complete the operation."
        }
    }
}


Are there permissions I need to set inside Azure in order to use this API?

Thanks again!

**Comment by ryankirchner** [comment]
Fixed it. I had an issue with the admin account that I was using to run the scripts.

Thanks as always for the help.
