### ISSUE TITLE
Need to be clearer on the first two statements

### ISSUE THREAD

**Issue by mealiffe** [MicrosoftDocs/OfficeDocs-Enterprise#224]
The first two statements in this doc state that load testing isn't permitted, and then state that it's strongly discouraged - these are two very different things. I'd suggest changing the "strongly discouraged" wording to "isn't permitted" so there is consistency of messaging.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2ecd3e9-2961-7bfc-b7e1-6f99e9b20658
* Version Independent ID: 5fd3e877-c745-a683-92d3-92bd3a86dfbe
* Content: [Capacity planning and load testing SharePoint Online](https://docs.microsoft.com/en-us/office365/enterprise/capacity-planning-and-load-testing-sharepoint-online)
* Content Source: [Enterprise/capacity-planning-and-load-testing-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/capacity-planning-and-load-testing-sharepoint-online.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@mealiffe Thank you for this suggestion

I will get this wording suggestion over to the Enterprise writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MSFTTracyP** [comment]
Addressed it in the doc.
