### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by lewislivingstone** [MicrosoftDocs/OfficeDocs-Enterprise#227]
Hi,
The following links appear to be broken: 
- "attributes synchronized to Azure Active Directory by Azure AD Connect." under Directory Cleanup Tasks
-  "Prepare for directory synchronization." under "Add an alternative UPN Suffix for AD DS"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c60ee789-fce6-6c95-150d-be4ae895730e
* Version Independent ID: d9e96954-3b85-bf8d-c7d3-916a4698fd77
* Content: [Prepare to provision users through directory synchronization to Office 365](https://docs.microsoft.com/en-us/office365/enterprise/prepare-for-directory-synchronization)
* Content Source: [Enterprise/prepare-for-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/prepare-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by aglasson** [comment]
I've also noticed the "Prepare for directory synchronization"[https://go.microsoft.com/fwlink/p/?LinkId=525430] link is broken on a ton of Microsoft documentation websites.

**Comment by robmazz** [comment]
@lewislivingstone and @aglasson  - thanks for your feedback, these links have been updated and fixed.
