### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by lewislivingstone** [MicrosoftDocs/OfficeDocs-Enterprise#228]
Hi,
The following link is broken:
"Integrating your on-premises identities with Azure Active Directory."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79589db3-4bf5-e940-0410-75d5f0ff97b8
* Version Independent ID: e7980b96-bab3-981e-2da8-6e1bdde9ba31
* Content: [Prepare a non-routable domain for directory synchronization](https://docs.microsoft.com/en-us/office365/enterprise/prepare-a-non-routable-domain-for-directory-synchronization)
* Content Source: [Enterprise/prepare-a-non-routable-domain-for-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/prepare-a-non-routable-domain-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@lewislivingstone - Thanks for the feedback, this link has been fixed and updated.
