### ISSUE TITLE
Remove links to paid content

### ISSUE THREAD

**Issue by Oatlad** [MicrosoftDocs/OfficeDocs-Enterprise#229]
Stop trying to sell LinkedIn video content in the user guides for the products I am already paying for....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0157c20-f401-82c5-eede-67c6505a688d
* Version Independent ID: 02e0575c-193a-3610-5496-e9076d51df3f
* Content: [Understanding Office 365 identity and Azure Active Directory](https://docs.microsoft.com/en-us/office365/enterprise/about-office-365-identity)
* Content Source: [Enterprise/about-office-365-identity.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/about-office-365-identity.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by AndreaBarr** [comment]
@Oatlad Where are the paid links? We are not seeing them but need this information so we can escalate this issue and get them addressed.

**Comment by jutsey** [comment]
There are several videos in the series. All of the preliminary videos are free, but when you try to go to the one that actually explains installation of AzureADConnect you have to go to linked in and sign up for Linked In Learning. And it requires you to sign up for the one month free trial.

**Comment by robmazz** [comment]
@jutsey - Thanks for your feedback. I'm not seeing the requirement for anything other than a free LinkedIn account for the AAD Connect video (https://www.linkedin.com/learning/office-365-manage-identities-using-azure-ad-connect/express-vs-custom-aad-connect?u=3322). If you don't want any type of LinkedIn account and you're looking for more details, you can find detailed AAD Connect installation guidance here - https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-install-roadmap.
