### ISSUE TITLE
Azure B2B on Sp 2016 open Issue

### ISSUE THREAD

**Issue by michelef71** [MicrosoftDocs/OfficeDocs-Enterprise#23]
Hi 
I have added the new Auth provider based on Azure.
If I add an user (choosing Name as Claim provider) and I try to login on SharePoint with this user i get "this site hasn't been shared with you".
I have tried to add the Azure CP solution, and i have noticed that I'm able to use the guest user only If i choose "extuser_hotmail.com#ext#@tenant.onmicrosoft.com"
that is the real upn that sharepoint receive from identity provider
I was expecting that the upn was the e-mail address specified on Azure
Thank you in advanced
Michele

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by ryankirchner** [comment]
Interesting. I am having an issue where (also using Name as the claim provider) I can log in to a site, but I don't have any of the administration options available. I made my account a web collection administrator after switching to the new provider I created. I am hovering over the name to make sure it is using the "name" claim. Still, inside SharePoint I can't do any admin tasks (change site permissions, etc). I wonder if there is an issue using Name as the claim type?

**Comment by ryankirchner** [comment]
I was able to fix my issue by using LDAPCP instead of AzureCP.

**Comment by denisebmsft** [comment]
Thank you, MicheleF71 and RyanKirchner for your feedback. We will look into this and get back to you soon.

**Comment by kaevans** [comment]
Yes, Azure uses the email#ext#@tenant.onmicrosoft.com format for B2B invited guest users. Using a claims provider such as AzureCP would query the Graph API to allow users to query using names instead of UPN and enable the People Picker. Using LDAPCP means it will query a domain controller, which would not work for invited guests.
