### ISSUE TITLE
Videotraniing url broken

### ISSUE THREAD

**Issue by UpsilonB** [MicrosoftDocs/OfficeDocs-Enterprise#230]
The url to the videotraining is broken. It links to a page that no longer exists.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: c937e8be-1696-c315-a93b-88f083279644
* Version Independent ID: c0c3d253-4bfe-1750-58a1-4d8f4a1e68d6
* Content: [Install and run the Office 365 IdFix tool](https://docs.microsoft.com/nl-be/office365/enterprise/install-and-run-idfix?redirectSourcePath=%252fen-us%252farticle%252fInstall-and-run-the-Office-365-IdFix-tool-f4bd2439-3e41-4169-99f6-3fabdfa326ac)
* Content Source: [Enterprise/install-and-run-idfix.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/install-and-run-idfix.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by AndreaBarr** [comment]
@UpsilonB Thank you for pointing this out. 

I will get this broken link information over to the Enterprise writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by robmazz** [comment]
@UpsilonB - Thanks for the feedback, this link has been fixed and updated.
