### ISSUE TITLE
MORE>Directory Synch not as indicated in this document

### ISSUE THREAD

**Issue by qwirk** [MicrosoftDocs/OfficeDocs-Enterprise#231]
The first panel now has this after More&gt; Directory Synchronization:

Active Directory preparation 
Active Directory synchronization allows your company’s administrators to continuously sync your existing on-premises user and group accounts with Azure Active Directory. 
Microsoft Azure Active Directory Connect tool can be used to setup Active Directory Synchronization 
Download Microsoft Azure Active Directory Connect tool 
Close 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2363e1c8-0003-dbb2-194f-10b25b732b8d
* Version Independent ID: ac43d1f5-f0e2-7818-0913-53a590c7a7e0
* Content: [Set up directory synchronization for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/set-up-directory-synchronization)
* Content Source: [Enterprise/set-up-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/set-up-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by AndreaBarr** [comment]
@qwirk Thank you for pointing this out

I will get this updated information over to the Enterprise writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
