### ISSUE TITLE
Missing sender IP

### ISSUE THREAD

**Issue by Bernskov** [MicrosoftDocs/OfficeDocs-Enterprise#232]
You are sending inbound mail from 40.107.0.0/16 but only 40.104.0.0/15 is mentioned in the Docs.
You should update the documentation 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Bernskov I have forwarded this information to the product team, who will evaluate and update the address ranges as needed in the next update. Thanks for letting us know.
