### ISSUE TITLE
Non-Microsoft controlled content hosted on some of the above endpoints

### ISSUE THREAD

**Issue by patros** [MicrosoftDocs/OfficeDocs-Enterprise#233]
For example azureedge.net is used for Azure CDN endpoints. Meaning anyone in the world can create a something.azureedge.net CDN profile and host whatever they like.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by patros** [comment]
Sorry, title should have read something about the listing being a bit misleading. i.e. the *.azureedge.net item is "Microsoft Stream - unauthenticated". It could be more specific which would be ideal. i.e. msstream1.azureedge.net or whatever it needs to be.

**Comment by robmazz** [comment]
@patros - thanks for the feedback, I'll get this over to the Enterprise content team for clarification.

**Comment by JoeDavies-MSFT** [comment]
@patros The *.azureedge.net FQDN is there to allow Microsoft to add and remove additional names and services as needed without having to maintain them their individual names. Because Microsoft owns the azureedge.net DNS domain and the DNS servers resolving names in that domain, only Microsoft can create new names and host new CDN profiles in that domain. I hope this helps.

**Comment by patros** [comment]
This gets even worse [https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service](https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service)

```
To help you better identify and differentiate Office 365 network traffic, a new web service publishes Office 365 endpoints, making it easier for you to evaluate, configure, and stay up to date with changes. This new web service replaces the XML downloadable files that are currently available. The XML format is planned to be phased out on October 2, 2018.

As a customer or a network perimeter device vendor, you can build against the new REST-based web service for the Office 365 IP address and FQDN entries. You can access the data directly in a web browser using these URLs.
```

**Comment by patros** [comment]
And also want to point out that this can be used for egress of data too [https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob).
