### ISSUE TITLE
Facebook や YouTube など Microsoft 社以外のアドレス識別について

### ISSUE THREAD

**Issue by SHIMSOFT** [MicrosoftDocs/OfficeDocs-Enterprise#234]
JSON 形式でダウンロードしたデータなどでは、Facebook や YouTube など Microsoft 社以外の URL も含まれていました。
これらのサードパーティ URL を JSON 系式データ内からピックアップする方法があれば教えてください。
Microsoft 社以外のどこのアドレスを利用する可能性があるのかなどの一覧を取りたいためです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8762d73c-32fc-a4f9-162a-b81ae4052ea3
* Version Independent ID: 554cc99d-b929-8db0-7ab7-0f666438e8cf
* Content: [Office 365 エンドポイントの管理](https://docs.microsoft.com/ja-jp/office365/enterprise/managing-office-365-endpoints?redirectSourcePath=%252farticle%252f99cab9d4-ef59-4207-9f2b-3728eb46bf9a)
* Content Source: [Enterprise/managing-office-365-endpoints.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/managing-office-365-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by AndreaBarr** [comment]
@SHIMSOFT Thank you for this feedback

I am getting this informaiton over to the Enterprise team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
