### ISSUE TITLE
No AAAA records are available for outlook.office365.com

### ISSUE THREAD

**Issue by samualblair** [MicrosoftDocs/OfficeDocs-Enterprise#236]
No AAAA records are available for outlook.office365.com

This prevents some users from accessing outlook.office365.com when on an IPv6 only network (such as Comcast when not running dual-stack). In addition documentation would suggest that there should be AAAA records available for this site/service.

**Per documentation the following IP (specifically ipv6) ranges could/should be used:**
```
outlook.office.com, outlook.office365.com

13.107.6.152/31, 13.107.9.152/31, 13.107.18.10/31, 13.107.19.10/31, 13.107.128.0/22, 23.103.160.0/20, 23.103.224.0/19, 40.96.0.0/13, 40.104.0.0/15, 52.96.0.0/14, 111.221.112.0/21, 131.253.33.215/32, 132.245.0.0/16, 134.170.68.0/23, 150.171.32.0/22, 157.56.232.0/21, 157.56.240.0/20, 191.232.96.0/19, 191.234.140.0/22, 204.79.197.215/32, 206.191.224.0/19, 
2603:1006::/40, 2603:1016::/40, 2603:1026::/40, 2603:1026:200::/39, 2603:1026:400::/39, 2603:1026:600::/44, 2603:1026:620::/44, 2603:1026:800::/44, 2603:1026:820::/45, 2603:1036::/39, 2603:1036:200::/40, 2603:1036:400::/40, 2603:1036:600::/40, 2603:1036:800::/38, 2603:1036:c00::/40, 2603:1046::/37, 2603:1046:900::/40, 2603:1056::/40, 2603:1056:400::/40, 2603:1056:600::/40, 2603:1096::/38, 2603:1096:400::/40, 2603:1096:600::/40, 2603:1096:a00::/39, 2603:1096:c00::/40, 2603:10a6:200::/40, 2603:10a6:400::/40, 2603:10a6:600::/40, 2603:10a6:800::/40, 2603:10d6:200::/40, 2620:1ec:4::152/128, 2620:1ec:4::153/128, 2620:1ec:c::10/128, 2620:1ec:c::11/128, 2620:1ec:d::10/128, 2620:1ec:d::11/128, 2620:1ec:8f0::/46, 2620:1ec:900::/46, 2620:1ec:a92::152/128, 2620:1ec:a92::153/128, 2a01:111:f400::/48

```

But Unable to resolve any IPv6 address for servers, making them not reachable via an IPv6 only internet (when not using translation technologies to an IPv4 internet).

**As shown below no AAAA records are available using Google DNS (v4 and v6) or Cloudflare DNS (v4 or v6) , this has also been confirmed with Comcast v6 DNS servers**

```
PCNAME:~user$ 
PCNAME:~user$ dig @2001:4860:4860::8888 outlook.office365.com

; <<>> DiG 9.10.6 <<>> @2001:4860:4860::8888 outlook.office365.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63534
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;outlook.office365.com.		IN	A

;; ANSWER SECTION:
outlook.office365.com.	154	IN	CNAME	outlook.ha.office365.com.
outlook.ha.office365.com. 32	IN	CNAME	outlook.ms-acdc.office.com.
outlook.ms-acdc.office.com. 32	IN	A	40.97.85.66
outlook.ms-acdc.office.com. 32	IN	A	40.97.134.18
outlook.ms-acdc.office.com. 32	IN	A	40.97.119.178
outlook.ms-acdc.office.com. 32	IN	A	40.97.84.18

;; Query time: 46 msec
;; SERVER: 2001:4860:4860::8888#53(2001:4860:4860::8888)
;; WHEN: Wed Nov 21 06:43:25 PST 2018
;; MSG SIZE  rcvd: 176

PCNAME:~user$ 



PCNAME:~user$ dig @8.8.8.8 outlook.office365.com

; <<>> DiG 9.10.6 <<>> @8.8.8.8 outlook.office365.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48738
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;outlook.office365.com.		IN	A

;; ANSWER SECTION:
outlook.office365.com.	60	IN	CNAME	outlook.ha.office365.com.
outlook.ha.office365.com. 11	IN	CNAME	outlook.ms-acdc.office.com.
outlook.ms-acdc.office.com. 4	IN	A	40.97.117.242
outlook.ms-acdc.office.com. 4	IN	A	40.97.80.18
outlook.ms-acdc.office.com. 4	IN	A	40.97.180.34
outlook.ms-acdc.office.com. 4	IN	A	40.97.118.162

;; Query time: 31 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Nov 21 06:42:46 PST 2018
;; MSG SIZE  rcvd: 176

PCNAME:~user$ 


PCNAME:~user$ 
PCNAME:~user$ 
PCNAME:~user$ dig @2606:4700:4700::1111 outlook.office365.com

; <<>> DiG 9.10.6 <<>> @2606:4700:4700::1111 outlook.office365.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14940
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;outlook.office365.com.		IN	A

;; ANSWER SECTION:
outlook.office365.com.	33	IN	CNAME	outlook.ha.office365.com.
outlook.ha.office365.com. 29	IN	CNAME	outlook.ms-acdc.office.com.
outlook.ms-acdc.office.com. 33	IN	A	40.97.80.2
outlook.ms-acdc.office.com. 33	IN	A	40.97.85.66
outlook.ms-acdc.office.com. 33	IN	A	40.97.132.210
outlook.ms-acdc.office.com. 33	IN	A	40.97.140.34

;; Query time: 45 msec
;; SERVER: 2606:4700:4700::1111#53(2606:4700:4700::1111)
;; WHEN: Wed Nov 21 06:44:29 PST 2018
;; MSG SIZE  rcvd: 176

PCNAME:~user$ dig @1.1.1.1 outlook.office365.com

; <<>> DiG 9.10.6 <<>> @1.1.1.1 outlook.office365.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58743
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;outlook.office365.com.		IN	A

;; ANSWER SECTION:
outlook.office365.com.	23	IN	CNAME	outlook.ha.office365.com.
outlook.ha.office365.com. 19	IN	CNAME	outlook.ms-acdc.office.com.
outlook.ms-acdc.office.com. 23	IN	A	40.97.132.210
outlook.ms-acdc.office.com. 23	IN	A	40.97.140.34
outlook.ms-acdc.office.com. 23	IN	A	40.97.80.2
outlook.ms-acdc.office.com. 23	IN	A	40.97.85.66

;; Query time: 42 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Wed Nov 21 06:44:39 PST 2018
;; MSG SIZE  rcvd: 176

PCNAME:~user$ 
```

**Comment by AndreaBarr** [comment]
@samualblair Thank you for this feedback

I'll get this request for the addition of the AAAA records to be included over to the Enterprise writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@samualblair I will forward this issue to the product teams for their investigation. Thanks for letting us know.

**Comment by kelleyvice-msft** [comment]
@samualblair - I can repro the problem using dig on a linux box using the exact commands in the OP. However, dig needs the **AAAA** or **ANY** parameter to output IPv6 results, and when I execute _dig outlook.office365.com AAAA @8.8.8.8_, I get IPv6 results as shown below. This was also successful against 1.1.1.1 and other DNS services.

Were you trying to troubleshoot an issue, or just confirming the IPv6 addresses in our endpoints documentation? Let me know if there is an underlying issue that still needs to be resolved.

**Using the original command _dig @8.8.8.8 outlook.office365.com_:**
$ dig @8.8.8.8 outlook.office365.com

; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7_4.2 <<>> @8.8.8.8 outlook.office365.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45098
;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;outlook.office365.com.  IN	A

;; ANSWER SECTION:
outlook.office365.com.	217	IN	CNAME	outlook.ha.office365.com.
outlook.ha.office365.com. 8	IN	CNAME	outlook.ms-acdc.office.com.
outlook.ms-acdc.office.com. 3550 IN	CNAME	sjc-efz.ms-acdc.office.com.
sjc-efz.ms-acdc.office.com. 10	IN	A	52.96.36.114
sjc-efz.ms-acdc.office.com. 10	IN	A	52.96.18.2
sjc-efz.ms-acdc.office.com. 10	IN	A	52.96.55.194
sjc-efz.ms-acdc.office.com. 10	IN	A	52.96.46.66

;; Query time: 5 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Apr 03 04:33:40 PDT 2019
;; MSG SIZE  rcvd: 198

**Using _dig outlook.office365.com AAAA @8.8.8.8_:**
$ dig outlook.office365.com AAAA @8.8.8.8

; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7_4.2 <<>> outlook.office365.com AAAA @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44645
;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;outlook.office365.com.  IN	AAAA

;; ANSWER SECTION:
outlook.office365.com.	13	IN	CNAME	outlook.ha.office365.com.
outlook.ha.office365.com. 17	IN	CNAME	outlook.ms-acdc.office.com.
outlook.ms-acdc.office.com. 3567 IN	CNAME	sjc-efz.ms-acdc.office.com.
sjc-efz.ms-acdc.office.com. 40	IN	AAAA	2603:1036:307:2894::2
sjc-efz.ms-acdc.office.com. 40	IN	AAAA	2603:1036:a03:28::2
sjc-efz.ms-acdc.office.com. 40	IN	AAAA	2603:1036:a03:6e::2
sjc-efz.ms-acdc.office.com. 40	IN	AAAA	2603:1036:307:2880::2

;; Query time: 5 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Apr 03 04:52:04 PDT 2019
;; MSG SIZE  rcvd: 246
