### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jordi-j** [MicrosoftDocs/OfficeDocs-Enterprise#238]
There's a typo at the top of the document, one of the links is a missing "t" in organization: "Common attacks and Microsoft capabilities that protect your organization".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096f9573-ba23-b0a0-23dc-7b0eb57a17d8
* Version Independent ID: 45643fe7-700e-8eca-b7b9-563327472d6b
* Content: [Microsoft Cloud IT architecture resources](https://docs.microsoft.com/en-us/office365/enterprise/microsoft-cloud-it-architecture-resources#common-attacks-and-microsoft-capabilities-that-protect-your-organization)
* Content Source: [Enterprise/microsoft-cloud-it-architecture-resources.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/microsoft-cloud-it-architecture-resources.md)
* Service: **o365-solutions**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by AndreaBarr** [comment]
@jordi-j Thank you for pointing this out

I will get this typo over to the Enterprise writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@jordi-j The typo has been fixed and should be merged to live sometime today.
