### ISSUE TITLE
'*.gvt1.com' and 'dl.google.com' are missing

### ISSUE THREAD

**Issue by Keisuke1234** [MicrosoftDocs/OfficeDocs-Enterprise#240]
Teams uses from '*.gvt1.com' and 'dl.google.com'. Should be added to the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by AndreaBarr** [comment]
@Keisuke1234 Thank you for pointing this out

I will get these over to the Enterprise writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@Keisuke1234 I have forwarded your suggestion to the product team who maintains the endpoints. Thanks for your feedback.
