### ISSUE TITLE
Office 365 URLs and IP address ranges

### ISSUE THREAD

**Issue by RamIyer5** [MicrosoftDocs/OfficeDocs-Enterprise#243]
We are unable to find the Office 365 URLs and IP address ranges in this site. request you to kindly let us know where we can find it 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2#section-1)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by nugentd** [comment]
Missing for me too :(

**Comment by dstrome** [comment]
Thanks @RamIyer5  and @nugentd for bringing this to our attention. We've reverted the erroneous changes and are working to ensure this doesn't happen again.
