### ISSUE TITLE
More specific detail / inclusion in Web Service

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Enterprise#244]
Hello, the first paragraph says:

"The web service scope is network endpoints that are required for connectivity from a user of Office 365 across an enterprise perimeter network. This currently does not include:

Network connectivity that may be required from a Microsoft datacenter to a customer network (inbound hybrid server network traffic).
Network connectivity from servers on a customer network across the enterprise perimeter (outbound server network traffic)."

Is the Web Service planned to eventually include these?  If so, is there any ETA?

Most Office 365 customers of any size are Exchange Hybrid deployment customers, and many of them rely on this information to be able to secure their firewalls.  The rows in this article for Exchange Online (rows 5-8), are not 100% clear on what IP's of Microsoft's are involved and which direction the traffic will be flowing.  Row 5 states to refer to the "Exchange Online" section of the Office 365 URLs and IP Ranges article, but there are multiple Exchange Online related sections on that page.  Is it safe to say that every IP listed in the entire Exchange Online section?

Now that the original page (Office 365 URLs and IP ranges) has been renamed to "&lt;Worldwide|DOD|21Vianet&gt; endpoints", and demoted to just client connectivity to Office 365 endpoints, there should be just as much detail in a server connectivity to (and from) Office 365 endpoints article.  Also, it shouldn't be how it is now, off in a "additional endpoints not included..." article.  It makes it sound as though these requirements aren't just as commonly required by customers.  These requirements are arguably way more important to customers as a higher percentage of customers protect their infrastructure/servers then the percentage of customers that filter their users' outbound client connectivity traffic.

Here's what I'm proposing:

1.) Under the main section "Office 365 IP Address and URLs", two new sections should be created:
  1.a) "Client Connectivity" (under which the "&lt;Worldwide | DOD | Vianet&gt; endpoints" articles would live.
1.b) "Server/infrastructure Connectivity" (under which similarly named subsections would live, with the fully-specific details contained there (not loosely referenced to another page like it is here in this article today).  The details would include direction, source/destination IP's, protocols.

I'm not sure if I can to a pull request on multiple pages at once to try and make this change and try to get it merged back in, but if I can do that, I would take a first stab at it.  The main problem with this is that there is no clear answer on here for me to know with confidence what the correct list of Microsoft IP's are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f067ba99-0e05-7b24-0074-c5573b2bcef3
* Version Independent ID: 22154e5a-18d3-eed6-d8c9-09cf4452b727
* Content: [Additional endpoints not included in the Office 365 IP Address and URL Web service](https://docs.microsoft.com/en-us/office365/enterprise/additional-office365-ip-addresses-and-urls)
* Content Source: [Enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@JeremyTBradshaw - Thank you for pointing this out
I will get these over to the Enterprise writing team for investigation.
Thank you for reporting and making the docs better. Much appreciated.
I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@JeremyTBradshaw Sorry for the delay. I have for forwarded your requests to the product teams that maintain these lists. Thanks
