### ISSUE TITLE
Exchange Online Collaboration Address Lists

### ISSUE THREAD

**Issue by mprentice22153** [MicrosoftDocs/OfficeDocs-Enterprise#247]
Is there a way to share Global Address Lists or contacts between multiple O365 Exchange Online tenants?  Or is this part of the functionality with the calendar sharing?  I'm not finding anything that explicitly addresses email address sharing between tenants.

Matthew

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41bcfce7-bfcf-f2da-f752-36ac0e497b78
* Version Independent ID: 880faa66-d243-6598-ae24-cf0e4d5a7c16
* Content: [Office 365 inter-tenant collaboration](https://docs.microsoft.com/en-us/office365/enterprise/office-365-inter-tenant-collaboration)
* Content Source: [Enterprise/office-365-inter-tenant-collaboration.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-inter-tenant-collaboration.md)
* Service: **o365-administration**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chris-pfs** [comment]
I have the same question

**Comment by robmazz** [comment]
@mprentice22153 - Thank you for pointing this out
I will get these over to the Enterprise writing team for investigation.
Thank you for reporting and making the docs better. Much appreciated.
I made a note to request the team to update this when the work is complete.

**Comment by SCS-sysadmin** [comment]
Any update? I also have this question. Thank you.

**Comment by bbchristian** [comment]
Also waiting for an answer to Matthew's question.

**Comment by bjbroecker** [comment]
I've also been doing extensive research on GAL synchronization. At this point, the best solution I've been able to find is setting up Microsoft Identity Manager (MIM) and turning up GALSync. I'm not looking forward to that.

**Comment by cabtilx** [comment]
As an alternative to GAL sync you can use the Graph API to retrieve the mailboxes from each tenant and silently invite them as B2B users in the other tenants, then un-hide these users from the GAL. This also means they can be added to groups and you can share SharePoint sites etc.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by chrfox** [comment]
checking with SMEs

**Comment by chrfox** [comment]
@mprentice22153   - thanks for your question.   Aside from the responses already posted here, I suggest you post your question to [TechCenter Forums](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsocial.technet.microsoft.com%2FForums%2Foffice%2Fen-us%2Fhome%3Fcategory%3Dexchangeserver&data=04%7C01%7Cchrfox%40exchange.microsoft.com%7Ca062ac4c8d574f363b9408d6bf8bde4d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636907004778934791%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=g3x34Up0ds0YM0Cq32XQurEXx1fDZFiStfx3Du9k7J0%3D&reserved=0)

Thanks again
Chris
