### ISSUE TITLE
Old information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-Enterprise#249]
This page has alot of references to very old versions of Office, please review and update where appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c20e446d-02fe-de0e-ac2a-2fc76fe1e3cd
* Version Independent ID: 626a7e4e-bc66-0e21-ba89-ad2ac9609f6c
* Content: [Best practices for using Office 365 on a slow network](https://docs.microsoft.com/en-us/office365/enterprise/best-practices-for-using-office-365-on-a-slow-network?redirectSourcePath=%252farticle%252ffd16c8d2-4799-4c39-8fd7-045f06640166)
* Content Source: [Enterprise/best-practices-for-using-office-365-on-a-slow-network.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/best-practices-for-using-office-365-on-a-slow-network.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by robmazz** [comment]
@DeanGross - Thank you for pointing this out
I will get these over to the Enterprise writing team for investigation.
Thank you for reporting and making the docs better. Much appreciated.
I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by nenonix** [comment]
@DeanGross @kaevans Please advise on what is needed to resolve this issue. Thanks.

**Comment by mypil** [comment]
@DeanGross @kaevans - We would like to follow up on this. Please respond to the query from nenonix. Thank you.

**Comment by mypil** [comment]
@kelleyvice-msft - can you please share your insights on this issue? 
Please advise what to update in case a PR needs to be created so we can have @nenonix do it. 

Thank you.

**Comment by kelleyvice-msft** [comment]
@mypil - Thanks for bumping this up. This is a complicated issue; references to obsolete Office products need to be updated, and the guidance needs to be updated to align with current O365 network optimization best practices. It is possible that we'll pull any valuable content out to other topics and retire this one. It's on my to do list, but I think it will be later in May before I get to it. In the meantime, simply updating product references and links would be useful if it won't take longer than a few hours.

**Comment by nenonix** [comment]
@kelleyvice-msft  it appears this has been address in the commit https://github.com/kaevans/OfficeDocs-Enterprise/commit/825d44011b72d2832a82834ab4bb536aea448986  - can you give me some feedback on that?

**Comment by kelleyvice-msft** [comment]
@nenonix - I don't see any changes to this file in 825d440. Are you sure that's the right one?

**Comment by nenonix** [comment]
@kelleyvice-msft I was not sure, but understand now, Thanks. I think I understand what is needed now.
