### ISSUE TITLE
Cannot index into a null array

### ISSUE THREAD

**Issue by c016smith** [MicrosoftDocs/OfficeDocs-Enterprise#250]
This comment above looks exactly like what I want, "To find all the licensed users who have been enabled or not enabled for specific services, use the following syntax:". I've followed that for a specific license I'm looking for, Microsoft Teams, under our EnterprisePack (E3 bundle). 

#this works great, $UPN being my account
(get-msoluser -UserPrincipalName $upn).licenses[8].serviceStatus[6] 

Returns:
ServicePlan ProvisioningStatus
----------- ------------------
TEAMS1      Success     

So that's great, I've found the right index # for License and ServiceStatus. 

However, when I try to run:
Get-MsolUser -All | where {$_.isLicensed -eq $true -and $_.Licenses[8].ServiceStatus[6].ProvisioningStatus -eq "Success"}

Returns:
Cannot index into a null array.
At line:1 char:28
+ ... ll | where {$_.isLicensed -eq $true -and $_Licenses[8].ServicesStatus ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray 

Character 28 is the first { after the Where statement. Am I missing something? I only have the one criteria (Microsoft Teams) so I didn't need the second -and ..... section. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f403603f-e17b-8b5b-cbd8-8e4c6f4e1728
* Version Independent ID: a93a3de1-25d3-4f7a-3e3e-3a6f25f88b75
* Content: [View account license and service details with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-account-license-and-service-details-with-office-365-powershell)
* Content Source: [Enterprise/powershell/view-account-license-and-service-details-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/view-account-license-and-service-details-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@c016smith - Thank you for your feedback, I will get these over to the Enterprise writing team for clarification.

**Comment by JoeDavies-MSFT** [comment]
@c016smith To find all the licensed users who have been enabled or not enabled for specific services has turned out to be more complicated than the simple example cited due to: 1. Users who might have multiple subscriptions, and 2. Ongoing changes to the list of services within each subscription. I have removed the section that describes this. Thanks for letting us know.
