### ISSUE TITLE
Missing EOP IPv6 range 2a01:111:f400:fc00::/54

### ISSUE THREAD

**Issue by Chrispaul01** [MicrosoftDocs/OfficeDocs-Enterprise#253]
Was cross checking to EOP article (https://docs.microsoft.com/en-us/office365/securitycompliance/eop/exchange-online-protection-ip-addresses) and noticed this one is missing 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-gb/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252farticle%252f8548a211-3fe7-47cb-abb1-355ea5aa88a2)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@Chrispaul01  - Thank you for your feedback, I will get this over to the Enterprise writing team for clarification.

**Comment by JoeDavies-MSFT** [comment]
@Chrispaul01 I have forwarded this issue to the teams that manage these address ranges and they will address this issue in the next update. Thanks for letting us know.
