### ISSUE TITLE
SharePoint Online Multi-geo?

### ISSUE THREAD

**Issue by SergePoint** [MicrosoftDocs/OfficeDocs-Enterprise#256]
The title of the article says "Multi-Geo Capabilities in OneDrive and SharePoint Online in Office 365", but there is no information about SharePoint Sites for Multi-geo.  Should the title be changed?   
Under this page it includes Sp site creation information and it mentions SharePoint multi-geo is in preview as April 26th.  https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-sites-provisioning 
Is SP Online Multi-geo now live or it's still in preview? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f3a2c9-0399-218d-cf9a-eb0f16fcbbb0
* Version Independent ID: da6ada6e-ce41-f772-74b8-144cf540d423
* Content: [Multi-Geo Capabilities in OneDrive and SharePoint Online in Office 365](https://docs.microsoft.com/en-us/office365/enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365)
* Content Source: [Enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
SharePoint Multi-Geo is not yet generally available. @AdwoodMicrosoft may have more details.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @SergePoint  @MikePlumleyMSFT  @DennisGaida 
MultiGeo for SharePoint online is now availble, there is no need to remove SharePoing from this article. I am going to create PR to update it.

Thank you

**Comment by mypil** [comment]
@SergePoint - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
