### ISSUE TITLE
List of Office 365 service plans and their friendly names for all services

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/OfficeDocs-Enterprise#26]
Dear Sir or Madam,

I am just about to prepare some PowerShell script to globally disable Stream Trial and enable Stream for Office 365 for all users (E1/E3).
I came across this support article "View licenses and services with Office 365 PowerShell":
https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-licenses-and-services-with-office-365-powershell#view-information-about-licensing-plans-and-the-available-licenses

Can I get a list of Office 365 service plans and their friendly names for ALL services?
The Contact Office support seems to be disabled. Therefore I chose this way.

Thank you.

Best regards,

Markus Hanisch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3baa87d3-9496-9bd2-739f-a136c1daacf3
* Version Independent ID: cfcd455b-36b0-53d6-80b4-805695919742
* Content: [View licenses and services with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-licenses-and-services-with-office-365-powershell#view-information-about-licensing-plans-and-the-available-licenses)
* Content Source: [Enterprise/powershell/view-licenses-and-services-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/view-licenses-and-services-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
Hi Markus, The list of Office 365 service plans and their friendly names for all services is only available through Office Support. The support link works for me. Can you tell me what you are seeing? Thanks

**Comment by junemay1001** [comment]
Hi Joe, I contacted Microsoft Support using the link. They say, I have to contact Business support or MSDN support. Is there an email address to which I can request this list of names? I hope the support link doesn't point to the right place where the list of services and friendly names are available.

**Comment by denisebmsft** [comment]
Hello junemay1001, 

Thank you for letting us know about this. We'll follow up soon.

**Comment by JoeDavies-MSFT** [comment]
Link to the web page for Office Business Support has been added/

**Comment by kombaiahmurugan** [comment]
@JoeDavies-MSFT , if possible, can you please share the license details (json file or other file) that you got from support?

**Comment by yovasx2** [comment]
Where is the list?

**Comment by th3r1dd1ck** [comment]
for those looking for the list - https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/licensing-service-plan-reference

**Comment by yovasx2** [comment]
I got that one, is not complete 😞:

ATP_ENTERPRISE : Advance threat protection (Safe links and safe attachments)
RIGHTSMANAGEMENT_STANDARD_STUDENT : Azure Active Directory Rights Management

Above items are missing and I have more examples

**Comment by JoeDavies-MSFT** [comment]
Please use the feedback at the end of the article to not missing items. Thanks.
