### ISSUE TITLE
Revocation is key

### ISSUE THREAD

**Issue by JLBevierre** [MicrosoftDocs/OfficeDocs-Enterprise#261]
As stated in the "Azure Active Directory": Refresh tokens [...] can be valid until revoked. 
The very question (and requirement) is to be able to revoke the refresh token in such a way that it immediately blocks the access to all services. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1570de51-50b1-d4cc-c1c7-832b3242ccb3
* Version Independent ID: f5250f91-0a48-20cf-8e2c-e2dc347edd88
* Content: [Session timeouts for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/session-timeouts)
* Content Source: [Enterprise/session-timeouts.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/session-timeouts.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by robmazz** [comment]
@JLBevierre - thanks for the feedback, I'll get this to the Enterprise content team for clarification.

**Comment by MSFTTracyP** [comment]
Here you go, @jlbevierre: 

1. [Revoke-AzureADUserAllRefreshToken](https://docs.microsoft.com/en-us/powershell/module/azuread/revoke-azureaduserallrefreshtoken?view=azureadps-2.0)

2. [Revoke-AzureADSignedInUserAllRefreshToken](https://docs.microsoft.com/en-us/powershell/module/azuread/revoke-azureadsignedinuserallrefreshtoken?view=azureadps-2.0 )
