### ISSUE TITLE
Clients need to connect to *.mail.protection.outlook.com on TCP port 25?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Enterprise#262]
This one seems like it doesn't fall inline with the new wording that these endpoints are intended for client-outbound connections.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@JeremyTBradshaw TCP port 25 is for SMTP traffic. Are you saying it should be TCP ports 80 or 443?

**Comment by JeremyTBradshaw** [comment]
@JoeDavies-MSFT Hi Joe.  No, what I'm trying to say is that the page states that it is intended for client-outbound connections, but I know that no clients actually connect on port 25 for SMTP.  Clients use port 587/smtp.office365.com.  It is servers that communicated bidrectionally on port 25 for SMTP.  "Clients" in the subject is where my emphasis was/is meant to be.

This page / these pages are among the most important for new Office 365 customers and I work with those kinds of customers for my job.  So I'm always going to be stickling for the fine details since I have to refer people here all the time.  It's continuously being improved which I appreciate.

I'm not even sure how you guys will or can correct this one, other than to say at the top of the page, that it is mostly intended for client-outbound connections, but some of the table entries are in fact for server inbound/outbound connections.  The other page ("Additional endpoints not included in the Office 365 IP Address and URL Web service") doesn't make mention of Exchange servers' SMTP traffic at all.  So it's like a missing bit, that is actually huge in importance.  Hope this helps.  You can feel free to close the issue.  I just wanted to point out the (in my opinion) lack of clarity on this one topic.

**Comment by JeremyTBradshaw** [comment]
@JoeDavies-MSFT  I'm referring to this quote:

"Endpoint data below lists requirements for connectivity from a user’s machine to Office 365. It does not include network connections from Microsoft into a customer network, sometimes called hybrid or inbound network connections."

It's actually not accurate, and TCP port 25 is not for client connections, it is only for server connections.  That is my understanding.  For clients, the intended SMTP pathway is TCP 587 to smtp.office365.com.

**Comment by JoeDavies-MSFT** [comment]
@JeremyTBradshaw I have forwarded this issue to the product team that owns these endpoints for their investigation. Closing this issue for now.

**Comment by almacho** [comment]
@JeremyTBradshaw,  I guess Port 25 is needed by "clients (or application)" if Pop3/IMAP is used.

**Comment by JeremyTBradshaw** [comment]
> @JeremyTBradshaw, I guess Port 25 is needed by "clients (or application)" if Pop3/IMAP is used.

Hi @almacho , thanks for the note.  I feel though that pop and imap clients ought to be using TCP 587 to SMTP.office365.com, not TCP 25 to the tenant MX host.  Maybe this is a misunderstanding that I have, but one I'll likely stick with too, because clients and 587 belong together where clients and 25 generally do not.
