### ISSUE TITLE
This Document still shows the Public Peering (which stands deprecated).

### ISSUE THREAD

**Issue by binoyjt** [MicrosoftDocs/OfficeDocs-Enterprise#263]
This Document still shows the Public Peering (which stands deprecated). Can this be updated to change the peering options and details about using the Microsoft peering instead of Public Peering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6943f9e3-df11-61ca-b5ef-da778e93d795
* Version Independent ID: 05ce76fc-573e-526c-d67e-0da86136147c
* Content: [ExpressRoute for Microsoft cloud connectivity](https://docs.microsoft.com/en-us/office365/enterprise/expressroute-for-microsoft-cloud-connectivity)
* Content Source: [Enterprise/expressroute-for-microsoft-cloud-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/expressroute-for-microsoft-cloud-connectivity.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@binoyjt I have updated the article. Due to our publishing processes, the poster (Visio and PDF) will be updated next week. Thanks so much for letting me know.

**Comment by JoeDavies-MSFT** [comment]
@binoyjt The updated poster is published.
