### ISSUE TITLE
"来園者" needs to be replaced with "ゲスト"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-Enterprise#264]
Strongly recommend to replace "来園者" with "ゲスト" , I can see "来園者" is used as a localized Japanese word of "guest" in English, however, it should be "ゲスト" which stands for guest user of Office 365.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 41bcfce7-bfcf-f2da-f752-36ac0e497b78
* Version Independent ID: 880faa66-d243-6598-ae24-cf0e4d5a7c16
* Content: [Office 365 テナント間コラボレーション](https://docs.microsoft.com/ja-jp/office365/enterprise/office-365-inter-tenant-collaboration)
* Content Source: [Enterprise/office-365-inter-tenant-collaboration.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-inter-tenant-collaboration.md)
* Service: **o365-administration**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by hyoshioka0128** [comment]
Strongly recommend to replace "来園者" with "ゲスト" , I can see "来園者" is used as a localized Japanese word of "guest" in English, however, it should be "ゲスト" which stands for guest user of Office 365.

**Comment by robmazz** [comment]
@hyoshioka0128 - thanks for the feedback, I'll get this over to the Enterprise content team for clarification.

**Comment by hyoshioka0128** [comment]
https://docs.microsoft.com/ja-jp/office365/enterprise/office-365-inter-tenant-collaboration

**Comment by denisebmsft** [comment]
@MollyMalone, can you take a look at this when you get a chance? Thank you!!

**Comment by OfficeGlobal** [comment]
Working on a fix (Bug 3205383)

**Comment by OfficeGlobal** [comment]
@MollyMalone , @hyoshioka0128 Article is HumanTranslated and published live. The word "guest" updated as requested

**Comment by hyoshioka0128** [comment]
@OfficeGlobal  Thanks.
