### ISSUE TITLE
Incorrect terminology used

### ISSUE THREAD

**Issue by steveianson** [MicrosoftDocs/OfficeDocs-Enterprise#266]
Hi - you need to change:
"In the new model, endpoints are segregated into three categories, Optimize, REQUIRED and Default, providing a priority-based pivot"
to
"In the new model, endpoints are segregated into three categories, Optimize, ALLOW and Default, providing a priority-based pivot"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6279eb8d-1df4-189d-8952-b6cde4cdf4a3
* Version Independent ID: e27f03c9-30f5-7fba-02f4-868abbf5d4ec
* Content: [Office 365 Network Connectivity Principles](https://docs.microsoft.com/en-us/Office365/Enterprise/office-365-network-connectivity-principles#BKMK_Categories)
* Content Source: [Enterprise/office-365-network-connectivity-principles.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-network-connectivity-principles.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by denisebmsft** [comment]
@steveianson thank you so much for the feedback. We're looking into this, and an update will be posted here soon.

**Comment by kelleyvice-msft** [comment]
Corrected in https://github.com/MicrosoftDocs/OfficeDocs-Enterprise-pr/pull/518. Thanks for the feedback, @steveianson!
