### ISSUE TITLE
Associate Office 365 tenant with Azure Subscription

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/OfficeDocs-Enterprise#267]
The video for Associating O365 tenant with Azure Subscription is quite confusing and appears to be outdated. Is there latest video available for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdf56d0-5b7a-f0df-86c2-14ce1c067514
* Version Independent ID: 76a8737d-8f21-56ae-93f5-5d7942813484
* Content: [Subscriptions, licenses, accounts, and tenants for Microsoft's cloud offerings](https://docs.microsoft.com/en-us/office365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings)
* Content Source: [Enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
@Anand-Moghe thank you very much for the feedback. We are looking into this, and an update will be posted here soon. Happy New Year!

**Comment by JoeDavies-MSFT** [comment]
@Anand-Moghe Can you describe the video you are referring to? This article does not contain one. Thank you.

**Comment by Anand-Moghe** [comment]
@JoeDavies-MSFT I was referring to link on this [page](https://docs.microsoft.com/en-us/office365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings) , which is referring to video [here](https://channel9.msdn.com/Series/Microsoft-Azure-Tutorials/Associate-an-Office-365-tenant-with-an-Azure-subscription).

**Comment by JoeDavies-MSFT** [comment]
@Anand-Moghe I found this article: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-subscriptions-associated-directory Can you verify that it contains the instructions you need? Thanks

**Comment by Anand-Moghe** [comment]
@JoeDavies-MSFT The article is referring to operation within single Azure Cloud. Azure AD and Microsoft Office 365 are two different cloud and they are on different AD.

**Comment by Anand-Moghe** [comment]
Closing the issue as the solution is found.
