### ISSUE TITLE
Dynamics365 DevOps architecture guidelines and steps

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/OfficeDocs-Enterprise#268]
I am looking for some guidance on how to go about setting up Azure DevOps for Microsoft Dynamics365.

Do you recommend using the Microsoft Dynamics365 subscription ID to login to Azure DevOps portal to create Azure DevOps Pipeline for Microsoft Dynamics365? Or do I have to first associate the Dynamics365 subscription in Azure before starting up Azure DevOps for Microsoft Dynamics365? Is there any architectural guidance available for these scenarios for setting up Azure DevOps for Microsoft Dynamics365?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdf56d0-5b7a-f0df-86c2-14ce1c067514
* Version Independent ID: 76a8737d-8f21-56ae-93f5-5d7942813484
* Content: [Subscriptions, licenses, accounts, and tenants for Microsoft's cloud offerings](https://docs.microsoft.com/en-us/office365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings)
* Content Source: [Enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
@Anand-Moghe thank you for posting your questions here. We are looking into this, and an update will be posted here soon. In the meantime, can you clarify your usage of Dynamics 365 (Business Central, Customer Engagement, Finance and Operations, Retail, or Talent)?

**Comment by Anand-Moghe** [comment]
@denisebmsft  I am looking into Finance and Operation use case. But I will definitely appreciate the DevOps strategy and guidelines across all usage scenario.

**Comment by JoeDavies-MSFT** [comment]
@Anand-Moghe Have you seen the guidance at https://docs.microsoft.com/en-us/dynamics365/unified-operations/retail/dev-itpro/new-environments-visual-studio-teams-branch-retail-projects?

**Comment by Anand-Moghe** [comment]
@JoeDavies-MSFT Thanks. Yes, I looked into it. Is that applicable across all Dynamics 365 (Business Central, Customer Engagement, Finance and Operations, Retail, or Talent) DevOps Project setup? 

There are different Microsoft Clouds - Office 365, Azure Commercial, Azure US Gov. etc.

My understanding was that to use Azure DevOps one needs a subscription into **Azure Commercial**. So if I have Microsoft **Office 365 subscription**, can I use that to create a project in Azure DevOps ? Or do I need to also buy another Azure Commercial Subscription also ? That sort of information or guideline was missing in the link you provided above.

**Comment by Anand-Moghe** [comment]
@JoeDavies-MSFT I got the answer from this [link](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-azure-active-directory-groups?view=vsts&tabs=new-nav) . So closing the issue.
