### ISSUE TITLE
Coexist 2 TokenIssuer in SPS

### ISSUE THREAD

**Issue by CSART69** [MicrosoftDocs/OfficeDocs-Enterprise#27]
Hi
I'm using a TokenIssuer using ADFS since weeks. Now I want to implement direct connexion to AzureAD as described in this article. For the test, and to avoid any issue on the existing web application using ADFS I create a new Web Application using this new provider.
The issue is that this new Web Application is still using the URL of the ADFS server in the wrealm parameter. I don't understand as I use a different realm for this new provider but it seems it isn't taken into account.
Any idea ?

**Comment by kaevans** [comment]
Are you saying that you want one web application to support both AAD and ADFS? If you only want one, then go to the settings for the Web Application and uncheck the ADFS provider for the zone (or all zones).

**Comment by CSART69** [comment]
Already done.

I have WebApp1 with ADFS provider (that I configured at first) and WebApp2 with DirectAAD provider (that I configured after). Only 1 provider per Webapp.

I’ve tried with a direct link : https://WebApp2/_trust/Default.aspx?trust=DirectAAD and then it is working, so my configuration is ok. But when I just type https://WebApp2, it is using the ADFS provider and doesn’t take into account the provider defined in Central Admin.

Maybe a cache somewhere ?

Already restarted everthing.

I’ve checked through powershell (Get-SPProvider…) and it is correctly defined…. But it is not taken into account.

Christophe

**Comment by kaevans** [comment]
Recommend trying InPrivate browser in IE/Edge, or InCognito in Chrome. This prevents caching of cookies for a particular user account and lets you switch between web applications and types of users.

**Comment by denisebmsft** [comment]
Thanks for your help, Kirk. And thanks CSART69 for the feedback/questions.

**Comment by kaevans** [comment]
Sorry you are having difficulties. The article works as written, the behavior is specific to your environment. Please contact Microsoft Support for assistance troubleshooting your configuration.

**Comment by denisebmsft** [comment]
CSART69, I hope you were able to get help from support.
