### ISSUE TITLE
Higher ports to be added for accomodating Direct Routing scenario

### ISSUE THREAD

**Issue by savusca** [MicrosoftDocs/OfficeDocs-Enterprise#270]
Skype for Business Online and Microsoft Teams section, for media requires only ports 3478-3481 to be opened towards 13.107.64.0/18, 52.112.0.0/14.

Higher ports 49 152 – 53 247 (UDP) needs to be opened towards 52.112.0.0/14 in order to accomodate Direct Routing scenarios, as per below documentation:
https://docs.microsoft.com/en-us/microsoftteams/direct-routing-plan#sip-signaling-fqdns-and-firewall-ports

Please change:

11 | OptimizeRequired | Yes | 13.107.64.0/18, 52.112.0.0/14 | UDP:3478, 3479, 3480, 3481
-- | -- | -- | -- | --

to:

11 | OptimizeRequired | Yes | 13.107.64.0/18, 52.112.0.0/14 | UDP:3478, 3479, 3480, 3481, 49152 – 53247 (Direct Routing Scenario)
-- | -- | -- | -- | --

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@savusca - thanks for the feedback, I'll get this over to the Enterprise content team for action.

**Comment by JoeDavies-MSFT** [comment]
@savusca Sorry for the delay. I have forwarded this issue to the product team that maintains this portion of the article for their consideration. Thanks for letting us know.
