### ISSUE TITLE
Seat Requirements

### ISSUE THREAD

**Issue by danielgatley** [MicrosoftDocs/OfficeDocs-Enterprise#273]
Unless i'm missing it the docs don't seem to detail the &gt;5K seat requirement.  We are a global (40+ countries) 1K seat organisation and multi-geo would solve some major data residency issues we currently have, so I keep checking back to see in the hope this restriction has changed.  It would be nice if the docs highlighted that restriction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f3a2c9-0399-218d-cf9a-eb0f16fcbbb0
* Version Independent ID: da6ada6e-ce41-f772-74b8-144cf540d423
* Content: [Multi-Geo Capabilities in OneDrive and SharePoint Online in Office 365](https://docs.microsoft.com/en-us/office365/enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365)
* Content Source: [Enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by StevenProvo** [comment]
Even MSFT website is not sure about it...
The en-us website states a minimum of 2500 seats (https://products.office.com/en-us/business/multi-geo-capabilities)
The european website states a minimum of 5000 seats...

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @danielgatley , please check PR #373 

Thank you

**Comment by mypil** [comment]
@danielgatley - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
