### ISSUE TITLE
Command "$licenses[<index>].ServicePlan" should be "$licenses[<index>].ServicePlans"

### ISSUE THREAD

**Issue by sparkf1** [MicrosoftDocs/OfficeDocs-Enterprise#275]
Hi, the command "$licenses[&lt;index&gt;].ServicePlan" which mentioned in below URL is not correct, that should be "$licenses[&lt;index&gt;].ServicePlans".

Article URL is "https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-licenses-and-services-with-office-365-powershell"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3baa87d3-9496-9bd2-739f-a136c1daacf3
* Version Independent ID: cfcd455b-36b0-53d6-80b4-805695919742
* Content: [View licenses and services with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-licenses-and-services-with-office-365-powershell)
* Content Source: [Enterprise/powershell/view-licenses-and-services-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/view-licenses-and-services-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@sparkf1 - thanks so much for the feedback, I'll get this over to the Enterprise content team for review.

**Comment by JoeDavies-MSFT** [comment]
@sparkf1 This is updated and published. Sorry for the inconvenience. Thanks for letting us know.
