### ISSUE TITLE
O365 Previously Authenticated session is still active after user is Signed Out

### ISSUE THREAD

**Issue by uz-it** [MicrosoftDocs/OfficeDocs-Enterprise#276]
[Enter feedback here]
I do not know where to paste this feed back, lets try here.

How to reproduce:
Start Edge browser in InPrivate mode.
1. Login to Office portal: https://www.office.com with adminaccount1@testtenant1.onmicrosoft.com
2. Click on "Sign Out" under My Account in top right.
3. Do not restart browser.
4. Click "Login as different user"
5. Login with adminaccount2@testtenant2.onmicrosoft.com
6. Click My account->My Account in top right  -> you'll see adminaccount1@testtenant1.onmicrosoft.com account information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1570de51-50b1-d4cc-c1c7-832b3242ccb3
* Version Independent ID: f5250f91-0a48-20cf-8e2c-e2dc347edd88
* Content: [Session timeouts for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/session-timeouts)
* Content Source: [Enterprise/session-timeouts.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/session-timeouts.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
Thanks for that excellent write-up of the process, @uz-it. You need to show other people this skill of yours -- it would make my job easier. 

It sounds to me as though you're using Edge (or another tabbed browser). Each tab in that browser is in the same browser session. You need to shut the browser to end the session (and some Office 365 pages will also direct you to). If you're testing, open your test browsers with a RunAs command, and if you need the Edge browser in Kiosk mode (to control session time-out), or you'd like to talk about another solution entirely (like making each tab a separate session), I would, for sure, go to Support for the browser to ask that question!
