### ISSUE TITLE
Cmdlets no longer available

### ISSUE THREAD

**Issue by argumemnon** [MicrosoftDocs/OfficeDocs-Enterprise#277]
This documentation is now inaccurate as the cmdlets for SharePoint have been deprecated as MS has moved over to their Graph API as of two years ago. See https://techcommunity.microsoft.com/t5/Office-365-Blog/Announcing-the-General-Availability-of-Microsoft-Graph-reporting/ba-p/137838

It would be nice to see this article updated to reflect the changes or at least notifying users of the removal of the cmdlets with PowerShell v6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0096189e-b3e3-e26e-2d55-711323ab2a5f
* Version Independent ID: 50d5393d-2dac-869a-8ade-dc2fc3d7a4cf
* Content: [Manage SharePoint Online users and groups with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-sharepoint-users-and-groups-with-powershell)
* Content Source: [Enterprise/powershell/manage-sharepoint-users-and-groups-with-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/manage-sharepoint-users-and-groups-with-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@argumemnon The article does not use any of the SharePoint Online cmdlets that were included in the deprecation in the cited blog post above. I have tested the commands and they work as documented.
