### ISSUE TITLE
TestConnectivity.Microsoft.com IP ranges missing in current link

### ISSUE THREAD

**Issue by Kovai-MSFT** [MicrosoftDocs/OfficeDocs-Enterprise#278]
TestConnectivity's IP ranges used to be in this URL earlier, no more seen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#exchange-online)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@Kovai-MSFT - thanks for your feedback, I'll get this over to the Enterprise content team for clarification.

**Comment by JoeDavies-MSFT** [comment]
@Kovai-MSFT We are not publishing IP addresses for Default category endpoints. See https://techcommunity.microsoft.com/t5/Office-365-Networking/Why-are-some-Office-365-network-endpoints-provided-as-URLs-only/m-p/310490#M97 for more details.
