### ISSUE TITLE
Notify on changes to API

### ISSUE THREAD

**Issue by stukey** [MicrosoftDocs/OfficeDocs-Enterprise#279]
Is it possible to notify us when changes are made to the API? e.g. you added the ‘impact’ element to each record returned by the changes web method in Nov 2018 and I only just noticed. It would be helpful to be informed when new properties and methods are added to this API. I am not a regular user of github, so I’m not sure if that feature is available in github or if Microsoft could just document changes to the API in an RSS feed or email subscription?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7ebf92c-e478-0f65-0494-97042e974b46
* Version Independent ID: 7e1b9b91-d60d-8665-9a39-2ca77a46b4ce
* Content: [Office 365 IP Address and URL Web service](https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service)
* Content Source: [Enterprise/office-365-ip-web-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by robmazz** [comment]
@stukey - thanks for your feedback, I'll get this over to the Enterprise content team for consideration.

**Comment by kelleyvice-msft** [comment]
@stukey - You can follow the **Office 365 networking community forum** at [Office 365 Networking](https://techcommunity.microsoft.com/t5/Office-365-Networking/bd-p/Office365Networking) to be notified when new attributes are added or other important changes are made to the web service. 

Thanks,
Kelley
