### ISSUE TITLE
Updates for 2016 / 2019

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Enterprise#281]
Need updated content for 2016 and 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0de63152-e5c3-0a29-a201-842acb3f06c0
* Version Independent ID: bc9c39ef-c32c-8d2d-9b49-36882f133c82
* Content: [Architectural models for SharePoint, Exchange, Skype for Business, and Lync](https://docs.microsoft.com/en-us/office365/enterprise/architectural-models-for-sharepoint-exchange-skype-for-business-and-lync#Exch2013_options)
* Content Source: [Enterprise/architectural-models-for-sharepoint-exchange-skype-for-business-and-lync.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/architectural-models-for-sharepoint-exchange-skype-for-business-and-lync.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@danmyhre - thanks for the feedback, I'll get this over to the Enterprise content team for investigation.

**Comment by JoeDavies-MSFT** [comment]
@danmyhre I will add your feedback to the backlog of content requests. Thanks for letting us know.
