### ISSUE TITLE
Faulty script

### ISSUE THREAD

**Issue by abr3ll** [MicrosoftDocs/OfficeDocs-Enterprise#282]
You should probably update the foreach loop under "Use the Azure Active Directory PowerShell for Graph module".
It calls the the variable $user that does not exist. Would need to be $_ instead.

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 5cdc030a-0015-fe77-eac3-4c5070c0c5a3
* Version Independent ID: 24107b9c-1f13-571c-1303-6019ba64dcea
* Content: [View licensed and unlicensed users with Office 365 PowerShell](https://docs.microsoft.com/sv-se/office365/enterprise/powershell/view-licensed-and-unlicensed-users-with-office-365-powershell)
* Content Source: [Enterprise/powershell/view-licensed-and-unlicensed-users-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/view-licensed-and-unlicensed-users-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@abr3ll - thanks for the feedback - I'll get this over to the Enterprise content team for consideration.

**Comment by JoeDavies-MSFT** [comment]
@abr3ll You are correct and I have updated the article. Must have been a copy-paste error on my part. Sorry for the inconvenience.
