### ISSUE TITLE
Update IP address for 4 FQDN

### ISSUE THREAD

**Issue by vishnutj** [MicrosoftDocs/OfficeDocs-Enterprise#283]
In the article, under Microsoft 365 Common and Office Online (59), the following URLs are mentioned, but not the IP addresses. This is causing customers to call Support to verify whether messages they are receiving to whitelist the IP addresses are legitimate because the article doesn’t list them.

The request is to add the following IP address to the list:

13.107.246.10 - aadcdn.msauth.net
117.18.232.200 - aadcdn.msftauth.net
23.8.180.58 - ccscdn.msauth.net
23.8.180.58 - ccscdn.msftauth.net

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%2fen-us%2farticle%2fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@vishnutj - thanks for the feedback, I'll get this over to the Enterprise content team for consideration.

**Comment by JoeDavies-MSFT** [comment]
@vishnutj We do not provide IP addresses for default category endpoints. See https://techcommunity.microsoft.com/t5/Office-365-Networking/Why-are-some-Office-365-network-endpoints-provided-as-URLs-only/m-p/310490#M97 for the details. Thanks for your feedback.
