### ISSUE TITLE
IP address ranges mismatch in JSON format - 40.92.0.0/14, 40.107.0.0/17. In JSON Format we see as 40.92.0.0/15", "40.107.0.0/16"

### ISSUE THREAD

**Issue by vishnutj** [MicrosoftDocs/OfficeDocs-Enterprise#284]
*.protection.outlook.com
23.103.132.0/22, 23.103.136.0/21, 23.103.144.0/20, 23.103.198.0/23, 23.103.200.0/22, 40.92.0.0/14, 40.107.0.0/17, 52.100.0.0/14, 52.238.78.88/32, 65.55.88.0/24, 65.55.169.0/24, 94.245.120.64/26, 104.47.0.0/17, 157.55.234.0/24, 157.56.110.0/23, 157.56.112.0/24, 207.46.100.0/24, 207.46.163.0/24, 213.199.154.0/24, 213.199.180.128/26, 216.32.180.0/23, 2a01:111:f400:7c00::/54, 2a01:111:f403::/48

When we download the same info in JSON format https://endpoints.office.com/endpoints/worldwide?clientrequestid=b10c5ed1-bad1-445f-b386-b919946339a7

"id": 9,
    "serviceArea": "Exchange",
    "serviceAreaDisplayName": "Exchange Online",
    "urls": [
      "*.protection.outlook.com"
    ],
    "ips": [
      "23.103.132.0/22",
      "23.103.136.0/21",
      "23.103.144.0/20",
      "23.103.198.0/23",
      "23.103.200.0/22",
      "40.92.0.0/15",
      "40.107.0.0/16", 

When we lookup the same info usin J SON format we see the ranges not to be accurate.

CIDR Range	40.92.0.0/14		CIDR Range	40.92.0.0/15
First IP	40.92.0.0		First IP	40.92.0.0
Last IP	40.95.255.255		Last IP	40.93.255.255
Total Host	262144		Total Host	131072
				
				
CIDR Range	40.107.0.0/17		CIDR Range	40.107.0.0/16
First IP	40.107.0.0		First IP	40.107.0.0
Last IP	40.107.127.255		Last IP	40.107.255.255
Total Host	32768		Total Host	65536

	Customer is looking for clarity on which are the updated list and also want to confirm that there are no other mismatches as this by the concerned team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%2fen-us%2farticle%2fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@vishnutj - thanks for the feedback, I'll send this to the Enterprise content team for clarification.

**Comment by JoeDavies-MSFT** [comment]
@vishnutj Due the current way the endpoints are updated and published, you should rely on the web services for the current list of endpoints. Depending on the timing of the update cycle, the "Office 365 URLs and IP address ranges" article may be 1-2 days out of date.
