### ISSUE TITLE
Doesn't work any more

### ISSUE THREAD

**Issue by bkeski** [MicrosoftDocs/OfficeDocs-Enterprise#286]
This method is being deprecated as of January 29, 2018. See details, and information on replacement MS Graph APIs available at https://techcommunity.microsoft.com/t5/Off
ice-365-Blog/Announcing-the-General-Availability-of-Microsoft-Graph-reporting/ba-p/137838

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecfa36f6-cbed-3eec-d668-c071214ca86f
* Version Independent ID: 9997e469-4374-354c-ca5b-4742a2522f19
* Content: [Aggregate customer reporting data via Windows PowerShell for Delegated Access Permission (DAP) partners](https://docs.microsoft.com/en-us/office365/enterprise/powershell/aggregate-customer-reporting-data-via-windows-powershell-for-delegated-access-pe)
* Content Source: [Enterprise/powershell/aggregate-customer-reporting-data-via-windows-powershell-for-delegated-access-pe.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/aggregate-customer-reporting-data-via-windows-powershell-for-delegated-access-pe.md)
* Service: **o365-administration**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @mypil , looks like the article need to be rewritten (to use Graph APIs [reportRoot: getMailboxUsageDetail](https://docs.microsoft.com/graph/api/reportroot-getmailboxusagedetail) instead of cmdlet Get-MailboxActivityReport) or completely removed, as PowerShell cmdlets cannot be used for reporting any more. 
For details, link provided by @bkeski  could be used.
Thank you

**Comment by mypil** [comment]
@chrfox - can you please share your insights on this issue? Please advise on how to proceed with this.

Thank you.

**Comment by chrfox** [comment]
Checking with the technical owners on updates.

**Comment by mypil** [comment]
@chrfox - Do you have any updates on this? Thank you.

**Comment by mypil** [comment]
@chrfox - I would like to follow up with you. Do you have any update? Thank you.

**Comment by chrfox** [comment]
the document has been removed
