### ISSUE TITLE
You're still using SharePoint Server 2013??

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/OfficeDocs-Enterprise#289]
We guess SharePoint Server 2013 is no long the way to go.
You don't think this docs should be up to date?? 
2013 is 6 years ago...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bb96b5d-b2b9-68b0-c383-f49725f68e86
* Version Independent ID: f89175b4-de29-0aa8-511c-f3ad015a0664
* Content: [Office 365 integration with on-premises environments](https://docs.microsoft.com/en-us/office365/enterprise/office-365-integration)
* Content Source: [Enterprise/office-365-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-integration.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@schittli - thanks for your feedback! Yes - we are actively working to update these docs as part of a larger refresh of the Office 365 content and as we bring newer Microsoft 365 content online. Thanks for pointing this out and I'll make sure it's updated during the refresh.
