### ISSUE TITLE
Download link at top is old module?

### ISSUE THREAD

**Issue by marklitwin** [MicrosoftDocs/OfficeDocs-Enterprise#290]
New module appears to be available in PowerShell gallery?  
https://www.powershellgallery.com/packages/O365CentralizedAddInDeployment/1.4.0.0 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 680b165b-5c8b-66c4-f9f4-0e20b8666f19
* Version Independent ID: cb17922d-a250-90d8-79d9-ee4662208eec
* Content: [Use the Centralized Deployment PowerShell cmdlets to manage add-ins](https://docs.microsoft.com/en-us/office365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins)
* Content Source: [Enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by cmcapellan** [comment]
Yes...please update link and remove old docs...was stuck until I saw @marklitwin's feedback. Thanks marklitwin!

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@marklitwin - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
