### ISSUE TITLE
404 missing link

### ISSUE THREAD

**Issue by JellyKid** [MicrosoftDocs/OfficeDocs-Enterprise#292]
The link in the following sentence is dead
"You can also review the Azure AD Connect version release history to see what is included and fixed in each release."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2363e1c8-0003-dbb2-194f-10b25b732b8d
* Version Independent ID: ac43d1f5-f0e2-7818-0913-53a590c7a7e0
* Content: [Set up directory synchronization for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/set-up-directory-synchronization)
* Content Source: [Enterprise/set-up-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/set-up-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@JellyKid - thanks for the feedback, broken link has been fixed and re-publishing topic now.
