### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/OfficeDocs-Enterprise#294]
Can we have these images fixed to display properly on Dark background? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 132cbf89-c6a0-cbe2-dd7e-5e449ce2f390
* Version Independent ID: 787afe5f-0111-a1f0-d33c-4ac4260b846b
* Content: [Azure ExpressRoute for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/azure-expressroute)
* Content Source: [Enterprise/azure-expressroute.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/azure-expressroute.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by robmazz** [comment]
@dcbrown16 - thanks for the feedback, I'll get this over to the Enterprise content team for action.

**Comment by kelleyvice-msft** [comment]
Updated images to display correctly in dark mode. Thanks @dcbrown16
