### ISSUE TITLE
Please automate the lot

### ISSUE THREAD

**Issue by jharms** [MicrosoftDocs/OfficeDocs-Enterprise#295]
Sometimes people just want the whole lot set up from scratch. Can't you just have a template ready to go with all the PS loaded up to automate the entire process from Azure build to connecting it to O365 for a trial. 

It's painful re-reading every step to make sure you have done it correctly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 128ee858-9946-1cfc-712a-c014f5353e97
* Version Independent ID: d513be8b-9c9a-eb6f-d6a9-d6c3afcace49
* Content: [Office 365 dev/test environment](https://docs.microsoft.com/en-us/office365/enterprise/office-365-dev-test-environment#feedback)
* Content Source: [Enterprise/office-365-dev-test-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-dev-test-environment.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@jharms - thanks for the feedback, I'll get this over to the Enterprise content team for consideration.

**Comment by JoeDavies-MSFT** [comment]
@jharms We have an ARM template to build out the simulated intranet. I will add the automated Office 365 trail subscription configuration to the list of content requests to address. Thanks for letting us know.
