### ISSUE TITLE
What to do when Admin Center is down?

### ISSUE THREAD

**Issue by TiloGit** [MicrosoftDocs/OfficeDocs-Enterprise#297]
What is the best approach if admin center is down? 

https://portal.office.com/landing give us 
```
You can try refreshing the page to solve the problem. You can also wait a few minutes and try again.
Close Support Information
Correlation ID:
wus#392319a9-a287-4ca2-b932-21dc4d12a1a2
Error code:
0
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd2a834a-296b-1c7d-7358-6f6a19f8f3c3
* Version Independent ID: 9ab6adbe-c651-d833-f395-64b7cddb2dd2
* Content: [How to check Office 365 service health](https://docs.microsoft.com/en-us/office365/enterprise/view-service-health?redirectSourcePath=%252fen-us%252farticle%252fhow-to-check-office-365-service-health-932ad3ad-533c-418a-b938-6e44e8bc33b0)
* Content Source: [Enterprise/view-service-health.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/view-service-health.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by fowl2** [comment]
There is https://status.office365.com/, which doesn't require authentication.

It would be great if this could be mentioned on this page somewhere.

**Comment by robmazz** [comment]
@fowl2 - great suggestion, I've updated the topic. @TiloGit - check  https://status.office365.com/ and please contact support if you are still having issues with accessing your tenant. https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products

**Comment by nddsoft** [comment]
Hi,
Unfortunately, this isn't working.  Currently office 365 services are down, such as One Drive, Office 365 apps and portal website.  However, https://status.office365.com/ is working and says no problem.  When clicking on the link "View your Microsoft 365 Service health.", you go here: https://portal.office.com/adminportal/home#/servicehealth, but portal.office.com is down.
