### ISSUE TITLE
Outdated diagram?

### ISSUE THREAD

**Issue by pazdedav** [MicrosoftDocs/OfficeDocs-Enterprise#299]
Isn’t the diagram in this article outdated? Azure ExpressRoute has only two types of peering: private and Microsoft (that includes access to Azure PaaS).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19703c82-ecc1-57d8-10e0-55d08cc0b8e8
* Version Independent ID: c228da5e-ef65-d8e2-ce8f-f8bb3623c56b
* Content: [Hybrid cloud overview](https://docs.microsoft.com/en-us/Office365/Enterprise/hybrid-cloud-overview?wt.mc_id=docsmsft-twitter)
* Content Source: [Enterprise/hybrid-cloud-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/hybrid-cloud-overview.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@pazdedav You are corrected. The figure has been updated. Thanks for letting us know.
