### ISSUE TITLE
Does not list necessary DNS records

### ISSUE THREAD

**Issue by JoshJ-MSFT** [MicrosoftDocs/OfficeDocs-Enterprise#301]
The following article specifies various DNS records and where they need to point:
https://support.microsoft.com/en-us/help/2566790/troubleshooting-skype-for-business-online-dns-configuration-issues-in

.this article (that I'm commenting on now) mentions alternate DNS records and mentions IPs.  It does not however say for example. what _sip._tls.&lt;domain&gt; should be pointing to.

Net result - DoD customer do not know what to setup DNS to point to and it's generating Critsit cases to support (me).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58bf69f3-b268-a5e6-2db8-63c496137226
* Version Independent ID: d8449616-ae9c-1b7b-224b-9f3f12d8a669
* Content: [Office 365 U.S. Government DoD endpoints](https://docs.microsoft.com/en-us/office365/enterprise/office-365-u-s-government-dod-endpoints)
* Content Source: [Enterprise/office-365-u-s-government-dod-endpoints.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-u-s-government-dod-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@JoshJ-MSFT - thank for the feedback, I'll get this over to the Enterprise content team for investigation.

**Comment by JoeDavies-MSFT** [comment]
@JoshJ-MSFT Moving this as a discussion inside Microsoft. Thanks for letting us know.
