### ISSUE TITLE
Include Office 365 Reporting API domain name in list

### ISSUE THREAD

**Issue by gabrielnovoa** [MicrosoftDocs/OfficeDocs-Enterprise#302]
Please, include "reportsweu.office.com" with IP: [13.69.251.46] to the list.
It's related to Office 365 Reporting API

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@gabrielnovoa  I will forward this to the product team members responsible for these lists for their consideration. Thanks
