### ISSUE TITLE
"Office 365 エンドポイントを管理します。" needs to be replaced with "Office 365エンドポイントの管理"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-Enterprise#303]
https://docs.microsoft.com/ja-jp/Office365/Enterprise/nat-support-with-office-365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 126f74f1-8e44-1409-049b-df8903412ef2
* Version Independent ID: f815f108-a9ff-8f4c-2a11-0c3073451c50
* Content: [NAT support with Office 365](https://docs.microsoft.com/en-us/Office365/Enterprise/nat-support-with-office-365)
* Content Source: [Enterprise/nat-support-with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/nat-support-with-office-365.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by MollyMalone** [comment]
Thanks for the feedback, shared with the localization vendors who will review and fix as appropriate.

**Comment by MollyMalone** [comment]
@hyoshioka0128 the issue is now fixed as you suggested.
