### ISSUE TITLE
Link en-us → ja-jp [Office 365エンドポイントの管理]

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-Enterprise#304]
https://docs.microsoft.com/ja-jp/Office365/Enterprise/nat-support-with-office-365

[Office 365 エンドポイントを管理します。](https://docs.microsoft.com/en-us/office365/enterprise/managing-office-365-endpoints?redirectSourcePath=%252farticle%252f99cab9d4-ef59-4207-9f2b-3728eb46bf9a)
↓
[Office 365エンドポイントの管理](https://docs.microsoft.com/ja-jp/office365/enterprise/managing-office-365-endpoints?redirectSourcePath=%252farticle%252f99cab9d4-ef59-4207-9f2b-3728eb46bf9a)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 126f74f1-8e44-1409-049b-df8903412ef2
* Version Independent ID: f815f108-a9ff-8f4c-2a11-0c3073451c50
* Content: [NAT support with Office 365](https://docs.microsoft.com/en-us/Office365/Enterprise/nat-support-with-office-365)
* Content Source: [Enterprise/nat-support-with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/nat-support-with-office-365.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by hyoshioka0128** [comment]
Sorry for my poor English.
Q: link on the Japanese content page ?
A:
(1) No problem with Japanese content page link。
 [Office 365 エンドポイントの管理](https://docs.microsoft.com/ja-jp/office365/enterprise/managing-office-365-endpoints) is displayed in Japanese.
(2) #303 "[Office 365 エンドポイントを管理します。]" needs to be replaced with "[Office 365エンドポイントの管理]"

**Comment by denisebmsft** [comment]
@hyoshioka0128 and @MollyMalone, is the title correct on this page (in the Japanese locale):
https://docs.microsoft.com/ja-jp/Office365/Enterprise/nat-support-with-office-365

**Comment by hyoshioka0128** [comment]
@MollyMalone, @denisebmsft Thanks.
