### ISSUE TITLE
Use cases for each item

### ISSUE THREAD

**Issue by ewoodrick** [MicrosoftDocs/OfficeDocs-Enterprise#305]
When looking at the Exchange section, for example, there is a list of 10 IDs, each with a category and a few with additional information in the category. 
There is no specific statement of client vs server connection (although some implication can be applied)
There is no indication if it is inbound or outbound traffic.

I need to configure a client firewall in front of their Exchange Servers to limit traffic to Office 365 only. Is that rules I, 9, and 10?
Rule ID 2 is labeled as SMTP, but I believe, since it is port 587, that in reality it is outbound relay traffic only?

Another example is ID 47. It it really required for ALL implementations? IDs 49, 50, 51?

How would I block ID 4 with a simple firewall? No IPs listed. I suspect that it is outbound only, but do clients need it, or only servers?

It is quite common for servers to bypass proxies and have direct paths in enterprises, but these paths are often quite restrictive. 

I believe that this information was available in the previously published version.

**Comment by robmazz** [comment]
@ewoodrick - haven't heard back from you regarding the topic in question, closing this issue.
