### ISSUE TITLE
Showing "**Office 365 IP アドレスと URL の Web サービス **"(Markdown notation)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-Enterprise#307]
https://docs.microsoft.com/ja-jp/office365/enterprise/office-365-ip-web-service

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7ebf92c-e478-0f65-0494-97042e974b46
* Version Independent ID: 7e1b9b91-d60d-8665-9a39-2ca77a46b4ce
* Content: [Office 365 IP Address and URL Web service](https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service)
* Content Source: [Enterprise/office-365-ip-web-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by robmazz** [comment]
@hyoshioka0128 - thanks for the feedback, I've assigned the topic author to this issue for consideration.

**Comment by OfficeGlobal** [comment]
@MollyMalone : Bug 3226084
___
@hyoshioka0128 , @robmazz We've fixed the title, no extra asterisks appears
