### ISSUE TITLE
[電源の BI および ExpressRoute] needs to be replaced with [Power BI と ExpressRoute]

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-Enterprise#308]
https://docs.microsoft.com/ja-jp/office365/enterprise/managing-office-365-endpoints
[電源の BI および ExpressRoute] → [Power BI と ExpressRoute]

[Power BI と ExpressRoute](https://docs.microsoft.com/ja-jp/power-bi/service-admin-power-bi-expressroute)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8762d73c-32fc-a4f9-162a-b81ae4052ea3
* Version Independent ID: 554cc99d-b929-8db0-7ab7-0f666438e8cf
* Content: [Managing Office 365 endpoints](https://docs.microsoft.com/en-us/office365/enterprise/managing-office-365-endpoints)
* Content Source: [Enterprise/managing-office-365-endpoints.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/managing-office-365-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@hyoshioka0128 - thanks for the feedback, I'll get this over to the Enterprise content team for consideration.

**Comment by JoeDavies-MSFT** [comment]
@hyoshioka0128 The link text has been updated. Thanks for letting us know.
