### ISSUE TITLE
Showing "** FastTrack**" (Markdown notation)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-Enterprise#309]
https://docs.microsoft.com/ja-jp/office365/enterprise/configure-services-and-applications

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fd40d4b-fc4c-537b-5081-8b7e616bd3f7
* Version Independent ID: 543ca399-9dec-fff8-4344-f0a9bd04f008
* Content: [Configure Office 365 Enterprise services and applications](https://docs.microsoft.com/en-us/office365/enterprise/configure-services-and-applications)
* Content Source: [Enterprise/configure-services-and-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/configure-services-and-applications.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@hyoshioka0128 - thanks for the feedback, I'll get this over to our localization team for correction.
