### ISSUE TITLE
"種類" needs to be replaced with "Type".

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-Enterprise#310]
https://docs.microsoft.com/en-us/office365/enterprise/managing-office-365-endpoints

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8762d73c-32fc-a4f9-162a-b81ae4052ea3
* Version Independent ID: 554cc99d-b929-8db0-7ab7-0f666438e8cf
* Content: [Managing Office 365 endpoints](https://docs.microsoft.com/en-us/office365/enterprise/managing-office-365-endpoints)
* Content Source: [Enterprise/managing-office-365-endpoints.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/managing-office-365-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@hyoshioka0128 - thanks for the feedback, I'll get this over to the Enterprise content team to correct the localization issue.

**Comment by JoeDavies-MSFT** [comment]
@hyoshioka0128 Can you provide your English version of "種類"? I am not finding the word "kind". Thanks

**Comment by hyoshioka0128** [comment]
made a mistake. In the Japanese page "種類" → "型".
Japanese : https://docs.microsoft.com/ja-jp/office365/enterprise/managing-office-365-endpoints

**Comment by JoeDavies-MSFT** [comment]
@hyoshioka0128 I have forwarded this issue to our localization staff for investigation. Thanks for letting us know.

**Comment by OfficeGlobal** [comment]
The article has been HumanTranslated and published live. Translation of "Type" changed properly
