### ISSUE TITLE
"Skype ビジネスおよびマイクロソフトのチーム" needs to be replaced with "Skype for Business と Microsoft Teams". 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-Enterprise#311]
https://docs.microsoft.com/en-us/office365/enterprise/managing-office-365-endpoints

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8762d73c-32fc-a4f9-162a-b81ae4052ea3
* Version Independent ID: 554cc99d-b929-8db0-7ab7-0f666438e8cf
* Content: [Managing Office 365 endpoints](https://docs.microsoft.com/en-us/office365/enterprise/managing-office-365-endpoints)
* Content Source: [Enterprise/managing-office-365-endpoints.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/managing-office-365-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@hyoshioka0128 - thanks for the feedback, I'll get this over to the Enterprise content team to correct the localization issue.

**Comment by MollyMalone** [comment]
@hyoshioka0128 Thank you for reporting this issue. However we will not fix the over-translation of Skype for Business and Microsoft Teams at this time. It is a known issue that some of our Product names are being unnecessarily translated by the machine translation tool. We are investigating a tool solution to fix these issues. At this time we can not fix each issue individually.
