### ISSUE TITLE
Showing <!---

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-Enterprise#312]
https://docs.microsoft.com/ja-jp/office365/enterprise/microsoft-cloud-it-architecture-resources?cid=kerryherger

決定することができます。
&lt;!---
Microsoft Cloud Services and Platform Options

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096f9573-ba23-b0a0-23dc-7b0eb57a17d8
* Version Independent ID: 45643fe7-700e-8eca-b7b9-563327472d6b
* Content: [Microsoft cloud IT architecture resources](https://docs.microsoft.com/en-us/office365/enterprise/microsoft-cloud-it-architecture-resources?cid=kerryherger)
* Content Source: [Enterprise/microsoft-cloud-it-architecture-resources.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/microsoft-cloud-it-architecture-resources.md)
* Service: **o365-solutions**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by robmazz** [comment]
@hyoshioka0128 - thanks for the feedback, I'll get this over to the Enterprise content team to correct the localization issue.

**Comment by BrendaCarter** [comment]
Thank you for the feedback. We're working on it . . .

**Comment by MollyMalone** [comment]
@hyoshioka0128 Good bug, thanks for reporting.  It also occurs on other languages.  I reported to the localization vendors who will fix it soon.

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.

**Comment by MollyMalone** [comment]
@hyoshioka0128 This issue is now fixed.  Thanks again for reporting it!
