### ISSUE TITLE
Showing "--->"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-Enterprise#313]
https://docs.microsoft.com/ja-jp/office365/enterprise/microsoft-cloud-it-architecture-resources?cid=kerryherger

Learn how Microsoft's own IT department is migrating to these cloud services and building its hybrid cloud. 
---&gt;
エンタープライズ アーキテクトのための Microsoft クラウド ID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096f9573-ba23-b0a0-23dc-7b0eb57a17d8
* Version Independent ID: 45643fe7-700e-8eca-b7b9-563327472d6b
* Content: [Microsoft cloud IT architecture resources](https://docs.microsoft.com/en-us/office365/enterprise/microsoft-cloud-it-architecture-resources?cid=kerryherger)
* Content Source: [Enterprise/microsoft-cloud-it-architecture-resources.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/microsoft-cloud-it-architecture-resources.md)
* Service: **o365-solutions**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by robmazz** [comment]
@hyoshioka0128 - thanks for the feedback, I'll get this over to the Enterprise content team to correct the localization issue.

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
