### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by v-olduch** [MicrosoftDocs/OfficeDocs-Enterprise#314]
the link on this line is currently broken:
The table below focuses on Active Directory Federation Services (AD FS), we also have more information on using third-party identity providers.
https://go.microsoft.com/fwlink/?LinkId=532869

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda21e42-6860-36c2-3cf3-ba1a69463a37
* Version Independent ID: d434ba6b-f987-3e1f-7330-8560b8d222e7
* Content: [Plan for third-party SSL certificates for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/plan-for-third-party-ssl-certificates)
* Content Source: [Enterprise/plan-for-third-party-ssl-certificates.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/plan-for-third-party-ssl-certificates.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@v-olduch - thanks for the feedback, the link has been updated and should appear in the public topic soon.
