### ISSUE TITLE
Error in PAC script

### ISSUE THREAD

**Issue by awesdorp** [MicrosoftDocs/OfficeDocs-Enterprise#315]
After viewing the script code i think there is an error. With type two, i see a check on the going explicit via proxy declaration of notin "allow" and "optimize". Basically it would result in the category "default" listing, but because there is a where clausule after that only include the urls listed in direct, the result is one URL entry to go via explicit proxy. I think the where clausule should do the opposite. I think the developer would only have URLs listed in the notdirect where the category is not optimize and default and exclude URLs when also listed in direct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8762d73c-32fc-a4f9-162a-b81ae4052ea3
* Version Independent ID: 554cc99d-b929-8db0-7ab7-0f666438e8cf
* Content: [Managing Office 365 endpoints](https://docs.microsoft.com/en-us/office365/enterprise/managing-office-365-endpoints)
* Content Source: [Enterprise/managing-office-365-endpoints.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/managing-office-365-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@awesdorp - thanks for the feedback, I'll get this over to the Enterprise content team for review.

**Comment by JoeDavies-MSFT** [comment]
@awesdorp I have forwarded this issue to the product team responsible for the PAC script files. They will post additional information here as needed. Thanks for letting us know.

**Comment by awesdorp** [comment]
Hi @JoeDavies-MSFT and @robmazz, its almost a year later, but i did not see any update on this matter. Can someone contact me or provide an update within the comments?
