### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by BobSegrest** [MicrosoftDocs/OfficeDocs-Enterprise#317]
A colleague of mine point me to this page as a guide for setting up my 1st Azure development farm and I have found it extremely helpful.  Like others I struggled, but if you follow the instructions the process works.  Let me offer a couple tips for those about to start.

#1 - This page is about the process of creating a new Azure environment.  It is not a big script that you load into PowerShell and run...  Some of the PowerShell commands are executed on you own system and some of them have to be executed on the new VMs you are creating AFTER you log into them.

#2 - Azure and its commands are being updated constantly.  Things are going to change, not every resource is available in ever Azure region and figuring out the changes is part of the learning curve.  Azure does a pretty good job telling you what is wrong in the error message it dumps into PowerShell.  Read these carefully and do the homework.  Asking is ok.  Quitting is just giving up...

#3 -  I found an article indicating that AzureRM commands are being deprecated.  It recommended using the command Enable-AzureRmAlias to ensure scripts written with AzureRM would still work.  It seemed that Azure provided better error information after I executed this command.  In particular, it helped me discover that the StorageAccountType StandardLRS is not available in the EastUS region that I am using.  When I changed StandardLRS to Standard_LRS in the PowerShell scripts, most of my issues with creating VMs went away.

I hope this helps the next guy get there a little quicker...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 136007e4-4ddd-a1d8-a3ac-251da6bd5311
* Version Independent ID: 5c1ec643-ac23-cf7c-c787-3ffb1b4f9674
* Content: [Base Configuration dev/test environment](https://docs.microsoft.com/en-us/office365/enterprise/base-configuration-dev-test-environment)
* Content Source: [Enterprise/base-configuration-dev-test-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/base-configuration-dev-test-environment.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@BobSegrest - thanks so much for the feedback, I'll get this over to our Enterprise content team for consideration.

**Comment by JoeDavies-MSFT** [comment]
@BobSegrest Thanks for you comments and for helping those who use this article. I was aware of the differing syntax for specifying the standard storage type. I will look into the AzureRM deprecation.
