### ISSUE TITLE
query for non-dependencies

### ISSUE THREAD

**Issue by zaikun1337** [MicrosoftDocs/OfficeDocs-Enterprise#318]
is there a way to really only grab serviceAreas withouth dependencies?
https://endpoints.office.com/endpoints/Worldwide?ServiceAreas=Exchange&ClientRequestId=b10c5ed1-bad1-445f-b386-b919946339a7
the URL above also grabs any "skype" and "common" URLs which I'd like to avoid.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7ebf92c-e478-0f65-0494-97042e974b46
* Version Independent ID: 7e1b9b91-d60d-8665-9a39-2ca77a46b4ce
* Content: [Office 365 IP Address and URL Web service](https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service)
* Content Source: [Enterprise/office-365-ip-web-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by robmazz** [comment]
@zaikun1337 - thanks for your question, I'll get this over to the Enterprise content team for action.

**Comment by kelleyvice-msft** [comment]
@zaikun1337 - I'm looking into this now, and will reply as soon as I can get some information. In the meantime, the following PowerShell script will output JSON of Exchange-specific values only:
```powershell
$uri = "https://endpoints.office.com/endpoints/Worldwide?ServiceAreas=Exchange&ClientRequestId=b10c5ed1-bad1-445f-b386-b919946339a7"
$exoEndpointsAll = Invoke-RestMethod -Uri $uri
$exoEndpoints = $exoEndpointsAll | ? {$_.serviceArea -eq "Exchange"} | ConvertTo-Json
$exoEndpoints
```
Kelley

**Comment by kelleyvice-msft** [comment]
@zaikun1337 - The information that I got from the product group is that there is no way to return records for a specific service area without its dependencies. If you have a need for that, a script like the one in my last reply is probably your best bet. I'd be interested to know more about why you prefer not to return common records; if there is a compelling reason, I can submit it as a change request.

I'll close this issue, but feel free to add further comments if you like.

Thanks,
Kelley
