### ISSUE TITLE
Why is express route not taken into consideration when gathering endpoints for sending through FWs?

### ISSUE THREAD

**Issue by keenov** [MicrosoftDocs/OfficeDocs-Enterprise#321]
For instance, if you run the script for USGovDOD, you get everything Allow and Optimize, but leave out

 Default
Required Yes domains.live.com
40.118.209.192/32, 168.62.190.41/32 TCP: 443, 80 

and 

5 Default
Required Yes attachments-dod.office365-net.us, autodiscover.&lt;tenant&gt;.mail.onmicrosoft.com, autodiscover.&lt;tenant&gt;.onmicrosoft.com TCP: 443, 80

Wouldn't we want these URLs to go express route if it's available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7ebf92c-e478-0f65-0494-97042e974b46
* Version Independent ID: 7e1b9b91-d60d-8665-9a39-2ca77a46b4ce
* Content: [Office 365 IP Address and URL Web service](https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service#example-python-script)
* Content Source: [Enterprise/office-365-ip-web-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by ojrb** [comment]
@mypil Hi ! I nave created the PR #378 based on the Issues #321 and #377, for you review to Merge ! Regards ! Orlando !

**Comment by ojrb** [comment]
Hi @mypil , as requested by @nenonix, I created one PR by Issue, in this case the new PR #387 solve only this issue, I add the edit changes recommended by @JohanFreelancer9. I add a paragraph explaining the considerations  when express route is used. Please review and Merge this new PR

**Comment by ojrb** [comment]
Hi @mypil , as requested by @nenonix, I created one PR by Issue, in this case I must deleted the other PRs because they have other files, that make confusing the  review and future merge.  I am very sorry for the inconvenience, the new PR #392  solve only this issue, I add the edit changes recommended by @JohanFreelancer9. I add a paragraph explaining the considerations when express route is used. Please review and Merge this new PR

**Comment by mypil** [comment]
@keenov - Thank you for engaging with the community here for the docs.

The article has been updated to incorporate your feedback. For your reference, kindly check on PR #403. 

We appreciate your contribution to make the docs better!
