### ISSUE TITLE
Showing "**接続エラーが発生した場合、次のトピックをご覧ください: **" (Markdown notation)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-Enterprise#323]
https://docs.microsoft.com/ja-jp/office365/enterprise/powershell/connect-to-office-365-powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@hyoshioka0128 - thanks for the feedback, I'll get this over to our Enterprise content team for review.

**Comment by JoeDavies-MSFT** [comment]
@hyoshioka0128 This issue has been forwarded to the team responsible for the Japanese version of this article. They will post more information here.

**Comment by OfficeGlobal** [comment]
The topic has been updated and published live
