### ISSUE TITLE
Connecting with Powershell with MFA Enabled

### ISSUE THREAD

**Issue by Ashley-Walton** [MicrosoftDocs/OfficeDocs-Enterprise#324]
The section of this document "Connection steps when using multi-factor authentication" does not work very well.
Initially you are prompted to sign in and you need to input your username as well as password & MFA code.
Then you immediately get prompted again to sign in (although this does populate the username this time), and you need to provide your password (again) and another MFA code.
If you add a line for connecting to Exchange Online as well, then you need to provide your password & MFA code at least 3 times.
Is there any way to cache your login details from the first prompt, or use your current session credentials for SSO authentication?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c551eb1-7ac5-cb02-cd1b-d67ca3886d85
* Version Independent ID: fb690e2e-420e-f697-60f2-39520283d385
* Content: [Connect to all Office 365 services in a single Windows PowerShell window](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window)
* Content Source: [Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Ashley-Walton There currently is no way to pass the user name and password to subsequent sign-ins when doing MFA.

**Comment by vscurtis** [comment]
so then $credential = get-credential is pretty useless and should not even be part of the outline above.

**Comment by DEberhardt** [comment]
Passing of a Credential Token without MFA is great.
With MFA it is a royal pain in the backside having to connect to 3 Services (especially if the Timout for the session is very low...) and you need to redo it 20 times a day (times 3)
Any chance this can be improved upon?
