### ISSUE TITLE
[LOC] Validate HTML comments in the article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-Enterprise#325]
Hello @BrendaCarter ,

 could you please check and update HTML comments in the article _microsoft-cloud-it-architecture-resources.md_
(https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/microsoft-cloud-it-architecture-resources.md)
We're having troubles with INTL version of the article - based on the communication with support HTML notation should be updated:

1. Replace all invalid HTML comment tags 
 a. \ to \-->
2. Remove space between open and close tag of <a>
 \<a name=""\> \</a\> to \<a name=""\>\</a\>

Related INTL issues: #313 #312

**Comment by BrendaCarter** [comment]
Greetings, this is fixed. Thank you!
