### ISSUE TITLE
Showing "**概要: ** "(Markdown notation) 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-Enterprise#326]
https://docs.microsoft.com/ja-jp/Office365/Enterprise/nat-support-with-office-365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 126f74f1-8e44-1409-049b-df8903412ef2
* Version Independent ID: f815f108-a9ff-8f4c-2a11-0c3073451c50
* Content: [NAT support with Office 365](https://docs.microsoft.com/en-us/Office365/Enterprise/nat-support-with-office-365)
* Content Source: [Enterprise/nat-support-with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/nat-support-with-office-365.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by robmazz** [comment]
@hyoshioka0128 - thanks for the feedback, I'll get this over to the Enterprise content team.

**Comment by denisebmsft** [comment]
@MollyMalone, can you take a look at this? Thanks in advance for your help!

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @denisebmsft The topic was updated and published live
___
(Bug 3205196)

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
