### ISSUE TITLE
The pictures are unclear and missed up. 

### ISSUE THREAD

**Issue by basseldamra** [MicrosoftDocs/OfficeDocs-Enterprise#327]
The pictures are unclear and missed up, it's impossible to read them. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d6fb94-5858-e752-427e-9e35371fa4b1
* Version Independent ID: 54d9ca69-39cc-a89b-a9e9-12f4d14ee110
* Content: [Routing with ExpressRoute for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/routing-with-expressroute)
* Content Source: [Enterprise/routing-with-expressroute.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/routing-with-expressroute.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by robmazz** [comment]
@basseldamra - thanks for the feedback, I'll get this over to the Enterprise content team for action.

**Comment by mypil** [comment]
@basseldamra - Thank you for submitting feedback.

Which specific picture or portion in the article is unclear and impossible to read?
Could you help us edit the article by giving us more detail or your suggestions of how we could edit the content to make that clear?

**Comment by basseldamra** [comment]
Apparently the issue appears when using the dark mode, the article has two pictures, both are disrupted in the dark mode. 

![Capture1554](https://user-images.githubusercontent.com/47389246/56126486-f9559200-5f83-11e9-8feb-842afff46a80.PNG)

**Comment by basseldamra** [comment]
The picture is edited to use a blank background which will make look like this in every dark background even in your PC, make the background white instead of blank and it should be good.

**Comment by mypil** [comment]
@basseldamra - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
