### ISSUE TITLE
Subscribing to status updates

### ISSUE THREAD

**Issue by m0liere** [MicrosoftDocs/OfficeDocs-Enterprise#328]
Is there a way I can subscribe to service status via a webhook or rss feed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd2a834a-296b-1c7d-7358-6f6a19f8f3c3
* Version Independent ID: 9ab6adbe-c651-d833-f395-64b7cddb2dd2
* Content: [How to check Office 365 service health](https://docs.microsoft.com/en-us/office365/enterprise/view-service-health#feedback)
* Content Source: [Enterprise/view-service-health.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/view-service-health.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@m0liere - thanks for your feedback. No, there isn't a service status notification endpoint for this - you'll need to access the Service Health page in the admin center. If you'd like to request a new feature for this support, please submit feedback on https://office365.uservoice.com. Thanks!

**Comment by dadcruz** [comment]
Hello, thought ill share this..
Please see link to documentation to use the API to get his information. 
https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-service-communications-api-reference.
Most log analytics providers already have integrations.  Eg https://docs.splunk.com/Documentation/AddOns/released/MSO365/About
