### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by gseive64** [MicrosoftDocs/OfficeDocs-Enterprise#330]
In the case the move failed, what are the possible error codes? Could you add those to the article? Provide a link to the page where they are listed and explained?
Thanks! Otherwise great article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b25327c1-71f7-2cdb-0463-cfa8bdd5a743
* Version Independent ID: 74b15568-0546-7248-26b1-381ac12385df
* Content: [Move a OneDrive site to a different geo-location](https://docs.microsoft.com/en-us/office365/enterprise/move-onedrive-between-geo-locations#feedback)
* Content Source: [Enterprise/move-onedrive-between-geo-locations.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/move-onedrive-between-geo-locations.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@gseive64, there are no error codes associated with a OneDrive move. Failures should be rare. If a failure occurs, you should try the move again.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot close
