### ISSUE TITLE
Error with Microsoft.Online.SharePoint.PowerShell module

### ISSUE THREAD

**Issue by Tokyo22** [MicrosoftDocs/OfficeDocs-Enterprise#332]
Hi!
I've found that `Import-Module Microsoft.Online.SharePoint.PowerShell` doesn't work for me.
However, `Install-Module Microsoft.Online.SharePoint.PowerShell` does work!

**Comment by robmazz** [comment]
@Tokyo22 - thanks for the feedback, do you have a specific topic that you're referencing? Please provide the link, thanks!

**Comment by robmazz** [comment]
Closing - no reply regarding which topic is in question.
