### ISSUE TITLE
Clarify requirement for Minimal or Full Hybrid Configuration

### ISSUE THREAD

**Issue by benjherb** [MicrosoftDocs/OfficeDocs-Enterprise#333]
Unless I'm missing something in this prereqs article or the "how to configure" one, I don't think either specify whether a Minimal or Full Hybrid Configuration is required to implement HMA. In a recent attempt to configure HMA on an Exchange 2016 CU10 server, the Minimal Hybrid Configuration option did not create the evoSTS auth server object. We had to switch to a Full Hybrid Configuration in order for the evoSTS auth server to get created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626caf29-7e88-0b56-2013-5c5b7c2a5917
* Version Independent ID: 2376192f-793d-0166-46c7-870cd0c41abb
* Content: [Hybrid Modern Authentication overview and prerequisites for using it with on-premises Skype for Business and Exchange servers](https://docs.microsoft.com/en-us/office365/enterprise/hybrid-modern-auth-overview)
* Content Source: [Enterprise/hybrid-modern-auth-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/hybrid-modern-auth-overview.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by robmazz** [comment]
@benjherb - thanks for the feedback, I'll get this over to the Enterprise content team for consideration.

**Comment by mbenadiba** [comment]
I agree. 
I have an on premise exchange deployment and want to implement MFA.
We already have Teams, and use azure ad for MFA to protect on premise Rd gateway and SSTP VPN. Now to add owa and exchange we need to run hybrid wizard and it would be good to run in minimal mode since no mail flow is needed. Just MFA for On-premise exchange. 

Thanks

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by ojrb** [comment]
@mypil the PR #379 solve this issue

**Comment by ojrb** [comment]
Hi @mypil , as requested by @nenonix, I created one PR by Issue, in this case the new PR #389  solve only this issue, I add the edit changes recommended by @nenonix  and @JohanFreelancer9. I add a paragraph explaining the requirements on Hybrid environments. Please review and Merge this new PR

**Comment by mypil** [comment]
@benjherb - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
