### ISSUE TITLE
 giphy.com is missing

### ISSUE THREAD

**Issue by naminakao** [MicrosoftDocs/OfficeDocs-Enterprise#335]
I believe giphy.com is required if users use gif in Microsoft Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by naminakao** [comment]
Based on the following techcommunity page, we used to have giphy in IP/FQDN page. Please restore it.
https://techcommunity.microsoft.com/t5/Microsoft-Teams/Microsoft-Teams-Giphy-is-not-working-loading-in-Application-or/td-p/66159

**Comment by JoeDavies-MSFT** [comment]
@naminakao I have forwarded this suggestion on to the product team that manages these endpoints for their consideration. Thanks for letting us know,
