### ISSUE TITLE
MVA Link is flagged as Retired

### ISSUE THREAD

**Issue by D-Jeffrey** [MicrosoftDocs/OfficeDocs-Enterprise#336]
Please replace the link with video content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 596c812b-a25a-e573-825b-debe0af35fd8
* Version Independent ID: 1669980c-0c80-ae7c-3bc3-6bfcc64fe924
* Content: [Test Office 365 with Cloud adoption Test Lab Guides (TLGs)](https://docs.microsoft.com/en-us/office365/enterprise/cloud-adoption-test-lab-guides-tlgs#feedback)
* Content Source: [Enterprise/cloud-adoption-test-lab-guides-tlgs.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/cloud-adoption-test-lab-guides-tlgs.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@D-Jeffrey The link has been removed. Thanks for letting us know.
