### ISSUE TITLE
Teams connecting to non listed IP's

### ISSUE THREAD

**Issue by therealdj99** [MicrosoftDocs/OfficeDocs-Enterprise#339]
Hello, ive noticed the teams client is connecting to IP address's listed above :( can this be updated? 
an example is 52.229.165.47
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@therealdj99 I have forwarded your request to the product team owners for their consideration in the next update. Thanks for letting us know.

**Comment by JoeDavies-MSFT** [comment]
@therealdj99 Can you be more specific about which IP addresses the Teams client is connecting to? You give an example. Are there others? Thanks

**Comment by therealdj99** [comment]
Hi, Here are some of the other IP address's seen..
13.107.6.156
52.229.165.47
42.80.97.152
13.94.40.40
40.83.127.218
40.113.86.19
13.75.46.153
13.76.170.95
52.169.29.157
13.107.3.128
Some of them may be skype related, but not 100% sure.
Thanks

**Comment by JoeDavies-MSFT** [comment]
@therealdj99 I have forwarded this to the product team for their investigation. Thanks for letting us know.
