### ISSUE TITLE
typo in PowerShell code

### ISSUE THREAD

**Issue by tdoan1** [MicrosoftDocs/OfficeDocs-Enterprise#340]
(Get-ADUser [guid][system.convert]::frombase64string((Get-MsolUser -UserPrincipalName &lt;UPN of user account&gt;).ImmutableID)).Guid

should be:
Get-ADUser ([guid][System.Convert]::FromBase64String((Get-MsolUser -UserPrincipalName tdoan@smu.edu).ImmutableID)).guid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f44fc7-086a-5a43-0fe3-7072b2885c37
* Version Independent ID: 9a026134-ee4b-5bff-82cd-f25d624e121d
* Content: [View user accounts with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-user-accounts-with-office-365-powershell#feedback)
* Content Source: [Enterprise/powershell/view-user-accounts-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/view-user-accounts-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@tdoan1 - thanks for the feedback, I'll get the Enterprise content team to review and verify.

**Comment by JoeDavies-MSFT** [comment]
@tdoan - I have made the change you cited above. Thanks for letting us know.
