### ISSUE TITLE
Teams Missing Host or Network

### ISSUE THREAD

**Issue by barrymelrose** [MicrosoftDocs/OfficeDocs-Enterprise#345]
Seeing traffic to 13.100.7.141 - not seeing that host or network specified in the endpoint list for Teams (or any other service/application).

Thanks!

**Comment by robmazz** [comment]
@barrymelrose - thanks for the feedback, I'll get this over to the Enterprise content team for investigation.

**Comment by barrymelrose** [comment]
Cool thanks. Right now I'm using 13.96.0.0/13 from the whois on arin.net. Guessing it's not that big though.

**Comment by JoeDavies-MSFT** [comment]
@barrymelrose I have forwarded this issue to the product teams for the investigation. Thanks for letting us know.
