### ISSUE TITLE
Missing IP in Office sharing functionallity because of missing IP 13.107.6.168

### ISSUE THREAD

**Issue by TorstenLaier** [MicrosoftDocs/OfficeDocs-Enterprise#346]
Hey, for being able to share e.g. a word file the IP 13.107.6.168 is required to be opened on the firewall/proxy. This IP is not mentioned in the lists for Office365 nor Azure. If the IP is not reachable the error message "Unfortunately, something is preventing us from sharing right now" appears. As soon as the IP is configured on the firewall the function is working as expected. We tried to address the issue of this missing IP in the Office365-IP range list or Azure IP range list by opening a Microsoft case, but were denied by the support. They cannot address this IP address to the corresponding teams that the IP is added to the list.

So I try it this way, in the hope that everyone gets something out of it.

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@TorstenLaier - thanks for the feedback, I'll forward this to the Enterprise content team for topic update consideration.

**Comment by JoeDavies-MSFT** [comment]
@TorstenLaier I have forwarded this issue to the product team that owns these endpoints for their investigation. Thanks for letting us know. Closing this issue for now.
