### ISSUE TITLE
Investigate IP/subnet for Exchange Online/login.microsoftonline.com

### ISSUE THREAD

**Issue by barrymelrose** [MicrosoftDocs/OfficeDocs-Enterprise#349]
Background and other elements at login.microsoftonline.com coming from 13.107.246.10 aadcdn.msauth.net don't seem to be on the list. Added 13.104.0.0/14 as a workaround.

Thanks!

**Comment by barrymelrose** [comment]
Also seeing r4.res.office365.com resolve to 104.91.44.19

**Comment by robmazz** [comment]
@barrymelrose - thanks for the feedback, I'll get this over to the Enterprise content team for consideration.

**Comment by JoeDavies-MSFT** [comment]
@barrymelrose I have forwarded this issue to the product team that owns these endpoints for their investigation. Closing this issue for now.
