### ISSUE TITLE
Reply URL not taken into account

### ISSUE THREAD

**Issue by Jeff-Pironneau** [MicrosoftDocs/OfficeDocs-Enterprise#35]
Hi,

I have tested the configuration on a SharePoint 2016 farm. 
For some reason, the "Reply URL" is not taken into account.
The authentication works but I am redirected to https://127.0.0.1:444/applications/default.aspx (default value) instead of the URL that I configured https://[SPWebApp].westeurope.cloudapp.azure.com/_trust/default.aspx.

The web app is configured with HTTPS on the default zone using bindings, AAM and self-signed certificate.
Any clue?

Thanks in advance
Regards

  Jeff P

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by Jeff-Pironneau** [comment]
Hi again, 

I have resolved the permission issue.
I had to choose the ClaimType "given name" instead of "Name" when giving permission.
This was for users in a Microsoft demo tenant.

When giving access to a guest/external user from another tenant, I had to choose the ClaimType "Name" for giving permission.

If anyone can explain, I will be interested!
Does this have anything to do with the fact that the user’s email address is contained in:
The “Name” claim type for a work account.
The “Email” claim type for a social/personal account contains.
?

Best regards

  Jeff P

**Comment by denisebmsft** [comment]
Thanks for the good questions, Jeff-Pironneau. We are looking into this.

**Comment by kaevans** [comment]
Added pull request: https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/52

**Comment by denisebmsft** [comment]
I believe Kirk Evans' recent update addressed this issue.

**Comment by moojjoo** [comment]
AADSTS50011: The reply uri specified in the request is not a valid URL. Allowed schemes: 'http,https' 
My Reply URL is - https://projects-dev02.piedmontng.com/   Why would I be getting the error above?

**Comment by kaevans** [comment]
@denisebmsft please close. Update did address this issue. @moojjoo commented but also has [duplicate issue](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/64).
