### ISSUE TITLE
images.edge.messenger.live.com is used by SfB Online to download Skype icon but not listed as required FQDN for SfB Online

### ISSUE THREAD

**Issue by MavisShi** [MicrosoftDocs/OfficeDocs-Enterprise#350]
Without bypassing this FQDN in proxy, users may keep getting network prompts after signing in SfB Online 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@MavisShi Moved this to an internal Microsoft discussion. Thanks.
