### ISSUE TITLE
add clarification for hotmail/outlook.com 

### ISSUE THREAD

**Issue by sulobr** [MicrosoftDocs/OfficeDocs-Enterprise#351]
[Enter feedback here]
Is it possible to add a statement to indicate if these O365 endpoints are not used/shared with our consumer space hotmail/outlook.com? I have a customer who is requesting for a documentation that includes this clarification so his security team can proceed with making firewall changes to allow connection. If any of these endpoints are used by hotmail/outlook.com, is it possible to identify them in this article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@sulobr - thanks for the feedback, I'll get this over to the Enterprise content team for consideration.

**Comment by JoeDavies-MSFT** [comment]
@sulobr This discussion has been taken internally at Microsoft.
