### ISSUE TITLE
Session timeout with Skype, Exchange Online, and ADFS

### ISSUE THREAD

**Issue by moorereason** [MicrosoftDocs/OfficeDocs-Enterprise#353]
What is the timeout for SfB client connecting to EXO with ADFS?  Users are having to re-auth throughout the day since we migrated to modern authentication.

We have Skype for Business 2015 on-prem (not in hybrid mode yet) with modern authentication using ADFS 2016.  Office 365 uses ADFS as primary auth.  Session timeout issue exists regardless of MFA enforcement.

Related to #245
Cc: @MSFTTracyP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1570de51-50b1-d4cc-c1c7-832b3242ccb3
* Version Independent ID: f5250f91-0a48-20cf-8e2c-e2dc347edd88
* Content: [Session timeouts for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/session-timeouts#feedback)
* Content Source: [Enterprise/session-timeouts.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/session-timeouts.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by robmazz** [comment]
@moorereason - thanks for the feedback, I'll get this over to the Enterprise content team for clarification.

**Comment by moorereason** [comment]
Our experience shows that the session timeout is 2 hours.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by MaratMussabekov** [comment]
Dear @moorereason ,
For MS Office products (including SfB), if you are connected via modern authentication, token should be valid for 90 days, so it is completely abnormal to enter credentials every two hours. I would recommend to check AD FS configuration, may be there are some limitations from its side?

Thank you

**Comment by mypil** [comment]
@moorereason - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
