### ISSUE TITLE
Small correction and a question...

### ISSUE THREAD

**Issue by RichardKForester** [MicrosoftDocs/OfficeDocs-Enterprise#354]
In Method 2, Step 1 there is this code snippet:

$subscr="&lt;subscription name&gt;"
Select-AzSubscription -SubscriptionName $subscrName -Current

which generates this error:

Set-AzContext : A parameter cannot be found that matches parameter name 'Current'.
At line:1 char:49
+ Select-AzSubscription -SubscriptionName $subscr -Current
+                                                 ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-AzContext], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand

Removing -Current works.  You may want to update this article.

Also, I have a question regarding the code for creating the VMs, specifically:

$vm=New-AzVMConfig -VMName DC1 -VMSize Standard_A1
$cred=Get-Credential -Message "Type the name and password of the local administrator account for DC1."
$vm=Set-AzVMOperatingSystem -VM $vm -Windows -ComputerName DC1 -Credential $cred -ProvisionVMAgent -EnableAutoUpdate
$vm=Set-AzVMSourceImage -VM $vm -PublisherName MicrosoftWindowsServer -Offer WindowsServer -Skus 2016-Datacenter -Version "latest"
$vm=Add-AzVMNetworkInterface -VM $vm -Id $nic.Id
$vm=Set-AzVMOSDisk -VM $vm -Name "DC1-OS" -DiskSizeInGB 128 -CreateOption FromImage -StorageAccountType "Standard_LRS"

The reuse of the variable $vm here would seem to make the value stored to change from line to line.  But stepping through each line shows that the $vm object has it's properties filled instead.  Is this something exclusive to Azure commands?  I don't think I've run into this in PowerShell before.  How does this work?  Or can you give me a reference?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 136007e4-4ddd-a1d8-a3ac-251da6bd5311
* Version Independent ID: 5c1ec643-ac23-cf7c-c787-3ffb1b4f9674
* Content: [Base Configuration dev/test environment](https://docs.microsoft.com/en-us/office365/enterprise/base-configuration-dev-test-environment#feedback)
* Content Source: [Enterprise/base-configuration-dev-test-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/base-configuration-dev-test-environment.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@RichardKForester  - thanks for the feedback, I'll get this over to the Enterprise content team for consideration.

**Comment by JoeDavies-MSFT** [comment]
@RichardKForester I have made the correction to the Select-AzSubscription command. Thanks so much for pointing that out. 

The use of the $vm object to collect properties and then to create a VM is specific to the New-AzVMConfig and other AzVM-based cmdlets. However, this is just a customized use of the New-Object and Add-Member cmdlets to create an object and define its properties.

**Comment by RichardKForester** [comment]
Thanks for the reply!  Really clears things up!
