### ISSUE TITLE
ExRCA IPs

### ISSUE THREAD

**Issue by curspice** [MicrosoftDocs/OfficeDocs-Enterprise#356]
The earlier version of this page used to have the ExRCA IP addresses.  Can they be added back?  Some locked-down customers like to open their firewall to ExRCA when they need to test.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by SuperTekBoy** [comment]
Would like to see the EXRCA IPs in this list as well. For customers that want to lock down their Exchange on-prem publishing to only allow connections from Office 365 IPs, these same customers would like to use the EXRCA tool against their hybrid environment.

**Comment by remydahl** [comment]
Yes please, this would be great! I've had to work in locked down environments that only had the Exchange Online IP addresses allowed through the firewall, and we weren't able to use the EXRCA tool for testing either. Please add these addresses so we can have them added to the whitelist.

**Comment by robmazz** [comment]
@curspice  - thanks for the feedback, I'll get this over to the Enterprise content team for consideration.

**Comment by JoeDavies-MSFT** [comment]
@curspice and @remydahl and @SuperTekBoy I have forwarded this issue to the product team that owns these endpoints for their investigation. Closing this issue for now.

**Comment by JoeDavies-MSFT** [comment]
@curspice @remydahl @SuperTekBoy These addresses have been moved here: https://docs.microsoft.com/office365/enterprise/urls-and-ip-address-ranges#exchange-online

**Comment by SuperTekBoy** [comment]
Is this covered by line item 74 with the DNS entry of "testconnectivity.microsoft.com"? Or elsewhere as an IP? Just asking because not all firewalls can build rules based on DNS alone (or the firewall admin prefers to use IPs for rules).
