### ISSUE TITLE
*.protection.outlook.com additional address range? 

### ISSUE THREAD

**Issue by Besdima** [MicrosoftDocs/OfficeDocs-Enterprise#357]
Playing around hybrid configuration, opened ip range from the list, but email still didn't go through.
In exchange online debug find out that the external address - ME1AUS01FT006.eop-AUS01.prod.protection.outlook.com - From IP: 125.239.156.8
Seems like this range didn't include into the table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@Besdima - thanks for the feedback, I'll get this over to the Enterprise content team for consideration.

**Comment by JoeDavies-MSFT** [comment]
@Besdima I have forwarded this issue to the product team that owns these endpoints for their investigation. Closing this issue for now.
