### ISSUE TITLE
type in PowerShell code

### ISSUE THREAD

**Issue by deFRAGerNZ** [MicrosoftDocs/OfficeDocs-Enterprise#359]
Get-MolUser -UserPrincipalName &lt;UPN of user account&gt; | Select-Object DisplayName,BlockCredential

should be:

Get-MsolUser -UserPrincipalName &lt;UPN of user account&gt; | Select-Object DisplayName,BlockCredential

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f44fc7-086a-5a43-0fe3-7072b2885c37
* Version Independent ID: 9a026134-ee4b-5bff-82cd-f25d624e121d
* Content: [View user accounts with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-user-accounts-with-office-365-powershell#feedback)
* Content Source: [Enterprise/powershell/view-user-accounts-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/view-user-accounts-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@deFRAGerNZ The article has been updated to correct this typo. Thanks so much for letting us know.
