### ISSUE TITLE
The last example is mislabeling services

### ISSUE THREAD

**Issue by milesgt** [MicrosoftDocs/OfficeDocs-Enterprise#36]
Do the following and you can see that the labels being applied in your output are incorrect:
$results = Get-MsolUser -UserPrincipalName <upn>
$results.licenses[0].ServiceStatus[0]

output:
ServicePlan   ProvisioningStatus
-----------   ------------------
BPOS_S_TODO_2 Success

Also when you create an html of the output with "ConvertTo-Html >", that is not a CSV.
Export-CSV if that's the desired output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f403603f-e17b-8b5b-cbd8-8e4c6f4e1728
* Version Independent ID: a93a3de1-25d3-4f7a-3e3e-3a6f25f88b75
* Content: [View account license and service details with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-account-license-and-service-details-with-office-365-powershell)
* Content Source: [Enterprise/powershell/view-account-license-and-service-details-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/view-account-license-and-service-details-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@milesgt, Example updated for services indexes and CSV issue. Thanks for letting us know.
