### ISSUE TITLE
Origins must be added using relative paths

### ISSUE THREAD

**Issue by bvduijn** [MicrosoftDocs/OfficeDocs-Enterprise#363]
In above example the command Add-SPOTenantCdnOrigin -CdnType Private -OriginUrl “https://contoso.sharepoint.com/sites/test/siteassets/folder1” is used to add an origin.

When I try to do this using our own tenant I get a message stating the origin needs te be a relative url

Version of PS Sharepoint module:
Get-Module -Name Microsoft.Online.SharePoint.PowerShell -ListAvailable | Select Name,Version

Name                                   Version       
----                                   -------       
Microsoft.Online.SharePoint.PowerShell 16.0.8615.1200
Microsoft.Online.SharePoint.PowerShell 16.0.8615.0   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2836d55d-6874-f366-60c2-e3043dd5547e
* Version Independent ID: 3c84c811-52bc-872e-48cf-54ecc2a9d7de
* Content: [Use the Office 365 Content Delivery Network (CDN) with SharePoint Online](https://docs.microsoft.com/en-us/office365/enterprise/use-office-365-cdn-with-spo#feedback)
* Content Source: [Enterprise/use-office-365-cdn-with-spo.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/use-office-365-cdn-with-spo.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by robmazz** [comment]
@bvduijn - thanks for the feedback, I'll get this over to the Enterprise content team for review.

**Comment by kelleyvice-msft** [comment]
@bvduijn - Thank you for reaching out. I can repro this issue, and will update the documentation accordingly.
The command you should use instead is:
`Add-SPOTenantCdnOrigin -CdnType Private -OriginUrl “/sites/test/siteassets/folder1”`
