### ISSUE TITLE
Office 2010 experience should be outlined

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/OfficeDocs-Enterprise#364]
unfortunately there are still businesses out there running office 2010 / still in the middle of getting rid of it.. so outline even the basic auth and its issues

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059ed9a7-ea75-0fa3-e246-4ad1f1b0c5bc
* Version Independent ID: d7598f96-3158-09ee-024a-6175599718cd
* Content: [How modern authentication works for Office 2013 and Office 2016 client apps](https://docs.microsoft.com/en-gb/office365/enterprise/modern-auth-for-office-2013-and-2016)
* Content Source: [Enterprise/modern-auth-for-office-2013-and-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/modern-auth-for-office-2013-and-2016.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by kenwith** [comment]
@officedocsbot assign @mypil

**Comment by kenwith** [comment]
@officedocsbot assign @mypil

**Comment by scanum** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@bakerm00 - Thank you for submitting feedback.

I will get this issue over to the Enterprise content team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@bakerm00 - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
