### ISSUE TITLE
#66 gbr.delve.office.com runs over Express Route

### ISSUE THREAD

**Issue by KevFM** [MicrosoftDocs/OfficeDocs-Enterprise#368]
Endpoint Set #66 markes 'gbr.delve.office.com' as being serviced over the Internet. In our environment this is actually serviced over Express Route.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@KevFM I have forwarded this issue to the product team responsible for maintaining these lists for their investigation. Thanks for letting us know.
