### ISSUE TITLE
I wish there was a description of the underlying network on top of each VPN is established

### ISSUE THREAD

**Issue by yscontrol** [MicrosoftDocs/OfficeDocs-Enterprise#37]
Is VPN established over public Internet connection provided by an ISP or public IP could be avoided by using same mechanism that is used by Amazon Direct-Connect  ? When talking network,  I wish protocol stack is specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f472c81-522c-1702-6a0d-4f2591f5e994
* Version Independent ID: 6018af3a-fde5-5733-d308-9d8f9629f10f
* Content: [Connect an on-premises network to a Microsoft Azure virtual network](https://docs.microsoft.com/en-us/office365/enterprise/connect-an-on-premises-network-to-a-microsoft-azure-virtual-network)
* Content Source: [Enterprise/connect-an-on-premises-network-to-a-microsoft-azure-virtual-network.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/connect-an-on-premises-network-to-a-microsoft-azure-virtual-network.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
Hi yscontrol, I added additional text to describe more details of the site-to-site VPN connection and the use of ExpressRoute (equivalent to Amazon Direct-Connect) as an alternative. I hope this helps. Joe
