### ISSUE TITLE
Add PF support limitation to page

### ISSUE THREAD

**Issue by SjaakRovers** [MicrosoftDocs/OfficeDocs-Enterprise#372]
PFs are currently not supported by multi-geo. Could they be added to the limitations list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85937c83-35db-0882-e226-a4f2f732de73
* Version Independent ID: ac0b646b-0fbf-eb24-6768-07cfcd51076b
* Content: [Exchange Multi-Geo](https://docs.microsoft.com/en-us/office365/enterprise/multi-geo-capabilities-in-exchange-online#feedback)
* Content Source: [Enterprise/multi-geo-capabilities-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/multi-geo-capabilities-in-exchange-online.md)
* Service: **o365-solutions**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@SjaakRovers - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@SjaakRovers, I added public folders to the list of limitations as you suggested. Public folders are supported in the central geo location; you just can't move them around to the satellite geo locations.

Thanks for the feedback.
