### ISSUE TITLE
Wrongly linked module

### ISSUE THREAD

**Issue by tomlarse** [MicrosoftDocs/OfficeDocs-Enterprise#374]
These instructions points the user to connect to AzureAD using the AzureAD module, but this module does not contain the `Get-MsolServicePrincipal` referenced in the instructions below

https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blame/live/Enterprise/configure-skype-for-business-for-hybrid-modern-authentication.md#L113

I suggest changing the link to point to https://docs.microsoft.com/en-us/powershell/azure/active-directory/overview?view=azureadps-1.0 in stead, as this module does contain the correct cmdlets. 

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: 7a887219-cf1d-af7e-d36a-4f541ee44a5e
* Version Independent ID: 3babb1cd-31b1-b53b-4a94-ba92d89f65a5
* Content: [How to configure Skype for Business on-premises to use Hybrid Modern Authentication](https://docs.microsoft.com/nb-no/office365/enterprise/configure-skype-for-business-for-hybrid-modern-authentication)
* Content Source: [Enterprise/configure-skype-for-business-for-hybrid-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/configure-skype-for-business-for-hybrid-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@tomlarse - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@tomlarse - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
