### ISSUE TITLE
Reworked the PowerShell script

### ISSUE THREAD

**Issue by samurai-ka** [MicrosoftDocs/OfficeDocs-Enterprise#377]
I've reworked the PowerShell script so you can use it with the PowerShell pipe.
https://github.com/samurai-ka/PS-Module-O365EndpointService

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7ebf92c-e478-0f65-0494-97042e974b46
* Version Independent ID: 7e1b9b91-d60d-8665-9a39-2ca77a46b4ce
* Content: [Office 365 IP Address and URL Web service](https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service#feedback)
* Content Source: [Enterprise/office-365-ip-web-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@samurai-ka - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by ojrb** [comment]
@mypil Hi ! I nave created the PR #378 based on the Issues #321 and #377, for you review to Merge ! Regards ! Orlando !

**Comment by ojrb** [comment]
Hi @mypil , as requested by @nenonix, I created one PR by Issue, in this case the new PR #388 solve only this issue, I add the edit changes recommended by @JohanFreelancer9. I add a paragraph reference the reworked script

**Comment by mypil** [comment]
@samurai-ka - Thank you for submitting feedback.

The article has been updated to incorporate your feedback. For your reference, kindly check on PR #403. 

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by samurai-ka** [comment]
@mypil Just seen you found a typo error and documented that in your page. I have updated the code now so the function will be named Invoke-EndpointService with d.
You might want to remove the warning about the typo error now.
Thank you for adding my little project to your documentation.

**Comment by mypil** [comment]
@ojrb - kindly check on the additional feedback from samurai-ka and please create a PR to make the necessary changes. Thank you.

**Comment by ojrb** [comment]
Hi @mypil  I created a new PR #410 to correct the command referenced by @samurai-ka ! Please Review and Merge !

**Comment by mypil** [comment]
@samurai-ka - We have already coordinated with the doc owner kelleyvice-msft and she will make the updates to the current version of the topic.

We appreciate your contribution to make the docs better.

**Comment by mypil** [comment]
@officedocsbot close
