### ISSUE TITLE
Security & Compliance Center

### ISSUE THREAD

**Issue by rpodric** [MicrosoftDocs/OfficeDocs-Enterprise#38]
Re that section, to be consistent with the rest of the page (and to not trigger a login prompt), use $credential instead of $UserCredential.

Also, to be consistent, -Authentication "Basic" instead of -Authentication Basic

And finally, leaving off "-Prefix cc" from the second line leads to a long list of yellow warnings. As was mentioned before, "Since cmdlts in Exchange Online and Compliance Center collide, we add a prefix 'CC' to all commands that refer to Compliance Center."

So, in summary, I'm sticking with:

```
$SccSession = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.compliance.protection.outlook.com/powershell-liveid/ -Credential $credential -Authentication "Basic" -AllowRedirection
Import-PSSession $SccSession -Prefix cc
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c551eb1-7ac5-cb02-cd1b-d67ca3886d85
* Version Independent ID: fb690e2e-420e-f697-60f2-39520283d385
* Content: [Connect to all Office 365 services in a single Windows PowerShell window](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window)
* Content Source: [Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@rpodric, PowerShell commands updated with your suggestions. Thanks for letting us know. Joe
