### ISSUE TITLE
Incorrect PowerShell Statement for assigning licenses to all unlicensed users

### ISSUE THREAD

**Issue by henryphillipsid** [MicrosoftDocs/OfficeDocs-Enterprise#384]
set-msoluserlicense expects an object ID or UPN to determine the user to set the license against. So it either needs something like -UserPrincipalName $_.UserPrincipalName adding or just straight pipe like Get-MsolUser -All -UnlicensedUsersOnly | Set-MsolUserLicense -AddLicenses "*:SPE_E5" which would actually achieve the same thing but allow for a shorter command

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d0e735d-ee63-38ec-9829-f9bd5017ccf6
* Version Independent ID: 67b1c8cc-f18e-0139-581b-306848f8f8e9
* Content: [Assign licenses to user accounts with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/assign-licenses-to-user-accounts-with-office-365-powershell)
* Content Source: [Enterprise/powershell/assign-licenses-to-user-accounts-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/assign-licenses-to-user-accounts-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@henryphillipsid - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@henryphillipsid I have corrected the PowerShell command and its examples to incorporate your command and remove the ForEach construct. Thanks for letting me know about this.
