### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by henryphillipsid** [MicrosoftDocs/OfficeDocs-Enterprise#385]
Would be nice to have an explanation as to why the azuread cmdlet returns far fewer roles than the msolrole cmdlet. Now I am thinking it might just be there is only so much you can interact with via the Graph (may increase over time) but I would like to know, rather than assume :) As here this is not just two different methods, it provides two completely different sets of results, meaning this is a scenario where you would need to use one over the other, rather than just a preference thing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbee503e-39f0-b277-20a5-659f1255d775
* Version Independent ID: 884eeb43-1b0b-e6fc-a405-2d50d646819e
* Content: [Assign roles to user accounts with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/assign-roles-to-user-accounts-with-office-365-powershell)
* Content Source: [Enterprise/powershell/assign-roles-to-user-accounts-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/assign-roles-to-user-accounts-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@henryphillipsid - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@henryphillipsid The output of Get-AzureADDirectoryRole is the list of currently installed Azure AD role templates. The updated article links to the definitive list of role names and the new block adds the role template if it doesn't already exist. Thanks for pointing this out.
