### ISSUE TITLE
/28 should not be the recommended size, /27 should be

### ISSUE THREAD

**Issue by eshudnow** [MicrosoftDocs/OfficeDocs-Enterprise#386]
You mention /28 should be the recommended size.  However, if you read the ExpressRoute with VPN Failover documentation, /27 or larger (For example, /25 or /26) is required.  You can see from this document, https://docs.microsoft.com/en-us/azure/expressroute/expressroute-howto-coexist-resource-manager, it explictly mentions, "The Gateway Subnet must be /27 or a shorter prefix (such as /26 or /25)."

Therefore, the document should be updated to recommend /27 or larger, not /28.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e19b241-53d3-f8c9-07bf-442d987ddf6f
* Version Independent ID: 79a1bde8-76fe-39aa-e410-0ac3c236eefa
* Content: [Designing networking for Microsoft Azure IaaS](https://docs.microsoft.com/en-us/office365/enterprise/designing-networking-for-microsoft-azure-iaas)
* Content Source: [Enterprise/designing-networking-for-microsoft-azure-iaas.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/designing-networking-for-microsoft-azure-iaas.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@eshudnow - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@eshudnow Thank you for the feedback, I have created a PR https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/391 to make necessary changes to reflect the correct value.

Regards
Sriraman

**Comment by mypil** [comment]
@eshudnow- From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
