### ISSUE TITLE
There are zero referenced to the CAS.MS URLs used by Cloud App Security here

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/OfficeDocs-Enterprise#390]
Is that documented elsewhere or should it be here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@chrislehr - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @chrislehr , Thank you for your feedback. Please note that this document is only based on Office365 related products. Cloud App Security CAS is an independent product as you have to buy its license separately so information related to CAS doesn't fall under this. 

You can find CAS related information at https://docs.microsoft.com/en-us/cloud-app-security/ 

Thanks.

**Comment by chrislehr** [comment]
Cas.ms also not listed there.  New issue for that then?

**Comment by joinimran** [comment]
Hello @chrisahlers, Yes, please. You can open your request at https://docs.microsoft.com/en-us/cloud-app-security/getting-started-with-cloud-app-security so that this can be escalated to the relevant team to help answer your question and make necessary additions in docs.

Thanks.

**Comment by mypil** [comment]
@chrislehr - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
