### ISSUE TITLE
Issue with document

### ISSUE THREAD

**Issue by zendack** [MicrosoftDocs/OfficeDocs-Enterprise#394]
I believe there is an issue with the Groups in Microsoft 365 for IT Architects document.  
1.  Stating that Yammer Groups do not get an OneNote or a Planner Plan.  I believe this is incorrect. 

2.  It shows the USER creating the Outlook based group.  Would it not make more sense to state "Outlook", following the standard with the other applications below.

3.  The document does not mention the other locations where O365 Groups can be created (Stream, for instance).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096f9573-ba23-b0a0-23dc-7b0eb57a17d8
* Version Independent ID: 45643fe7-700e-8eca-b7b9-563327472d6b
* Content: [Microsoft cloud IT architecture resources](https://docs.microsoft.com/en-us/office365/enterprise/microsoft-cloud-it-architecture-resources)
* Content Source: [Enterprise/microsoft-cloud-it-architecture-resources.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/microsoft-cloud-it-architecture-resources.md)
* Service: **o365-solutions**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@zendack - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete

**Comment by BrendaCarter** [comment]
Looking into this . . .

**Comment by mypil** [comment]
@BrendaCarter - Do you have any updates on this? 

Thank you.

**Comment by BrendaCarter** [comment]
Yes, still working on this.

**Comment by mypil** [comment]
@BrendaCarter - Do you have any updates on the progress of this?

Thank you.

**Comment by mypil** [comment]
@BrendaCarter - We would like to follow up. Do you have any updates?

Thank you.

**Comment by BrendaCarter** [comment]
Greetings, this document has been updated to differentiate between Office-connected Yammer groups and regular Yammer groups.
