### ISSUE TITLE
[LOC] Invalid link in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-Enterprise#395]
There is an invalid link in an article.

**Repro steps**:
1. Go to https://docs.microsoft.com/en-us/Office365/Enterprise/performance-troubleshooting-plan
2. Search for "Plan for Internet bandwidth usage for Office 365" link
3. Click on the link

**Actual results**:
Link redirects to 404 error
**Expected results**:
Link redirects to an existing page or is removed from the article

**GH article**:
https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/performance-troubleshooting-plan.md

![image](https://user-images.githubusercontent.com/47977325/56731257-5c9cac80-675a-11e9-870d-b1a65f52e64a.png)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@OfficeGlobal - Thank you for pointing this out.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by ojrb** [comment]
@mypil this issue is solved with the PR #401, Please review and Merge !

**Comment by mypil** [comment]
@ojrb - Let's first get the inputs from the author @MSFTTracyP if that portion should be removed or if there is a working link for this. 

@MSFTTracyP - We need your insights on this issue. Do you have the correct URL for the "Plan for Internet bandwidth usage for Office 365" link? Or should this portion of the article need to be removed (PR #401 addresses the removal)? Please advise. 

Thank you.

**Comment by ojrb** [comment]
Sure @mypil  The problem with this link is that not exists an update on the link and is broken ! I wait for the @MSFTTracyP comments !

**Comment by mypil** [comment]
@MSFTTracyP - We would like to follow up. Do you have any updates? Thanks.

**Comment by mypil** [comment]
@OfficeGlobal -  From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
