### ISSUE TITLE
[LOC] Invalid link in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-Enterprise#396]
There is an invalid link in an article.

**Repro steps**:
1. Go to https://docs.microsoft.com/en-us/Office365/Enterprise/monitor-connectivity
2. Search for "Office 365 Management API" link
3. Click on the link

**Actual results**:
Link redirects to 404 error
**Expected results**:
Link redirects to an existing page or is removed from the article

**GH article**:
https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/monitor-connectivity.md

![image](https://user-images.githubusercontent.com/47977325/56733499-9f618300-6760-11e9-98df-f9c8b6a6d78f.png)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@OfficeGlobal - Thank you for pointing this out.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@kelleyvice-msft - We need your insights on this issue. Do you have the correct URL for the"Office 365 Management API" link? Or should this portion of the article need to be removed? 
Please advise so we can let @ojrb create a PR for this. Thank you.

**Comment by ojrb** [comment]
@mypil the issue was solved with the PR #402 . I modified the correct link that works ! Please review and Merge !

**Comment by kelleyvice-msft** [comment]
Merged. Thank you!
