### ISSUE TITLE
Unable to query expired SKUs for removal with Powershell

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/OfficeDocs-Enterprise#397]
Hi,

Just noticed if you have user assigned to a SKU that has been cancelled (shows availability 0 out of 0 licenses available )

First, the user assigned to the license isn't automatically unassigned from it.
Secondly, when trying to remove these with powershell, it isn't possible cause you get an error that the license is invalid.

See error
![image](https://user-images.githubusercontent.com/43186451/56738308-a098ad00-676c-11e9-8ead-f3d2a7a183d9.png)

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90144912-28c3-e215-7763-12beddc645c7
* Version Independent ID: c2aa496c-51d4-ffd9-9b06-e3a7097d027a
* Content: [Remove licenses from user accounts with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell)
* Content Source: [Enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@xNiklasJern Can you remove the cancelled license from the Office 365 admin center? Thanks

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by xNiklasJern** [comment]
@JoeDavies-MSFT Yes I could do it manually, one by one. Wasn't able to utilize the new admin center to unassigned the license. Since the SKU didn't show up if multiple users were selected.

**Comment by JoeDavies-MSFT** [comment]
@xNiklasJern  I can add a note to this article: 

You cannot use the Set-MsolUserLicense cmdlet to unassign users from canceled licenses. You must do this individually for each user account in the Microsoft 365 admin center.

Is this correct? Thanks

**Comment by xNiklasJern** [comment]
@JoeDavies-MSFT That would be correct, yes.
But the question is really more about why is cancelled SKU still assigned to a user and why can't it be removed with Powershell

**Comment by JoeDavies-MSFT** [comment]
@xNiklasJern I will pass this question on to the product team members for their consideration for investigation and fixing. In the mean time, I will update the article with a note and the above text. Thanks for letting us know about this.
