### ISSUE TITLE
IPv6 support for Example PowerShell Script

### ISSUE THREAD

**Issue by layer9de** [MicrosoftDocs/OfficeDocs-Enterprise#399]
The PowerShell Script for receiving endpoint information is great. It however does not include IPv6 addresses yet. Is there a particular reason for that? We are already running a dual stacked network and therefore need an easy way to automatically receive updates to the IPv6 addresses as well. It would be great if the script could be amended correspondingly.

There is a script on https://gallery.technet.microsoft.com/office/Get-Office-365-Endpoint-b533554a that already has support for IPv6 implemented. I'd rather like to use a script officially provided by Microsoft however.

Best Regards
Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7ebf92c-e478-0f65-0494-97042e974b46
* Version Independent ID: 7e1b9b91-d60d-8665-9a39-2ca77a46b4ce
* Content: [Office 365 IP Address and URL Web service](https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service#feedback)
* Content Source: [Enterprise/office-365-ip-web-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by kelleyvice-msft** [comment]
Thanks for the feedback, @layer9de! I'll look this over and discuss with the PMs for the endpoint web service.
- Kelley

**Comment by mypil** [comment]
@kelleyvice-msft - Do you have any updates on this?

Thank you.

**Comment by mypil** [comment]
@kelleyvice-msft - I would like to follow up. Any updates on this?

Thank you.

**Comment by layer9de** [comment]
Hi Joyce,

thank you. In the meantime I managed to solve this by myself. The script already returns IPv6 addresses as well but for outputting them they need to be filtered.

I have added the following to put IPv6 addresses in the variable $flatIp6s which then can be outputted any way you want:

    $flatIp6s = $endpointSets | ForEach-Object {
        $endpointSet = $_
        $ips = $(if ($endpointSet.ips.Count -gt 0) { $endpointSet.ips } else { @() })
        # IPv6 strings have colons while IPv6 strings have dots
        $ip6s = $ips | Where-Object { $_ -like '*:*' }
        $ipCustomObjects = @()
        if ($endpointSet.category -in ("Optimize")) {
            $ipCustomObjects = $ip6s | ForEach-Object {
                [PSCustomObject]@{
                    category = $endpointSet.category;
                    ip = $_;
                    tcpPorts = $endpointSet.tcpPorts;
                    udpPorts = $endpointSet.udpPorts;
                }
            }
        }
        $ipCustomObjects
    }

For example, output following into a file afterwards:

($flatIp6s.ip | Sort-Object -Unique) | Out-File -Append C:\scripts\Office365\endpoints.txt

**Comment by kelleyvice-msft** [comment]
@layer9de - Thanks for this! I've incorporated your addition into the script and am waiting for PM review before updating the script in the topic. I also added the following to the output section:
``` powershell
    Write-Output "IPv6 Firewall IP Address Ranges"
    ($flatIp6s.ip | Sort-Object -Unique) -join "," | Out-String
```
Thanks so much for the very valuable suggestion!

**Comment by kelleyvice-msft** [comment]
I've updated the topic with the suggested changes. @layer9de - thanks again!

Kelley
