### ISSUE TITLE
Connect-MsolService - Change parameter name from AzureEnvironmentName to AzureEnvironment

### ISSUE THREAD

**Issue by brainpr** [MicrosoftDocs/OfficeDocs-Enterprise#404]
The Connect-MsolService cmdlet from MSOnline PowerShell module does not have a parameter named -AzureEnvironmentName, although the AzureAD module does.

The Connect-MsolService parameter name to specify the Azure Environment needs to be corrected in the table in the following section: https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell#step-2-connect-to-azure-ad-for-your-office-365-subscription-1

Action: Change each occurrence of 
    "Connect-MsolService -AzureEnvironmentName"
            to 
    "Connect-MsolService -AzureEnvironment"

--
Current Incorrect Text:

Office 365 cloud | Command
-- | --
Office 365 Worldwide (+GCC) | Connect-MsolService
Office 365 operated by 21 Vianet | Connect-MsolService -AzureEnvironmentName AzureChinaCloud
Office 365 Germany | Connect-MsolService -AzureEnvironmentName AzureGermanyCloud
Office 365 U.S. Government DoD and Office 365 U.S. Government GCC High | Connect-MsolService -AzureEnvironmentName USGovernment

<><><><><>

Resulting Correct Text:

Office 365 cloud | Command
-- | --
Office 365 Worldwide (+GCC) | Connect-MsolService
Office 365 operated by 21 Vianet | Connect-MsolService -AzureEnvironment AzureChinaCloud
Office 365 Germany | Connect-MsolService -AzureEnvironment AzureGermanyCloud
Office 365 U.S. Government DoD and Office 365 U.S. Government GCC High | Connect-MsolService -AzureEnvironment USGovernment

<><><><><>

Reference:
https://docs.microsoft.com/en-us/powershell/module/msonline/connect-msolservice?view=azureadps-1.0

<><><><><>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@brainpr - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hello @brainpr Thanks for your feedback, I created a Pull Request to correct the article with the correct parameter name.
Thanks again.

**Comment by mypil** [comment]
@brainpr - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
