### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/OfficeDocs-Enterprise#405]
There are lines marked as code that should not be, for example this line:
To disable lean popouts for all users in your organization:

Additionally, the limitations of lean popups should be further explained visually. When you say "Skype for Business presence" isn't available, what does that actually mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0adf74-b4de-678c-4213-cafe76476dd7
* Version Independent ID: d2cc6acf-7abc-0568-afd0-2b6e1fff380e
* Content: [Use lean popouts to reduce memory used when reading mail messages](https://docs.microsoft.com/en-us/office365/enterprise/use-lean-popouts-to-reduce-memory-used-when-reading-mail-messages)
* Content Source: [Enterprise/use-lean-popouts-to-reduce-memory-used-when-reading-mail-messages.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/use-lean-popouts-to-reduce-memory-used-when-reading-mail-messages.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@SwiftOnSecurity - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@SwiftOnSecurity Thank you for your feedback. I have made the changes to reflect the lines and codes differently on PR https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/409 .

The limitations talks about the Skype for business presence which shows up on a email message. Hope that helps!

Regards
Sriraman MS

**Comment by mypil** [comment]
@SwiftOnSecurity - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated

**Comment by mypil** [comment]
@officedocsbot close
