### ISSUE TITLE
What happened to the Exchange Hybrid IP Ranges page?

### ISSUE THREAD

**Issue by ckssaas** [MicrosoftDocs/OfficeDocs-Enterprise#407]
The page I've been using for years to configure Exchange Hybrid now redirects to this page, but the top of the article states: "Endpoint data below lists requirements for connectivity from a user’s machine to Office 365. It does not include network connections from Microsoft into a customer network, sometimes called hybrid or inbound network connections." I can't find a reference in the Hybrid Exchange section either. Where is the information for Hybrid Exchange now located? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ckssaas - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by ckssaas** [comment]
Thank you!

**Comment by mypil** [comment]
@JoeDavies-MSFT - can you please share your insights on this issue?

Thank you.

**Comment by JoeDavies-MSFT** [comment]
@ckssaas As part of the reorganization and simplification of the Office 365 endpoints, not all of the previously published endpoints are now published. See the information on Exchange Hybrid in this article: https://docs.microsoft.com/en-us/office365/enterprise/additional-office365-ip-addresses-and-urls

**Comment by ckssaas** [comment]
@JoeDavies-MSFT Thanks for the link. The statement "If you need the NAT IP addresses used by Exchange Online servers to restrict inbound connections from specific source IP ranges, they are listed in Office 365 URL & IP ranges under the "Exchange Online" service area." (which is what I'm looking for) sends me back to this page. The old page was specific about listing about 30 EOP subnets relevant to inbound internal hybrid mail flow. Typically the subnets listed on that page would match the inbound connector created by the Hybrid Configuration Wizard. I just compared the "Inbound from Office 365" connectors on a live hybrid I configured for a customer 3 years ago and a hybrid I configured for another customer 2 weeks ago. The scoped IP's were almost identical (suggesting few changes in 3 years). Comparing the list above to the inbound hybrid connectors, the list above only has 104.47.0.0/17, 40.107.0.0/16, and 2a01:111:f400:7c00::/54 in common, which leads me to believe that either I am misunderstanding which subnets to expect intraorganizational hybrid mail to originate from, or that some information somewhere may be incomplete. That is, unless the EXO/EOP subnets have in fact changed dramatically in the last 2 weeks. This is what the hybrid configuration wizard is currently scoping for "Inbound from Office 365" 
 hybrid connectors: 

104.47.0.0/17
134.170.101.0/24
134.170.140.0/24
134.170.171.0/24
157.55.133.160/27
157.56.110.0/23
157.56.112.0/24
157.56.116.0/25
157.56.120.0/25
157.56.87.192/26
207.46.100.0/24
207.46.108.0/25
207.46.163.0/24
207.46.51.64/26
213.199.154.0/24
213.199.180.128/26
216.32.180.0/23
23.103.132.0/22
23.103.136.0/21
23.103.144.0/20
23.103.198.0/23
23.103.200.0/21
40.107.0.0/16
40.92.0.0/14
52.100.0.0/24
65.55.169.0/24
65.55.88.0/24
94.245.120.64/26
2a01:111:f400:7c00::/54
2a01:111:f400:fc00::/54

Thanks

**Comment by lion2500** [comment]
Hi. I'll add some information. I find an web archive https://web.archive.org/web/20181119030144/https://docs.microsoft.com/en-us/office365/SecurityCompliance/eop/exchange-online-protection-ip-addresses
And also I find this: https://social.technet.microsoft.com/Forums/en-US/e493ef15-17b0-40f2-8b81-003a6f9295f9/announcement-deprecation-of-eop-outbound-ip-address-ranges?forum=onlineservicesexchange

That's why I wanna ask: why do we get know only for now? Why doesn't Microsoft sent any warnings about changes? When it's time to pay for service it's always do.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Do you have any updates on this? 

Thank you.

**Comment by mypil** [comment]
@JoeDavies-MSFT - We would like to follow up. Do you have any updates?

Thank you.

**Comment by mypil** [comment]
@JoeDavies-MSFT - We would like to follow up. Do you have any updates on this?

cc: @LauraWi 

Thank you.

**Comment by JoeDavies-MSFT** [comment]
@ckssaas I have asked a member of the Exchange Online product team to address your questions.

**Comment by MoGilbo** [comment]
@JoeDavies-MSFT I'm also trying to fill in a firewall request form to allow inbound connections from O365 to our on-prem Hybrid Exchange servers and can't do so without these details. Can we get an estimate on how long it will take to provide this information so I can advise the project I'm working on.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Do you have any updates?

Thank you.

**Comment by JornMich** [comment]
> 
> 
> @ckssaas I have asked a member of the Exchange Online product team to address your questions.

Currently working on an Exchange Hybrid migration where we need this information. Would like to see an update on this soon.

**Comment by JoeDavies-MSFT** [comment]
@ckssaas, @JornMich FYI: I am waiting for a reply from the product team.

**Comment by MoGilbo** [comment]
Any updates on this? Another week on still have doughnuts.

**Comment by NeedsCoffee** [comment]
Bump! 70 days... any news please?

**Comment by JornMich** [comment]
We ended up analyzing the incoming traffic on the firewall. This resulted in using ID #1 from this page for incoming TCP 443 connections and ID #10 for incoming SMTP traffic.

@NeedsCoffee @MoGilbo @mypil

**Comment by NeedsCoffee** [comment]
Thank you @JornMich, that's good enough for me!

**Comment by kenwith** [comment]
Hi All, this is a really great thread! Thank you all for the valuable information. Regarding the documentation that was unpublished. We aren't able to maintain that list of endpoints that was found above. I agree it has some very valuable information but since it is not able to be maintained it can't be guaranteed to be accurate since those could change. The best place to get the latest information would be to open a support request in your tenant and they can prioritize getting you the right information to get your configuration setup. I love this thread though because it really shows how great this community is and how everyone jumps in to help get to a resolution. I love it.

**Comment by ckssaas** [comment]
@kenwith Hi Ken, your positivity is appreciated but this is very disappointing. Regarding inefficiencies, this resolution will affect Microsoft Support, Microsoft Partners, and Microsoft customers alike. My tiny consultancy alone is essentially configuring Exchange Hybrids around the clock so this will cost everyone. I can't imagine keeping an entire support team up to date with EOP subnets is more efficient than posting them to a single page. Best.

**Comment by lion2500** [comment]
@ckssaas. Totally agree with you.
I asked our regional support about this issue. And guess what they say: use the rss feed (I don't remember particular link, cause I'm in vacation, could add it's later). It's just great.
