### ISSUE TITLE
I ran into a number of problems while going through this documentation

### ISSUE THREAD

**Issue by grdylan** [MicrosoftDocs/OfficeDocs-Enterprise#41]
1. `Install-Module MSOnline` gave an error as follows:
Could not retrieve modules repository from 'https://github.com/psget/psget/raw/master/Directory.xml'.

This one was solved by prefixing the command like so `powershellget\Install-Module MSOnline`

2. After being prompted for my username and password, I got an invalid username or password error.

I thought this was quite weird since I use a password manager. I tried again and it still didn't work. 
Next I tried a previously used password and to my surprise this worked.
Then I tried signing into my account on the web with the previously used password and it didn't work (strange)
Signing in on the web with the newer password works!

So it seems that my password is stored twice in 2 difference systems!?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@grdylan, I tried the instructions on a new virtual machine and it worked as documented. If you want to pursue a solution to this problem, please contact Microsoft Support at https://support.microsoft.com/contactus/. Thanks
