### ISSUE TITLE
Provide permission using AD security group on Sharepoint

### ISSUE THREAD

**Issue by sav169** [MicrosoftDocs/OfficeDocs-Enterprise#411]
I have configured Azure AD authentication and it is working fine for individual users. How do I provide permissions on a site using AD security group? We have several AD groups that are used to provide permissions in SharePoint. These AD security groups sync with Azure AD and to O365.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@sav169 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by sav169** [comment]
https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication
I am following the above document to use Azure AD authetication for Sharepoint server 2016 on prem

**Comment by mypil** [comment]
@sav169 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by sav169** [comment]
I have tried that in the past. Since our Sharepoint environemnt is on-prem, O354 support have closed the incident saying they dont support on prem sharepoint. 
The document I am following explains how to add Azure AD users to sharepoint but it dosent explain how to add Azure AD groups. We provide permissions in Sharepoint using AD groups. It would be good if the information to add Azure AD groups is provided in the document - https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication

**Comment by mypil** [comment]
@tseward - as discussed, kindly assist with this issue. Thank you.

**Comment by tseward** [comment]
@sav169 which attribute are you using as your identifier for your users today? AAD SSO has limited support for on-prem sync'ed AD groups, mainly about what it will emit from Active Directory. More info here:

https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-group-claims

**Comment by mypil** [comment]
@sav169 - We would like to follow up. Can you please respond to the query of tseward?

Thank you.

**Comment by sav169** [comment]
Hi Trevor, Thanks for providing the document. I was able to successfully add Azure AD security groups  in Sharepoint following your article and https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/109
I used the Group ID attribute and updated the group claim type mapping in the STS and its is working for me. Thanks for your help
