### ISSUE TITLE
Microsoft Teams and related productivity services in Microsoft 365 for IT architects visio points to a personal OneDrive

### ISSUE THREAD

**Issue by Laotseu** [MicrosoftDocs/OfficeDocs-Enterprise#413]
When I try to open the downloaded https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/raw/live/Enterprise/downloads/msft-m365-teams-logical-architecture.vsdx Visio, I'm asked to login in order to access bcarter personal OneDrive. I'm thinking that the uploaded Visio reference a shape stencil that is stored in that person OneDrive and should have been removed.

Another way would be to put the shape stencil on a CDN and make it available to everyone.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096f9573-ba23-b0a0-23dc-7b0eb57a17d8
* Version Independent ID: 45643fe7-700e-8eca-b7b9-563327472d6b
* Content: [Microsoft cloud IT architecture resources](https://docs.microsoft.com/en-ca/office365/enterprise/microsoft-cloud-it-architecture-resources#feedback)
* Content Source: [Enterprise/microsoft-cloud-it-architecture-resources.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/microsoft-cloud-it-architecture-resources.md)
* Service: **o365-solutions**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Laotseu - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete

**Comment by mypil** [comment]
@BrendaCarter - can you please share your insights on this issue? 

Thank you.

**Comment by BrendaCarter** [comment]
Working on replicating this issue . . .

**Comment by mypil** [comment]
@BrendaCarter - Do you have any updates on this?

thank you.

**Comment by mypil** [comment]
@BrendaCarter - We would like to follow up. Do you have any updates?

Thank you.

**Comment by BrendaCarter** [comment]
I believe this issue is fixed. Please test and let me know if it's still a problem.
