### ISSUE TITLE
Remove unquoted and unused code item.

### ISSUE THREAD

**Issue by hmizael** [MicrosoftDocs/OfficeDocs-Enterprise#415]
Please, remove "$x.ServicePrincipalnames.Add("https://eas.contoso.com/")"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba93584-38f6-bc46-9784-c14492de8f75
* Version Independent ID: 2fc5806d-bc80-9cc4-a051-1a9f16322c8d
* Content: [How to configure Exchange Server on-premises to use Hybrid Modern Authentication](https://docs.microsoft.com/en-us/office365/enterprise/configure-exchange-server-for-hybrid-modern-authentication#feedback)
* Content Source: [Enterprise/configure-exchange-server-for-hybrid-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/configure-exchange-server-for-hybrid-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@hmizael - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@hmizael Thank you for the feedback. We have made the necessary  changes to the document on PR https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/416
