### ISSUE TITLE
"Delete and restore user accounts" or "Delete user accounts"? 

### ISSUE THREAD

**Issue by arowswell** [MicrosoftDocs/OfficeDocs-Enterprise#417]
Sidebar and link says "Delete and restore user accounts" but title says "Delete user accounts". Only has content for "Delete user accounts". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 223fde07-be36-8fb8-b756-4f3c8087210f
* Version Independent ID: 4d993987-b95a-62d8-0237-e4caec5908d2
* Content: [Delete user accounts with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/delete-and-restore-user-accounts-with-office-365-powershell)
* Content Source: [Enterprise/powershell/delete-and-restore-user-accounts-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/delete-and-restore-user-accounts-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@arowswell - Thank you for submitting feedback.

Upon checking the document content, there is actually a portion under the "_Use the Microsoft Azure Active Directory Module for Windows PowerShell_" section which discusses how to restore deleted user accounts and even provides some syntax examples of Powershell commands on how this is done. 

I hope this helps clarify your issue. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
