### ISSUE TITLE
ask for correct information for port of Skype for Business Online and Microsoft Teams

### ISSUE THREAD

**Issue by XixiHuang333** [MicrosoftDocs/OfficeDocs-Enterprise#418]
For 21vianet, 50K outbound port are still required for skype for business conference call.
Ask for correct information for port of Skype for Business Online and Microsoft Teams on this document.
Please contact me at xixih@microsoft.com 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd0d24e-7a31-8a50-ffdd-7823b6c6c01c
* Version Independent ID: 601aeca3-2c5c-3dda-0402-e4fffaa98ae0
* Content: [URLs and IP address ranges for Office 365 operated by 21Vianet](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges-21vianet)
* Content Source: [Enterprise/urls-and-ip-address-ranges-21vianet.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges-21vianet.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@XixiHuang333 - Thank you for submitting this feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Can you please share your insights on this issue?

Thank you.

**Comment by mypil** [comment]
@XixiHuang333 - Could you please assist us by suggesting how this content could be edited to incorporate your feedback? If you could suggest what the appropriate text and where it should be placed, I could assign one of our team members to create a Pull Request to get it added or you may also create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content. Thank you.

**Comment by XixiHuang333** [comment]
HI Joyce,

Do you have previous document version of this?



________________________________

**Comment by mypil** [comment]
@XixiHuang333 - No, I don't have the previous document version. For this issue that you have, I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by XixiHuang333** [comment]
HI Joyce,

I am support engineer from Microsoft Office 365 support team. I have Office 365 21vianet customer who encountered skype for business call issue. I vaguely remembered 50K-60K should be allowed in previous version document of this page.
https://docs.microsoft.com/zh-cn/office365/enterprise/urls-and-ip-address-ranges-21vianet
There is no transport relay for Gallatin skype for business online.

Thus, we suggested customer allow the following port range then the issue was resolved.
TCP/443
UDP 3478-3481
TCP/UDP 50, 000 – 59, 000

In addition, Microsoft Teams is not available and there is no transport rely for Gallatin Office 365. Thus, the information of current version document is not accurate. As Office 365 support, we worry about more customer may be impacted by this.

Also CC technical writers. Sorry that if this is no appropriate way to loop you here.

Thanks,
Xixi

**Comment by mypil** [comment]
@officedocsbot reopen

**Comment by mypil** [comment]
@XixiHuang333 - Thanks for sharing this additional information. I am reopening this issue to get this investigated. Please standby for further updates.

**Comment by mypil** [comment]
@MaratMussabekov - as discussed, kindly work on this issue. Thanks.

**Comment by JoeDavies-MSFT** [comment]
This is being investigated internally as a possible future update. Closing for now.
