### ISSUE TITLE
proxyAddresses - Invalid characters -  apostrophe ?

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/OfficeDocs-Enterprise#419]
This document does not include apostrophe as Invalid characters for proxyAddresses, userPrincipalName and mail
See https://support.microsoft.com/en-au/help/2001616/a-user-s-office-365-email-address-unexpectedly-contains-an-underscore

Reference:
https://blogs.technet.microsoft.com/rmilne/2015/05/14/managing-directory-synchronisation-notes-from-the-field/
https://www.granikos.eu/de/justcantgetenough/PostId/276/email-address-policies-and-the-apostrophe
https://support.microsoft.com/en-au/help/4101088/debug-csinterpoolreplication-can-not-correct-pool-ownership-conflict
https://office365.uservoice.com/forums/289138-office-365-security-compliance/suggestions/19550350-apostrophe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c60ee789-fce6-6c95-150d-be4ae895730e
* Version Independent ID: d9e96954-3b85-bf8d-c7d3-916a4698fd77
* Content: [Prepare for directory synchronization to Office 365](https://docs.microsoft.com/en-us/office365/enterprise/prepare-for-directory-synchronization#feedback)
* Content Source: [Enterprise/prepare-for-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/prepare-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@DavidTaig - Thank you for submitting this feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@DavidTaig Thank you for your feedback. We have added apostrophe to the invalid characters list. this is being tracked on PR  https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/421

**Comment by mypil** [comment]
@DavidTaig - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated

**Comment by JoeDavies-MSFT** [comment]
@DavidTaig  This updates has been published. Thanks again for letting us know.
