### ISSUE TITLE
*.svc.ms listed as "default" required

### ISSUE THREAD

**Issue by Strick1969** [MicrosoftDocs/OfficeDocs-Enterprise#420]
Due to the way that share point zips multiple files and then send from a ".svc.ms" address i respectfully request that line 39 on the article be copied to line 31. specifically the "*.svc.ms" piece 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#sharepoint-online-and-onedrive-for-business)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Strick1969 - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@Strick1969  Thank you for your Feedback. We have made the requested change via PR https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/compare/live...msbemba:patch-6

**Comment by JoeDavies-MSFT** [comment]
@Strick1969 I will pass your suggestion on to the SharePoint Online product team that maintains these endpoints for their consideration in the next update. Thanks for letting us know.
