### ISSUE TITLE
IDfix installation confusion

### ISSUE THREAD

**Issue by ohannanen** [MicrosoftDocs/OfficeDocs-Enterprise#424]
IDfix isn't installed. It's a standalone/portable app that's executed after it's unzipped. There isn't an installation wizard that creates shortcuts or adds it to Programs and Features. Using "Install" language throughout this article can imply that it can be uninstalled and cause confusion. Also, the unzip process doesn't include a Winzip self extractor. It'd probably be better just to say to unzip the file using the native Windows extraction process (right click, Extract All...). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c937e8be-1696-c315-a93b-88f083279644
* Version Independent ID: c0c3d253-4bfe-1750-58a1-4d8f4a1e68d6
* Content: [Install and run the Office 365 IdFix tool](https://docs.microsoft.com/en-us/office365/enterprise/install-and-run-idfix#feedback)
* Content Source: [Enterprise/install-and-run-idfix.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/install-and-run-idfix.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ohannanen - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@ohannanen , @mypil I have updated the article based on your suggestions and stepping through a download/extract process. It is now much clearer that IdFix tool is a download, not a program that is installed. Thanks for letting us know.
