### ISSUE TITLE
The guide is not helpful in enterprise enviroment

### ISSUE THREAD

**Issue by linhnguyennhu** [MicrosoftDocs/OfficeDocs-Enterprise#426]
in Office365 tenant have over 10000 users, we need add more -MaxResults 200000. But the script will take a lot of time to run. 

The better way is run simple command below, we can use excel to create commands quickly 
 Add-MsolRoleMember -RoleMemberEmailAddress abc@xyz.com -RoleName "role name"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbee503e-39f0-b277-20a5-659f1255d775
* Version Independent ID: 884eeb43-1b0b-e6fc-a405-2d50d646819e
* Content: [Assign roles to user accounts with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/assign-roles-to-user-accounts-with-office-365-powershell#feedback)
* Content Source: [Enterprise/powershell/assign-roles-to-user-accounts-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/assign-roles-to-user-accounts-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@linhnguyennhu - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
User Voice **https://office365.uservoice.com**

You might find others have made a similar request that you can add to, or you can open a new one.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by JoeDavies-MSFT** [comment]
@linhnguyennhu I added the "-All" parameter to all instances of the Get-MsolUser command and added sections showing the use of email names (UPNs).

**Comment by linhnguyennhu** [comment]
> @linhnguyennhu I added the "-All" parameter to all instances of the Get-MsolUser command and added sections showing the use of email names (UPNs).

Yep, it can run. But it will take a lot of time. My Office365 tenant have about 12k users, when i run the command, it will take about 3-5 minute for a user. If i run Add-MsolRoleMember only, it will take about few seconds.
