### ISSUE TITLE
Notes for required categories

### ISSUE THREAD

**Issue by warleygr** [MicrosoftDocs/OfficeDocs-Enterprise#428]
When implementing on complex environments or big companies, we need to know and explain why to open some ports/FQDNs/IPs. I'm missing the notes for the required categories, explaining what functionality is involved on each category. It would be helpful even to troubleshoot possible issues.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@warleygr  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Can you please share your insights on this issue?

Thank you.

**Comment by mypil** [comment]
@JoeDavies-MSFT - We would like to follow up.  Can you please share your insights on this issue?

Thank you.

cc: @LauraWi

**Comment by JoeDavies-MSFT** [comment]
@warleygr  Unfortunately, there is no other information available on the endpoints other than what is published. Previous versions of the endpoints content had additional notes, but this information has been removed to streamline the internal vetting and publication process.
