### ISSUE TITLE
Get-SPOGeoMoveStateCompatibility  mentioned in Note?

### ISSUE THREAD

**Issue by RaghuramP** [MicrosoftDocs/OfficeDocs-Enterprise#429]
Is Get-SPOGeoMoveStateCompatibility a cmdlet or some script? Using latest SPO PowerShell module this is not listed as cmdlet?
PS C:\Users\&gt; gcm *spogeo*

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Add-SPOGeoAdministrator                            16.0.88... Microsoft.Online.SharePoint.PowerShell
Cmdlet          Get-SPOGeoAdministrator                            16.0.88... Microsoft.Online.SharePoint.PowerShell
Cmdlet          Get-SPOGeoMoveCrossCompatibilityStatus             16.0.88... Microsoft.Online.SharePoint.PowerShell
Cmdlet          Get-SPOGeoStorageQuota                             16.0.88... Microsoft.Online.SharePoint.PowerShell
Cmdlet          Remove-SPOGeoAdministrator                         16.0.88... Microsoft.Online.SharePoint.PowerShell
Cmdlet          Set-SPOGeoStorageQuota                             16.0.88... Microsoft.Online.SharePoint.PowerShell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b25327c1-71f7-2cdb-0463-cfa8bdd5a743
* Version Independent ID: 74b15568-0546-7248-26b1-381ac12385df
* Content: [Move a OneDrive site to a different geo location](https://docs.microsoft.com/en-us/office365/enterprise/move-onedrive-between-geo-locations#feedback)
* Content Source: [Enterprise/move-onedrive-between-geo-locations.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/move-onedrive-between-geo-locations.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@RaghuramP - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@MikePlumleyMSFT @AdwoodMicrosoft - Do you have any updates on this?

Thank you.

**Comment by MikePlumleyMSFT** [comment]
@RaghuramP the Get-SPOGeoMoveStateCompatibility cmdlet is left over from a preview version of multi-geo. The functionality is covered by Get-SPOGeoMoveCrossCompatibilityStatus as described in the [Validating the environment](https://docs.microsoft.com/Office365/Enterprise/move-onedrive-between-geo-locations#validating-the-environment) section. I've updated the article to remove the note. Thanks for catching this.

**Comment by mypil** [comment]
@RaghuramP - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
