### ISSUE TITLE
Is it possible to authenticate guest/social Azure AD users in this way?

### ISSUE THREAD

**Issue by grizzljt** [MicrosoftDocs/OfficeDocs-Enterprise#43]
Since Azure AD uses different claim types for users who logged in with work or social addresses, how do we support both scenarios?  Is there a way to do claim conversions either through the portal or PowerShell?

**Comment by kaevans** [comment]
This article only covers Azure AD, which does support invited guest users. This article does not cover Azure AD B2C for social identities.

**Comment by grizzljt** [comment]
Thanks Kirk.  As that is a significantly beneficial feature of Azure AD, it seems like it might be worth a mention in the article if that is an unsupported featured.

**Comment by denisebmsft** [comment]
Thank you for the suggestion, grizzljt. I'll make a note to add that note.

**Comment by kaevans** [comment]
@grizzljt I didn't add the note as Azure AD is a different product than Azure AD B2C. I believe the article is clear to its goal of how to configure SharePoint to authenticate to AAD.

@denisebmsft recommend to close.

**Comment by grizzljt** [comment]
I misunderstood, I didn't mean B2C users.  I meant Guest users in Azure AD.  I was unable to log in via a guest user following this documentation.  Are you certain guest users are supported?

**Comment by kaevans** [comment]
I did have problems with this when using AzureCP. The reason appears to be how it stores the user principal name in the dbo.UserInfo table and how SharePoint inspects the user "name" claim. If we remove AzureCP from the equation, it works in SharePoint 2016. 

To verify behavior, I created a cloud only user in another directory.
![image](https://user-images.githubusercontent.com/7107098/41048096-a228de9e-6973-11e8-839c-69e97ca47b60.png)
Go to https://myapps.microsoft.com and sign in as the new user. After signing in, you are prompted to change the password. Once changed, you are prompted with the Keep Me Signed In prompt (if configured for your tenant). 
![image](https://user-images.githubusercontent.com/7107098/41048308-05a2865a-6974-11e8-96ba-bfd2943cc567.png)
Open another window and log into the tenant where the app is registered. Add the newly created user from the other tenant as a guest user.
![image](https://user-images.githubusercontent.com/7107098/41048695-ee9ac804-6974-11e8-833a-c0a27384ea6e.png)
Once added as a guest user, go to the Enterprise Application and add the user.
![image](https://user-images.githubusercontent.com/7107098/41048802-2d75b8f4-6975-11e8-98ee-5fb3f8002512.png)

Go to the SharePoint site in another window as a user with Owner permission on the site. Add the user to the site by using their email address and selecting the "name" claim.
![image](https://user-images.githubusercontent.com/7107098/41048491-6ca68978-6974-11e8-94b6-399e15a0dc43.png)
Go back to the window where you are logged in as the guest user and access the SharePoint site.
![image](https://user-images.githubusercontent.com/7107098/41048904-61d74d9c-6975-11e8-8872-fa12d95159b7.png)

**Comment by kaevans** [comment]
@denisebmsft as the issue seems specific to AzureCP, and the ability to invite guest users via B2B was verified and demonstrated, please close.

**Comment by grizzljt** [comment]
I can resolve guest users via AzureCP without issue on SP2016 with ADFS.  Could you weigh in @Yvand ?

**Comment by kaevans** [comment]
@grizzljt @Yvand The issue that I am seeing is that AzureCP add the tp_Login value in the UserInfo table with the full external UPN from AAD, but using the name claim as mapped results in the UPN as reflected in the source directory. In this screenshot, the red ones were added using AzureCP, the green ones added using the name claim in the people picker without AzureCP.

![image](https://user-images.githubusercontent.com/7107098/41195593-f801867a-6bf5-11e8-88ad-af3caf07fbc4.png)

**Comment by Yvand** [comment]
The behaviour is due to how properties are stored for Guest users (compared to Member users) in Azure AD.

I ran queries below using [Microsoft Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) (which AzureCP uses since the last version) to illustrate it:

Get Member users:
/users?$filter=UserType eq 'Member' &$select=userPrincipalName, mail, UserType &$top=5
```json
"value": [
	{
		"mail": null,
		"userPrincipalName": "aadUser1@AADTENANT.onmicrosoft.com",
		"userType": "Member"
	}
]
```

Get Guest users:
/users?$filter=UserType eq 'Guest' &$select=userPrincipalName, mail, UserType &$top=5
```json
"value": [
	{
		"mail": "yvan84@MAIL.com",
		"userPrincipalName": "yvan84_MAIL.com#EXT#@AADTENANT.onmicrosoft.com",
		"userType": "Guest"
	}
]
```

AzureCP (by default) uses property "userPrincipalName", which is fine for Member users. But for Guest users, that property doesn't contain the "expected" value, which is in property "mail".

Azure AD handles that when it populates the SAML token during sign-in:

- When a Member user signs-in, Azure AD sets the claim "name" with the value in "userPrincipalName"
- When a Guest user signs-in, Azure AD sets the claim "name" with the value in "mail"

So, ideally, I think AzureCP should do the same: for Guest users, use the value in "mail" to create the permission (instead of the "userPrincipalName").

What do you think?

**Comment by kaevans** [comment]
@Yvand I don't know if that's a valid assumption, the email could be orthogonal to the value in the NameIdentifier claim. Further, I have some older external users that have userType: Member where the mail claim is not present. I have an email to the AAD team asking about the inconsistencies.

**Comment by Yvand** [comment]
@kaevans Great, indeed, it is just an assumption and it would be nice to know for sure how to handle Guest users.

@grizzljt This updates the claims in the SAML token, but this doesn't impact how AzureCP queries users. Even with v12, I think that the problem explained by @kaevans (with his screenshot of UserInfo table) is correct and prevents to grant direct access to Guest users.

**Comment by denisebmsft** [comment]
Thanks, Yvand and grissljt, for the feedback. And thanks, kaevans, for looking into this. I will keep this issue open for now and will check in again soon.
