### ISSUE TITLE
endpoints.office.com && Dropbox.

### ISSUE THREAD

**Issue by apmari** [MicrosoftDocs/OfficeDocs-Enterprise#433]
Hi there,
as a O365 customer, i configured my Cisco WSAs (web proxies) to download the live feed of the O365 sites directly from you (https://endpoints.office.com/endpoints/worldwide).
Now, we forbid access to online cloud and file exchanger site but our proxies were working weird.
With suprise i found www.dropbox.com and other external URLs in the feed.
Why are you including all these URLs not part of your perimeter?
I think is very etically unfair. Do you have some solid reason?
Regards,
apm

**Comment by JoeDavies-MSFT** [comment]
I have asked someone from the product team to answer your question.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by JoeDavies-MSFT** [comment]
@apmari From the product team: We publish the endpoint as “optional”. We also mention that we integrate with dropbox for outlook for Android and iOS.

**Comment by apmari** [comment]
Hi there Joe,
i read the paper and is true, is classified as "Optional" (https://docs.microsoft.com/it-it/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252fen-us%252farticle%252foffice-365-urls-and-ip-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2)
I need to find a way to build the query only to receive essential informations we need.
Thanks,
apm
