### ISSUE TITLE
Configure Skype for Business hyperlink is not working

### ISSUE THREAD

**Issue by bament-hun** [MicrosoftDocs/OfficeDocs-Enterprise#434]
Hello Team,

if you are on this page: https://docs.microsoft.com/en-us/office365/enterprise/hybrid-modern-auth-overview and click on Configure Skype for Business original page is just refreshed, however it should redirected to here:
https://docs.microsoft.com/en-us/office365/enterprise/configure-skype-for-business-for-hybrid-modern-authentication

please fix

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@bament-hun - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
@mypil  this item has been solved already.

**Comment by mypil** [comment]
@j0rt3g4 - As discussed, it does not appear to be fixed yet so please re-check it. Thank you.

**Comment by j0rt3g4** [comment]
Will do

**Comment by j0rt3g4** [comment]
Fixing broken link with PR #436

**Comment by mypil** [comment]
@bament-hun - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
