### ISSUE TITLE
no history for this page, not attached to Hybrid Modern Auth

### ISSUE THREAD

**Issue by bament-hun** [MicrosoftDocs/OfficeDocs-Enterprise#435]
this page should be connected to this thread:
Office 365 Enterprise  / Plan for Office 365 /  Hybrid modern authentication

See related Github report from me: https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/434

it's very hard to find for our customers.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
Closing this issue as it is a duplicate or related to issue #434.

**Comment by mypil** [comment]
@officedocsbot reopen
