### ISSUE TITLE
Outdate info

### ISSUE THREAD

**Issue by LTUTE** [MicrosoftDocs/OfficeDocs-Enterprise#437]
https://channel9.msdn.com/Series/Microsoft-Azure-Tutorials/Associate-an-Office-365-tenant-with-an-Azure-subscription is outdated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdf56d0-5b7a-f0df-86c2-14ce1c067514
* Version Independent ID: 76a8737d-8f21-56ae-93f5-5d7942813484
* Content: [Subscriptions, licenses, accounts, and tenants for Microsoft's cloud offerings](https://docs.microsoft.com/en-us/office365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings#feedback)
* Content Source: [Enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@LTUTE - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LTUTE** [comment]
Grate, thank you a lot!

2019-06-14, pn 21:34, Joyce Y. <notifications@github.com> rašė:

**Comment by msbemba** [comment]
@LTUTE Thank you for your feedback. We have created  PR https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/438 for the changes requested.

**Comment by JoeDavies-MSFT** [comment]
Updates to article published live. Thanks, everyone!
