### ISSUE TITLE
IP in use that is not documented

### ISSUE THREAD

**Issue by dsbrodbeck** [MicrosoftDocs/OfficeDocs-Enterprise#441]
Your 'Office 365 Partners Support' told me to leave this here.  I received a rejected email message based on the IP that the sending server used.  The IP is not in the spf record Microsoft has documented and so it was rejected as spam.  The header follows.  20.177.254.156 is the undocumented IP.

Received: from SN6PR06MB4589.namprd06.prod.outlook.com (52.135.115.87) by
 SN6PR06MB6045.namprd06.prod.outlook.com (20.177.254.156) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.20.1856.14; Mon, 6 May 2019 21:16:22 +0000
Received: from SN6PR06MB4589.namprd06.prod.outlook.com
 ([fe80::5c99:3b8a:3fec:3940]) by SN6PR06MB4589.namprd06.prod.outlook.com
 ([fe80::5c99:3b8a:3fec:3940%4]) with mapi id 15.20.1856.012; Mon, 6 May 2019
 21:16:22 +0000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#exchange-online)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@dsbrodbeck - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Can you please share your insights on this issue?

Thank you.

**Comment by JoeDavies-MSFT** [comment]
@dsbrodbeck The FQDN SN6PR06MB6045.namprd06.prod.outlook.com is covered by the endpoint *.outlook.com. This is a Default category endpoint and should be treated as normal Internet traffic. With these types of wildcard FQDNs, we do not provide corresponding lists of IP addresses. See https://docs.microsoft.com/en-us/office365/enterprise/office-365-network-connectivity-principles#new-office-365-endpoint-categories for more information. Thanks for your question.

**Comment by dsbrodbeck** [comment]
Hey Joe, thanks.

How do I resolve this issue then with the authorized IPs for purposes of SPF records then?  The server sending this message is/was not in the provided SPF record (spf.protection.outlook.com) or its included domains, and so any system running DMARC or inspecting SPF results will flag messages from this server as suspicious.  This means I have delivery issues when I turn DMARC and SPF 'on'.

The DMAC system does not use FQDNs but instead IP addresses or IP networks with CIDR.

Thanks
David
________________________________
