### ISSUE TITLE
Urls for OneDrive

### ISSUE THREAD

**Issue by lmarianko** [MicrosoftDocs/OfficeDocs-Enterprise#442]
When clicking on the sync button in the OneDrive client to download the client, it directs you to https://onedrive.live.com/about/download/.  However this URL is not contained in the URL list for SharePoint/OneDrive in this document.  Shouldn't it be there? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@lmarianko - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@lmarianko I am checking with the product team on this URL. Thanks for letting us know.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Do you have any updates on this?

Thank you.

**Comment by JoeDavies-MSFT** [comment]
@lmarianko Issue resent to the product team. Thanks

**Comment by JoeDavies-MSFT** [comment]
@lmarianko This is being discussed internally. I can't give you a timeframe for when this issue will be decided. Thanks so much for letting us know.
