### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by chi-ltd** [MicrosoftDocs/OfficeDocs-Enterprise#443]
Out of interest, is it possible to increase the default timeouts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1570de51-50b1-d4cc-c1c7-832b3242ccb3
* Version Independent ID: f5250f91-0a48-20cf-8e2c-e2dc347edd88
* Content: [Session timeouts for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/session-timeouts)
* Content Source: [Enterprise/session-timeouts.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/session-timeouts.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@chi-ltd - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
