### ISSUE TITLE
Is *.s-msedge.net missing from the Skype / Teams section?

### ISSUE THREAD

**Issue by Glylyna** [MicrosoftDocs/OfficeDocs-Enterprise#444]
It seems that one of the domains used for teams.microsoft.com is missing from the required URL list. 
While setting up rules based on the chart above, we were hit by the fact that ultimately teams.microsoft.com wasn't working because it ultimately requires s-msedge.net to operate ( Teams.microsoft.com resolves to teams-afd.trafficmanager.net which in turn resolves to &lt;something&gt;.s-msedge.net). Shouldn't this domain be included?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Glylyna - Thank you for submitting this feedback.

I will get this over to @JoeDavies-MSFT for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by msbemba** [comment]
@Glylyna  Thank you for the feedback. I have created a PR https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/454 to reflect the changes in doc.

Thanks
Sri

**Comment by JoeDavies-MSFT** [comment]
@Glylyna I have forwarded this issue to the product team who maintains the endpoints for Teams for their consideration in a future update. Thanks for letting us know.

**Comment by JoeDavies-MSFT** [comment]
@Glylyna Please see https://docs.microsoft.com/en-us/office365/enterprise/managing-office-365-endpoints#bkmk_cname for more information on this issue.
