### ISSUE TITLE
Two "Step 2"s and no step 3

### ISSUE THREAD

**Issue by severud** [MicrosoftDocs/OfficeDocs-Enterprise#445]
I see that there are two items listed at "Step 2" and then "Step 4": 
2. Directory object and attribute preparation
2. Prepare the userPrincipalName attribute
Too bad headers can't be made as ordered lists with GFM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c60ee789-fce6-6c95-150d-be4ae895730e
* Version Independent ID: d9e96954-3b85-bf8d-c7d3-916a4698fd77
* Content: [Prepare for directory synchronization to Office 365](https://docs.microsoft.com/en-us/office365/enterprise/prepare-for-directory-synchronization)
* Content Source: [Enterprise/prepare-for-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/prepare-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@severud - Thank you for pointing this out.

PR #446 has been created to fix and close this issue once the PR is merged.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@severud - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for reporting and making the docs better. Much appreciated.

**Comment by mypil** [comment]
@officedocsbot close
