### ISSUE TITLE
Documentation needed on "keep me signed in option"

### ISSUE THREAD

**Issue by onursamiolmez** [MicrosoftDocs/OfficeDocs-Enterprise#447]
I'm still a little confused about how this plays with "keep me signed in option" in AAD. No mention of it here and not very good documentation on how this affects access token time periods anywhere on docs.microsoft.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1570de51-50b1-d4cc-c1c7-832b3242ccb3
* Version Independent ID: f5250f91-0a48-20cf-8e2c-e2dc347edd88
* Content: [Session timeouts for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/session-timeouts#feedback)
* Content Source: [Enterprise/session-timeouts.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/session-timeouts.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@onursamiolmez - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by alevere** [comment]
I agree on the lack of documentation onursamiolmez pointed out.

**Comment by joinimran** [comment]
@onursamiolmez Thank you for query on this doc. Please note this doc is applicable for Office365 services. Your AAD related services, please see https://techcommunity.microsoft.com/t5/Azure-Active-Directory-Identity/Fewer-login-prompts-The-new-8220-Keep-me-signed-in-8221/ba-p/245310 and for sessions durations please see https://techcommunity.microsoft.com/t5/Azure-Active-Directory-Identity/Changes-to-the-Token-Lifetime-Defaults-in-Azure-AD/ba-p/245304

Regards,
Imran

**Comment by mypil** [comment]
@onursamiolmez - From our understanding, the issue has been answered by joinimran. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
