### ISSUE TITLE
#8 is incorrectly defined as not Express Route

### ISSUE THREAD

**Issue by KevFM** [MicrosoftDocs/OfficeDocs-Enterprise#450]
ID #8 is defined as not being Express Route service but the matches that I have in our environment (attachments.office.net and autodiscover-s.outlook.com) are all serviced via Express Route.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@KevFM - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by KevFM** [comment]
Apologies. I forgot commenting directly in Github won't include the relevant link.

https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges

Regards,
Kev
[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges>
Office 365 URLs and IP address ranges | Microsoft Docs<https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges>
Summary: Office 365 requires connectivity to the Internet. The endpoints below should be reachable for customers using Office 365 plans, including Government Community Cloud (GCC).
docs.microsoft.com



Kevin Farnes  |  Senior Professional Services Engineer
Palo Alto Networks  |  140 Leadenhall Street  |  London  EC3V 4QT  |  UK
Mobile: +44 (0) 7879 772468  | www.paloaltonetworks.com<mailto:email@paloaltonetworks.com>
JMS: +44 (0) 1225 818133 | farnesk@jms.mod.uk
MODNET: kevin.farnes100@mod.gov.uk


________________________________

**Comment by mypil** [comment]
@JoeDavies-MSFT - Can you please share your insights on this issue? 

This might need to be consulted with the product team that manages the endpoint data for this content. Here are some details for your reference:

Content Title: **Office 365 URLs and IP address ranges**
Live Content: **https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges**
Content Source: **https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md**

Thank you for your kind assistance.

**Comment by JoeDavies-MSFT** [comment]
KevFM From the definition of the "ER" Column: When ER is No, this means that ExpressRoute is not supported for this endpoint set. However, it should not be assumed that no routes are advertised for an endpoint set where ER is No.  Does this address your issue? Thanks

**Comment by KevFM** [comment]
Hi Joe,

As a statement this simply doesn't make sense.

I don't understand how you can have an Endpoint Set that isn't supported over Express Route but you still advertise routes to that Endpoint Set over Express Route and all access to that Endpoint Set is via Express Route?

Surely if it wasn't supported over Express Route then I shouldn't be able to access it via Express Route?

Regards,
Kev



Kevin Farnes  |  Senior Professional Services Engineer
Palo Alto Networks  |  140 Leadenhall Street  |  London  EC3V 4QT  |  UK
Mobile: +44 (0) 7879 772468  | www.paloaltonetworks.com<mailto:email@paloaltonetworks.com>
JMS: +44 (0) 1225 818133 | farnesk@jms.mod.uk
MODNET: kevin.farnes100@mod.gov.uk


________________________________

**Comment by mypil** [comment]
@JoeDavies-MSFT - Can you please assist to respond to KevFM's additonal query? 

Thank you.

**Comment by JoeDavies-MSFT** [comment]
@KevFM I have forwarded this issue to the product team responsible for maintaining the Exchange Online endpoints for their investigation. Hope to have an answer soon.

**Comment by JoeDavies-MSFT** [comment]
@KevFM Here is the response: Because these endpoints are in the Default category, they would not be listed as supported on ExpressRoute (ExpressRoute = No). If you are routing to ExpressRoute by IP addresses rather than the more common URL routing with proxy servers, then these servers may route traffic to your two listed URLs over ExpressRoute without any problems.

**Comment by KevFM** [comment]
But that still doesn't explain why, if its not supported over Express Route, you would provide routing via Express Route. Surely the fact that you are providing routes over Express Route means it is supported - I don't understand the difference. Regardless of whether you route via IP or by URL, that fact that you can access it via Express Route surely means its supported over Express Route.

Are you saying they are only listed as not supported over Express Route because they are in the Default category?

I'm trying to understand the ER column as I need to define firewall policies based on that information, i.e. making sure that the correct URL's go down the correct path. At the moment I can't reliably do this as the more accurate definition of the ER columns seems to be either 'Yes' or 'Maybe' as it seems 'No' doesn't really mean 'No'.

Regards,
Kev


Kevin Farnes  |  Senior Professional Services Engineer
Palo Alto Networks  |  140 Leadenhall Street  |  London  EC3V 4QT  |  UK
Mobile: +44 (0) 7879 772468  | www.paloaltonetworks.com<mailto:email@paloaltonetworks.com>
JMS: +44 (0) 1225 818133 | farnesk@jms.mod.uk
MODNET: kevin.farnes100@mod.gov.uk


________________________________
