### ISSUE TITLE
aadcdn.msauth.cn and aadcdn.msftauth.cn are missing in Microsoft 365 Common section

### ISSUE THREAD

**Issue by leapyear1969** [MicrosoftDocs/OfficeDocs-Enterprise#452]
Users need to connect to the two CDNs if they want visit office 365 Service. Please add the two CDN addrees to the list.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd0d24e-7a31-8a50-ffdd-7823b6c6c01c
* Version Independent ID: 601aeca3-2c5c-3dda-0402-e4fffaa98ae0
* Content: [URLs and IP address ranges for Office 365 operated by 21Vianet](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges-21vianet#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges-21vianet.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges-21vianet.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@leapyear1969 - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@leapyear1969  Thank you for the feedback. We have raised a PR https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/453 to reflect changes in the common section.

Thanks
Sri

**Comment by JoeDavies-MSFT** [comment]
@leapyear1969 I have forwarded your request to the product team that manages these endpoints for their consideration in a future update. Thanks for letting us know.
