### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/OfficeDocs-Enterprise#455]
The link to the SOF website is broken (https://www.skypeoperationsframework.com/). In addition, it doesnt seem like I can access MyAvisor on the FastTrack site anymore either, I guess I missed some news. Can you please update the article with the relevant replacement, if any?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b23150f-2d5e-daaf-838d-db67e6513299
* Version Independent ID: 55cf7d62-fdf9-7499-5603-d093cfb0effc
* Content: [Assessing Office 365 network connectivity](https://docs.microsoft.com/en-us/office365/enterprise/assessing-network-connectivity)
* Content Source: [Enterprise/assessing-network-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/assessing-network-connectivity.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@michevnew - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@kelleyvice-msft - I checked and validated this, there's an error: "This site can’t be reached www.skypeoperationsframework.com’s server IP address could not be found".

Do you happen to know the correct URL for this? Or should the hyperlink for Skype Operations Framework be removed from the document content?

Please advise on how to proceed so we can create a PR if needed to get this fixed. Thank you.

**Comment by kelleyvice-msft** [comment]
Looking into this now.

**Comment by kelleyvice-msft** [comment]
Some links and references were out of date. I updated the topic with a new set of resource links and removed references to obsolete tools. Republishing now.
@michevnew - I'm looking into how to access MyAdvisor, but it appears I need to do some configuration first. I will reply back when I have information.
Kelley

**Comment by mypil** [comment]
@michevnew - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
