### ISSUE TITLE
enterpriseregistration.windows.net CIDR 

### ISSUE THREAD

**Issue by byteben** [MicrosoftDocs/OfficeDocs-Enterprise#456]
Hey,

I have observed the following:-
enterpriseregistration.windows.net is a CNAME for enterpriseregistration.trafficmanager.net &gt; is a CNAME for  prod-a-drs-eus2.cloudapp.net &gt; resolves to 23.100.68.183 (CIDR 23.100.0.0/15).

It would be useful to have these IP's documented (below) as we saw many Azure AD Hybrid join failures relating to this range until we unblocked it on our firewall.

https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@byteben - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Can you please share your insights on this issue?

Thank you.

**Comment by JoeDavies-MSFT** [comment]
@bytenbe This IP address is included in the range 23.100.64.0/21, which is listed in the "Azure IP Ranges and Service Tags – Public Cloud" JSON file at https://www.microsoft.com/en-us/download/details.aspx?id=56519. These Azure endpoints are outside the scope of the Office 365 endpoints article. Thanks

**Comment by byteben** [comment]
Thanks Joe,

That’s useful to know. It kinda made sense to me to include it as the other CNAMES for Hybrid join are in this doc

Kind Regards
Ben

Sent from my iPhone

On 9 Jul 2019, at 18:44, Joe Davies <notifications@github.com<mailto:notifications@github.com>> wrote:


@bytenbe This IP address is included in the range 23.100.64.0/21, which is listed in the "Azure IP Ranges and Service Tags – Public Cloud" JSON file at https://www.microsoft.com/en-us/download/details.aspx?id=56519. These Azure endpoints are outside the scope of the Office 365 endpoints article. Thanks
