### ISSUE TITLE
Office proxy settings?

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [MicrosoftDocs/OfficeDocs-Enterprise#458]
Hello,

We are attempting to set up Office build 16.26 on our Macs. We do have a proxy and it is configured in System Preferences with appropriate credentials. We are encountering an issue on first launch with activation. We are getting a popup that says "No network connection Please check your network settings and try again". We are able to access the internet because it works through Safari. We've run Wireshark and are seeing many 407 errors despite having credentials entered in the System proxy settings.

The documentation says that builds 15.27 or later have specific fixes for NTLM and Kerberos servers. It doesn't seem that Office recognizes that we have valid proxy credentials. We have not come across any preference keys related to proxy settings/use. Is there something special we need to do to have Office use the System proxy settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a31219ba-1069-9336-daa2-2f76e35e7ba6
* Version Independent ID: 6d0c419f-8a41-a6cc-222f-9b44dfb4716d
* Content: [Network requests in Office for Mac](https://docs.microsoft.com/en-us/office365/enterprise/network-requests-in-office-2016-for-mac)
* Content Source: [Enterprise/network-requests-in-office-2016-for-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/network-requests-in-office-2016-for-mac.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@FMCUSystemAdmins - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by FMCUSystemAdmins** [comment]
Great, thank you so much.
Thanks,
Craig Jones
Sr. System Administrator
Firstmark Credit Union | Information Technology
2023 Gold Canyon Dr. | San Antonio, TX 78232
210.341.9602 x10514
craigj@firstmarkcu.org<mailto:mcraigj@firstmarkcu.org> | www.firstmarkcu.org<http://www.firstmarkcu.org/>
CONFIDENTIAL NOTIFICATION: This electronic mail message and any files or documents transmitted with it contain information belonging to the sender that is confidential and may be legally privileged.  This information is intended for the use of the individual or entity to which it is addressed.  If you are not the intended recipient, be advised that you may have received this electronic mail in error and that any use, including but not limited to, disclosure, copying, distribution, forwarding, printing, dissemination of any kind, or action taken in reaction to or reliance on the contents of the information is strictly prohibited.  If you have received this electronic mail message in error, please immediately delete it as permanently as possible and notify the sender.

**Comment by JoeDavies-MSFT** [comment]
@FMCUSystemAdmins I have forwarded this issue to the internal owners to analyze your request and respond. Please stay tuned. Thanks

**Comment by FMCUSystemAdmins** [comment]
Great, thank you for your help.
Thanks,
Craig Jones
Sr. System Administrator
Firstmark Credit Union | Information Technology
2023 Gold Canyon Dr. | San Antonio, TX 78232
210.341.9602 x10514
craigj@firstmarkcu.org<mailto:mcraigj@firstmarkcu.org> | www.firstmarkcu.org<http://www.firstmarkcu.org/>
CONFIDENTIAL NOTIFICATION: This electronic mail message and any files or documents transmitted with it contain information belonging to the sender that is confidential and may be legally privileged.  This information is intended for the use of the individual or entity to which it is addressed.  If you are not the intended recipient, be advised that you may have received this electronic mail in error and that any use, including but not limited to, disclosure, copying, distribution, forwarding, printing, dissemination of any kind, or action taken in reaction to or reliance on the contents of the information is strictly prohibited.  If you have received this electronic mail message in error, please immediately delete it as permanently as possible and notify the sender.

**Comment by FMCUSystemAdmins** [comment]
Any updates on this?

**Comment by FMCUSystemAdmins** [comment]
Hello, has there been any progress on this?

From: Craig Jones
Sent: Wednesday, July 17, 2019 1:32 PM
To: MicrosoftDocs/OfficeDocs-Enterprise <reply@reply.github.com>; MicrosoftDocs/OfficeDocs-Enterprise <OfficeDocs-Enterprise@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/OfficeDocs-Enterprise] Office proxy settings? (#458)

Any updates on this?

**Comment by mypil** [comment]
@FMCUSystemAdmins - The product team is still investigating on this issue. We will provide updates as soon as we have the information. Thank you for your patience.

**Comment by FMCUSystemAdmins** [comment]
We understand that updates will be provided as information is available and we appreciate the team looking into this.  However, this issue is preventing us from moving some projects forward. Just sending this to ensure it is kept on the radar.

Thanks.

**Comment by JoeDavies-MSFT** [comment]
@FMCUSystemAdmins Please open a service ticket in your tenant at https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=phone. Thanks

**Comment by FMCUSystemAdmins** [comment]
We have opened a service ticket. Thank you.

**Comment by guytz72** [comment]
FMCUSystemAdmins I'm having the same issue when trying to set up Outlook for O365 on a Mac behind a corportate proxy.  Everything else is working ok when accessing the internet, but I can't set up Outlook.  If I open a hole in the proxy and alow the Mac out then it works fine.  Close the hole (as per policy everything needs to go throught the proxy) and it does not work.  Did you get any resolution from MS?

**Comment by FMCUSystemAdmins** [comment]
Attached is where we left off with troubleshooting.
With us working with a proxy (which is the bane of our existence) and not having dedicated Mac expertise in-house, we have yet to actually crack down on ensuring our users and their Macs truly have access to all required endpoints for the Office suite to behave as expected.
