### ISSUE TITLE
Is "Office 365 Endpoint Functions Module" section needed?

### ISSUE THREAD

**Issue by rykoma** [MicrosoftDocs/OfficeDocs-Enterprise#459]
Do we really need to introduce the O365EndpointFunctions.psm1 in this document? The way to use the web service is already described in "Example PowerShell Script" section and "Example Python Script" section.

And the way to create a PAC file from the response of the web service is described in the following document.  
In this document, we are introducing Get-PacFile script. This script is a 1st party script and the author is Microsoft.

Managing Office 365 endpoints  
https://docs.microsoft.com/en-us/office365/enterprise/managing-office-365-endpoints

But, O365EndpointFunctions.psm1 is a 3rd party script.

The readers of the document misunderstand that O365EndpointFunctions.psm1 is provided by Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7ebf92c-e478-0f65-0494-97042e974b46
* Version Independent ID: 7e1b9b91-d60d-8665-9a39-2ca77a46b4ce
* Content: [Office 365 IP Address and URL Web service](https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service#feedback)
* Content Source: [Enterprise/office-365-ip-web-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@rykoma - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@kelleyvice-msft - Can you please share your insights on this issue?

Thank you.

**Comment by JeremyTBradshaw** [comment]
@rykoma @mypil @kelleyvice-msft - adding my opinion - I like that the module gets its own section and link.  I wouldn't want to have had to learn of its existence by having had to read through the entire example PowerShell script, and noticing the import-module / install-module parts.

Maybe it could get its own entire  page, but to hide its existence in an example script, I don't think that would be good.  Imagine if Azure AD module was only mentioned in example scripts - nobody would know it existed.

**Comment by rykoma** [comment]
@JeremyTBradshaw , thank you for your comment! I understand your point, but this is a Microsoft official documentation and in my opinion, it shouldn't introduce any 3rd party solution, especially when we have a 1st party solution.  
If we really need to introduce O365EndpointFunctions.psm1, I think it should state that it is a 3rd party script. Not only that, we should also state that we have the Get-PacFile script as a 1st party script.

In fact, we once had a customer who was confused as to why we have two solutions to create a PAC file from the response of the Office 365 IP Address and URL Web service, and we ended up recommending Get-PacFile over O365EndpointFunctions.psm1 because the former is provided by Microsoft. (btw, Microsoft does not offer customer support for either of the scripts, because they are released under the MIT license.)

**Comment by JeremyTBradshaw** [comment]
@rykoma I totally missed that it's 3rd party.  Now I agree with you.  The example is far enough for that.  I'm the same in wanting to advise customers on official features/tools 3rd party.

Thanks for clearing that up for me.

**Comment by kelleyvice-msft** [comment]
I agree that we should remove this section. It's possible this section was added before the Get-PacFile module was published. I'll remove it, and replace it with a summary and link to the Get-PacFile section in the Managing Office 365 endpoints topic. Thanks @rykoma for calling this out.

**Comment by kelleyvice-msft** [comment]
Complete. Thanks again! https://github.com/MicrosoftDocs/OfficeDocs-Enterprise-pr/pull/809
