### ISSUE TITLE
Code to get Verification DNS record is missing a parameter

### ISSUE THREAD

**Issue by AaronKung** [MicrosoftDocs/OfficeDocs-Enterprise#462]
This code does not give you the TXT record value needed:

Get-MsolDomainVerificationDNS -TenantId &lt;customer TenantId&gt; -DomainName &lt;FQDN of new domain&gt;

It is missing:
-Mode DnsTxtRecord

Should be: Get-MsolDomainVerificationDNS -TenantId &lt;customer TenantId&gt; -DomainName &lt;FQDN of new domain&gt; -Mode DnsTxtRecord

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36dec558-04d2-208a-7e87-51489a9973e9
* Version Independent ID: 6198b8c1-7ded-c451-97ab-63425e4c925c
* Content: [Add a domain to a client tenancy with Windows PowerShell for Delegated Access Permission (DAP) partners](https://docs.microsoft.com/en-us/office365/enterprise/powershell/add-a-domain-to-a-client-tenancy-with-windows-powershell-for-delegated-access-pe#feedback)
* Content Source: [Enterprise/powershell/add-a-domain-to-a-client-tenancy-with-windows-powershell-for-delegated-access-pe.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/add-a-domain-to-a-client-tenancy-with-windows-powershell-for-delegated-access-pe.md)
* Service: **o365-administration**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@AaronKung - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hello @AaronKung thanks for your feedback.
I created a pull request to correct the example.
Thank you

**Comment by mypil** [comment]
@AaronKung - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
