### ISSUE TITLE
[LOC] UNRESOLVED_TOKEN_VAL displayed in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-Enterprise#463]
**article:** add-a-domain-to-a-client-tenancy-with-windows-powershell-for-delegated-access-pe.md
**author:** chrfox
**GH:** https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/add-a-domain-to-a-client-tenancy-with-windows-powershell-for-delegated-access-pe.md

**repro steps:**
 - open the mentioned article
 - check "_What do you need to know before you begin?_" paragraph
   - _UNRESOLVED_TOKEN_VAL(GENL_O365_PowerShell_BeforeYouBegin)_ displayed

screen:
![image](https://user-images.githubusercontent.com/47977325/61215977-90112680-a70c-11e9-967c-0d6c93b2add2.png)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@OfficeGlobal - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@OfficeGlobal - The issue has been resolved. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
