### ISSUE TITLE
Question Regarding Modern Team Sites

### ISSUE THREAD

**Issue by Peter-Ross-C** [MicrosoftDocs/OfficeDocs-Enterprise#477]
Does the above only apply to Classic Team Sites with server publishing enabled? As the options above do not even show up without having that setting enabled and that setting is not supported on Modern Team sites. 

So is the current navigation on the Modern Team sites using a more efficient method for rendering the current nav?

I feel this needs to be clearer in the docs. 

Thank you kindly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe686368-f607-9a7d-710b-d51c3f8f6c9a
* Version Independent ID: 01b5902a-6e23-62d9-f0a3-7c1e86194ef1
* Content: [Navigation options for SharePoint Online](https://docs.microsoft.com/en-us/office365/enterprise/navigation-options-for-sharepoint-online#feedback)
* Content Source: [Enterprise/navigation-options-for-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/navigation-options-for-sharepoint-online.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Peter-Ross-C - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Peter-Ross-C - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
