### ISSUE TITLE
For the given PowerShell script

### ISSUE THREAD

**Issue by 2009gautamkumar** [MicrosoftDocs/OfficeDocs-Enterprise#478]
Dear Microsoft, For the given PowerShell script, kindly put a disclaimer 

"Microsoft assumes every single person reading this article is a geek in scripting, Hence no examples for executing the script is provided"

Things such as:
1. Should it be run from ISE or as a .PS1 file 
2. Line 4 [$datapath = $Env:TEMP + "\endpoints_clientid_latestversion.txt"]
should it be modified to some location, etc. ?

Hence if this article can have a disclaimer it will be better to look for information elsewhere for those people who are not good in scripting.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7ebf92c-e478-0f65-0494-97042e974b46
* Version Independent ID: 7e1b9b91-d60d-8665-9a39-2ca77a46b4ce
* Content: [Office 365 IP Address and URL Web service](https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service)
* Content Source: [Enterprise/office-365-ip-web-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@2009gautamkumar - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@kelleyvice-msft - Can you please share your insights on this issue?

Thank you.

**Comment by kelleyvice-msft** [comment]
@2009gautamkumar - Thanks for reaching out. Your point is well taken; we do make implicit assumptions about the reader's familiarity with scripting. I will take this feedback to our writing team and discuss how we might make it easier for readers to know how to use scripts we provide in our content.

With respect to this particular script, it can be run either in the ISE or in the console by running the following in a PowerShell console:
``` powershell
powershell.exe -file <path to the script>\<script name>.ps1
```
**$Env:TEMP** is a global PowerShell variable that contains the path to the current user's TEMP directory, usually _C:\Users\<username>\AppData\Local\Temp_. You can simply run $Env:TEMP in a PowerShell console and it will output the path. If you would like to save the output .txt file somewhere specific, you can change line 4 from:
``` powershell
$datapath = $Env:TEMP + "\endpoints_clientid_latestversion.txt"
```
to:
``` powershell
$datapath = "c:\somefoldername\endpoints_clientid_latestversion.txt"
```
I will add some of this information to the section containing the script, close this issue and take this back to the writing team for discussion. Thanks again.

Kelley

**Comment by kelleyvice-msft** [comment]
@2009gautamkumar - I've updated the script and related guidance in the topic https://aka.ms/ipurlws to help clarify how it should be used and to improve its usefulness. I'd love to hear your feedback on the revisions. Again, thanks for helping to improve out content!

Kelley
