### ISSUE TITLE
CDN will not work if you have custom mail domains

### ISSUE THREAD

**Issue by jkuter** [MicrosoftDocs/OfficeDocs-Enterprise#479]
Even if you do not have a custom (vanity) domain set for SharePoint this feature will still not work if you have a custom mail domain (this will be almost every enterprise user).  Please update your text at the top of this article to be more clear and define that this feature will not work if you have a vanity domain set for any part of Office 365, not just SharePoint. I added a uservoice here https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/38218450-enable-cdn-for-tenants-with-custom-domains-assigne

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97626653-f653-d954-7a39-e5beac635e18
* Version Independent ID: 86f7d0b5-3a63-7511-0fc6-e3d98bea4b74
* Content: [Use the Office 365 Content Delivery Network (CDN) with SharePoint Online](https://docs.microsoft.com/en-us/office365/enterprise/use-office-365-cdn-with-spo#feedback)
* Content Source: [Enterprise/use-office-365-cdn-with-spo.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/use-office-365-cdn-with-spo.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@jkuter - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@jkuter - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
