### ISSUE TITLE
Content is wrong

### ISSUE THREAD

**Issue by christianpilz** [MicrosoftDocs/OfficeDocs-Enterprise#48]
The contect on that page is wrong. Using the latest AzureAD Modules it is required to even uninstall msoidcli to log in using mfa enabled accounts. Please correct...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@christianpilz I have tested the procedures in this article on a new virtual machine and was able to successfully do a multi-factor authentication with the latest Azure AD module and the MSOIDCLI module installed.  If you want to pursue a solution to this problem based on your configuration, please contact Microsoft Support at https://support.microsoft.com/contactus/.
