### ISSUE TITLE
URL : *.blob.core.windows.net

### ISSUE THREAD

**Issue by takawazoe** [MicrosoftDocs/OfficeDocs-Enterprise#481]
The URL *.blob.core.windows.net (67, 75) should be "Yes" for Express Route, since this is advertised. We investigated with Azure and SharePoint team based on the issue and we found this should be "Yes".

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@takawazoe - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by takawazoe** [comment]
Link is here.  @mypil 
https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges
Thank you.

**Comment by mypil** [comment]
@takawazoe - Thank you for submitting this feedback.

I will get this over to @JoeDavies-MSFT for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by JoeDavies-MSFT** [comment]
Started an internal email thread to discuss. Closing this issue. Thanks
