### ISSUE TITLE
Now that 2FA is going to be enforced for all Partner administrative Tenant accounts, how can we run this with 2FA enabled accounts?

### ISSUE THREAD

**Issue by Absoblogginlutely** [MicrosoftDocs/OfficeDocs-Enterprise#482]
With the upcoming 2FA enforcement, how do we run commands across all tenants with a 2FA enabled account?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f4d0d02-7d9f-b10c-9c86-8f82459dabe1
* Version Independent ID: 5fa035e4-554d-1b30-6609-96fbda5eecfd
* Content: [Connect to Exchange Online tenants with remote Windows PowerShell for Delegated Access Permissions (DAP) partners](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-exchange-online-tenants-with-remote-windows-powershell-for-delegated#feedback)
* Content Source: [Enterprise/powershell/connect-to-exchange-online-tenants-with-remote-windows-powershell-for-delegated.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-exchange-online-tenants-with-remote-windows-powershell-for-delegated.md)
* Service: **o365-administration**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Absoblogginlutely - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@Absoblogginlutely Thank you for your feedback. There is no single cmdlet or a method to connect to all Customer tenants at a time. You will have to connect to one at a time using the cmdlet

$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.outlook.com/powershell-liveid?DelegatedOrg=<customer tenant domain name> -Credential $UserCredential -Authentication Basic -AllowRedirection

Where the tenantdomainname being the tenant that you want to connect to .

Hope this helps!

Regards
Sri

**Comment by mypil** [comment]
@Absoblogginlutely - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by weyCC81** [comment]
There is no MFA Support, only Workaround: https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-mfasettings#trusted-ips
