### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Enterprise#483]
Need to add details on which licenses are required for admin accounts.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96784dc6-991a-fb80-cd0c-ae8217c32f45
* Version Independent ID: 0532ace1-bf55-916f-708d-5444c49d77b1
* Content: [Protect your Office 365 global administrator accounts](https://docs.microsoft.com/en-us/office365/enterprise/protect-your-global-administrator-accounts?redirectSourcePath=%252fen-us%252farticle%252fProtect-your-Office-365-global-administrator-accounts-6b4ded77-ac8d-42ed-8606-c014fd947560)
* Content Source: [Enterprise/protect-your-global-administrator-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/protect-your-global-administrator-accounts.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@danmyhre - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@danmyhre Thank you for your feedback. There are no licenses required for being a global administrator or a custom admin. That is the reason why you don't see any information about the licenses.

Hope this helps!

Regards
Sri

**Comment by danmyhre** [comment]
That is what I thought too, but support is saying otherwise.  For example, you must have an EXO license assigned to be able to set properties on an Office 365 group.

**Comment by JoeDavies-MSFT** [comment]
@danmyhre There is an issue of product licenses (such as "Office 365 E5"), which a global admin must have, and individual app or service licenses (such as "Exchange Online (Plan 2)"). You can see the level of hierarchy in the Microsoft 365 admin center when configuring licenses for a user. 

To address your question, the article above is about protecting user accounts that have the global admin role assigned. All of these accounts must have an Office 365 product licenses assigned to them. The requirements of individual app or service licenses are documented in the articles that are relevant to the app or service. Thanks.
