### ISSUE TITLE
Assign licenses to user accounts not possible without usage location

### ISSUE THREAD

**Issue by abdulrehmanbinaltaf** [MicrosoftDocs/OfficeDocs-Enterprise#487]
must need to specify the usage location before the assigning licence
Set-MsolUser -UserPrincipalName username@domain.com -UsageLocation "SA" ; Set-MsolUserLicense -UserPrincipalName username@domain.com -AddLicenses "ksauhsedu:STANDARDWOFFPACK_IW_STUDENT

Import-csv .\user.csv | FOREACH { Set-MsolUser -UserPrincipalName $_.EmailAddress -UsageLocation "SA" ; Set-MsolUserLicense -UserPrincipalName $_.Emailaddress -AddLicenses "ksauhsedu:STANDARDWOFFPACK_IW_STUDENT" }

or need to run separate commands to specify the location first then assigning the licence , as mentioned in the DOC
Set-MsolUser -UserPrincipalName username@domain.com  -UsageLocation "SA" 
Set-MsolUserLicense -UserPrincipalName username@domain.coma -AddLicenses "ksauhsedu:STANDARDWOFFPACK_IW_STUDENT"

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@abdulrehmanbinaltaf - May we know which Microsoft document link you used in reference to this issue?

Please share it with us so we can investigate further. 

Thank you.

**Comment by mypil** [comment]
@abdulrehmanbinaltaf - We would like to follow up. Can you please share which Microsoft document link you used in reference to this issue?

**Comment by JoeDavies-MSFT** [comment]
@abdulrehmanbinaltaf  I have added a prominent note about assigning the usage location to accounts as a prerequisite to assigning a license and added more instructions to this article: https://docs.microsoft.com/en-us/office365/enterprise/powershell/assign-licenses-to-user-accounts-with-office-365-powershell

**Comment by mypil** [comment]
@abdulrehmanbinaltaf - From our understanding, the issue you raised has been answered by JoeDavies-MSFT. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
