### ISSUE TITLE
Default depends when the tenent got created

### ISSUE THREAD

**Issue by TiloGit** [MicrosoftDocs/OfficeDocs-Enterprise#489]
Can you specify since when the default is on: under 
Availability of modern authentication for Office 365 services

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059ed9a7-ea75-0fa3-e246-4ad1f1b0c5bc
* Version Independent ID: d7598f96-3158-09ee-024a-6175599718cd
* Content: [How modern authentication works for Office 2013 and Office 2016 client apps](https://docs.microsoft.com/en-us/office365/enterprise/modern-auth-for-office-2013-and-2016?redirectSourcePath=%252farticle%252f776c0036-66fd-41cb-8928-5495c0f9168a)
* Content Source: [Enterprise/modern-auth-for-office-2013-and-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/modern-auth-for-office-2013-and-2016.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by TiloGit** [comment]
this wiki states:  https://social.technet.microsoft.com/wiki/contents/articles/34339.skype-for-business-online-enable-your-tenant-for-modern-authentication.aspx

_Note: As of **August 1, 2017**, for all newly created Office 365 tenants, use of modern authentication is now ON by default for Exchange Online and Skype for Business Online._

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@TiloGit  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@TiloGit - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
