### ISSUE TITLE
Fully Available

### ISSUE THREAD

**Issue by waynemarks** [MicrosoftDocs/OfficeDocs-Enterprise#49]
Hi, is this available under the 'education subscription'? it would be a massive benefit to our universities 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f3a2c9-0399-218d-cf9a-eb0f16fcbbb0
* Version Independent ID: da6ada6e-ce41-f772-74b8-144cf540d423
* Content: [Multi-Geo Capabilities in OneDrive and SharePoint Online in Office 365](https://docs.microsoft.com/en-us/office365/enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365)
* Content Source: [Enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by Sameer-MSFT** [comment]
Hi Wayne, thanks for reaching out. We're currently making Multi-Geo available to customers with >5K Office 365 seats in the commercial space. We want to make sure that these customers are on boarded efficiently and have the best service experience, therefore we’re starting with stipulations to manage and scale the service in a controlled way. However, I am super interested in learning universities' global data residency needs and how Multi-Geo can help. It would be great if you can share scenarios here. Thanks!

**Comment by waynemarks** [comment]
Hi, thanks for replying back and I would be very interested if we were able to contact direct on this off this thread I would be very grateful, we are currently at 10k mailboxes globally for our universities. If you were able provide me contact details to continue offline that would be great, thank you  :-)

**Comment by Sameer-MSFT** [comment]
Happy to listen to your requirements. Please add me on LinkedIn and send an inmail. https://www.linkedin.com/in/samsearth/
