### ISSUE TITLE
Naming guidance 

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-Enterprise#493]
Any tips on prefixes vs suffixes for admin accounts? All A for admins will show up first in people pickers when typing the admins name, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96784dc6-991a-fb80-cd0c-ae8217c32f45
* Version Independent ID: 0532ace1-bf55-916f-708d-5444c49d77b1
* Content: [Protect your Office 365 global administrator accounts](https://docs.microsoft.com/en-us/office365/enterprise/protect-your-global-administrator-accounts#feedback)
* Content Source: [Enterprise/protect-your-global-administrator-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/protect-your-global-administrator-accounts.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@eschrader - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@eschrader There are no Microsoft recommendations for naming admin accounts. Note that no matter what you name them, any authenticated user can use PowerShell commands to easily get a list.
