### ISSUE TITLE
Azure Information Protection

### ISSUE THREAD

**Issue by liest** [MicrosoftDocs/OfficeDocs-Enterprise#495]
In Office apps version 2016 it requires *.aadrm.com to not have any SSL inspection acording to this document: https://docs.microsoft.com/en-us/azure/information-protection/requirements
We had to whitelist *.aadrm.com and exempt it from SSL inspection and DPI for the Azure Information Protection to work.
I suggest that the site be moved to the category Optimize.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@liest  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Can you please share your insights on this issue?

Thank you.

**Comment by JoeDavies-MSFT** [comment]
@liest I will forward this suggestion to the product team that manages the information on this page to consider for future updates. Thanks for letting us know.
