### ISSUE TITLE
https://js.live.net missing from Office 365 Whitelist

### ISSUE THREAD

**Issue by MrDoNotBreak** [MicrosoftDocs/OfficeDocs-Enterprise#496]
In office online, if you open a powerpoint/word/excel and use the save-as functionality, it will reach out to https://js.live.net/v7.2/OneDrive.js to load and find onedrive locations to save to. 

Unfortunately this URL is not part of the whitelist documentation and so - in our enterprise it was blocked. Please ad js.live.net to the whitelist documentation. Attached is a screenshot. 
![2019-08-14_09-47-22](https://user-images.githubusercontent.com/9993922/63019098-bf958900-be9a-11e9-9c9f-153b3060a053.png)

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@MrDoNotBreak - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@MrDoNotBreak - We would like to follow up. Can you please share which Microsoft document link you used in reference to this issue?

**Comment by mypil** [comment]
@MrDoNotBreak - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve or make better, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft page or doc which is found at the bottom of the page. Thank you.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by MrDoNotBreak** [comment]
@mypil  - hello, sorry for not writing. I had not seen this. This refers to all the whitelist URL's listed here: https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges

**Comment by mypil** [comment]
**Reopening issue to get Doc owner's insights**

**Comment by mypil** [comment]
@MrDoNotBreak - Thank you for submitting this feedback and for sharing the doc link.

I will get this over to @JoeDavies-MSFT  for investigation and to get his insights. 

Thank you for reporting and making the docs better. Much appreciated.

**Comment by JoeDavies-MSFT** [comment]
@MrDoNotBreak I have forwarded this request to the product team who manages this list for their consideration. Thanks for letting us know.

**Comment by MrDoNotBreak** [comment]
Hello @JoeDavies-MSFT  - Is there any update or can we push this somehow? Our enterprise pulls the whitelist from the REST endpoint provided by microsoft - but currently, we cannot rely on it completely as this url is still not on the whitelist. I also created a premier ticket months ago but no luck there either.
