### ISSUE TITLE
Multiple AD Forests with same routable UPN Suffix

### ISSUE THREAD

**Issue by AlekseySokol** [MicrosoftDocs/OfficeDocs-Enterprise#497]
Hello
We have Forest A and Forest B, between them two way trust. also we use signle ADFS server for both servers
In Forest we have added routable UPN suffix domainxyz.com. My question is it possible to add same domainxyz.com routable UPN suffix to Forest B.
I think not because an authentication flow but where I could find some deep explanation of that.
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79589db3-4bf5-e940-0410-75d5f0ff97b8
* Version Independent ID: e7980b96-bab3-981e-2da8-6e1bdde9ba31
* Content: [Prepare a non-routable domain for directory synchronization](https://docs.microsoft.com/en-us/office365/enterprise/prepare-a-non-routable-domain-for-directory-synchronization?redirectSourcePath=%252fen-us%252farticle%252fHow-to-prepare-a-non-routable-domain-such-as-local-domain-for-directory-synchronization-e7968303-c234-46c4-b8b0-b5c93c6d57a7)
* Content Source: [Enterprise/prepare-a-non-routable-domain-for-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/prepare-a-non-routable-domain-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@AlekseySokol - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@AlekseySokol - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products: **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
