### ISSUE TITLE
Web-based option via Office 365 Admin Portal

### ISSUE THREAD

**Issue by c016smith** [MicrosoftDocs/OfficeDocs-Enterprise#50]
Will Microsoft be able to provide this All-in-One console from a web-based portal, similar to the Azure portal with Powershell access? That would be tremendously helpful for all admin users from any machine, without having to install these modules and keep them up-to-date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c551eb1-7ac5-cb02-cd1b-d67ca3886d85
* Version Independent ID: fb690e2e-420e-f697-60f2-39520283d385
* Content: [Connect to all Office 365 services in a single Windows PowerShell window](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window)
* Content Source: [Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@c016smith The Azure Cloud Shell is currently only for Azure admin tasks and does not yet support inclusion of the Office 365 PowerShell modules. I cannot say when this will be supported. Thanks
