### ISSUE TITLE
You can build in a check to see if AzureAD is connected or not

### ISSUE THREAD

**Issue by Tuumke** [MicrosoftDocs/OfficeDocs-Enterprise#500]
if($azureConnection.Account -eq $null){
    $azureConnection = Connect-AzureAD
}else{
	Write-Warning "We already have a session for AzureAD"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c551eb1-7ac5-cb02-cd1b-d67ca3886d85
* Version Independent ID: fb690e2e-420e-f697-60f2-39520283d385
* Content: [Connect to all Office 365 services in a single Windows PowerShell window](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window#feedback)
* Content Source: [Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by Tuumke** [comment]
Update:
Doesnt really seem to work. Testing this now:
```
if([Microsoft.Open.Azure.AD.CommonLibrary.AzureSession]::AccessTokens.Count -gt 0){
    Write-Warning "We already have a session for AzureAD"
}else{
	Connect-AzureAD
}
```

**Comment by mypil** [comment]
@Tuumke - Thank you for submitting feedback.

Can you please share what specific issue you have with this doc?  We would really appreciate if you are able to help by providing more details as to what should be edited and/or included.

**Comment by Tuumke** [comment]
Well not with this doc per-se, but more with the way the connect-azuread is working. This doc shows a script to connect to mosft of , if not all the cloud services. But doesnt give you a way to check if you already have a connect-azuread session up and running. So its just something to extend the scripts on this page.

**Comment by mypil** [comment]
@Tuumke - Thanks for sharing this additional feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@Tuumke I will consider this in a future update to this article. Thanks for letting us know.
