### ISSUE TITLE
URL ow2.res.office365.com is not listed in doc, which block users from accessing OWA

### ISSUE THREAD

**Issue by joiecen** [MicrosoftDocs/OfficeDocs-Enterprise#502]
Users are following Office 365 URLs and IP address ranges to whitelist urls and ip to access Exchange online mailbox. But recently some users are blocked to access OWA due to that URL ow2.res.office365.com is blocked by firewall. Please confirm and add URL ow2.res.office365.com into the list, then users can adjust their whitelist accordingly.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@joiecen - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by joiecen** [comment]
@mypil  https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges this is the link I reported issue to. This link is very important to a lot of customers to configure whitelist or exceptions on their firewall and proxy. Missing of this url has resulted some customer issues. Please help to confirm and adjust asap. Thanks a lot.

**Comment by mypil** [comment]
@joiecen - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-product)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by JoeDavies-MSFT** [comment]
@joiecen I have forwarded this request to the product team owners that maintain these endpoints for their consideration in a future update. Thanks for letting us know.
