### ISSUE TITLE
add onedrive.js link to whitelist

### ISSUE THREAD

**Issue by andi744** [MicrosoftDocs/OfficeDocs-Enterprise#503]
could you please add this url to the whitelisted endpoints?
https://js.live.net/v7.2/OneDrive.js
its not added here and its blocking the user in the Web App "save a copy" to OneDrive for business.

thanks
Andi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@andi744 - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Can you please share your insights on this issue?

Thank you.

**Comment by JoeDavies-MSFT** [comment]
@andi744 I have forwarded this request to the product team owners who maintain these lists for consideration of a future update. Thanks for letting us know.

**Comment by andi744** [comment]
@JoeDavies-MSFT  - thanks for your help. yes, hopefully the doc can be updated
