### ISSUE TITLE
Typo's

### ISSUE THREAD

**Issue by Playajay** [MicrosoftDocs/OfficeDocs-Enterprise#504]
In item number 2. under heading "Turn on Hybrid Modern Authentication for Skype for Business on-premises", it says: "Run this command, on-premises, to get a list of SFB web service URLs."
I think you mean "Run this command ONLINE" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a887219-cf1d-af7e-d36a-4f541ee44a5e
* Version Independent ID: 3babb1cd-31b1-b53b-4a94-ba92d89f65a5
* Content: [How to configure Skype for Business on-premises to use Hybrid Modern Authentication](https://docs.microsoft.com/en-us/office365/enterprise/configure-skype-for-business-for-hybrid-modern-authentication#feedback)
* Content Source: [Enterprise/configure-skype-for-business-for-hybrid-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/configure-skype-for-business-for-hybrid-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Playajay - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@Playajay It's not a typo. You run this cmdlet on-premises after you import the Azure Active Directory Module in Windows Powershell (for example):

![image](https://user-images.githubusercontent.com/41186174/64175133-5b476300-ce63-11e9-9270-a08b138401af.png)

**Comment by mypil** [comment]
@Playajay - From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
