### ISSUE TITLE
Another Typo

### ISSUE THREAD

**Issue by Playajay** [MicrosoftDocs/OfficeDocs-Enterprise#505]
Under section "Turn on Hybrid Modern Authentication for Skype for Business on-premises" -&gt; Item 4. It says :"Verify your new records were added..... https://lyncweb01.contoso.com"
But your example uses  https://lyncwebint01.contoso.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a887219-cf1d-af7e-d36a-4f541ee44a5e
* Version Independent ID: 3babb1cd-31b1-b53b-4a94-ba92d89f65a5
* Content: [How to configure Skype for Business on-premises to use Hybrid Modern Authentication](https://docs.microsoft.com/en-us/office365/enterprise/configure-skype-for-business-for-hybrid-modern-authentication#feedback)
* Content Source: [Enterprise/configure-skype-for-business-for-hybrid-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/configure-skype-for-business-for-hybrid-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Playajay - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Playajay - From our understanding, the issue has been resolved based on the merged commit [[72003d0](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/72003d062eedc9992d3f5b3cb440d2723e09a711)] but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
