### ISSUE TITLE
Little typo in TOC entry

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/OfficeDocs-Enterprise#506]
Greetings,
The TOC entry for this page says "dynchronization" instead of "synchronization".
"Deploy a directory dynchronization server in Azure IaaS"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e916a1b-2bec-24af-6c46-c50780f97b5d
* Version Independent ID: 279c76f6-4653-3ea9-8ad8-e827680bbc4e
* Content: [Deploy Office 365 Directory Synchronization in Microsoft Azure](https://docs.microsoft.com/en-us/office365/enterprise/deploy-office-365-directory-synchronization-dirsync-in-microsoft-azure#feedback)
* Content Source: [Enterprise/deploy-office-365-directory-synchronization-dirsync-in-microsoft-azure.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/deploy-office-365-directory-synchronization-dirsync-in-microsoft-azure.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@a-zaf - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@a-zaf This is been corrected and published. Thanks so much for letting us know.
