### ISSUE TITLE
PDL missing for new Geos.

### ISSUE THREAD

**Issue by cimares** [MicrosoftDocs/OfficeDocs-Enterprise#513]
The PDL codes are missing for the United Arab Emirates and South Africa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdf84db6-c7e8-9a68-0b60-eb0af2de593a
* Version Independent ID: bc0ed520-fccd-c390-b706-71ddfeab4085
* Content: [Office 365 Multi-Geo](https://docs.microsoft.com/en-us/office365/enterprise/office-365-multi-geo#feedback)
* Content Source: [Enterprise/office-365-multi-geo.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-multi-geo.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@cimares - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@cimares The article was updated and now contains the PDLs for South Africa and United Arab Emirates

**Comment by mypil** [comment]
@cimares - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
