### ISSUE TITLE
PDL missing for new GEOs

### ISSUE THREAD

**Issue by cimares** [MicrosoftDocs/OfficeDocs-Enterprise#514]
PDL not given for South Africa or United Arab Emirates. Also missing the eDiscovery data location

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d41ff16-b5cc-d2d2-6bb9-2134a0fafcd9
* Version Independent ID: ebb5ff30-995f-92ff-f536-4386a7817b5f
* Content: [Office 365 Multi-Geo tenant configuration](https://docs.microsoft.com/en-us/office365/enterprise/multi-geo-tenant-configuration)
* Content Source: [Enterprise/multi-geo-tenant-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/multi-geo-tenant-configuration.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@cimares - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@cimares The article was updated and now contains the PDLs for South Africa and United Arab Emirates. Regarding "eDiscovery Data Location", that will be also added asap, which was noted in the table.

**Comment by mypil** [comment]
@cimares - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
