### ISSUE TITLE
Video playback speed

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/OfficeDocs-Enterprise#515]
Hi. Request a way to adjust the playback speed of the video. This does not appear possible today. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0157c20-f401-82c5-eede-67c6505a688d
* Version Independent ID: 02e0575c-193a-3610-5496-e9076d51df3f
* Content: [Office 365 identity models and Azure Active Directory](https://docs.microsoft.com/en-us/office365/enterprise/about-office-365-identity#)
* Content Source: [Enterprise/about-office-365-identity.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/about-office-365-identity.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@adrianwells - Thank you for submitting feedback. 

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Is there way to adjust the playback speed of the video within this doc? Please share your inputs.

Thank you.

**Comment by JoeDavies-MSFT** [comment]
@adrianwells Sorry. There is no ability to adjust the playback speed for this video. Thanks for your question.

**Comment by adrianwells** [comment]
@mypil  and @JoeDavies-MSFT Thank you for the reply. Have seen this feature in another Microsoft docs with embedded video hence the inquiry.
