### ISSUE TITLE
I'd like to know what problem happens if I have a tenant  configured with custom domains

### ISSUE THREAD

**Issue by AiHirano** [MicrosoftDocs/OfficeDocs-Enterprise#517]
I realized  this restriction note recently added that Office 365 CDN does not currently support tenants configured with custom or "vanity" domains . I  already configured Office 365 CDNs on my tenant configured with custom domain about two years ago, it seems any problem doesn't happen. I'd like to know what problem happens if I have a tenant  configured with custom domains. And I'd like to know what is the best way if we have custom domains.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97626653-f653-d954-7a39-e5beac635e18
* Version Independent ID: 86f7d0b5-3a63-7511-0fc6-e3d98bea4b74
* Content: [Use the Office 365 Content Delivery Network (CDN) with SharePoint Online](https://docs.microsoft.com/en-us/office365/enterprise/use-office-365-cdn-with-spo#feedback)
* Content Source: [Enterprise/use-office-365-cdn-with-spo.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/use-office-365-cdn-with-spo.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@AiHirano - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by AiHirano** [comment]
@mypil Thank you for your reply.  I already opened a service ticket, but unfortunately  I couldn't get reasonable reply. When I make a better proposal, I will post it again.
