### ISSUE TITLE
Extra space after "-" (Set-UnifiedGroup -Identity "Internal senders only" - RequireSenderAuthenticationEnabled $true)

### ISSUE THREAD

**Issue by TaddEDawson** [MicrosoftDocs/OfficeDocs-Enterprise#520]
Extra space after "-" (Set-UnifiedGroup -Identity "Internal senders only" - RequireSenderAuthenticationEnabled $true) 

Users running the command via Copy Paste will get exception

Should be
Set-UnifiedGroup -Identity "Internal senders only" -RequireSenderAuthenticationEnabled $true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b960f93b-6dc5-36e4-20f5-a7ee68382468
* Version Independent ID: c0bee411-b022-bf2c-03c7-0510e9252fc6
* Content: [Manage Office 365 Groups with PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-office-365-groups-with-powershell#feedback)
* Content Source: [Enterprise/powershell/manage-office-365-groups-with-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/manage-office-365-groups-with-powershell.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@TaddEDawson - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@TaddEDawson  Thank you for your feedback. We have corrected the CMdlet via PR https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/521

Thanks
Sri

**Comment by mypil** [comment]
@TaddEDawson - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
