### ISSUE TITLE
Incorrect Information on PDL and SharePoint Sites

### ISSUE THREAD

**Issue by lindendaniels2** [MicrosoftDocs/OfficeDocs-Enterprise#523]
The article states: When a user creates a SharePoint group-connected site, their PDL is used to determine the geo location where the site and its associated Group mailbox is created.
This is not the case if SharePoint multi geo is not configured. We have tested this for user PDL = Japan, but SharePoint Multi Geo not configured and the Sites are created in APAC. The article should state some like: When a user creates a SharePoint group-connected site *and have configured a SharePoint Multi Geo satellite location*, their PDL is used to determine the geo location where the site and its associated Group mailbox is created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f3a2c9-0399-218d-cf9a-eb0f16fcbbb0
* Version Independent ID: da6ada6e-ce41-f772-74b8-144cf540d423
* Content: [Multi-Geo Capabilities in OneDrive and SharePoint Online](https://docs.microsoft.com/en-us/office365/enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365#feedback)
* Content Source: [Enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@lindendaniels2 - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MikePlumleyMSFT** [comment]
Updated the sentence to clarify.

**Comment by mypil** [comment]
@lindendaniels2 - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
