### ISSUE TITLE
Wrong Virtual Network Name

### ISSUE THREAD

**Issue by huzzeytech** [MicrosoftDocs/OfficeDocs-Enterprise#525]
If you use the ARM template from Phase 1 the name of the Virtual Network would be: TlgBaseConfig-01-VNET not TestLab as line 7 suggests. Therefore the script fails. ARM Template (https://github.com/maxskunkworks/TLG/tree/master/tlg-base-config_3-vm) is linked on this page: https://docs.microsoft.com/en-us/office365/enterprise/base-configuration-dev-test-environment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a0b3f11-8f84-f015-82db-5f0d049e1a76
* Version Independent ID: 949d1ec8-4335-4827-83d7-3f67bb9a26fa
* Content: [Federated identity for your Office 365 dev/test environment](https://docs.microsoft.com/en-us/office365/enterprise/federated-identity-for-your-office-365-dev-test-environment#phase-2-create-the-ad-fs-server)
* Content Source: [Enterprise/federated-identity-for-your-office-365-dev-test-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/federated-identity-for-your-office-365-dev-test-environment.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@huzzeytech I added some lines that create a new variable named $vnetName and assume a template build-out, with instructions to change the variable value if they did the PowerShell method:

$vnetName="TlgBaseConfig-01-VNET"
# NOTE: If you built your simulated intranet with Azure PowerShell, comment the previous line with a "#" and remove the "#" from the next line.
#$vnetName="TestLab"

Sorry for the inconvenience. Thanks so much for letting us know.
