### ISSUE TITLE
Possible error in table

### ISSUE THREAD

**Issue by sagy** [MicrosoftDocs/OfficeDocs-Enterprise#526]
There might be an error in the tables above. Under the column "Registry key present?". For the first row, shouldn't it be "No, or EnableADAL = 0" instead of "No, or EnableADAL = 1"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059ed9a7-ea75-0fa3-e246-4ad1f1b0c5bc
* Version Independent ID: d7598f96-3158-09ee-024a-6175599718cd
* Content: [How modern authentication works for Office 2013 and Office 2016 client apps](https://docs.microsoft.com/en-us/office365/enterprise/modern-auth-for-office-2013-and-2016?redirectSourcePath=%252farticle%252fe4c45989-4b1a-462e-a81b-2a13191cf517)
* Content Source: [Enterprise/modern-auth-for-office-2013-and-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/modern-auth-for-office-2013-and-2016.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@sagy  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @sagy ,
for me it looks like the table is correct.
as modern authentication is enabled by default, in case registry case is not presented (NO), it would be the equivalent of EnableADAL = 1, so it must be "No, or EnableADAL = 1"

Thank you

**Comment by mypil** [comment]
@sagy - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
