### ISSUE TITLE
Typo (ja-jp) "Set-unifiedgroup"→"Get-UnifiedGroup"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-Enterprise#527]
ja-jp:"https://docs.microsoft.com/ja-jp/office365/enterprise/powershell/manage-office-365-groups-with-powershell"
![manage-office-365-groups-with-powershell_j](https://user-images.githubusercontent.com/40815708/65317771-67f3e700-dbd7-11e9-91b1-6eb387789460.png)

en-us:"https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-office-365-groups-with-powershell"
![manage-office-365-groups-with-powershell_e](https://user-images.githubusercontent.com/40815708/65317780-6aeed780-dbd7-11e9-8e04-de393dde5a29.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b960f93b-6dc5-36e4-20f5-a7ee68382468
* Version Independent ID: c0bee411-b022-bf2c-03c7-0510e9252fc6
* Content: [Manage Office 365 Groups with PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-office-365-groups-with-powershell)
* Content Source: [Enterprise/powershell/manage-office-365-groups-with-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/manage-office-365-groups-with-powershell.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@hyoshioka0128  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@OfficeGlobal - Can you please assist with this Translation (Localization) issue?

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 , @mypil article has been HumanTranslated and published live

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - Thank you.
Closed #527
