### ISSUE TITLE
Azure AD "one-time registration"? Not!

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/OfficeDocs-Enterprise#529]
On this page the link titled "Register your free Azure Active Directory subscription" has comment "you have to complete a one-time registration process", however in the linked page https://go.microsoft.com/fwlink/?LinkId=617127 there is no mention of any one-time registration process. Either the link text and comment are wrong or they link to the wrong page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf4bfe19-070d-9ceb-d88c-e60d72f362c1
* Version Independent ID: 69af3732-0341-a054-6f4b-43407640a94b
* Content: [Integrated Apps and Azure AD for Office 365 administrators](https://docs.microsoft.com/en-us/office365/enterprise/integrated-apps-and-azure-ads)
* Content Source: [Enterprise/integrated-apps-and-azure-ads.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/integrated-apps-and-azure-ads.md)
* Service: **o365-administration**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@softwarecraft - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @softwarecraft ,
looks like the original link was [Register your free Azure Active Directory subscription](https://docs.microsoft.com/windows/client-management/mdm/register-your-free-azure-active-directory-subscription).
However, this info is outdated, there is no need to perform any registration for Office 365 subscribers now.
I will create the PR to change this article

**Comment by mypil** [comment]
@softwarecraft - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
