### ISSUE TITLE
"fwlink" type links to deprecated pages

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/OfficeDocs-Enterprise#530]
These redirector links now all direct to the same legacy page for O365 REST API not to the original specific content. Please update the links to the precise content pages.
* https://go.microsoft.com/fwlink/?LinkId=617137
* https://go.microsoft.com/fwlink/?LinkId=617138
* https://go.microsoft.com/fwlink/?LinkId=617140

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf4bfe19-070d-9ceb-d88c-e60d72f362c1
* Version Independent ID: 69af3732-0341-a054-6f4b-43407640a94b
* Content: [Integrated Apps and Azure AD for Office 365 administrators](https://docs.microsoft.com/en-us/office365/enterprise/integrated-apps-and-azure-ads)
* Content Source: [Enterprise/integrated-apps-and-azure-ads.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/integrated-apps-and-azure-ads.md)
* Service: **o365-administration**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@softwarecraft  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@softwarecraft - From our understanding, the issue has been resolved based on the merged commit [[0be6c3c](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/0be6c3c353b4266f2e7f31c454446517d8170e3d)]. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
