### ISSUE TITLE
please include dl.google.com and *.gvt1.com to Teams section

### ISSUE THREAD

**Issue by ikukoyoneda** [MicrosoftDocs/OfficeDocs-Enterprise#531]
Teams client is accessing to dl.google.com and *.gvt1.com to check if there are any updates on Chromium, but these are not included in the Teams section. Could you add them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@ikukoyoneda - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Can you please share your insights on this issue?

Thank you.

**Comment by JoeDavies-MSFT** [comment]
@ikukoyoneda I have forwarded this request to the product team who manages the Teams list of endpoints for their consideration. Thanks for letting us know.
