### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Koning53** [MicrosoftDocs/OfficeDocs-Enterprise#532]
The link to 'Performance in the modern SharePoint experience' seems to be broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70479983-f316-d8f5-6af4-27a28986d868
* Version Independent ID: 901cdd4d-0d15-a25f-623e-b47d2b5fea1a
* Content: [Optimize page calls in SharePoint Online modern and classic publishing site pages](https://docs.microsoft.com/en-us/Office365/Enterprise/modern-page-call-optimization#feedback)
* Content Source: [Enterprise/modern-page-call-optimization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/modern-page-call-optimization.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@Koning53  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Koning53 - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
