### ISSUE TITLE
SharePoint 2013 is in extended support as well

### ISSUE THREAD

**Issue by rainerasbach** [MicrosoftDocs/OfficeDocs-Enterprise#535]
This article mentions SharePoint 2013 as a target platform to migrate to. However SharePoint 2013 is in extended Support as well.  This does not improve the situation for the customer.

This article says: support lifecycle (the time during which Microsoft provides new features, bug fixes, security fixes, and so on)
This is not correct for most customer. When the product is in extended support phase, no new features are implemented and bug fixes are only developed for security problems unless a customer has a special Unified Support contract.
Please refer to https://support.microsoft.com/en-us/help/14085 
This text has to be changed because it could raise a false expectation from customers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 675ee242-0ad6-d256-fef7-8d7a448ebc77
* Version Independent ID: 29834faf-913f-9eaa-d627-b1228cb154ad
* Content: [Upgrading from SharePoint 2010](https://docs.microsoft.com/en-us/office365/enterprise/upgrade-from-sharepoint-2010#feedback)
* Content Source: [Enterprise/upgrade-from-sharepoint-2010.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/upgrade-from-sharepoint-2010.md)
* Product: **office-online-server**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@rainerasbach - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@rainerasbach - As per my understanding, SharePoint 2013 has extended support till 4/11/2023 which can give users another four years if they are using SharePoint 2013. If users are using Sharepoint 2010 then Microsoft has recommended that its good to move to SharePoint 2013 as its extended support will be available up to 2023 but it is also recommended that the good option is to move to SharePoint 2016 or SharePoint online which can surely be adopted. Additionally, I have added a link for users to understand the Product Life Cycle Policy.

Imran

**Comment by rainerasbach** [comment]
Yes, the extended support for SharePoint 2013 is until 4/11/2013, but extended support is limited compared to full support.
Microsoft does not make any non-security related changes to the product.

The latest on-premises version of SharePoint is SharePoint 2019. So this should be the version to migrate to at this point in time.

  Rainer Asbach

**Comment by mypil** [comment]
@rainerasbach  - From our understanding, the issue has been resolved based on the merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/425d923228b9d7aef1e7e2817580d46c0af964c8 but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
