### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by carry2web** [MicrosoftDocs/OfficeDocs-Enterprise#536]
link text: " Data Encryption Technologies in Office 365" points to https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-encryption-in-the-microsoft-cloud-overview.md is broken. Shoulp probably be: https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 6efbbb49-fe33-beb3-2b9c-ca0b83e2dbdf
* Version Independent ID: 4f01b2a8-8a68-e310-20e9-e8da3ed499b6
* Content: [Tenant Isolation in Office 365](https://docs.microsoft.com/nl-nl/office365/Enterprise/office-365-tenant-isolation-overview)
* Content Source: [Enterprise/office-365-tenant-isolation-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-tenant-isolation-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@carry2web - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@carry2web - From our understanding, the issue has been resolved based on the merged commit [[8c4fc1a](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/8c4fc1a3eaa4146f1d1a6733508261ed06959580)] but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
