### ISSUE TITLE
ID71 - No IPv4?

### ISSUE THREAD

**Issue by KevFM** [MicrosoftDocs/OfficeDocs-Enterprise#537]
Is ID71 correct showing that this FQDN is IPv6 only, there are no IPv4 addresses? On our system I'm showing matches to this wildcard that are IPv4, e.g. ow1.res.office365.com resolving to 88.221.0.214.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@KevFM - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Can you please share your insights on this issue? 

Thank you.

**Comment by JoeDavies-MSFT** [comment]
@KevFM I have forwarded this request to the product team that manages this set of endpoints for their consideration in a future update. Thanks for letting us know.
