### ISSUE TITLE
Documentation Updates Needed

### ISSUE THREAD

**Issue by BrettNoake** [MicrosoftDocs/OfficeDocs-Enterprise#538]
We are testing the AIP plugin and have found the IP ranges specified for the plugin require optimization in order to prevent the certificate pinning from breaking. The endpoint listed (104.47.0.0/17 ) for this plugin falls within the "allow" category which does not require optimization but that will not work. We would like to see this updated in the documentation as our security team is hesitant to make configurations that are not in-line with what Microsoft has published. I opened an Azure Support ticket regarding this and they redirected me here. I have documentation of our testing but will not put that in a public forum. You can access my support ticket for that information.

**Comment by mypil** [comment]
@BrettNoake - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by BrettNoake** [comment]
Do you have access to view my azure support ticket that contained all the documentation?


Brett Noake
SharePoint Analyst
Chevron Phillips Chemical Company
832-458-3560

**Comment by mypil** [comment]
@BrettNoake - No, we don't have access to it.

**Comment by BrettNoake** [comment]
Ok, I can send you what I have. Is this going to be posted on GitHub? I don’t want to send anything that is company specific or sensitive if so. Sorry for all the questions, this is a new process for me as I have historically dealt with premier support only.

Brett Noake
SharePoint Analyst
Chevron Phillips Chemical Company
832-458-3560

**Comment by mypil** [comment]
@BrettNoake - Yes, what you share here will be in GitHub. If you need to send the feedback privately to the doc owner, then, we need to know what the MS document link is. Can you just help to provide us the document link for us to find out who the doc owner is? 

Thank you.

**Comment by BrettNoake** [comment]
https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges

Brett Noake
SharePoint Analyst
Chevron Phillips Chemical Company
832-458-3560

**Comment by mypil** [comment]
@BrettNoake - Thank you for providing the link. Let me loop in the doc owner so you can share your feedback with him.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Can you possibly assist with this issue? 

Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
Content Source: [/Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)

Thank you.

cc: @kenwith

**Comment by JoeDavies-MSFT** [comment]
@BrettNoake I have forwarded your request to the Exchange Online product team for their investigation and consideration in a future update. Thanks for letting us know.
