### ISSUE TITLE
WAP Federation Service Name - Internal or Public DNS

### ISSUE THREAD

**Issue by huzzeytech** [MicrosoftDocs/OfficeDocs-Enterprise#539]
When configuring the proxy, should I use the public DNS name? Isn't this just resolving back to the Proxy? I can resolve the public DNS name from proxy, certificates are in their proper stores, and have walked through the steps again, yet the config wizard leaves me with this error:
An error occurred when attempting to establish a trust relationship with the federation service. Error: Unable to connect to the remote server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a0b3f11-8f84-f015-82db-5f0d049e1a76
* Version Independent ID: 949d1ec8-4335-4827-83d7-3f67bb9a26fa
* Content: [Federated identity for your Office 365 dev/test environment](https://docs.microsoft.com/en-us/office365/enterprise/federated-identity-for-your-office-365-dev-test-environment#phase-3-create-the-web-proxy-server)
* Content Source: [Enterprise/federated-identity-for-your-office-365-dev-test-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/federated-identity-for-your-office-365-dev-test-environment.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by huzzeytech** [comment]
The example PowerShell is misleading for this step:
"$testZone="<the FQDN of your testlab domain from phase 1, example: testlab.contoso.com>"
should be:
"$testZone="testlab.<your public DNS domain>, example: testlab.contoso.com>"

The way I read the example was to use the internal FQDN of the domain from step 1:
fs.corp.contoso.com

**Comment by mypil** [comment]
@huzzeytech - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@huzzeytech You are correct. The PowerShell commands are using the external federation service FQDN, not the internal FQDN. I have corrected the commands to reflect this. Sorry for the inconvenience. Thanks so much for letting us know.
