### ISSUE TITLE
Application error when acess /, Error=ID4014: A Security TokenHandler is not registered.

### ISSUE THREAD

**Issue by moojjoo** [MicrosoftDocs/OfficeDocs-Enterprise#54]
3 Questions ---------------------------!!!!!!!!!!!!!

1. Is there any setup on ADFS required?

2.  If the answer above is "NO", I am getting - in the ULS Logs

`Application error when access /, Error=ID4014: A SecurityTokenHandler is not registered to read security token ('Assertion', 'urn:oasis:names:tc:SAML:2.0:assertion').   at Microsoft.IdentityModel.Web.TokenReceiver.ReadToken(String tokenXml, XmlDictionaryReaderQuotas readerQuotas)     at Microsoft.IdentityModel.Web.WSFederationAuthenticationModule.SignInWithResponseMessage(HttpRequest request)     at Microsoft.IdentityModel.Web.WSFederationAuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs args)     at Microsoft.SharePoint.IdentityModel.SPFederationAuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs eventArgs)     at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()     at System.Web.HttpApplication.Execute... 1d74659e-02a9-601e-d2d0-f7f2e174f79f`

I have followed the following doc from Microsoft to configure - https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication

I have run the PowerShell scripts as written, but "NO LUCK" as you can see from the logs.

3. How do you configure Center Admin in SharePoint to only need to authenticate the Trust aka adding a > Center Admin > Manager Web applications > Authentication Providers > Custom Sign In Page (How do you configure the trusted sign in page, if you add like it explains in the article /_trust/ will it create a new page?  Right now I am only using the Default Sign In Page which gives you a choice of

- Windows Authentication
- AzureAD

Thank you ahead of time.

**Comment by kaevans** [comment]
@moojjoo - ADFS is not used in this configuration, SharePoint receives a SAML 1.1 token directly from AzureAD.

The error indicates "A SecurityTokenHandler is not registered to read security token ('Assertion', 'urn:oasis:names:tc:SAML:2.0:assertion')", meaning it is likely that not all steps from the article were completed. SharePoint 2013 and 2016 require SAML 1.1, your configuration appears to be using SAML 2.0, meaning the steps for removing the existing SAML 2.0 token issuance policy and adding a SAML 1.1 token issuance policy were either missed or did not complete successfully. 

@denisebmsft please close.

**Comment by BilawalAsghar** [comment]
how i remove SAML 2.0 and add SAML 1.1 , please help.

**Comment by kaevans** [comment]
@BilawalAsghar follow the steps in the article in the order they are written. The PowerShell script shows how to remove the SAML 2.0 issuance policy and add a SAML 1.1 issuance policy.

@denisebmsft Please close.
