### ISSUE TITLE
Mobile Deletions

### ISSUE THREAD

**Issue by noahmauer** [MicrosoftDocs/OfficeDocs-Enterprise#542]
If a document is loaded on a mobile device (tested on Android), and edited using the App (Word, PowerPoint, etc), if the document is deleted from the "Recents" tab, it is unrecoverable via the Recycle Bin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cefde46c-31d4-54ad-8c5c-44f23d8509b7
* Version Independent ID: ae9d8dc1-dafc-7bb6-b9de-c5ddc049dadf
* Content: [Office 365 SharePoint Online Data Deletion](https://docs.microsoft.com/en-us/office365/Enterprise/office-365-sharepoint-online-data-deletion#feedback)
* Content Source: [Enterprise/office-365-sharepoint-online-data-deletion.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-sharepoint-online-data-deletion.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@noahmauer  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@noahmauer - Can you please confirm that data the file you have modified was uploaded to SharePoint online and when you have deleted it from the recent of the mobile apps it gets deleted from SharePoint online as well?

If this is the case then you need to open up a support ticket for its investigation from the support staff.

Regards,
Imran.

@mypil , Please let the user know how a support ticket can be opened for this case.

**Comment by mypil** [comment]
@noahmauer - You can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this issue can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
