### ISSUE TITLE
Outlook connecting to IPs not included in worldwide endpoint list

### ISSUE THREAD

**Issue by layer9de** [MicrosoftDocs/OfficeDocs-Enterprise#543]
Hi all,

we are experiencing some issues with Outlook clients connecting to IPv6 and IPv4 endpoints that are not included in the worldwide endpoint list for Exchange Online. This causes Outlook to hang for 30-60 seconds on "Loading profile" during startup and causes freezes and usabiliy issues while working especially if Outlook has mailboxes that are not configured with cached mode. If we allow access to the IP addresses that Outlook is connecting to the issues go completely away .

We for example see connections to the following IPv6 addresses that are not included in the IP range list from Microsoft:

`2603:1026:100:16::2`
`2603:1026:101:14::2`

This can be seen while running `netstat -anbo` in Windows 10 with Outlook running:

<img width="454" alt="outlook-ipv6-01" src="https://user-images.githubusercontent.com/49995420/65768655-d84bbc80-e131-11e9-970a-69b50d3da5f7.png">

<img width="454" alt="outlook-ipv6-02" src="https://user-images.githubusercontent.com/49995420/65768640-ce29be00-e131-11e9-8bf2-d5f1fd59f3be.png">

There is no listed IPv6 subnet that includes the prefix 2603:1026:**1**00:: in the official worldwide endpoint list. Resolving the URL outlook.office365.com from the Optimize category for Exchange Online actually sometimes resolves to those addresses which explains the connections in the first place:

<img width="282" alt="outlook-ipv6-03" src="https://user-images.githubusercontent.com/49995420/65768146-6161f400-e130-11e9-94b9-de3d18aef738.png">

For IPv4 we see connections to the following addresses which aren't included in any of the listed subnets either:

`40.90.23.153`
`40.90.23.154`
`40.90.137.127`

We are currently using Outlook versions 1902 11328.20420 (SAC) and 1908 11929.20300 (SACT) and observing this behaviour in both versions.

Since the Office 365 URLs and IP address ranges list seems not to be a reliable source we have now allowed https traffic to all destinations for our clients as otherwise no stable connection to Outlook (and possibly other services from Office 365) is possible.

If the URL and IP address list is not kept up to date and does not include all the endpoints the applications are connecting to all measures for seperating traffic are pretty much useless as we are risking timeouts and usability issues (which are actually happen).

Best Regards
Michael

**Comment by JoeDavies-MSFT** [comment]
@layer9de  I have forwarded these address ranges to the product team for their consideration in a future update. Thanks for letting us know.
