### ISSUE TITLE
Step 1 fails; Install-Module doesn't exist on Server 2012R2

### ISSUE THREAD

**Issue by jgwinner** [MicrosoftDocs/OfficeDocs-Enterprise#545]
The instructions for Step 1 fail on a brand new install of Server 2012R2; I applied all Windows patches. 

Installation media was from MSDN, "en_windows_server_2012_r2_with_update_x64_dvd_6052708.iso"

I got this:

Install-Module : The term 'Install-Module' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.

I tried the troubleshooting steps from an elevated PowerShell script and got the following error:

PS C:\Windows\system32> (Get-Item C:\Windows\System32\WindowsPowerShell\v1.0\Modules\MSOnline\Microsoft.Online.Administr
ation.Automation.PSModule.dll).VersionInfo.FileVersion
Get-Item : Cannot find path
'C:\Windows\System32\WindowsPowerShell\v1.0\Modules\MSOnline\Microsoft.Online.Administration.Automation.PSModule.dll'
because it does not exist.

I checked the version of powershell (again, fresh install of 2012R2 from patched media, and all windows patches)

PS C:\Windows\system32> Get-Host | Select-Object Version

Version
-------
4.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by jgwinner** [comment]
I tried the troubleshooting steps from an elevated PowerShell script and got the following error:

PS C:\Windows\system32> (Get-Item C:\Windows\System32\WindowsPowerShell\v1.0\Modules\MSOnline\Microsoft.Online.Administr
ation.Automation.PSModule.dll).VersionInfo.FileVersion
Get-Item : Cannot find path
'C:\Windows\System32\WindowsPowerShell\v1.0\Modules\MSOnline\Microsoft.Online.Administration.Automation.PSModule.dll'
because it does not exist.

I checked the version of powershell (again, fresh install of 2012R2 from patched media, and all windows patches)

PS C:\Windows\system32> Get-Host | Select-Object Version

Version
-------
4.0

**Comment by mypil** [comment]
@jgwinner  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@jgwinner As per https://docs.microsoft.com/en-us/powershell/scripting/install/installing-windows-powershell?view=powershell-6, please install PowerShell 5.1 from https://www.microsoft.com/en-us/download/details.aspx?id=54616. The try installing the AzureAD module and let use know if it is successful. Thanks

**Comment by jgwinner** [comment]
@JoeDavies-MSFT That isn't listed as a prerequisite on the referring page (Enterprise/powershell/connect-to-office-365-powershell.md). I followed all of the prereq's and it failed. If Powershell 5.1 is required, it needs to be listed on this page and a step added, before the user is directed to perform an activity that fails.

That is the bug.

**Comment by jgwinner** [comment]
@JoeDavies-MSFT Whoops, I take that back. Server 2012R2 does have that version installed.

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\jgwinner> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.3053
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3053
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\Users\jgwinner>
```

Wouldn't Microsoft double check documentation by doing a fresh install of the products being documented?

**Comment by JoeDavies-MSFT** [comment]
@jgwinner I just tested this on a fresh Windows Server 2012 R2 virtual machine.

I added a note in the "What do you need to know before you begin?" section to inform readers that they have to have PowerShell 5.1 or later installed and for listed, older versions of Windows, a link to the 5.1 download.

Sorry for the inconvenience. Thanks so much for letting us know.
