### ISSUE TITLE
[LOC] Broken table layout

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-Enterprise#547]
**article:** external-domain-name-system-records
**author:** kvice
**URL:** https://docs.microsoft.com/en-us/office365/enterprise/external-domain-name-system-records
___
**Repro steps:**
 1. Go to URL above
 2. check the tables under
     - External DNS records required for email in Office 365 (Exchange Online)
     - External DNS records required for Skype for Business Online

e.g. PrintScreen:
![image](https://user-images.githubusercontent.com/47977325/65940633-42fa4200-e429-11e9-8604-dec16c566955.png)

**Comment by mypil** [comment]
@OfficeGlobal  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Solving issue #547 in PR #552

**Comment by mypil** [comment]
@OfficeGlobal  - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
