### ISSUE TITLE
Expand data resiliency details for other services part of office 365

### ISSUE THREAD

**Issue by MarcAir** [MicrosoftDocs/OfficeDocs-Enterprise#548]
I have been looking for data resiliency for SharePoint online and OneDrive for Business -[Exchange Online Data Resiliency in Office 365](https://docs.microsoft.com/en-us/office365/enterprise/office-365-exchange-data-resiliency) is exactly what I was looking for, but only for Exchange Online. 
Having a detailed page, like the Exchange Online mentioned above, for SharePoint online, OneDrive for Business, Teams, Yammer, etc., would be helpful and consistent with the rest of the Data Resiliency docs in this section. 
Having this information will help us sell the online services in a consistent way. To that end, assuage fears and objections for the need for traditional backup services for most scenarios. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9e7a9f6-71fb-22f8-bf1e-ed51e683d668
* Version Independent ID: 6e03f2dd-e011-1172-fcfa-01521a700a4b
* Content: [Data Resiliency in Office 365](https://docs.microsoft.com/en-us/office365/enterprise/office-365-data-resiliency-overview#office-365-data-resiliency-principles)
* Content Source: [Enterprise/office-365-data-resiliency-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-data-resiliency-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@MarcAir  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by robmazz** [comment]
@MarcAir - thanks for the feedback, I'm investigating with the SharePoint and OneDrive teams. I'll respond here with an update soon.

**Comment by mypil** [comment]
@MarcAir - From our understanding, the issue you raised has been answered by robmazz. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
