### ISSUE TITLE
Clarification on note about "vanity" domains

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/OfficeDocs-Enterprise#549]
We have quite a few "vanity" domains configured (for email addresses), but the CDN seems to work fine for us. 

Could this note be clarified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de6ef6f0-6360-23f7-8088-1b47692050b9
* Version Independent ID: e0f9fe4e-8743-060f-ab7a-e91e6292061e
* Content: [Content delivery networks](https://docs.microsoft.com/en-us/office365/enterprise/content-delivery-networks)
* Content Source: [Enterprise/content-delivery-networks.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/content-delivery-networks.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@sparkitect - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by kelleyvice-msft** [comment]
Thanks, @sparkitect. I'm working on getting more information about exactly how this works, and I will update the content once I have.

**Comment by Stealth7777** [comment]
This functionality is in pre-release which is why the documentation has not been updated yet. It has not been released to GA yet. No date available yet for GA announcement.

**Comment by kelleyvice-msft** [comment]
@sparkitect - I will work with the CDN team to update our documentation for GA of this functionality. In the meantime, I will close this issue. Thanks very much for reaching out!

**Comment by Stealth7777** [comment]
@sparkitect I believe I found your comment on another post. I believe you are actually misunderstanding what a vanity domain is. A SharePoint domain has no relationship to your Exchange domains. 99% of SharePoint customers do not have a vanity domain. If you look at the SharePoint URL then you will see what your SharePoint domain is. For example contoso.sharepoint.com is the SharePoint domain for a company called Contoso and who created their Office 365 tenant with the name Contoso.onmicrosoft.com. The SharePoint domain has nothing to do with what you configure in Exchange. We have a handful of customers that were created when SharePoint Online first started that had actual vanity domains and that is who we are updating to GA in the near future. If you are not part of those initial customers then this has no effect on you.

**Comment by sparkitect** [comment]
@Stealth7777 
Thanks, Scott. I thought that might be the case (me not understanding something) since it did in fact work for us.

However, the note is still misleading in that it links to the instructions for adding an Exchange Domain.

@kelleyvice-msft Kelly, would you consider reopening the issue? At the very lest, the note shouldn't link to instructions for something that **doesn't** cause the CDN errors.

**Comment by kelleyvice-msft** [comment]
Thanks, @sparkitect. I am actually removing references to custom domains from the CDN topics, as Scott has pointed out that it's not applicable to the current SharePoint Online architecture. These updates should be live later today. Thanks again for contributing!
