### ISSUE TITLE
Migrate Data chats flock to office 365

### ISSUE THREAD

**Issue by cesaralcazar** [MicrosoftDocs/OfficeDocs-Enterprise#550]
Hello,
I need migrate Flock (Communication & Collaboration Platform for Modern Teams) to Microsoft Teams (Office 365), how to do it?,
for examples, groups, chats, images and documents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34a6adfe-51db-1fa6-20c4-3aee61172168
* Version Independent ID: aa6f41a2-e37f-0c13-7eb9-9772194bc22c
* Content: [Migrate your organization data to Office 365 Enterprise](https://docs.microsoft.com/en-us/office365/enterprise/migrate-data-to-office-365#feedback)
* Content Source: [Enterprise/migrate-data-to-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/migrate-data-to-office-365.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@cesaralcazar To my knowledge, there is no documentation for this migration. Please ask this question as an issue on this article: https://docs.microsoft.com/en-us/MicrosoftTeams/how-to-roll-out-teams

A Teams writer will be able to answer regarding future plans for this content.
