### ISSUE TITLE
missing URL

### ISSUE THREAD

**Issue by zkanth** [MicrosoftDocs/OfficeDocs-Enterprise#551]
The feed doesn't contain "onedrive.live.com". Could you please add that to your o365 feed. We are importing your feeds using minmeld on our palo alto firewalls

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@zkanth  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by JoeDavies-MSFT** [comment]
@zkanth I have forwarded your request to the product team that manages the list of endpoint for their consideration in a future update. Thanks for letting us know.

**Comment by zkanth** [comment]
Thank you for your response. Do we have any turnaround time?
Regards,
Zaffar
