### ISSUE TITLE
"Encryption in the Microsoft Cloud" link is broken

### ISSUE THREAD

**Issue by grizzlyjere** [MicrosoftDocs/OfficeDocs-Enterprise#553]
The "Encryption in the Microsoft Cloud" in the first paragraph is broken, returning a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cefde46c-31d4-54ad-8c5c-44f23d8509b7
* Version Independent ID: ae9d8dc1-dafc-7bb6-b9de-c5ddc049dadf
* Content: [Office 365 SharePoint Online Data Deletion](https://docs.microsoft.com/en-us/office365/Enterprise/office-365-sharepoint-online-data-deletion)
* Content Source: [Enterprise/office-365-sharepoint-online-data-deletion.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-sharepoint-online-data-deletion.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@grizzlyjere - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@grizzlyjere - PR #554 has been created to fix and close this broken link issue once the PR is merged.

Thank you for pointing this out. We greatly appreciate your contribution to make the docs better!
