### ISSUE TITLE
What about other O365 apps/services not listed?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-Enterprise#555]
Such as Outlook mobile app, Teams mobile app, and all the desktop apps (especially Outlook), and Office.com.
We've been testing MFA for a few people and during our testing we've taken notice of how some applications or services don't seem to require re-authentication as often as we thought.
Here are some of the actions we thought would cause users to need to re-authenticate but didn't:
* Desktop applications after a reboot or user logoff/logon
* Desktop applications after closing applications
*  Web apps (Office.com) after closing/reopening browser
* Web apps (Office.com) after leaving them open for long periods of time (such as over night).
* Mobile apps (specifically Outlook and Teams) after rebooting device.
* Mobile apps (specifically Outlook and Teams) after closing/reopening app.

It seems obvious that some other form of timeout is in play for these, but they're not listed.  From a security standpoint, at the very least, it would be good to know what the session timeouts are for these apps/services not already listed in this article.  At best, it would also be good to know if the timeout period can be changed for any of them and how to change it.  I notice Set-OrganizationConfig in the article for setting it for Outlook web app but no mention of how to set for all the other applications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1570de51-50b1-d4cc-c1c7-832b3242ccb3
* Version Independent ID: f5250f91-0a48-20cf-8e2c-e2dc347edd88
* Content: [Session timeouts for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/session-timeouts)
* Content Source: [Enterprise/session-timeouts.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/session-timeouts.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@Canis-Lupis  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@MSFTTracyP - I have tried to find out the required details on the internet but it looks like there is no proper information available. Can you please share any details you have regarding MS Teams, Outlook Mobile Apps, Outlook desktop app. 

Regards,
Imran

**Comment by Canis-Lupis** [comment]
Thanks, Imran, but I'm not sure what you are asking.  I gave all the details in my original post. To recap, here's what we tested to see if a user needed to re-authenticate but none of these actions caused the users to re-authenticate:


  *   Desktop applications after a reboot or user logoff/logon
  *   Desktop applications after closing applications
  *   Web apps (Office.com) after closing/reopening browser
  *   Web apps (Office.com) after leaving them open for long periods of time (such as over night).
  *   Mobile apps (specifically Outlook and Teams) after rebooting device.
  *   Mobile apps (specifically Outlook and Teams) after closing/reopening app.

In addition, I should probably add to my original question, how does enabling SSO affect the session time out not only for the apps listed in the article, but the ones I listed as well?  Thanks for your attention on this.

________________________________

**Comment by joinimran** [comment]
@canis-lupis, as of now there is no information required from your side. I was trying to engage the doc owner to see if there are more details available for this document so that we can update with your required details and any other information available regarding this. 

Thanks.

**Comment by mypil** [comment]
@MSFTTracyP - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by Gideon122** [comment]
As everyone else has been commenting, what about all the other Office 365 offerings?  What are the session timeouts for Word, PowerPoint, and Excel?  Please answer Canis-Lupis's original post.  C'mon Microsoft!  Don't claim this article is for Office 365 and leave out most of what makes up Office 365!

**Comment by cam-mielbye** [comment]
@Canis-Lupis Any update on whether enabling SSO forces a session reset/reauthentication? We're federating our domain and enabling Okta SSO.

**Comment by Canis-Lupis** [comment]
@cam-mielbye , sorry, no update.

**Comment by MSFTTracyP** [comment]
Hi there. I think the information that you're currently missing is in the preview article for Azure AD token lifetimes (which includes information on token types and timeouts in SSO). Thanks! 

![image](https://user-images.githubusercontent.com/33558605/71930686-00938000-3151-11ea-9da9-7f37211e7a61.png)
