### ISSUE TITLE
How to set 'Mail' property?

### ISSUE THREAD

**Issue by lesterw1** [MicrosoftDocs/OfficeDocs-Enterprise#557]
How do I set the primary email address property (.Mail)? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46857454-f2fd-2254-5a44-0a0ca1a7f068
* Version Independent ID: 35ea3b33-903c-1a1c-a8ba-146608b40ece
* Content: [Configure user account properties with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/configure-user-account-properties-with-office-365-powershell#feedback)
* Content Source: [Enterprise/powershell/configure-user-account-properties-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/configure-user-account-properties-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@lesterw1  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@lesterw1 I have added notes for mapping the Mail property to the corresponding parameters in the Set-AzureADUser and Set-MsolUser commands. Thanks for your question.

**Comment by lesterw1** [comment]
I see the note but unfortunately setting the "OtherMails" property only sets the alternative email addresses. It does NOT change the primary .Mail property. I just tested this. So the annotation in the documentation is not correct. :(

**Comment by JoeDavies-MSFT** [comment]
@lesterw1 Please try the instructions at https://mymicrosoftexchange.wordpress.com/tag/mail-attribute/ and let me know if they work for you.

**Comment by mypil** [comment]
@lesterw1 - From our understanding, the issue you raised has been answered by JoeDavies-MSFT. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
