### ISSUE TITLE
Office 365 CDN supports for custom / vanity domain tenant

### ISSUE THREAD

**Issue by mitanabe** [MicrosoftDocs/OfficeDocs-Enterprise#558]
Could you reflect the following update also to other language pages including Japanese page?

Update use-office-365-cdn-with-spo.md 
Revised note to remove inapplicable references to custom domains.
https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/aa3d8b69c580c487c5eaad7f17e5eae7b340587b#diff-370304163f36aa3f74d2c963637989c3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97626653-f653-d954-7a39-e5beac635e18
* Version Independent ID: 86f7d0b5-3a63-7511-0fc6-e3d98bea4b74
* Content: [Use the Office 365 Content Delivery Network (CDN) with SharePoint Online](https://docs.microsoft.com/en-us/office365/enterprise/use-office-365-cdn-with-spo#feedback)
* Content Source: [Enterprise/use-office-365-cdn-with-spo.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/use-office-365-cdn-with-spo.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@mitanabe  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@kelleyvice-msft - Can you please share your insights on this issue? 

Is this something that @OfficeGlobal should handle as part of Translation/Localization?

Thank you.

cc: @kenwith

**Comment by mypil** [comment]
@TinaMcN - Can you please share your inputs if this issue should be handled by the Translation/Localization team?

Thank you.

**Comment by TinaMcN** [comment]
@OfficeGlobal Can you please investigate this.  The English content was updated 1-Oct but the MT'd pages were last updated in May.  The Note near the top of the page (highlighted in purple) includes this text in Japanese that should be removed.  The issue also occurs for other languages.
"Office 365 CDN は、現在、カスタムまたは "バニティ" ドメインで構成されているテナントをサポートしていません。 「ドメインを 365 office に追加する」の手順に従って office 365 テナントのコンポーネントにドメインを追加した場合、cdn からコンテンツにアクセスしようとすると、OFFICE 365 CDN によってエラーが返されます。"

**Comment by OfficeGlobal** [comment]
@TinaMcN we have checked the issue. The article is not properly visible at LocFiles level in iCMS. The source was re-Index. In case it will not help, we'll log an issue to iCMS support team

**Comment by OfficeGlobal** [comment]
@mitanabe we can see the article was updated at live site. (MachineTranslated)

**Comment by mitanabe** [comment]
@OfficeGlobal @mypil @TinaMcN 
I confirmed the page was updated. I appreciate your kind help. We can close this case now.
