### ISSUE TITLE
GEO and Groups

### ISSUE THREAD

**Issue by JT-Serco-2019** [MicrosoftDocs/OfficeDocs-Enterprise#559]
GEO Admins cannot manage O365 Group connected SharePoint sites but can add themselves as a Site Collection Admins to a O365 GROUP.  Change Opening sentence to:  “You can configure separate administrators for each geo location that you have in your tenant. These administrators will have access to the SharePoint Online and OneDrive settings that are specific to their geo location and can add themselves as Site Collection Admin's via PowerShell “Set-SPOUser” cmdlet to O365 Group connected sites.”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3563cead-033f-932d-6a8b-e34ab4cc68da
* Version Independent ID: 21a1502b-efa3-df19-4176-423c43fe3e4e
* Content: [Add or remove a geo administrator](https://docs.microsoft.com/en-us/office365/enterprise/add-a-sharepoint-geo-admin#feedback)
* Content Source: [Enterprise/add-a-sharepoint-geo-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/add-a-sharepoint-geo-admin.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@JT-Serco-2019  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hello @JT-Serco-2019 I am proposing to the authors of the article adding this information to the article. Let's see if they approve it.
Thanks for your feedback!

**Comment by MikePlumleyMSFT** [comment]
The behavior here is the same as a non-multi-geo environment. SharePoint admins can add themselves as site or group admins in the SharePoint admin center as needed.

**Comment by get-itips** [comment]
Hello @JT-Serco-2019 
As @MikePlumleyMSFT explained, this is the usual behavior so no need to add this to this article, however, your contribution will be visible and remain at the bottom of the article.
Many thanks

**Comment by JT-Serco-2019** [comment]
Serco Business

Mike,

I hate to say it or they misunderstood, a Geo Admin are not assigned as SharePoint Admins because SharePoint Admins have access to all GEO Locations, GEO admins only have access to sites on their GEO and cannot add themselves to a O365 Group  in their GEO, they can add themselves to the SharePoint site as a Site Collection Admin by using PowerShell command only. There is no GUI interface.

JT

James K. Turner, PMP & Security+
Systems Administrator IV &
Collaboration Tech Lead,
Microsoft 365 SharePoint
Enterprise Applications Serco Inc.

T: 719.629.6382
james.turner@serco-na.com<mailto:james.turner@serco-na.com>


www.serco-na.com<http://www.serco-na.com/>

[cid:image001.png@01D2039F.1FE01BF0]

**Comment by mypil** [comment]
@MikePlumleyMSFT - Can you please share your inputs on this additional feedback?

Thank you.

cc: @kenwith

**Comment by mypil** [comment]
@JT-Serco-2019 - We appreciate your efforts to clarify the docs.

Regarding your additional feedback, we have reached out to the Product team and we were told that the usual admin activities are available in the UI for geo-administrators for sites in their geo location. In any case, the PowerShell option is really outside the scope of the document.

Thank you for your contribution to make the docs better! Much appreciated!
