### ISSUE TITLE
spelling error

### ISSUE THREAD

**Issue by pianofu** [MicrosoftDocs/OfficeDocs-Enterprise#561]
"trail" expiration date should be "trial" expiration date

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdf56d0-5b7a-f0df-86c2-14ce1c067514
* Version Independent ID: 76a8737d-8f21-56ae-93f5-5d7942813484
* Content: [Subscriptions, licenses, accounts, and tenants for Microsoft's cloud offerings](https://docs.microsoft.com/en-us/office365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings#feedback)
* Content Source: [Enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@pianofu - PR #562  has been created to fix and close this issue once the PR is merged.

Thank you and we appreciate your contribution to make the docs better!
