### ISSUE TITLE
SPO IP range used by EXO during Hybrid MRS moves 

### ISSUE THREAD

**Issue by Davidm17011** [MicrosoftDocs/OfficeDocs-Enterprise#563]
We are seeing traffic on 40.108.208.171 and 40.108.208.169 when doing Hybrid MRS move from on-prem EXCH to EXO.  When we block those endpoints, some of the MRS jobs fail.  These IPs are not listed under EXO, but are listed under SPO/ODfB (40.108.128.0/17).  Are you saying that SPO ranges must be allowed in order to do mailbox migrations, or are these IPs being reassigned to EXO?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@Davidm17011 - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by JoeDavies-MSFT** [comment]
@Davidm17011 I have forwarded this issue to the product teams who manage these endpoints for answers to your question. Thanks

**Comment by mypil** [comment]
@JoeDavies-MSFT - Do you have any updates from the product team?

Thank you.

**Comment by mypil** [comment]
@JoeDavies-MSFT @LauraWi - We would like to follow up. Do you have any updates from the Product team?

Thank you.

**Comment by LauraWi** [comment]
Hi, @Davidm17011  Guidance from engineering is that, yes, you need to allow connectivity to the SharePoint IP addresses.
