### ISSUE TITLE
Could this Resp API stop to include wildcard URL

### ISSUE THREAD

**Issue by wtffrance** [MicrosoftDocs/OfficeDocs-Enterprise#564]
If the goal of this rest API is to make our life easier to configure network perimeter device, this Resp API should NOT use wildcard URL: Not all perimeter device are supporting "wildcard" hostname, and if they do, it is pretty resource demanding.

Using Wildcard "hostname"  rely on reverse DNS lookup. Which means that microsoft should be able to easily and automatically  update this rest-api when updating its dns-zone and reverse zone. 

Notice also that the name "URL" is wrongly use in this document/Rest API. what is called urls is actually just "FQDN" and wildcard FDQN
URL are welldefined, for example in https://tools.ietf.org/html/rfc1738 and its "syntax" is specified using a BNF in https://tools.ietf.org/html/rfc1738#section-5. the "url" in this document are barely "host" or domains....  This is a semantic detail, that is not too important, and we can live with it...

BUT stop using  wildcard usage would really be a good thing... 

Looking forward to your positive answer.
Regards,

Jean

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7ebf92c-e478-0f65-0494-97042e974b46
* Version Independent ID: 7e1b9b91-d60d-8665-9a39-2ca77a46b4ce
* Content: [Office 365 IP Address and URL web service](https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service#feedback)
* Content Source: [Enterprise/office-365-ip-web-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@wtffrance  - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature request on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by wtffrance** [comment]
Hi Joyce, and thank you for your quick answer.I am actually integrating our firewall services with 365 for our customer. I do not have a 365 account myself. I actually accidentally use this old test git hub account that was "private", and not a business account...  So I will try to do what you required, but I will probably use a lot of time getting an account, creating the ticket, etc. for something I feel fall under common sens....  But can you help me: which forum should I use? Office 365 Security & Compliance ?Office 365 Business Center?General?an other one ?Thank you!Best regardsJean TedescoLe 21 octobre 2019 à 11:03, "Joyce Y." <notifications@github.com> a écrit :  @wtffrance - Thank you for engaging with the community here for the docs.I know the product teams are always looking for user feedback and feature request on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in UserVoice. You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.Thank you for your contribution to make the docs better! Much appreciated!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mypil** [comment]
@wtffrance - You may submit your feedback on this forum- **https://office365.uservoice.com/forums/273493-office-365-admin**.

Thank you.

**Comment by 99littlebugs** [comment]
Based on the docs, it seems like the asterisk (*) is meant to indicate your tenant name. That said, I raised https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/828 because it was only working for some sections. Stay tuned.
