### ISSUE TITLE
Remote Server returned an error

### ISSUE THREAD

**Issue by DTA-TNovak** [MicrosoftDocs/OfficeDocs-Enterprise#565]
![image](https://user-images.githubusercontent.com/56815440/67248452-40cb5680-f4b0-11e9-9974-288ea35292c2.png)

Am trying to connect to Sfb online using Powershell on RDS environment. 

Help!!

**Comment by mypil** [comment]
@DTA-TNovak - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
