### ISSUE TITLE
Limitations on Modern portal site

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-Enterprise#566]
Let me check two points in this article.

1. Portal site and collaboration site
---------------------------------------
This article is for portal sites.
Can these limits be ignored for small and medium-sized collaboration sites? (i.e., Team site, communication site, etc.)

By the way, according to here (https://docs.microsoft.com/en-us/sharepoint/portal-health
) , the word "portal" is defined as follows.

> A portal is a SharePoint site where your default landing page(s) for your company is created. Large organizations can have several portals. If you expect more than 20% of your users within your organization to access the page, you should consider that a portal page.

2. Site scope (site collection or single site)
--------------------------------------------
It has been a while since the modern site was provided, but many users still create and use subsites in modern sites.

To avoid confusion, you should clearly describe whether the "site" in this article means a site collection scope or a single site scope.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43947744-f6f9-aae0-0ecd-fc4a6c7fe1f1
* Version Independent ID: 9501312d-a1a0-91c4-ec6a-e9d042b1b5d1
* Content: [SharePoint Online modern portal site limits](https://docs.microsoft.com/en-us/office365/enterprise/modern-portal-limits#feedback)
* Content Source: [Enterprise/modern-portal-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/modern-portal-limits.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@kefujino - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@kefujino Thank you for your feedback.

1)You are correct, the limits and recommendations are only for portal sites and not for collaboration sites( Team or communication site).

2) The site in this article means a Single Site and I don't think that needs to be explicitly mentioned Since we mention Site collection limits when we talk about site collection scope.

Hope this Helps!

Thanks
Sri

**Comment by mypil** [comment]
@kefujino  - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by kefujino** [comment]
@msbemba
Thank you for your quick reply.
Since performance tuning is so important for many customers, I asked the article content.

@mypil
For now, there are no questions, so please close it.
Thank you!
