### ISSUE TITLE
Missing info for managing Exchange Online with MFA - Connect-EXOPSSession

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/OfficeDocs-Enterprise#568]
Please update docs with Connect-EXOPSSession ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c551eb1-7ac5-cb02-cd1b-d67ca3886d85
* Version Independent ID: fb690e2e-420e-f697-60f2-39520283d385
* Content: [Connect to all Office 365 services in a single Windows PowerShell window](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window)
* Content Source: [Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@hkusulja  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@hkusulja The current article contains a link to the [Connect to Exchange Online PowerShell using multi-factor authentication](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/connect-to-exchange-online-powershell/mfa-connect-to-exchange-online-powershell) article, which contains the detailed instructions on how to install the Exchange Online Remote PowerShell Module and connect using Connect-EXOPSSession. These instructions should not be duplicated here. Thanks for your comment.
