### ISSUE TITLE
Missing Email Address

### ISSUE THREAD

**Issue by AlN3t** [MicrosoftDocs/OfficeDocs-Enterprise#57]
Hi, I tried to setup an alert on a list but it is complaining that
You do not have an e-mail address. 

How do we sync the email address from Azure AD?

Is it through Step 4 by adding a $map4 to the powershell?

Please advise.

Thanks,
Alain

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
Apologies, I do not have a tenant with O365 to test with emails. However, the default behavior for the AAD application is to include the email claim as `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress`.

![image](https://user-images.githubusercontent.com/7107098/40430838-a478e404-5e6b-11e8-93df-fae0e31d812d.png)

Using this, you should be able to add another claim type mapping. 

`
$map = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name" -IncomingClaimTypeDisplayName "name" -LocalClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn"
$map2 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname" -IncomingClaimTypeDisplayName "GivenName" -SameAsIncoming
$map3 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname" -IncomingClaimTypeDisplayName "SurName" -SameAsIncoming
$map4 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress" -IncomingClaimTypeDisplayName "Email" -SameAsIncoming
`
Please try it out and let us know if this works.

**Comment by AlN3t** [comment]
Thanks I was able to include the email using $map4.

However in user profile of a user
The only information that have been mapped are
Account name: i:0e.t|azuread|firstname.lastname@domain.com
Name: firstname.lastname@domain.com

I was expecting in User profile that First name should have been mapped to "GivenName" ClaimType, Last name: to "SurName" ClaimType and Work Email to "Email" ClaimType. But those fields are blank.

**Comment by sngoz** [comment]
If I manually enter the email address in a user profile, a 2013 workflow email to the creator, and I assume also an alert, will work. 

Has anyone set up some sort of user profile sync to sync values such as email, manager, department with Azure AD?

**Comment by kaevans** [comment]
@sngoz There is no built-in capability for SharePoint to sync user profiles with Azure AD. As you pointed out, it works if you add those attributes to the user profile. You will need to build this capability yourself. The two components you need are something to [read user profiles from the Graph](https://developer.microsoft.com/en-us/graph/docs/concepts/azuread-users-concept-overview) and to [programatically store them into the user profile system](https://blogs.msdn.microsoft.com/kaevans/2013/05/23/sharepoint-2013-user-profile-sync-for-claims-users/) in the section "What if My User Doesn’t Come From Active Directory?" (see the end of the article).
