### ISSUE TITLE
How long do deleted sites hang around?

### ISSUE THREAD

**Issue by giveitaGo** [MicrosoftDocs/OfficeDocs-Enterprise#570]
If one of our global admins wanted to restore a deleted site collection, is there a limit to how long a deleted site collection will be available for restore?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cefde46c-31d4-54ad-8c5c-44f23d8509b7
* Version Independent ID: ae9d8dc1-dafc-7bb6-b9de-c5ddc049dadf
* Content: [Office 365 SharePoint Online Data Deletion](https://docs.microsoft.com/en-us/office365/enterprise/office-365-sharepoint-online-data-deletion)
* Content Source: [Enterprise/office-365-sharepoint-online-data-deletion.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-sharepoint-online-data-deletion.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@giveitaGo - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @giveitaGo ,
Sharepoint Online sites, as well as site collections are also retained for 93 days. Please see [Restore deleted sites](https://docs.microsoft.com/sharepoint/restore-deleted-site-collection) 
Thank you

**Comment by mypil** [comment]
@giveitaGo - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
