### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dlyall-maine** [MicrosoftDocs/OfficeDocs-Enterprise#572]
How many separate subscriptions can be created within a single tenant? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdf56d0-5b7a-f0df-86c2-14ce1c067514
* Version Independent ID: 76a8737d-8f21-56ae-93f5-5d7942813484
* Content: [Subscriptions, licenses, accounts, and tenants for Microsoft's cloud offerings](https://docs.microsoft.com/en-us/office365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings#feedback)
* Content Source: [Enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@dlyall-maine  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
@dlyall-maine  
A subscription is a way you add services or licenses to the same tenant.
This number has a high limit, so no matter what you do, you won't reach that number.

I'd think that it should be something like 1 million, or something excessively big.

**Comment by mypil** [comment]
@dlyall-maine - From our understanding, the issue has been answered by j0rt3g4. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.
