### ISSUE TITLE
How to enable all services.

### ISSUE THREAD

**Issue by denis-kvochka** [MicrosoftDocs/OfficeDocs-Enterprise#573]
Hello.
It is not clear how to enable all services. For en example, if some services were disabled before and now I need to enable all of them. 
    -LicenseOptions parameter doesn't accept an empty value of $LO (empty list of disabled plans).

What to do?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add5965d-008c-f030-45df-653ce3e9a1b3
* Version Independent ID: 6646ad46-d40d-fee3-5ca1-3272d3b3e4fb
* Content: [Disable access to services with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/disable-access-to-services-with-office-365-powershell#feedback)
* Content Source: [Enterprise/powershell/disable-access-to-services-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/disable-access-to-services-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@denis-kvochka  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@denis-kvochka I don't see a way to selectively enable services within a license using the Set-MsolUserLicense cmdlet. Please try removing and then assigning the license for a user account to re-enable all the services that have been disabled. See https://docs.microsoft.com/en-us/powershell/module/azuread/set-azureaduserlicense?view=azureadps-2.0

**Comment by BillyA7** [comment]
> Hello.
> It is not clear how to enable all services. For en example, if some services were disabled before and now I need to enable all of them.
> -LicenseOptions parameter doesn't accept an empty value of $LO (empty list of disabled plans).
> 
> What to do?
> 
> Thanks
> 
This will enable all services

$LO = New-MsolLicenseOptions -AccountSkuId <AccountSkuId>

**Comment by JoeDavies-MSFT** [comment]
@BillyA7 I have added your suggestion to the article. Thanks so much for letting us know.
