### ISSUE TITLE
key: AlwaysUseMSOAuthForAutodiscover reg key required

### ISSUE THREAD

**Issue by afield1235** [MicrosoftDocs/OfficeDocs-Enterprise#576]
Why isn't this key listed? It appears to be required for Outlook 2016 to transition to use modern auth. I enabled modern auth (OAUTH) for Windows Outlook and NO USERS are being prompted to use modern auth. I even set up a brand new machine and it failed also. This doesn't seem to work without that key also but it is absent from this page. All these registry keys are pretty lame considering Microsoft makes both Office365 and Outlook 2016. You couldn't have made this easier for clients??

Also Outlook "365" actually is Outlook 2016? The branding further complicates this issue.

**Outlook 2016**

    Modern Authentication is enabled by default.

    Recommend that users force Outlook to use Modern Authentication. To do that, set the DWORD value of the following registry key to 1. 

    HKEY_CURRENT_USER\Software\Microsoft\Exchange\AlwaysUseMSOAuthForAutoDiscover

    For more information, see KB 3126599 - Outlook prompts for password when Modern Authentication is enabled. 

    MAPI/HTTP cannot be disabled. For more information, see KB 2937684 - Outlook 2010, 2013, or 2016 may not connect using MAPI over HTTPs as expected. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059ed9a7-ea75-0fa3-e246-4ad1f1b0c5bc
* Version Independent ID: d7598f96-3158-09ee-024a-6175599718cd
* Content: [How modern authentication works for Office 2013 and Office 2016 client apps](https://docs.microsoft.com/en-us/office365/enterprise/modern-auth-for-office-2013-and-2016?redirectSourcePath=%252farticle%252fe4c45989-4b1a-462e-a81b-2a13191cf517)
* Content Source: [Enterprise/modern-auth-for-office-2013-and-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/modern-auth-for-office-2013-and-2016.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@afield1235  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Added on PR #603

**Comment by MSFTTracyP** [comment]
Article is updated. My thanks, all!

**Comment by mypil** [comment]
@afield1235 -  From our understanding, the issue has been resolved so we will close this issue. 


Thank you for your contribution to make the docs better! Much appreciated!
