### ISSUE TITLE
This section is confusion

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-Enterprise#577]
Exchange Server on-premises in a hybrid Office 365 environment

If you are using Exchange server 2013, At least one server must have the Mailbox and Client Access server roles installed. While it is possible to install the Mailbox and Client Access roles on separate servers, we strongly recommend that you install both roles on each server to provide additional reliability and improved performance.

Both roles must be on the same server?  That is what is implied.  The next section then contradicts that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626caf29-7e88-0b56-2013-5c5b7c2a5917
* Version Independent ID: 2376192f-793d-0166-46c7-870cd0c41abb
* Content: [Hybrid Modern Authentication overview and prerequisites for using it with on-premises Skype for Business and Exchange servers](https://docs.microsoft.com/en-us/office365/enterprise/hybrid-modern-auth-overview)
* Content Source: [Enterprise/hybrid-modern-auth-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/hybrid-modern-auth-overview.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@r-milne  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Thanks for your feedback @r-milne I have made the changes in the document to make it clear. For the second part "If you are using Exchange server 2016 or later version, at least one server must have the Mailbox server role installed." This only applies to the exchange server 2016 and the 1st statement applies to the exchange server 2013.

Thanks.

**Comment by mypil** [comment]
@r-milne - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/f91daeaa9812ebdbf10035d5bbbd6a9f31f3d7fd. 


Thank you for your contribution to make the docs better! Much appreciated!
