### ISSUE TITLE
Policies Questions

### ISSUE THREAD

**Issue by moojjoo** [MicrosoftDocs/OfficeDocs-Enterprise#58]
kaevans, thank you for all your time first and foremost.  We are so close to getting this to work.

1. In the url is the **Application Object ID** suppose to be used?  https://graph.windows.net/myorganization/servicePrincipals/[Table 1 = Application Object ID/policies ?
2. If 1 == true, then I am getting the following:

{
    "odata.metadata": "https://graph.windows.net/myorganization/$metadata#directoryObjects",
    "value": [
        {
            "odata.type": "Microsoft.DirectoryServices.Policy",
            "objectType": "Policy",
            "objectId": "XXXXXXX-923b-458f-a025-5033#########",
            "deletionTimestamp": null,
            "alternativeIdentifier": null,
            "definition": [
                "{\r\n  \"TokenIssuancePolicy\": {\r\n    \"Version\": 1,\r\n    \"SigningAlgorithm\": \"http://www.w3.org/2001/04/xmldsig-more#rsa-sha256\",\r\n    \"TokenResponseSigningPolicy\": \"TokenOnly\",\r\n    \"SamlTokenVersion\": **\"2.0\**"\r\n  }\r\n}"
            ],
            "displayName": "TokenIssuancePolicy",
            "isTenantDefault": false,
            "keyCredentials": [],
            "type": "TokenIssuancePolicy"
        }
    ]
}

In the article there is nothing that mentions **Application Registrations**, does this need to be performed and what settings need to be applied?  And if that it true, what permissions are needed.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by moojjoo** [comment]
When running and logging in with Global Administrator Account:
Import-Module c:\_cert\Initialize.ps1
$objectid = "1cd1a10a-17b0-449c-98ca-a6742326d4f0"
$saml2policyid = Get-PoliciesAssignedToServicePrincipal -servicePrincipalId $objectid | ?{$_.displayName -EQ "TokenIssuancePolicy"} | select objectId
Remove-PolicyFromServicePrincipal -policyId $saml2policyid -servicePrincipalId $objectid
$policy = Add-TokenIssuancePolicy -DisplayName SPSAML11 -SigningAlgorithm "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" -TokenResponseSigningPolicy TokenOnly -SamlTokenVersion "1.1"
Set-PolicyToServicePrincipal -policyId $policy.objectId -servicePrincipalId $objectid

Getting the following Error in PowerShell:
Loading ADAL Assemblies ...
True
GetPoliciesAssignedToEntityUrl: Using graph endpoint: https://graph.windows.net entity: servicePrincipals entityId: 1cd1a10a-17b0-449c-98ca-a6742326d4f0
HTTP GET https://graph.windows.net/myorganization/servicePrincipals/1cd1a10a-17b0-449c-98ca-a6742326d4f0/policies?api-version=1.6
AssignPolicyToEntity: Using graph endpoint: https://graph.windows.net entity: servicePrincipals entityId: 1cd1a10a-17b0-449c-98ca-a6742326d4f0
HTTP DELETE https://graph.windows.net/myorganization/servicePrincipals/1cd1a10a-17b0-449c-98ca-a6742326d4f0/$links/policies/@{objectId=8b8ce23d-923b-458f-a025-5033a5626cfb}?api-version=1.6
Invoke-RestMethod : {"odata.error":{"code":"Request_UnsupportedQuery","message":{"lang":"en","value":"Unsupported referenced-object resource identifier for link property 'policies'."}}}
At C:\_cert\MSGraphTokenLifetimePolicy.psm1:339 char:15
+     $result = Invoke-RestMethod @parameters
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
GetEntityUrl: Using graph endpoint: https://graph.windows.net entity: policies entityId: 
HTTP POST https://graph.windows.net/myorganization/policies/?api-version=1.6
{"displayName":"SPSAML11","type":"TokenIssuancePolicy","definition":["{\"TokenIssuancePolicy\":{\"TokenResponseSigningPolicy\":\"TokenOnly\",\"SamlTokenVersion\":\"1.1\",\"SigningAlgorithm\":\"http://www.w3.org/2001/04/xmldsig-more#rsa-sha256\",\"Version\":1
}}"]}
AssignPolicyToEntity: Using graph endpoint: https://graph.windows.net entity: servicePrincipals entityId: 1cd1a10a-17b0-449c-98ca-a6742326d4f0
GetEntityUrl: Using graph endpoint: https://graph.windows.net entity: policies entityId: 198e0f69-fca4-47fb-b23a-775ffcfdc27a
HTTP POST https://graph.windows.net/myorganization/servicePrincipals/1cd1a10a-17b0-449c-98ca-a6742326d4f0/$links/policies?api-version=1.6
{"url":"https://graph.windows.net/myorganization/policies/198e0f69-fca4-47fb-b23a-775ffcfdc27a?api-version=1.6"}
Invoke-RestMethod : {"odata.error":{"code":"Request_MultipleObjectsWithSameKeyValue","message":{"lang":"en","value":"Request contains property changes that would result in property-uniqueness violation(s). Please retry your request with corrected 
values."}}}
At C:\_cert\MSGraphTokenLifetimePolicy.psm1:339 char:15
+     $result = Invoke-RestMethod @parameters
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by kaevans** [comment]
Step 3, Item 6 above shows where to get the application object ID, there is a screen shot that shows the property blade where to obtain it from.

The part of the error that indicates the problem:

'Request_MultipleObjectsWithSameKeyValue","message":{"lang":"en","value":"Request contains property changes that would result in property-uniqueness violation(s)'

This indicates that there is an existing TokenIssuancePolicy assigned for the object ID. Whether that is the SAML 2.0 policy or if there is a SAML 1.1 policy that you have from a previous run. 

The PowerShell simply wraps calls to [manage TokenIssuancePolicies using the Graph API](https://msdn.microsoft.com/en-us/library/azure/ad/graph/api/policy-operations#create-a-policy). You'll see that the PowerShell sample is really just HTTP GET, POST, and DELETE commands using those URLs from the document I just linked to.  

Knowing that, you can easily troubleshoot this yourself by issuing these calls using the Azure AD Graph Explorer to do things like [list the existing policies](https://msdn.microsoft.com/en-us/library/azure/ad/graph/api/policy-operations#list-policies). Each application can have only one token issuance policy, so if you see one that's already there (like an existing SAML 2.0 policy), it needs to be removed before adding a new one.

**Comment by kaevans** [comment]
Updated based on your feedback. Thank you!  https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/78
