### ISSUE TITLE
Discrepancy between explanatory paragraph and sample code : New-SPOSiteGroup vs Set-SPOSiteGroup 

### ISSUE THREAD

**Issue by John471** [MicrosoftDocs/OfficeDocs-Enterprise#581]
Heading : Create a site collection group (https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-sharepoint-users-and-groups-with-powershell#create-a-site-collection-group)
The paragraph below says : You use the *Set*-SPOSiteGroup command to *create a new* SharePoint group and add it to the ContosoTest site collection.
Whereas the sample code immediately below uses *New*-SPOSiteGroup
Suggestion : Update the paragraph text to align with the sample code text; the required cmdlet to "create a new SharePoint group" is New-SPOSiteGroup (not Set-SPOSiteGroup)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0096189e-b3e3-e26e-2d55-711323ab2a5f
* Version Independent ID: 50d5393d-2dac-869a-8ade-dc2fc3d7a4cf
* Content: [Manage SharePoint Online users and groups with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-sharepoint-users-and-groups-with-powershell#create-a-site-collection-group)
* Content Source: [Enterprise/powershell/manage-sharepoint-users-and-groups-with-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/manage-sharepoint-users-and-groups-with-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@John471  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@John471 This has been corrected and published. Thanks so much for letting us know.
