### ISSUE TITLE
Inquiry about structural navigation caching

### ISSUE THREAD

**Issue by taisino** [MicrosoftDocs/OfficeDocs-Enterprise#587]
As per the following article, caching for structural navigation will improve performance.
https://support.office.com/en-us/article/f163053f-8eca-4b9c-b973-36b395093b43

But this article has still described "Structural navigation, is NOT a recommended navigation option in SharePoint Online".
Could you check which one is correct?

A. Structural navigation will be optimized using cache, but still not recommended and we should guide customer to other options.
B. The performance degradation risk by using structural navigation will be gone by caching, and they can use this without worry.

If B is correct, I appreciate if you will remove "Structural navigation, is NOT a recommended navigation option" statement from this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe686368-f607-9a7d-710b-d51c3f8f6c9a
* Version Independent ID: 01b5902a-6e23-62d9-f0a3-7c1e86194ef1
* Content: [Navigation options for SharePoint Online](https://docs.microsoft.com/en-us/office365/enterprise/navigation-options-for-sharepoint-online?redirectSourcePath=%252fen-us%252farticle%252fnavigation-options-for-sharepoint-online-adb92b80-b342-4ecb-99a1-da2a2b4782eb)
* Content Source: [Enterprise/navigation-options-for-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/navigation-options-for-sharepoint-online.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@taisino  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by kelleyvice-msft** [comment]
I'm adding the topic's author @LoreenLa to the issue.

**Comment by LoreenLa** [comment]
Thanks for the feedback! I'm checking on this and will report back.

**Comment by LoreenLa** [comment]
Thanks again for the feedback! What I've learned is that structural navigation caching is not yet broadly available. So, for the majority of users, the recommendation is still not to use structural navigation if possible. For those users who have the caching option, then we hope you use it and give us feedback about your experience. The article https://support.office.com/en-us/article/f163053f-8eca-4b9c-b973-36b395093b43 is also not broadly available yet, but was created primarily for those who have opted in to targeted/early release features. Once this feature is more broadly available, we will update the content to reflect the latest recommendations.  I hope that is helpful.

**Comment by taisino** [comment]
Hi LoreenLa, thank you very much for your prompt response.
I  understand your explanation completely, and will give the feedback if I'll find anything about caching option.
Please close this discussion.

**Comment by carletto75** [comment]
Any news about general availability of structural navigation caching ?
It is still not available in my tenant.

**Comment by LoreenLa** [comment]
Thanks for asking! We haven’t started rolling to targeted release yet, but we expect to do so in late Q1.
