### ISSUE TITLE
Adding Group to appear in the Quick Launch of the site's People and Groups Page

### ISSUE THREAD

**Issue by John471** [MicrosoftDocs/OfficeDocs-Enterprise#589]
This might be a logical page on which to detail how to use PowerShell to add a SharePoint Group to the site's People and Groups page; i.e. to specify which SharePoint Groups to list in the left pane of the *People and Groups* page for a Web site.
Not sure if/how it is possible with SharePoint Online PowerShell, although after days of scouring the internet, I was eventually able to work it out using PnP PowerShell.
Is referring to PnP cmdlets out of scope for this page?
Is there a way to do this with SPO cmdlets?
For PnP this involves:-
1) to retrieve the existing ID's of the associate(d) groups: Get-PnPPropertyBag -key vti_associategroups
and
2) Set-PnPPropertyBagValue -key vti_associategroups -value GroupAID;GroupBID;GroupCID (etc.) e.g. Set-PnPPropertyBagValue -key vti_associategroups -value "112;118;712;101;504"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0096189e-b3e3-e26e-2d55-711323ab2a5f
* Version Independent ID: 50d5393d-2dac-869a-8ade-dc2fc3d7a4cf
* Content: [Manage SharePoint Online users and groups with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-sharepoint-users-and-groups-with-powershell#feedback)
* Content Source: [Enterprise/powershell/manage-sharepoint-users-and-groups-with-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/manage-sharepoint-users-and-groups-with-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@John471  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@John471 This is an interesting idea for PowerShell. However, the best I can do right now is add it to the list of documentation requests for future consideration. Thanks for letting us know.
