### ISSUE TITLE
spelling/grammar error

### ISSUE THREAD

**Issue by danijeljw** [MicrosoftDocs/OfficeDocs-Enterprise#59]
... Exchange organization (also called themigration administrator) must have the ... 

should be:

... Exchange organization (also called the migration administrator) must have the ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e30c7516-2eb7-548d-6a9d-36ab647779ee
* Version Independent ID: 2d88e8be-b787-c8d6-e514-32f4cb5cca1d
* Content: [Use PowerShell to perform a cutover migration to Office 365](https://docs.microsoft.com/en-us/office365/enterprise/powershell/use-powershell-to-perform-a-cutover-migration-to-office-365)
* Content Source: [Enterprise/powershell/use-powershell-to-perform-a-cutover-migration-to-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/use-powershell-to-perform-a-cutover-migration-to-office-365.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by denisebmsft** [comment]
Thanks for letting us know about this. We fixed it.
