### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by 9songs** [MicrosoftDocs/OfficeDocs-Enterprise#590]
Hi,
there is a spelling mistake in the following sentence within the M365 section: gorup should be group.
OLD: Note that Members can invite refers to members in Azure AD (as opposed to guests) and not to site or gorup members in Microsoft 365. 
NEW: Note that Members can invite refers to members in Azure AD (as opposed to guests) and not to site or group members in Microsoft 365. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bb31720-7494-ab3f-6a3d-5c395649e75d
* Version Independent ID: 81c36ae8-fbaa-c411-4bd2-a4db98e249e1
* Content: [Microsoft 365 guest sharing settings reference](https://docs.microsoft.com/en-us/office365/enterprise/microsoft-365-guest-settings#feedback)
* Content Source: [Enterprise/microsoft-365-guest-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/microsoft-365-guest-settings.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@9songs - Thank you for submitting feedback.

PR #591 has been created to fix and close this issue once the PR is merged.

Thank you and we appreciate your contribution to make the docs better!
