### ISSUE TITLE
What is the IP adddress of the server that runs SPD worflows in Office 365. 

### ISSUE THREAD

**Issue by sunilprabha** [MicrosoftDocs/OfficeDocs-Enterprise#592]
we are using Sharepoint online, and have built number of Workflows, I am curious to see why share point Workflow  server IP  address are not posted. Where do they execute form the range given for share point in the above article is not correct.  is someone going to post that information. 
Regards
Sunil 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?source=docs#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@sunilprabha - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by JoeDavies-MSFT** [comment]
@sunilprabha Can you tell me the URLs/FQDNs you are connecting to and the IP addresses you are seeing? Thanks

**Comment by sunilprabha** [comment]
we are using Office 365 [***.SharePoint.com ] , and workflows are built under that domain or subsite/list which are trying to access our Azure hosted Web API. Currently the web api is open to public in order the  share point to post data.  So I have added the above IP for SharePoint so that the API[****.azurewebsites.net] will allow the communication in firewall rules. 
What is see is WF are not getting triggered form the above IP range, I get a different IP in the logs, which is owned/assigned by MS. I need the IP address so that i can make changes to the  API firewall .

**Comment by JoeDavies-MSFT** [comment]
@sunilprabha I have forwarded your question to the team that manages these endpoints for their comment. Thanks for your feedback.
