### ISSUE TITLE
characters are replaced with "_"

### ISSUE THREAD

**Issue by UKayo** [MicrosoftDocs/OfficeDocs-Enterprise#593]
Please add a note to the section below to clarify that when using directory sync, any characters other than "-" is replaced with "_"

・mailNickname (Exchange alias)
　　　The attribute value cannot begin with a period (.).
　　　The attribute value must be unique within the directory.

This note is needed, as the docs below indicate that EXO allows characters in "alias," and also allowed for cloud users.
https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailbox?view=exchange-ps

-Alias 
The Alias parameter specifies the Exchange alias (also known as the mail nickname) for the recipient. This value identifies the recipient as a mail-enabled object, and shouldn't be confused with multiple email addresses for the same recipient (also known as proxy addresses). A recipient can have only one Alias value.
The value of Alias can contain letters, numbers and the characters !, #, $, %, &, ', *, +, -, /, =, ?, ^, _, `, {, |, } and ~. Periods (.) are allowed, but each period must be surrounded by other valid characters (for example, help.desk). Unicode characters from U+00A1 to U+00FF are also allowed. The maximum length of the Alias value is 64 characters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c60ee789-fce6-6c95-150d-be4ae895730e
* Version Independent ID: d9e96954-3b85-bf8d-c7d3-916a4698fd77
* Content: [Prepare for directory synchronization to Office 365](https://docs.microsoft.com/en-us/office365/enterprise/prepare-for-directory-synchronization)
* Content Source: [Enterprise/prepare-for-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/prepare-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@UKayo  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@UKayo I have looked into this and don't see the connection between your request and the EXO article and reference you describe above. Where does it say that any characters other than "-" are replaced with "_"? Can you clarify? Thanks.

**Comment by mypil** [comment]
@UKayo - We would like to follow up. Can you please respond to the query of JoeDavies-MSFT? 

Thank you.

**Comment by JoeDavies-MSFT** [comment]
@UKayo I added a note to the https://docs.microsoft.com/en-us/office365/enterprise/prepare-for-directory-synchronization topic in the mailNickname (Exchange alias) section about underscores added to converted names. Thanks for letting us know.
