### ISSUE TITLE
Get-AzureADUser -All

### ISSUE THREAD

**Issue by CountlessNumber** [MicrosoftDocs/OfficeDocs-Enterprise#594]
The Get-AzureADuser command didn't return any results. I had to include -All $true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cdc030a-0015-fe77-eac3-4c5070c0c5a3
* Version Independent ID: 24107b9c-1f13-571c-1303-6019ba64dcea
* Content: [View licensed and unlicensed users with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-licensed-and-unlicensed-users-with-office-365-powershell)
* Content Source: [Enterprise/powershell/view-licensed-and-unlicensed-users-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/view-licensed-and-unlicensed-users-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@CountlessNumber  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@CountlessNumber I have added the Get-AzureAdUser -All $true command as a note. Thanks for your feedback.
