### ISSUE TITLE
IP Ranges Required for AutoDetect

### ISSUE THREAD

**Issue by quickclix75** [MicrosoftDocs/OfficeDocs-Enterprise#596]
Please can this page be updated to include reference to the two IP Ranges detailed at this link https://docs.microsoft.com/en-gb/office365/enterprise/additional-office365-ip-addresses-and-urls
Without opening up these on premises the mobile client fails to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba93584-38f6-bc46-9784-c14492de8f75
* Version Independent ID: 2fc5806d-bc80-9cc4-a051-1a9f16322c8d
* Content: [How to configure Exchange Server on-premises to use Hybrid Modern Authentication](https://docs.microsoft.com/en-us/office365/enterprise/configure-exchange-server-for-hybrid-modern-authentication)
* Content Source: [Enterprise/configure-exchange-server-for-hybrid-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/configure-exchange-server-for-hybrid-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@quickclix75  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@quickclix75  Thank you for the feedback. We have added the information in the doc via https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/613

Thanks
Sri

**Comment by mypil** [comment]
@quickclix75 - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/7e8085946781c88ac33b1bd133a14d26223c816c. 


Thank you for your contribution to make the docs better! Much appreciated!
