### ISSUE TITLE
A great tool, but sometimes hard to act on

### ISSUE THREAD

**Issue by SimonJHudson** [MicrosoftDocs/OfficeDocs-Enterprise#597]
Having learned of this from the Intrazone podcast, I am delighted by what it can help with. However it's pretty hard to convert insights to action; in particular it's really hard to work out which images are the ones that need trimming down to size.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad660ca-262d-19f0-a28a-bb834095b4e0
* Version Independent ID: ea31f15c-4528-901f-2a67-28b378573a18
* Content: [Use the Page Diagnostics tool for SharePoint Online](https://docs.microsoft.com/en-us/office365/enterprise/page-diagnostics-for-spo?redirectSourcePath=%252fen-us%252farticle%252fdbab2593-dc6a-40f7-adfe-031b9baa620f#feedback)
* Content Source: [Enterprise/page-diagnostics-for-spo.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/page-diagnostics-for-spo.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@SimonJHudson  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@SimonJHudson - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature request on how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://sharepoint.uservoice.com/)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
