### ISSUE TITLE
Request for adding <tenant>-admin.sharepoint.com to ID 31

### ISSUE THREAD

**Issue by sasaito** [MicrosoftDocs/OfficeDocs-Enterprise#599]
[Enter feedback here]
SharePoint Admin Center URL <tenant>-admin.sharepoint.com isn't listed in ID 31, which indicates SharePoint related FQDN.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?source=docs#skype-for-business-online-and-microsoft-teams)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@sasaito I have forwarded your request to the product team that manages these endpoints for their consideration in a future update. Thanks for letting us know.
