### ISSUE TITLE
RemovePolicyFromServicePrinciple Issue

### ISSUE THREAD

**Issue by KlaBier** [MicrosoftDocs/OfficeDocs-Enterprise#60]
Hi Kirk,
great article, thanks...
I don't know if this is an issue or if there is already another Workaround/update on this, but when I use RemovePolicyFromServicePrinciple Cmdlet with a variable in -policyId  ("$saml2policyid" in your example) it will presents an error (unsupported query ...). Using the Id directly instead of the variable will work fine.

Thanks
Klaus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
Updated script, thank you for reporting this!  https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/78
