### ISSUE TITLE
Guests deleting files

### ISSUE THREAD

**Issue by jgwinner** [MicrosoftDocs/OfficeDocs-Enterprise#600]
Where is the setting to prevent Guests from deleting files? I just tested it, and a guest was able to delete a file from a Teams area, and via the SharePoint link.

This is obviously a compliance issue; there has got to be a setting somewhere to prevent the dataloss and corporate IP theft.

Please advise / update the docs. Thank you,

        == John ==

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bb31720-7494-ab3f-6a3d-5c395649e75d
* Version Independent ID: 81c36ae8-fbaa-c411-4bd2-a4db98e249e1
* Content: [Microsoft 365 guest sharing settings reference](https://docs.microsoft.com/en-us/office365/enterprise/microsoft-365-guest-settings)
* Content Source: [Enterprise/microsoft-365-guest-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/microsoft-365-guest-settings.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@jgwinner  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@jgwinner Thank you for the feedback. File permissions for members and guests reflect whatever your admin has set in your SharePoint settings. You can review the settings via  https://docs.microsoft.com/en-us/sharepoint/external-sharing-overview

Hope this Helps!

Thanks
Sri

**Comment by jgwinner** [comment]
If I give them the sharepoint link, yes. However, If I allow a Guest into the Teams accounts, they can still delete files. I've tested this. So your link only works if I don't allow any Guests to collaborate, post messages, chat, etc.

In other words, Teams has to be out of the picture.

This does not suit a business need and is a data vulnerability.

I've been working on this for a couple of weeks now. If we can't get a good way to prevent Guests, in a Teams environment, from altering or deleting files, would you suggest that I submit this to CERT as a  
data vulnerability?

        == John ==

**Comment by msbemba** [comment]
@jgwinner  Do the Guest users have access to edit files in the SharePoint permission for this o365 group?

**Comment by jgwinner** [comment]
Again, no. But as soon as I add them to the Team, they get delete access.

I was on a remote session for over an hour with MS support. They eventually said "couldn't be done".

        == John ==

**Comment by msbemba** [comment]
@jgwinner If anyone with the link has access to edit the file like mentioned in the article https://docs.microsoft.com/en-us/office365/enterprise/microsoft-365-guest-settings#sharepoint-and-onedrive-file-and-folder-link-settings then the guest will be able to delete the files. So can you go again to the settings and make changes to the group site permissions?

**Comment by jgwinner** [comment]
I'm not sure I understand what you are asking me to repeat.

First, if I send people the Sharepoint link, sure, they only have download and not edit capability ... exactly what I sent them. That only proves SharePoint works.

That doesnt' do Teams any good. I want people in a team to be able to download files, but not delete them or edit them.

Again, I already did each of the steps you mention, and the MS rep in the trouble ticket already did that as well. So these steps have been done multiple times. They don't fix the product vulnerability. 

        == John ==

**Comment by msbemba** [comment]
@jgwinner Thank you for the feedback. I have played around with settings on teams and couldn't locate an option to turn off this feature. I'll work with the team to see how to take this forward.

Thanks
Sri

**Comment by jgwinner** [comment]
Thanks.

Regarding this issue, I think it's important to document the fact that Guests have delete access, and this can't be turned off, especially as the settings sort of imply you can (but just for messages).

        == John ==

**Comment by mypil** [comment]
@jgwinner - Can you please share with us the MS support ticket number when you were troubleshooting with the MS support rep? 

Thank you.

**Comment by jgwinner** [comment]
Sure! However, most of the trouble shooting was a remote session where he went through every, single, screen.

Ticket 17561100 via O365

        == John ==

**Comment by msbemba** [comment]
@jgwinner  We have confirmed that guests do get edit/delete perm when added to items/planner. There will be no update to this document, However, the Author is planning to call this out on https://docs.microsoft.com/en-us/microsoftteams/guest-experience in a few days. 

Thank you for your feedback.

@mypil  You can Close this now as the author will call out this on another doc.

Thanks
Sri

**Comment by jgwinner** [comment]
Thank you! 

This forum is often used for changes to products, but honestly in this case I was mainly looking for this information to be documented so that it's clear as it just seems so absurd.

        == John ==

**Comment by jgwinner** [comment]
Oh - it may be possible to put in a solution with data loss prevention, but I have not tried that yet. The author could call that out, a tutorial would be a big help.

**Comment by mypil** [comment]
@jgwinner - Thank you for your contribution to make the docs better. 

The author has been informed of your suggestions and it will surely be part of their consideration in updating the docs. 

We appreciate your feedback so keep it coming!
