### ISSUE TITLE
Tilde in proxyAddresses is not supported

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Enterprise#601]
In practice, and while working with MS Support, we determined that having Tilde (~) in the proxyAddresses, will result in the email address being evaluated as though the Tilde is not actually there, and this can lead to false-positive DirSync errors about duplicate proxyAddresses.

I can share share in private the MS support ticket # for reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c60ee789-fce6-6c95-150d-be4ae895730e
* Version Independent ID: d9e96954-3b85-bf8d-c7d3-916a4698fd77
* Content: [Prepare for directory synchronization to Office 365](https://docs.microsoft.com/en-us/office365/enterprise/prepare-for-directory-synchronization)
* Content Source: [Enterprise/prepare-for-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/prepare-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@JeremyTBradshaw  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@JeremyTBradshaw I will add this note: A tilde (~) character in email addresses will be ignored. This can lead to false-positive directory synchronization errors about duplicate proxyAddresses. Does this properly capture the issue? Thanks

**Comment by JeremyTBradshaw** [comment]
Hi @JoeDavies-MSFT , yes you got it exactly.  Thanks.

**Comment by JoeDavies-MSFT** [comment]
@JeremyTBradshaw Updated and published. Thanks for letting us know.
