### ISSUE TITLE
Gateway Subnet Range

### ISSUE THREAD

**Issue by scr8er** [MicrosoftDocs/OfficeDocs-Enterprise#602]
Hi there

I'm trying to understand the gateway subnet size limitations, it's hard to find information, nobody knows exactly what makes you need to reserve /27, /28 or even /25.
You can find gateway subnet calculators that just give you the last subnet available range for a network, binary calculations based on VNET Address space but nothing based on the cloud architecture or the client needs. 
Does anybody know why exactly this kind of subnet needs /28-/27-/26 or /25? 
For what? If I need to develop a central hub cloud network architecture and need to understand this before deploy It.

Above issue talks about /25 for express route - VPN failover configuration, but it don't say why.  Does it reserve an IP for each peer? Does it reserve an IP for each VNET? For internal purposes? Routing? 

What if my cloud grows insanely? if I don't know how this limitation works, maybe someday I will face a bad situation.

Thanks in advance.

Edit: Some examples

[https://docs.microsoft.com/es-es/azure/architecture/reference-architectures/hybrid-networking/vpn#vnet-and-gateway-subnet](https://docs.microsoft.com/es-es/azure/architecture/reference-architectures/hybrid-networking/vpn#vnet-and-gateway-subnet)

> "Allocating 32 addresses to this subnet **will help to prevent reaching gateway size limitations** in the future."

What limitations?

[https://docs.microsoft.com/es-es/azure/vpn-gateway/vpn-gateway-vpn-faq#gateways](https://docs.microsoft.com/es-es/azure/vpn-gateway/vpn-gateway-vpn-faq#gateways)

> "The IP addresses in the gateway subnet a**re allocated to the gateway service**. **Some configurations require more IP addresses to be allocated to the gateway services than do others**. You want to make sure your gateway subnet contains enough IP addresses to accommodate future growth and possible additional new connection configurations."

What configurations? How does the gateway service use this IP addresses?

> we recommend that you create a gateway subnet of /27 or larger (/27, /26, /25 etc.). Look at the requirements for the configuration that you want to create and verify that the gateway subnet you have will meet those requirements.

Mysterious requirements.

[https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/migrate-best-practices-networking#best-practice-configure-a-gateway-for-vpn-gateways](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/migrate-best-practices-networking#best-practice-configure-a-gateway-for-vpn-gateways)

> The prefix length of the gateway subnet can have a maximum prefix length of 29 (for example, 10.119.255.248/29). The current recommendation is that you use a prefix length of 27 (for example, 10.119.255.224/27).

Recommends /27 again.
>

**Comment by mypil** [comment]
@scr8er - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by scr8er** [comment]
> @scr8er - May we know which Microsoft document link you used in reference to this issue?
> Please share it with us so we can investigate further. Thank you.
I've updated the main post, but here you have several documentation links where gateway subnets are mention where I can't find an answer for that question about subnet.

[https://docs.microsoft.com/es-es/azure/vpn-gateway/vpn-gateway-vpn-faq#gateways](https://docs.microsoft.com/es-es/azure/vpn-gateway/vpn-gateway-vpn-faq#gateways)

[https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/migrate-best-practices-networking#best-practice-configure-a-gateway-for-vpn-gateways](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/migrate-best-practices-networking#best-practice-configure-a-gateway-for-vpn-gateways)

**Comment by JoeDavies-MSFT** [comment]
@scr8er Please copy your feedback in its entirety and create an issue in the topic at https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-vpn-faq. This is the most definitive source of this guidance and the writer should be able to answer your questions about why /27 is recommended. Thanks
