### ISSUE TITLE
Get-CSOAuthConfiguratin is not for Exchange command.  It's for Skype 

### ISSUE THREAD

**Issue by alambert0008** [MicrosoftDocs/OfficeDocs-Enterprise#604]
The document states.

"You can check the status on your Exchange or Skype for Business servers, on premises, by running the Get-CSOAuthConfiguration command in PowerShell."

However its only for Skype for Business servers and NOT for Exchange.

**Comment by mypil** [comment]
@alambert0008 - This issue appears to be a duplicate to issue #605. Closing this duplicate issue. Thank you.
