### ISSUE TITLE
Get-CSOAuthConfiguratin is not for Exchange command. It's for Skype

### ISSUE THREAD

**Issue by alambert0008** [MicrosoftDocs/OfficeDocs-Enterprise#605]
The document states.

"You can check the status on your Exchange or Skype for Business servers, on premises, by running the Get-CSOAuthConfiguration command in PowerShell."

However its only for Skype for Business servers and NOT for Exchange.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626caf29-7e88-0b56-2013-5c5b7c2a5917
* Version Independent ID: 2376192f-793d-0166-46c7-870cd0c41abb
* Content: [Hybrid Modern Authentication overview and prerequisites for using it with on-premises Skype for Business and Exchange servers](https://docs.microsoft.com/en-us/office365/enterprise/hybrid-modern-auth-overview#feedback)
* Content Source: [Enterprise/hybrid-modern-auth-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/hybrid-modern-auth-overview.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out, @alambert0008. I will research and correct this.

**Comment by dustinwooldridge** [comment]
To find this in Exchange Online you can connect to Exchange Online session and run-
Get-OrganizationConfig | ft OAuth*

OAuth2ClientProfileEnabled
--------------------------
                     False

**Comment by mypil** [comment]
@kelleyvice-msft - Do you have any updates on this?

**Comment by kelleyvice-msft** [comment]
working on updating this today.

**Comment by kelleyvice-msft** [comment]
I've updated this topic, and it should be live shortly. In addition to PowerShell example updates, I also made quite a few revisions in wording and formatting to improve readability.
