### ISSUE TITLE
Should this work in the new CORE powershell?

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/OfficeDocs-Enterprise#610]
Should this work in the new CORE powershell? I use V7.0.0 and get:
Connect-MsolService: The term 'Connect-MsolService' is not recognized as the name of a cmdlet,

**Comment by JoeDavies-MSFT** [comment]
@Ofer-Gal I am looking into the official position now.

**Comment by JoeDavies-MSFT** [comment]
@Ofer-Gal I just confirmed that the MSOnline module and "Msol" cmdlets are not supported by PowerShell Core. You need to run them from Windows PowerShell. I will update the Office 365 PowerShell articles for this in the near future. Thanks for your feedback.
