### ISSUE TITLE
What about the timeouts for MFA?

### ISSUE THREAD

**Issue by JessWonga** [MicrosoftDocs/OfficeDocs-Enterprise#611]
It would be useful to have MFA enabled account timeouts here as well. Especially if users do not tick the option to remember 'up to 60 days'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1570de51-50b1-d4cc-c1c7-832b3242ccb3
* Version Independent ID: f5250f91-0a48-20cf-8e2c-e2dc347edd88
* Content: [Session timeouts for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/session-timeouts#feedback)
* Content Source: [Enterprise/session-timeouts.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/session-timeouts.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@JessWonga - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com/forums/273493-office-365-admin)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
