### ISSUE TITLE
IdFix 

### ISSUE THREAD

**Issue by LeeHalford** [MicrosoftDocs/OfficeDocs-Enterprise#612]
In the "Office 365 IdFix Guide version 1.11.docx" and the same version of the app that comes with, it doesn't pick up the & in the Primary SMTP addresses. 

As per the article stated here:
https://cloudrun.co.uk/exchange-online/special-characters-in-upn-and-email-addresses-in-office-365-migrations/

Please update the IdFix Tool and documentation to reflect the notes in this article. 

[IdFix.zip](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/files/3884312/IdFix.zip)

**Comment by mypil** [comment]
@LeeHalford - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by LeeHalford** [comment]
https://docs.microsoft.com/en-us/office365/enterprise/prepare-for-directory-synchronization#2-directory-object-and-attribute-preparation

Specifically the proxyAddresses and the Invalid Characters.

This does not reflect the same as the instructions from the article from cloudrun.co.uk:
https://cloudrun.co.uk/exchange-online/special-characters-in-upn-and-email-addresses-in-office-365-migrations/

Lee Halford | Senior System Administrator | Infrastructure Services, Networking and Unified Communications | Ministry of Education | New Zealand

**Comment by JoeDavies-MSFT** [comment]
@LeeHalford Please submit this issue to https://github.com/microsoft/idfix/issues. The team that maintains the IdFix tool will address it. Thanks for letting us know.

**Comment by LeeHalford** [comment]
Hi @JoeDavies-MSFT,

I am logging an issue over there as well; to update the code. But the docs also need updating. Will the coding team do that as well? I note the code is at version 2.0.2.0. But that’s not coming up as the latest download, or being linked to on this docs website either.
It looks like there are two versions of the documentation floating around, one on here and one over there. Not understanding how the back end of the Microsoft Docs website works, if it’s changed over there will it be replicated back over here?

Kind regards,
Lee Halford
