### ISSUE TITLE
Documentation is wrong

### ISSUE THREAD

**Issue by SDedik** [MicrosoftDocs/OfficeDocs-Enterprise#614]
This page says:
To get full details of all the add-ins plus the assigned users and groups, pipe the output of the Get-OrganizationAddIn cmdlet to the Format-List cmdlet, as shown in the following example.
Get-OrganizationAddIn |Format-List

This does not work! Get-OrganizationAddIn retrieves only most generic AddIn properties like Name, ProductID. It does not return AssignedUser and AssignedGroups properties. They are only returned if Get-OrganizationAddIn cmdlet is run with -ProductId parameter.

This goes against PowerShell typical usage scenarios and makes cmdlets piping useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 680b165b-5c8b-66c4-f9f4-0e20b8666f19
* Version Independent ID: cb17922d-a250-90d8-79d9-ee4662208eec
* Content: [Use the Centralized Deployment PowerShell cmdlets to manage add-ins](https://docs.microsoft.com/en-us/office365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins?redirectSourcePath=%252farticle%252f94f4e86d-b8e5-42dd-b558-e6092f830ec9#feedback)
* Content Source: [Enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by get-itips** [comment]
Hello @SDedik 
Thanks for noticing, I could reproduce, I am proposing thru a PR, improving that Ps line to get full details of all add-ins in a one-liner.
Thank you

**Comment by mypil** [comment]
@SDedik -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/346f1c69f731d38c33546ebf443a48334a4cc9c1. 


Thank you for your contribution to make the docs better! Much appreciated!
