### ISSUE TITLE
40.100.*.* and 52.98.77 ranges are missing

### ISSUE THREAD

**Issue by vidarak** [MicrosoftDocs/OfficeDocs-Enterprise#617]
Name: hkg-efz.ms-acdc.office.com
Addresses: 40.100.2.114
40.100.54.18
40.100.2.98
52.98.77.98
Aliases: outlook.office365.com
outlook.ms-acdc.office.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@vidarak We typically don't publish all of the IP addresses for a FQDN such as outlook.office365.com. See https://techcommunity.microsoft.com/t5/Office-365-Networking/Why-are-some-Office-365-network-endpoints-provided-as-URLs-only/m-p/310490#M97 for more information, Thanks for your feedback.

**Comment by vidarak** [comment]
Why publish any IP ranges for this FQDN if the list can't be trusted?
