### ISSUE TITLE
Error: A SecurityTokenHandler is not registered to read security token ('Assertion', 'urn:oasis:names:tc:SAML:2.0:assertion')

### ISSUE THREAD

**Issue by RoyKimYYZ** [MicrosoftDocs/OfficeDocs-Enterprise#62]
Upon Azure AD authentication and then access to the SP Site, I get the SP error:
"ID4014: A SecurityTokenHandler is not registered to read security token ('Assertion', 'urn:oasis:names:tc:SAML:2.0:assertion'). "
Is it because I didn't execute properly the PowerShell script to add SAML 1.1 token issuance policy in Azure AD? How do I troubleshoot or verify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
The SAML 2.0 token issuance policy must first be removed prior to adding the SAML 1.1 token issuance policy.

**Comment by RoyKimYYZ** [comment]
Thanks for quick response. But I managed to resolve and my brain just got fried from it. Allow to explain for the benefit of others.
1) The SAML 2.0 token issuance policy was removed. But there was no 1.1 token issuance policy. 
2) I think that was because I inadvertently created the 1.1 token issuance policy more than once and then tried to add by running
Set-PolicyToServicePrincipal -policyId $policy.objectId -servicePrincipalId $objectid
3) And then assuming it all worked, if it was in this state, that's when I try to login into SP and get the securitytokenhandler error.
4) So I run Get-Policy and I see many policies with the same display name of SPSAML11. I believe by adding Set-PolicyToServicePrincipal this is where there is a conflict issue.
5) I use Remove-Policy -policyId <id> and remove all policies with the display nam eof SPSAML11
6) I execute 
$policy = Add-TokenIssuancePolicy -DisplayName SPSAML11 -SigningAlgorithm "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" -TokenResponseSigningPolicy TokenOnly -SamlTokenVersion "1.1"
Set-PolicyToServicePrincipal -policyId $policy.objectId -servicePrincipalId $objectid
7) Login to sharepoint via Azure AD Ent App
8) Success
Thanks everyone for their comments to help me figure it out.

**Comment by kaevans** [comment]
Thanks for your patience, @RoyKimYYZ. You're right, there can be only one token issuance policy, if there is another SAML 1.1 policy that must also first be removed before adding another (although an existing one should work just fine). Glad you got it working.

**Comment by RoyKimYYZ** [comment]
Thanks @kaevans + team for all your work. I'll be ready to demo this at the Toronto SharePoint User Group on Wed. https://bit.ly/2IhjMpT

**Comment by BilawalAsghar** [comment]
dear All,

when i execute command Get-Policy, it asks for credentials, i enter my hotmail credentials,which has rights on application and is owner, but it says, 
Invoke-RestMethod : {"odata.error":{"code":"Authentication_Unauthorized","message":{"lang":"en","value":"User was not found."}}}
At E:\Bilawal\MSGraphTokenLifetimePolicy.psm1:339 char:15
+     $result = Invoke-RestMethod @parameters -ContentType "application/json"
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

could you please help.

**Comment by kaevans** [comment]
@BilawalAsghar your comment does not apply to the original issue, please open a new issue in the future. 

The user configuring the SAML 1.1 policy must be a member of the directory and not a federated user. Create a new user in the directory with sufficient permissions and then configure an application while logged in as that user.

@denisebmsft  please close.

**Comment by BilawalAsghar** [comment]
@Kaevans oh my God, you make my day man, it worked as you mentioned. thanks alot.
