### ISSUE TITLE
Missing IP addresses for outlook.office365.com in "Office 365 URLs and IP address ranges"

### ISSUE THREAD

**Issue by vidarak** [MicrosoftDocs/OfficeDocs-Enterprise#620]
@JoeDavies-MSFT Your link doesn't answer my question. It speaks about some endpoints being provided as URLs only under the Default category. That's not what my case is about. For Exchange Online, ID 1 - Optimize Required, you have listed outlook.office365.com and a large number of IP addresses. What is the purpose of that list of IP addresses if it isn't complete and cannot be trusted? It appears to be the perfect way to give an inconsistent customer experience.

_Originally posted by @vidarak in https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/617#issuecomment-558696847_

**Comment by mypil** [comment]
@JoeDavies-MSFT - Can you please share your insights on this issue related to https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/617#issuecomment-558696847?

Thank you.

cc: @kenwith

**Comment by JoeDavies-MSFT** [comment]
@vidarak I have asked the product team who maintains these address to respond to your question. Thanks.

**Comment by JoeDavies-MSFT** [comment]
@vidarak The 40.100.*.* and 52.98.77 address ranges are included in the list of address ranges for outlook.office365.com.  40.100.*.* is included in 40.96.0.0/13 and 52.98.77 is included in 52.96.0.0/14. Thanks
