### ISSUE TITLE
Get-CsUserSession don't include QoEReport for MS Teams calls

### ISSUE THREAD

**Issue by MAAHamid** [MicrosoftDocs/OfficeDocs-Enterprise#621]
Hello Team,

Get-CsUserSession don't include QoEReport for MS Teams calls, Will it be available soon?

![image](https://user-images.githubusercontent.com/34710611/69720206-be6f2b80-111a-11ea-8acd-c9d6f4ba700f.png)

**Comment by mypil** [comment]
@MAAHamid - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@MAAHamid - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
