### ISSUE TITLE
Message Analyzer is an effective tool for troubleshooting network issues.

### ISSUE THREAD

**Issue by richard-artes** [MicrosoftDocs/OfficeDocs-Enterprise#622]
"Message Analyzer is an effective tool for troubleshooting network issues."

But Microsoft Message Analyzer (MMA) is being retired and its download packages removed from microsoft.com sites on November 25 2019.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b27f7338-33e6-d006-2038-068767ec0ea3
* Version Independent ID: f82bca63-1a2e-4cdf-6564-9eb6d281b892
* Content: [Network and migration planning for Office 365](https://docs.microsoft.com/en-gb/office365/enterprise/network-and-migration-planning#feedback)
* Content Source: [Enterprise/network-and-migration-planning.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/network-and-migration-planning.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@richard-artes -  Can you please share what specific issue you have with this doc? Or are you just giving a general user feedback?

If you have some issues with this doc, we would really appreciate if you are able to help by providing more details as to what should be edited and/or included. 

Thank you!

**Comment by richard-artes** [comment]
Yes, references to Microsoft Message Analyzer are no longer relevant and should be removed. If you click on the link to https://technet.microsoft.com/library/jj649776.aspx then you see a message saying this tool is no longer supported. The tool is no longer available for download so there is no point in mentioning it in the article. The whole sentance should be removed:

: Message Analyzer is an effective tool for troubleshooting network issues. Message Analyzer captures, displays, and analyzes protocol-based messaging traffic and system messages. Message Analyzer also lets you import, aggregate, and analyze data from log and trace files.

**Comment by mypil** [comment]
@richard-artes - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/e1116229cb2a8ee2ede2e3e06204fc1d1ddf19c6. 


Thank you for your contribution to make the docs better! Much appreciated!
