### ISSUE TITLE
collection Recycle Bin vs second stage recycle bin

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/OfficeDocs-Enterprise#625]
Is the 'collection Recycle Bin' the same as the second stage recycle bin? If not, what's the difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cefde46c-31d4-54ad-8c5c-44f23d8509b7
* Version Independent ID: ae9d8dc1-dafc-7bb6-b9de-c5ddc049dadf
* Content: [Office 365 SharePoint Online Data Deletion](https://docs.microsoft.com/en-us/office365/enterprise/office-365-sharepoint-online-data-deletion)
* Content Source: [Enterprise/office-365-sharepoint-online-data-deletion.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-sharepoint-online-data-deletion.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by markjjo** [comment]
@GiantCrocodile From https://support.office.com/article/restore-deleted-items-from-the-site-collection-recycle-bin-5fa924ee-16d7-487b-9a0a-021b9062d14b:

"When you delete items (including OneDrive for Business files) from a SharePoint site, they're sent to the site Recycle Bin (also called the first-stage Recycle Bin), where you can restore them if you need to. When you delete items from a site Recycle Bin, they're sent to the site collection Recycle Bin (also called the second-stage Recycle Bin)."

**Comment by GiantCrocodile** [comment]
I assume this means yes @markjjo? It would make sense to clarify this in the docs too to prevent confusion by using 2 terms for the same thing.
