### ISSUE TITLE
XML with Proxy is wrong

### ISSUE THREAD

**Issue by FrankCarius** [MicrosoftDocs/OfficeDocs-Enterprise#626]
The "system.net" should be at the sam elevel as "&lt;system.identityModel.services&gt;" and not inside of "&lt;system.identityModel.services&gt;".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626caf29-7e88-0b56-2013-5c5b7c2a5917
* Version Independent ID: 2376192f-793d-0166-46c7-870cd0c41abb
* Content: [Hybrid Modern Authentication overview and prerequisites for using it with on-premises Skype for Business and Exchange servers](https://docs.microsoft.com/en-us/office365/enterprise/hybrid-modern-auth-overview#do-you-meet-modern-authentication-prerequisites)
* Content Source: [Enterprise/hybrid-modern-auth-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/hybrid-modern-auth-overview.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by joinimran** [comment]
@FrankCarius Thank you for your feedback. As per system.net documentation it looks like the syntax is placed at the correct place. Please see https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/system-net-element-network-settings for more details.

Thanks 
Imran

**Comment by FrankCarius** [comment]
Not really. The XML in the doc has the hirarchy
<system.identityModel.services>
  <system.net>
    <defaultProxy>

And <system.identityModel.services>  is below <configuration>  A normal reader would now try to add the setting at:

<configuration>
  <system.identityModel.services>
    <system.net>
      <defaultProxy>

But if you check https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/system-net-element-network-settings then is should be

<configuration>
    <system.net>
      <defaultProxy>

My customer had it at 

<configuration>
  <system.identityModel.services>
    <system.net>
      <defaultProxy>
and it was not working. Removing the "  <system.identityModel.services>" solved the problem.
Or better.  Replace <system.identityModel.services> with <configuration>

i hope i explained it better now.

**Comment by joinimran** [comment]
@FrankCarius Can you please cofirm that removing the <system.net> works as expected and solved the issue.

**Comment by FrankCarius** [comment]
Sorry for the bad formatting. Github remove some of the `<>`-brackets . I try to write it again and hope is it readable now..

`The XML in the doc has the hierarchy
<system.identityModel.services>
  <system.net>
    <defaultProxy>

And <system.identityModel.services>  is below the <configuration>  
My customer added it like that:

<configuration>
  <system.identityModel.services>
    <system.net>
      <defaultProxy>

But if you check https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/system-net-element-network-settings then is should be direct below configuratoin

<configuration>
    <system.net>
      <defaultProxy>

My customer had a configuration with 
<configuration>
  <system.identityModel.services>
    <system.net>
      <defaultProxy>
and it was not working. 
Removing the "<system.identityModel.services>" solved the problem.
Or better.  Replace <system.identityModel.services> with <configuration>

i hope i explained it better now.
`

**Comment by FrankCarius** [comment]
Sorry for the bad formatting. Github remove some of the `&lt;&gt;`-brackets . I try to write it again and hope is it readable now..

`The XML in the doc has the hierarchy
&lt;system.identityModel.services&gt;
  &lt;system.net&gt;
    &lt;defaultProxy&gt;

And &lt;system.identityModel.services&gt;  is below the &lt;configuration&gt;  
My customer added it like that:

&lt;configuration&gt;
  &lt;system.identityModel.services&gt;
    &lt;system.net&gt;
      &lt;defaultProxy&gt;

But if you check https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/system-net-element-network-settings then is should be direct below configuratoin

&lt;configuration&gt;
    &lt;system.net&gt;
      &lt;defaultProxy&gt;

My customer had a configuration with 
&lt;configuration&gt;
  &lt;system.identityModel.services&gt;
    &lt;system.net&gt;
      &lt;defaultProxy&gt;
and it was not working. 
Removing the "&lt;system.identityModel.services&gt;" solved the problem.
Or better.  Replace &lt;system.identityModel.services&gt; with &lt;configuration&gt;

i hope i explained it better now.
`

**Comment by mypil** [comment]
@FrankCarius - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/f665d3e7916b846aafe4ccd1ded789e28876bdc3. 


Thank you for your contribution to make the docs better! Much appreciated!
