### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-Enterprise#627]
Does this work despite dependencies?  For example, in the web admin interface, if you try to assign Office web to an account (E3 license) without SharePoint, you get an error, "to assign a license that contains Office for the web, you must also assign one of the following service plans: SharePoint Online (Plan 2), SharePoint Online Kiosk, SharePoint Online (Plan 1)."  So, am I able to bypass this if assigning Office web without SharePoint (i.e. using -DisabledPlans for SharePoint) using PowerShell?

Also, I've been told by MS support that OneDrive does not work if SharePoint isn't also assigned.  There may be other dependencies I'm unaware of.  

If this does not work where there are dependencies in play, could you mention that?  Better yet, a list of all the services that are dependent on other services would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add5965d-008c-f030-45df-653ce3e9a1b3
* Version Independent ID: 6646ad46-d40d-fee3-5ca1-3272d3b3e4fb
* Content: [Disable access to services with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/disable-access-to-services-with-office-365-powershell)
* Content Source: [Enterprise/powershell/disable-access-to-services-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/disable-access-to-services-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Canis-Lupis I added a note at the top of the article about service dependencies when attempting to disable a service. I will add your request to publish a list of service dependencies to our documentation backlog. Thanks so much for letting us know about this.
