### ISSUE TITLE
Automated scripts using account with MFA enabled

### ISSUE THREAD

**Issue by NWH-SAmin5** [MicrosoftDocs/OfficeDocs-Enterprise#628]
Is there any way to run scheduled tasks using accounts enabled with MFA? If yes what is best practice.
Everywhere I see suggestion to create account with MFA disabled. What if Organizations are very strict with not creating such account. Please add suggestions on these documents for Scheduled/Automated scripts using account with MFA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f318af5-7da8-daec-d038-7bca3d4cabf8
* Version Independent ID: 7cb9bf9d-5b01-7cbd-fa54-cb9847b61fc2
* Content: [Manage Skype for Business Online with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell)
* Content Source: [Enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@NWH-SAmin5 Service principals are the best practice for script authentication in Azure AD, which is used by Office 365. See https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-3.1.0 for the details. Thanks for your comment.

**Comment by NWH-SAmin5** [comment]
@JoeDavies-MSFT Are you suggesting to use Azure Service Principals for writing Skype For Business Online powershell scripts for automating tasks like assigning Teams Messaging Policy for new users add to the tenant? Any pointers for this please?

**Comment by tbogle** [comment]
I've been unsuccessful in finding a way to make this work with Service Principles.  I followed instructions on the link you suggested, but the new-csonlinesession command doesn't appear to accept any form of a credential other than a traditional username/password.  Can you provide a link to documentation showing how this our work specifically with Skype For Businessness Online?
