### ISSUE TITLE
Links in 'Security & Compliance Center PowerShell' section

### ISSUE THREAD

**Issue by JMGEHMAN** [MicrosoftDocs/OfficeDocs-Enterprise#63]
Both links in the 'Security & Compliance Center PowerShell' section of the doc refer to Exchange Online, which seems incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 093230b9-42d4-1efa-32dd-ec05d309b38c
* Version Independent ID: a5658dff-1925-d15f-863c-26dd9d1c28d5
* Content: [Cmdlet references for Office 365 services](https://docs.microsoft.com/en-us/office365/enterprise/powershell/cmdlet-references-for-office-365-services)
* Content Source: [Enterprise/powershell/cmdlet-references-for-office-365-services.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/cmdlet-references-for-office-365-services.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@JMGEHMAN I updated the links Thanks for letting us know.
