### ISSUE TITLE
We have to give more detail information for each IDs with no description.

### ISSUE THREAD

**Issue by Altemir** [MicrosoftDocs/OfficeDocs-Enterprise#630]
My customers want to know what these URL's are used for. Please check and update this document easier to understand.

**Comment by mypil** [comment]
@Altemir - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@Altemir - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
