### ISSUE TITLE
Will O365 multi geo license ever be available via CSP ?

### ISSUE THREAD

**Issue by al128128** [MicrosoftDocs/OfficeDocs-Enterprise#635]
Please make Office 365 Multi-Geo license available via CSP.

**Comment by mypil** [comment]
@al128128 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by al128128** [comment]
Hi,

 

This location:

 

https://docs.microsoft.com/en-us/office365/enterprise/office-365-multi-geo

**Comment by mypil** [comment]
@al128128 - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Office 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.

I found one UserVoice entry that is similar to this feature request - https://office365.uservoice.com/forums/264636-general/suggestions/37838308-add-multi-geo-to-csp. You may want to add in your comments or you can upvote.

Thank you for your contribution to make the docs better! Much appreciated!
