### ISSUE TITLE
Showing wrong object ID?  

### ISSUE THREAD

**Issue by moojjoo** [MicrosoftDocs/OfficeDocs-Enterprise#64]
Please see my blog post as I am trying to get an answer --- (THIS HAS BEEN FIGURED OUT - I put in https://projects-dev02.domain.com/ to fix the issue for the Identifier (Entity ID) [http://moojjoo.blogspot.com/2018/05/auzre-ad-error_36.html](http://moojjoo.blogspot.com/2018/05/auzre-ad-error_36.html) 

However, I have the same URL for the reply and I am getting the following error:
Request Id:  8d32161a-39cc-49d4-b42d-cc48669e0700 
 
Correlation Id:  9acb6832-6da0-407c-929f-48a72964e249 

Timestamp:  2018-05-18T23:20:52Z 
 
Message:  AADSTS50011: The reply uri specified in the request is not a valid URL. Allowed schemes: 'http,https'

**Comment by moojjoo** [comment]
Is there anybody out there?

**Comment by kaevans** [comment]
@moojjoo Sorry that you have run into so many issues with your configuration. 

I again tried the instructions on a new web application and provider and it worked as documented. However, my test shows "/_trust/default.aspx" appended to the replyURL, where this was not stated in the documentation. Can you please try with the "/_trust/default.aspx" appended?  Here is a screen shot of my most recent test for clarification:

![image](https://user-images.githubusercontent.com/7107098/40321973-7010d3d2-5cf6-11e8-819e-54568cdf46f4.png)

This forum is to report issues with the technical accuracy of the document referenced, not a general support forum. While we try to address issues here in a timely manner, we do not offer a time guarantee on how quickly we can respond. If you require immediate assistance, please contact Microsoft Support at https://support.microsoft.com/contactus/.

**Comment by moojjoo** [comment]
@kaevans please close we got this working, we did what @RoyKimYYZ did.

**Comment by kaevans** [comment]
Updated script to avoid issues as noted, thank you @moojjoo! [PR 78](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/78)
