### ISSUE TITLE
Error related to the Referrer instructions

### ISSUE THREAD

**Issue by spplante** [MicrosoftDocs/OfficeDocs-Enterprise#646]
As documented in the HTTP protocol, the "referrer" header specified in this article should actually be "referer" with one "r" instead of two, otherwise the GET request will ignore the header. That being said, the following paragraph should be modified :

"If you use a network tool such as Fiddler to test your assets outside of rendering the asset from a SharePoint page, you must manually add the referrer header “Referrer: https://yourdomain.sharepoint.com” to the GET request where the URL is the root URL of your SharePoint Online tenant."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97626653-f653-d954-7a39-e5beac635e18
* Version Independent ID: 86f7d0b5-3a63-7511-0fc6-e3d98bea4b74
* Content: [Use the Office 365 Content Delivery Network (CDN) with SharePoint Online](https://docs.microsoft.com/en-us/office365/enterprise/use-office-365-cdn-with-spo#feedback)
* Content Source: [Enterprise/use-office-365-cdn-with-spo.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/use-office-365-cdn-with-spo.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
Nice catch, @spplante. Thanks much! I'll fix this ASAP.

**Comment by kelleyvice-msft** [comment]
Updated, should be live in ~15 minutes.
