### ISSUE TITLE
Unhelpful link

### ISSUE THREAD

**Issue by JimTheFrog** [MicrosoftDocs/OfficeDocs-Enterprise#648]
This page says "For more information on expedited de-provisioning, see Cancel Office 365" but there's nothing on the linked page about expedited de-provisioning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcee03fe-5fcb-8f42-e391-a0aac5c2f597
* Version Independent ID: 04c1b86d-c058-92c9-eb12-cc3f3b409044
* Content: [Data Retention, Deletion, and Destruction in Office 365](https://docs.microsoft.com/en-us/office365/enterprise/office-365-data-retention-deletion-and-destruction-overview#feedback)
* Content Source: [Enterprise/office-365-data-retention-deletion-and-destruction-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-data-retention-deletion-and-destruction-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by joinimran** [comment]
@JimTheFrog Looks like the link is working. Can you please double check.

**Comment by JimTheFrog** [comment]
@joinimran I didn't say the link doesn't work. The destination page (https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/cancel-your-subscription) worked fine for me. 

My point is that there's nothing on the destination page about expedited de-provisioning. You can't say "for more information on X, see <page>" when <page> doesn't even mention X.

It seems there are three solutions:
1) Update the destination page so it actually talks about expedited de-provisioning.
2) Link to a different page that actually talks about expedited de-provisioning.
3) Remove the unhelpful link.

**Comment by joinimran** [comment]
Thank you so much for sharing the details @JimTheFrog 

I got your point very clearly and I am on it. 

Thank you.

**Comment by mypil** [comment]
@JimTheFrog - From our understanding, the issue you raised has been fixed based on the author's https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/681#issuecomment-580814792  so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
