### ISSUE TITLE
Missing IP address

### ISSUE THREAD

**Issue by jimthemcp** [MicrosoftDocs/OfficeDocs-Enterprise#649]
there appears to be a missing IP address for *.protection.outlook.com
40.87.84.197
Can someone confirm and update? thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@jimthemcp This issue is being discussed internally at Microsoft.

**Comment by darylzero** [comment]
It's March 26th, have you finished discussing this yet!?
Why is it so hard to get a list of IP's from you guys?  People have been asking for these IP's for over a year all over the web.
