### ISSUE TITLE
This documentation should discuss how to connect with MFA.

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-Enterprise#65]
e.g.

$session = New-CsOnlineSession -UserName mike@tenant.onmicrosoft.com
Import-PSSession $session

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f318af5-7da8-daec-d038-7bca3d4cabf8
* Version Independent ID: 7cb9bf9d-5b01-7cbd-fa54-cb9847b61fc2
* Content: [Manage Skype for Business Online with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell)
* Content Source: [Enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell.md)
* Service: **o365-administration**
* Product: **unspecified**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Mike-Crowley You are correct and the oversight has been addressed. Thanks for letting us know.
