### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by mmascolino** [MicrosoftDocs/OfficeDocs-Enterprise#651]
Can you actually do this an Exchange Admin?  The PowerShell module says Company i.e. Global Admin and if you go over to this page:
https://docs.microsoft.com/en-us/office365/admin/manage/manage-deployment-of-add-ins?redirectSourcePath=%252farticle%252f737e8c86-be63-44d7-bf02-492fa7cd9c3f.aspx&view=o365-worldwide
about the admin center, it too mentions Global Admin.

So is it possible to do any of this as Exchange Admin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 680b165b-5c8b-66c4-f9f4-0e20b8666f19
* Version Independent ID: cb17922d-a250-90d8-79d9-ee4662208eec
* Content: [Use the Centralized Deployment PowerShell cmdlets to manage add-ins](https://docs.microsoft.com/en-us/office365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins)
* Content Source: [Enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by get-itips** [comment]
Hello @mmascolino 
I tested in my lab, assigning a regular user Exchange Admin Role and I was able to follow this instructions with no issues.

Hope this information helps you,

**Comment by mypil** [comment]
@mmascolino - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by get-itips. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
