### ISSUE TITLE
Does this have Azure B2B API at play?

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/OfficeDocs-Enterprise#652]
Is Azure B2B API used when inviting guests to access? I got to this section of documentation by clicking a link found in https://docs.microsoft.com/en-us/sharepoint/create-b2b-extranet. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2296f91f-ac66-7d38-1aae-479bbcef9b87
* Version Independent ID: db8bfc32-701d-c245-08ea-ec864da86c9d
* Content: [Collaborate with guests in a site](https://docs.microsoft.com/en-us/Office365/Enterprise/collaborate-in-a-site)
* Content Source: [Enterprise/collaborate-in-a-site.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/collaborate-in-a-site.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@jebalert if you invite guests to the Office 365 group, it uses Azure AD B2B. If you invite users separately to the SharePoint site, it doesn't use Azure B2B unless you've configured [SharePoint and OneDrive integration with Azure AD B2B](https://docs.microsoft.com/sharepoint/sharepoint-azureb2b-integration-preview).

**Comment by mypil** [comment]
@jebalert - From our understanding, the issue you raised has been answered by MikePlumleyMSFT so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
