### ISSUE TITLE
Firewall Rule Direction

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/OfficeDocs-Enterprise#653]
Though most of the IP Address/URL mentioned in the article would be considered as destination and would need only Outbound firewall rule. But Few IP Addresses/URL's (e.g. EOP) would need Inbound as well as outbound firewall rule for port 25. Can we add some details on direction part to provide more clarity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@3novsan I have passed your request to the product team that manages the lists of endpoints for their consideration in future updates. Thanks for your feedback.

**Comment by danmyhre** [comment]
Any update?  Why was this closed?  This is a great ask.
