### ISSUE TITLE
Could list the registry key in question instead of just mentioning it in passing

### ISSUE THREAD

**Issue by oddhair** [MicrosoftDocs/OfficeDocs-Enterprise#654]
I'm sure I can find the ADAL registry key but why do you mention the key on this page without specifying where it is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059ed9a7-ea75-0fa3-e246-4ad1f1b0c5bc
* Version Independent ID: d7598f96-3158-09ee-024a-6175599718cd
* Content: [How modern authentication works for Office 2013 and Office 2016 client apps](https://docs.microsoft.com/en-us/office365/enterprise/modern-auth-for-office-2013-and-2016?redirectSourcePath=%252farticle%252fhow-modern-authentication-works-for-office-2013-and-office-2016-client-apps-e4c45989-4b1a-462e-a81b-2a13191cf517)
* Content Source: [Enterprise/modern-auth-for-office-2013-and-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/modern-auth-for-office-2013-and-2016.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by RAJU2529** [comment]
I will give the registry key

**Comment by RAJU2529** [comment]
@oddhair . type the following lines in cmd with administartor rights


**REG ADD HKCU\SOFTWARE\Microsoft\Office\16.0\Common\Identity /v EnableADAL /t REG_DWORD /d 1**

**REG ADD HKCU\SOFTWARE\Microsoft\Office\16.0\Common\Identity /v Versioon /t REG_DWORD /d 1**

**Comment by MSFTTracyP** [comment]
Updates should be coming. Thank you.

**Comment by VLG17** [comment]
@RAJU2529 "Modern authentication is already enabled for Office 2016 clients, **you do not need to set registry keys for Office 2016.**"

@oddhair I will add the location of the keys that need to be added for Office 2013 clients

**Comment by mypil** [comment]
@oddhair - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/90749f8ad511e26c2b30bd8abf6f026c24e0ead2. 


Thank you for your contribution to make the docs better! Much appreciated!
