### ISSUE TITLE
Instructions are confusing

### ISSUE THREAD

**Issue by agupta-au** [MicrosoftDocs/OfficeDocs-Enterprise#655]
The page on Step 1 redirects to instructions on installing the AzureAD module (and MSOL) but nowhere does it mention that both modules are required.

I think this should be made explicit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b245b5d3-be8c-00a5-c373-05eb5d74ff7d
* Version Independent ID: d7020de2-b00a-6a9d-e062-c76052df17f7
* Content: [Turn off directory synchronization for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/turn-off-directory-synchronization#feedback)
* Content Source: [Enterprise/turn-off-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/turn-off-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by get-itips** [comment]
Hello @agupta-au 

Actually, all cmdlets that include _Msol_ are from the _Azure Active Directory Module for Windows PowerShell_ so that is the only one module required to run that cmdlet.

I will create a pull request to propose changes to the article, and it will be reviewed by the author of the article.

Thank you

**Comment by mypil** [comment]
@agupta-au -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/5e03dea5063615d1d6326859edf3b0c557fbee29. 


Thank you for your contribution to make the docs better! Much appreciated!
