### ISSUE TITLE
Working with connected office groups

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-Enterprise#66]
It would be great if you would provide some examples of working the members of the Office Groups that are connected to SPO sites.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0096189e-b3e3-e26e-2d55-711323ab2a5f
* Version Independent ID: 50d5393d-2dac-869a-8ade-dc2fc3d7a4cf
* Content: [Manage SharePoint Online users and groups with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-sharepoint-users-and-groups-with-powershell)
* Content Source: [Enterprise/powershell/manage-sharepoint-users-and-groups-with-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/manage-sharepoint-users-and-groups-with-powershell.md)
* Service: **o365-administration**
* Product: **unspecified**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
Thanks for the suggestion, Dean! We'll look into this.

**Comment by JoeDavies-MSFT** [comment]
@DeanGross Hi Dean, I am looking into this and have added it to my work items going forward. Thanks for letting us know this was needed. Joe
