### ISSUE TITLE
Outlook App for iOS/Android IP range

### ISSUE THREAD

**Issue by MumpekPumpa** [MicrosoftDocs/OfficeDocs-Enterprise#661]
Should the provided list also include the IP ranges for Outlook App for iOS/Android?

We're seeing connections from 40.101.0.0/14 and 52.97.0.0/14 which are not on the list. Could you please verify and provide the full list used by Outlook App for mobile devices (we're actually using on-premises Exchange).

**Comment by mypil** [comment]
@MumpekPumpa - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by MumpekPumpa** [comment]
Sure, I'm referring to: https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges.

**Comment by mypil** [comment]
@MumpekPumpa - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@LauraWi - Can you please share your insights on this issue? This is based on the below doc details:

Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?source=docs#feedback)
Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)


Thank you.

cc: @kenwith

**Comment by LauraWi** [comment]
The info in this topic is auto-generated from the same tool that feeds the REST API with this info. I will follow up with engineering to understand if it should include this.

**Comment by LauraWi** [comment]
Hi @MumpekPumpa Per engineering, these ranges are on the list. The topic lists only specific IPs for Office 365 servers you should route directly to. Here is the FAQ that addresses your question. https://docs.microsoft.com/en-us/office365/enterprise/managing-office-365-endpoints#i-see-network-requests-to-ip-addresses-not-on-the-published-list-do-i-need-to-provide-access-to-them
