### ISSUE TITLE
Re-evaluate article effectiveness

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/OfficeDocs-Enterprise#662]
Last update was 1/2017 - Can this article be re-evaluated based on the newer versions of ProPlus. Consider including article detail that breaks down the probable range of connection count based on the Office application... i.e. Outlook, Teams, etc. This will allow better design for customers that know their Office application adoption.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 126f74f1-8e44-1409-049b-df8903412ef2
* Version Independent ID: f815f108-a9ff-8f4c-2a11-0c3073451c50
* Content: [NAT support with Office 365](https://docs.microsoft.com/en-us/office365/enterprise/nat-support-with-office-365)
* Content Source: [Enterprise/nat-support-with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/nat-support-with-office-365.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@CHDAFNI-MSFT - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

**Comment by mypil** [comment]
@kelleyvice-msft - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by kelleyvice-msft** [comment]
@CHDAFNI-MSFT - This is certainly a valid ask. I will look at what would be required to update connection data for the current client version. Thanks!

**Comment by mypil** [comment]
@CHDAFNI-MSFT - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author kelleyvice-msft  so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
