### ISSUE TITLE
Second section title

### ISSUE THREAD

**Issue by mmascolino** [MicrosoftDocs/OfficeDocs-Enterprise#663]
Shouldn't the second section be called something like "Use the Microsoft Online Services Module for Windows PowerShell"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3baa87d3-9496-9bd2-739f-a136c1daacf3
* Version Independent ID: cfcd455b-36b0-53d6-80b4-805695919742
* Content: [View licenses and services with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-licenses-and-services-with-office-365-powershell)
* Content Source: [Enterprise/powershell/view-licenses-and-services-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/view-licenses-and-services-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@mmascolino Thank you for the feedback. The module is called Azure AD module(Msonline) - You can also check the link for more information- https://docs.microsoft.com/en-us/powershell/azure/active-directory/install-msonlinev1?view=azureadps-1

Hope this helps

Thanks
Sri

**Comment by mypil** [comment]
@mmascolino - Thank you for submitting this feedback.

From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
