### ISSUE TITLE
Correct typing of MFA

### ISSUE THREAD

**Issue by marconipoveda** [MicrosoftDocs/OfficeDocs-Enterprise#664]
Hi everyone.

I've noted that in this page we are refering to MFA as _multifactor authentication_ but in the rest of documentation pages the word **multifactor** has a hypen in between.

I would like to suggest the use of **multi-factor authentication**.

Best regards.

**Comment by marconipoveda** [comment]
Sorry I'm having problems with my first issue. I'm refering to this page.

Enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell.md

**Comment by mypil** [comment]
@marconipoveda - Thank you for submitting feedback. 

PR #677  has been created to fix and close this issue once the PR is merged.


We appreciate your contribution to make the docs better! Keep it coming!
