### ISSUE TITLE
Domain names and IP ranges relationship

### ISSUE THREAD

**Issue by cat-mucius** [MicrosoftDocs/OfficeDocs-Enterprise#665]
What's the relationship between the DNS domain names and the subnets specified near them? Do they complement one another? Or this means that the DNS names resolve to IP addresses in these subnets?

For instance:
*.protection.outlook.com
40.92.0.0/15, 40.107.0.0/16, 52.100.0.0/14, 52.238.78.88/32, 104.47.0.0/17, 2a01:111:f403::/48

Does this mean that any hosts under *.protection.outlook.com will always resolve to these 6 ranges? Or this means that I must open access on my firewall/proxy BOTH to the hosts under *.protection.outlook.com AND to all these ranges?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by LauraWi** [comment]
Hi @cat-mucius Does this FAQ entry address your question: https://docs.microsoft.com/en-us/office365/enterprise/managing-office-365-endpoints#some-office-365-urls-point-to-cname-records-instead-of-a-records-in-the-dns-what-do-i-have-to-do-with-the-cname-records

**Comment by cat-mucius** [comment]
Thanks, but not really - I wasn't asking about CNAMEs. But this one maybe does:

>> "When using a PAC file for direct egress of vital Office 365 network traffic, you also need to allow connectivity to the IP addresses behind these URLs on your network perimeter firewall. This is done by fetching the IP addresses for the same Office 365 endpoint categories as specified in the PAC file and creating firewall ACLs based on those addresses."

So as I understand:
- If I don't use direct access (all requests pass through proxy), it's enough to configure the proxy to allow traffic to *.protection.outlook.com. Hosts under this domain will always resolve to IP addresses in these ranges, so there's NO NEED to allow explicitly access to these ranges on the proxy.
- However, if I route traffic there directly via a firewall (which cannot be set with wildcard domain such as *.protection.outlook.com as destination), then I need to configure the firewall to allow traffic to these subnets:
40.92.0.0/15, 40.107.0.0/16, 52.100.0.0/14, 52.238.78.88/32, 104.47.0.0/17, 2a01:111:f403::/48

Is my understanding correct?

**Comment by LauraWi** [comment]
Since I'm monitoring this topic for a direct who's on leave (I am not a networking SME), I posed this one to my engineering contacts for this space. His answer: "Yes, that’s the right idea. The underlying assumption here, which is pretty common in enterprises who use proxy servers, is that the client is blocked from direct Internet access by an IP firewall and the proxy server is not blocked. This means that by forwarding the traffic to the proxy server and if the proxy server allows the connection, there’s no additional IP firewall ACL’s required."

**Comment by cat-mucius** [comment]
Ok, Laura, thank you!

**Comment by nitvit610** [comment]
We've run in to this same issue just yesterday.
We added all of the IPs listed on our firewall for Exchange Online, however when running a connector validation, it was connecting from xxxxxxxxxx.eop-gbr01.prod.protection.outlook.com (185.20.130.66) which was coming from a completely different IP address than what is listed on this page.

**Comment by cat-mucius** [comment]
@nitvit610, that's strange, because according to https://bgp.he.net/ip/185.20.130.66, the IP address belongs to some telecommunications company "[ITS Technology Group Limited](https://www.itstechnologygroup.com)". They don't offer CDN, so it doesn't seem likely that Microsoft service would be frontend by their IP.

Maybe it's your some local DNS issue?

**Comment by nitvit610** [comment]
@cat-mucius potentially. I'm not a network engineer myself so this is only what they told me (and what I could see from the error message).
I'd been told that we'd added all the IPs under the Exchange Online section, yet still weren't able to connect.

We ended up fixing it by opening ports 25 & 443 to all IP ranges but obviously this is not ideal.

**Comment by mymebenha** [comment]
So what's the conclusion?  Do we need to allow both the wildcard domain names and the IP addresses or is it enough to allow the wildcard FQDNs?

**Comment by cat-mucius** [comment]
If I understood @LauraWi 's response correctly, FQDNs are enough (accessed via proxy).
My experience so far supports that, Office sites worked pretty well, but I didn't test their functionality in depth, just "touched the surface".
