### ISSUE TITLE
Ranges of Azure tenants?

### ISSUE THREAD

**Issue by cat-mucius** [MicrosoftDocs/OfficeDocs-Enterprise#667]
Do any of these IP ranges include ones that contain public IP addresses allocated to 3rd-parties, such as VMs or webapps run in Azure by companies other than Microsoft?

If I allow my network to communicate with these ranges, will it be possible to reach some resource (server, application, webservice) rented by someone else at Microsoft datacenter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by LauraWi** [comment]
These are Microsoft internal.

**Comment by cat-mucius** [comment]
Well, not exactly.
For instance, the "Common" section lists the *.msappproxy.net domain in the Allow & Required categories, and *.cloudapp.net in Default & Optional. I know for fact that 3rd-party resources can be placed under these domains, because I placed some. :-)  When you publish an application using Azure AD Application Proxy, it gets an hostname under *.cloudapp.net, with another hostname under *.msappproxy.net as a CNAME.
