### ISSUE TITLE
Close parenthesis on the "See Also" page

### ISSUE THREAD

**Issue by calebcoverdale** [MicrosoftDocs/OfficeDocs-Enterprise#669]
There is a ")" on the See Also section for the link "Create a secure guest sharing environment)"
I don't think that needs to be there. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7df65c5-ea03-f39b-ea7f-14809c15abc1
* Version Independent ID: 7ed5fef7-51f8-1b6b-e220-49dcc59e98c2
* Content: [Collaborate with guests in a team](https://docs.microsoft.com/en-us/Office365/Enterprise/collaborate-as-a-team#feedback)
* Content Source: [Enterprise/collaborate-as-a-team.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/collaborate-as-a-team.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@calebcoverdale - Thank you for pointing this out.

PR #678  has been created to fix and close this issue once the PR is merged.


We appreciate your contribution to make the docs better! Keep it coming!
