### ISSUE TITLE
Additional clarification please

### ISSUE THREAD

**Issue by USAGonzo00** [MicrosoftDocs/OfficeDocs-Enterprise#670]
When you state that the eDiscovery data location is in the US for Canadian mailboxes (for example), this does not explain what this means.  If the data resides in the US, it may be considered subject to production.  So some entities feel that eDiscovery is creating risk by using the US data centers.  Please clarify what data is stored in the US, what state the data is in (such as the fact that the data may be stored in an encrypted blob), and how long that data resides there.  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e08a752-f73a-439f-728f-a8fc7e8952af
* Version Independent ID: a38b9339-689c-13b8-1bcd-9ac203dbc487
* Content: [Configure Office 365 Multi-Geo eDiscovery](https://docs.microsoft.com/en-us/office365/enterprise/multi-geo-ediscovery-configuration#feedback)
* Content Source: [Enterprise/multi-geo-ediscovery-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/multi-geo-ediscovery-configuration.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by VLG17** [comment]
@USAGonzo00 [This article](https://docs.microsoft.com/en-us/microsoft-365/compliance/export-a-content-search-report#whats-included-in-the-report) on what's included in the Content Search report will tell you what eDiscovery data is stored.

The above mentioned article also mentiones where the data is temporarily (two weeks) stored:

> When you export a report, **the data is temporarily stored in a unique Azure Storage area in the Microsoft cloud** before it's downloaded to your local computer. Be sure that your organization can connect to the endpoint in Azure, which is *.blob.core.windows.net (the wildcard represents a unique identifier for your export). **The search results data is deleted from the Azure Storage area two weeks after it's created.**

You could also refer to [the compliance offerings](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-home), should you need to demonstrate adherence to a certain standard.

**Comment by mypil** [comment]
@USAGonzo00 -  Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17 so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
