### ISSUE TITLE
Extra "h" in link

### ISSUE THREAD

**Issue by githubsteveb** [MicrosoftDocs/OfficeDocs-Enterprise#672]
Extra "h" in link: "hhttps://aka.ms/monitorconnectivity365"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1ea02fa-82cc-bbe7-4642-c548115f5ddf
* Version Independent ID: b5cd59f9-f9a3-43c2-65bf-80b7e509b4e2
* Content: [Monitor Office 365 connectivity](https://docs.microsoft.com/en-us/office365/enterprise/monitor-connectivity)
* Content Source: [Enterprise/monitor-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/monitor-connectivity.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@githubsteveb - Thank you for pointing this out.

PR #673 has been created to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
