### ISSUE TITLE
Reserve space for top section in modern page

### ISSUE THREAD

**Issue by rpskumar** [MicrosoftDocs/OfficeDocs-Enterprise#682]
"Reserve corresponding space for asynchronously rendering media or visual elements to avoid skipped frames and stuttering (also known as jank)"
My Communication site Home page has 2 sections layout. Section 1 layout is full width style with 1 custom App to display Hero style news  web part(custom SPFx web part to display 5 images and link to News from SharePoint list. The images are less than 300 KB. 
Section 2 has 3 columns layout with 3 custom SPfx web parts. 2 SPFx Image web part and 1 event web part. 
I do not have performance issue in overall page load (5 - 7 seconds). However section 2 web parts appear on page first and then take a second to load section 1. From user view , Section 2 web parts loads, then all of sudden section 1 web part is appearing by pushing down section 2. 
How to avoid the flickering effect on page? Is there any way to sequence the section loading or reserve space for section 1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1474f9d0-2267-4bd7-e28d-6ff2c6761dbc
* Version Independent ID: cf7dd353-9b01-7087-66ac-b7c793ffa085
* Content: [Optimize web part performance in SharePoint Online modern site pages](https://docs.microsoft.com/en-us/office365/enterprise/modern-web-part-optimization#feedback)
* Content Source: [Enterprise/modern-web-part-optimization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/modern-web-part-optimization.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@rpskumar - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
