### ISSUE TITLE
Microsoft 365 > Sharing - Not correct

### ISSUE THREAD

**Issue by nikmanzotti** [MicrosoftDocs/OfficeDocs-Enterprise#686]
There is no more Security and Compliance link in the Office 365 admin section.
See a similar issue for the "Microsoft Teams guest access checklist" docs:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3812

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bb31720-7494-ab3f-6a3d-5c395649e75d
* Version Independent ID: 81c36ae8-fbaa-c411-4bd2-a4db98e249e1
* Content: [Microsoft 365 guest sharing settings reference](https://docs.microsoft.com/en-us/office365/enterprise/microsoft-365-guest-settings#feedback)
* Content Source: [Enterprise/microsoft-365-guest-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/microsoft-365-guest-settings.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@nikmanzotti I updated the article with new navigation for several steps.

**Comment by mypil** [comment]
@nikmanzotti - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
