### ISSUE TITLE
False Positive Status Definition

### ISSUE THREAD

**Issue by adagioajanes** [MicrosoftDocs/OfficeDocs-Enterprise#687]
The only item that Status Definitions seems to be missing is "False positive". I know it's self explanatory. But, its useful to document for people developing around the service communications api. And the service communications api page doesn't list the status definitions that can come in messages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd2a834a-296b-1c7d-7358-6f6a19f8f3c3
* Version Independent ID: 9ab6adbe-c651-d833-f395-64b7cddb2dd2
* Content: [How to check Office 365 service health](https://docs.microsoft.com/en-us/office365/enterprise/view-service-health#feedback)
* Content Source: [Enterprise/view-service-health.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/view-service-health.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by VLG17** [comment]
@adagioajanes I see the article contains already the missing information, so i guess it has been updated since you requested it.

![image](https://user-images.githubusercontent.com/41186174/74311448-2cb9a680-4d78-11ea-809b-fbaf84a2e884.png)

**Comment by mypil** [comment]
@adagioajanes - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
