### ISSUE TITLE
Azure AD support for SAML 1.1 is still shows a Preview release, It is Public?

### ISSUE THREAD

**Issue by balajimadgundi** [MicrosoftDocs/OfficeDocs-Enterprise#69]
Azure AD support for SAML 1.1 is still shows a Preview release, It is Public? If it not, then when is the tentative date and how we will be notified about this?

**Comment by kaevans** [comment]
Apologies for the delay. The underlying protocol aspects are fully supported. We are working to improve the configuration experience, but the steps described in this article will continue to work. Subscribe to the [EMS Blog](https://cloudblogs.microsoft.com/enterprisemobility/) for updates. 

@denisebmsft please close
