### ISSUE TITLE
Add teams module

### ISSUE THREAD

**Issue by BenoitNgs** [MicrosoftDocs/OfficeDocs-Enterprise#690]
Hello,

May be added the connexion a Teams environnement in this script ?

Install-Module -Name MicrosoftTeams
Import-Module -Name MicrosoftTeams
connect-MicrosoftTeams -Credential $credential

Sorry if it's out of subjet.

Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c551eb1-7ac5-cb02-cd1b-d67ca3886d85
* Version Independent ID: fb690e2e-420e-f697-60f2-39520283d385
* Content: [Connect to all Office 365 services in a single Windows PowerShell window](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window#feedback)
* Content Source: [Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by get-itips** [comment]
Hello @BenoitNgs 
Just for you to know, I am working on adding Teams to the article.
I should have news soon. Thanks

**Comment by mypil** [comment]
@BenoitNgs - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/cc97732b4696c9973d073eefdb1e6043647175fe. 


Thank you for your contribution to make the docs better! Much appreciated!
