### ISSUE TITLE
More specifics on domain?

### ISSUE THREAD

**Issue by jvplopper** [MicrosoftDocs/OfficeDocs-Enterprise#691]
"Type the domain that you want to use with the geo location" - wondering if you could provide more specifics here.  For instance, is this our domain.onmicrosoft.com?  Is is this our on-prem domain name?  Does it need to be a unique domain per satellite location? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d41ff16-b5cc-d2d2-6bb9-2134a0fafcd9
* Version Independent ID: ebb5ff30-995f-92ff-f536-4386a7817b5f
* Content: [Office 365 Multi-Geo tenant configuration](https://docs.microsoft.com/en-us/office365/enterprise/multi-geo-tenant-configuration)
* Content Source: [Enterprise/multi-geo-tenant-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/multi-geo-tenant-configuration.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by VLG17** [comment]
You need to enter a namespace for your satellite location (geo) and assign it the unique URL prefix:

![image](https://user-images.githubusercontent.com/41186174/74312342-30e6c380-4d7a-11ea-940c-fdc13cb66114.png)

**Comment by mypil** [comment]
@jvplopper  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
