### ISSUE TITLE
Missing information about Teams

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-Enterprise#692]
Please provide information about we should plan Teams data in multi-geo scenarios. Is it possible to put mailboxes for Teams channels into specific geos? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2278ef5d-6c7c-a8cb-d518-d2a996ace6f5
* Version Independent ID: 6c2cf399-a9f6-783c-d579-7b7a55e3fd17
* Content: [Plan for Office 365 Multi-Geo](https://docs.microsoft.com/en-us/office365/enterprise/plan-for-multi-geo)
* Content Source: [Enterprise/plan-for-multi-geo.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/plan-for-multi-geo.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by VLG17** [comment]
@DeanGross [This article](https://docs.microsoft.com/en-us/microsoftteams/teams-experience-o365odb-spo-multi-geo) talks about Teams in a multi-geo scenario. I will add a note about it in the article you mentioned.

Regarding your question about Teams team/channel mailbox, the new behavior is to store the mail and the attachment in the Sharepoint site that got created when creating the mailbox. 

![image](https://user-images.githubusercontent.com/41186174/74314183-aef89980-4d7d-11ea-9660-030f52094ec7.png)


So the [multi-geo rules for SharePoint](https://techcommunity.microsoft.com/t5/office-365-blog/now-available-multi-geo-in-sharepoint-and-office-365-groups/ba-p/263302) will apply to that.

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/9a3dc363e3fc3ed03de2d8930b525365a95abeeb. 


Thank you for your contribution to make the docs better! Much appreciated!
