### ISSUE TITLE
Unclear Impact

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-Enterprise#693]
Given that Teams uses SPO sites, it would seem that Teams can actually use multi-geo, but the statement above specifically excludes Teams. Please provide some information about how Teams works with a Group and SPO site that are assigned to a specific geo. 

Will all of the mailboxes for each channel in the Team be created in that Geo? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f3a2c9-0399-218d-cf9a-eb0f16fcbbb0
* Version Independent ID: da6ada6e-ce41-f772-74b8-144cf540d423
* Content: [Multi-Geo Capabilities in OneDrive and SharePoint Online](https://docs.microsoft.com/en-us/office365/enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365)
* Content Source: [Enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@DeanGross While SharePoint and Office 365 groups are multi-geo aware, other parts of Teams such as chat and meeting notes are not. See [Teams in a multi-geo environment](https://docs.microsoft.com/microsoftteams/teams-experience-o365odb-spo-multi-geo) for more info. @AdwoodMicrosoft would the channel mailboxes go to the group geo?

**Comment by DeanGross** [comment]
Thanks for the quick response. Looking forward to the answer from @AdwoodMicrosoft

**Comment by mypil** [comment]
@AdwoodMicrosoft - Do you have any updates on this?

Thank you.

cc: @kenwith

**Comment by MikePlumleyMSFT** [comment]
From @AdwoodMicrosoft: 

Mailboxes for Teams are stored in Exchange online. Because exchange is a Multi-Geo workload, this means that if a customer’s tenant is Multi-Geo enabled, their Group Mailbox will be created in the geo location matching the PDL of the group creator. 

Every Team creates an O365 group under the seams and the group in a Multi-Geo tenancy gets stamped with the PDL of the creating user.

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MikePlumleyMSFT so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by DeanGross** [comment]
@MikePlumleyMSFT  thanks for the clear explanation, that makes perfect sense to me and is easily understandable. Now, I just need to figure out a good approach to recommend to clients that need to ensure Team mailboxes are put into the correct geo. I'm guessing that they will need a customized provisioning process that provides the appropriate UX
