### ISSUE TITLE
Updated Link required on this page https://docs.microsoft.com/en-us/office365/enterprise/network-planning-and-performance?redirectSourcePath=%252fen-us%252farticle%252fNetwork-planning-and-performance-tuning-for-Office-365-e5f1228c-da3c-4654-bf16-d163daee8848

### ISSUE THREAD

**Issue by ralphsalb** [MicrosoftDocs/OfficeDocs-Enterprise#694]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 376fa7c6-9c9b-9715-05c6-1789a473f9ad
* Version Independent ID: 3cc6fdbd-ce6e-d8b4-b52f-a0dd08c1e788
* Content: [Network planning and performance tuning for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/network-planning-and-performance?redirectSourcePath=%252fen-us%252farticle%252fNetwork-planning-and-performance-tuning-for-Office-365-e5f1228c-da3c-4654-bf16-d163daee8848)
* Content Source: [Enterprise/network-planning-and-performance.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/network-planning-and-performance.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by ralphsalb** [comment]
The correct link for Top 10 Tips is:  https://docs.microsoft.com/en-us/archive/blogs/onthewire/top-10-tips-for-optimising-troubleshooting-your-office-365-network-connectivity

**Comment by mypil** [comment]
@ralphsalb - Thank you for pointing this out.

PR #698  has been created to fix and close this issue once the PR is merged.


We appreciate your contribution to make the docs better! Keep it coming!
