### ISSUE TITLE
PowerShell command Get-SPOTenantCdnOrigin is incorrect

### ISSUE THREAD

**Issue by Justin-Nash** [MicrosoftDocs/OfficeDocs-Enterprise#699]
I have spent over half a day trying to run Get-SPOTenantCdnOrigin -CdnType Public -OriginUrl */CLIENTSIDEASSETS . The problem is two fold:
1. There is no command Get-SPOTenantCdnOrigin
2. There is no parameter -OriginUrl

Please refer to your own martial: https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotenantcdnorigins?view=sharepoint-ps 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97626653-f653-d954-7a39-e5beac635e18
* Version Independent ID: 86f7d0b5-3a63-7511-0fc6-e3d98bea4b74
* Content: [Use the Office 365 Content Delivery Network (CDN) with SharePoint Online](https://docs.microsoft.com/en-us/office365/enterprise/use-office-365-cdn-with-spo?source=docs#set-up-and-configure-the-office-365-cdn-by-using-the-sharepoint-online-management-shell)
* Content Source: [Enterprise/use-office-365-cdn-with-spo.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/use-office-365-cdn-with-spo.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by VLG17** [comment]
@Justin-Nash Did you get this to work in the end? A few things:

1. Your command is missing the "s" after Origin. It should be: Get-SPOTenantCdnOrigin**s**

2. You don't need to specify the -OriginUrl to get it. You just neet to run "Get-SPOTenantCdnOrigins -CdnType Public":

![image](https://user-images.githubusercontent.com/41186174/75234268-f7bf4200-57c2-11ea-9cff-b8ccf5aa29c6.png)

**Comment by Justin-Nash** [comment]
I did get it to work but I created this issue so your documentation would be updated. It still has yet to be updated, you have a line of script on this page "Add-SPOTenantCdnOrigin -CdnType Public -OriginUrl */CLIENTSIDEASSETS". As you stated the command is missing an "s".

Please review this page the script in question can be found in your documentation under https://docs.microsoft.com/en-us/office365/enterprise/use-office-365-cdn-with-spo?source=docs#my-client-side-web-part-or-sharepoint-framework-solution-isnt-working third scrpt after heading.

**Comment by VLG17** [comment]
@Justin-Nash The missing "s" is for the "Get" cmdlet not the "Add" one:

[Get-SPOTenantCdnOrigins](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotenantcdnorigins?view=sharepoint-ps)

[Add-SPOTenantCdnOrigin](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spotenantcdnorigin?view=sharepoint-ps)

So there is nothing missing in the article, as far as i can see.

**Comment by Justin-Nash** [comment]
My mistake I thought your documentation had not been updated. After a second review it looks like it has been. The documentation originally had the line:

> Get-SPOTenantCdnOrigin -CdnType Public -OriginUrl */CLIENTSIDEASSETS

That has since been modified to reflect the documentation I referenced:

> https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotenantcdnorigins?view=sharepoint-ps

The only reason i started this ticket was so you could update the documentation as the original documentation was incorrect.
