### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by scottclarke1** [MicrosoftDocs/OfficeDocs-Enterprise#701]
Hey Guys
"When the eDiscovery Manager or Administrator role is set for a particular satellite location, the eDiscovery Manager or Administrator will only be able to perform eDiscovery search actions against the SharePoint sites and OneDrive sites located in that satellite location."

Does this include the central tenant location as well or are search actions solely restricted to the applicable security filter? 
For example, if my tenant is located in GBR and I have a filter that permits searches in NAM, and a user who is assigned the NAM filter performs a search, will results be returned for both GBR and NAM or just NAM?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e08a752-f73a-439f-728f-a8fc7e8952af
* Version Independent ID: a38b9339-689c-13b8-1bcd-9ac203dbc487
* Content: [Configure Office 365 Multi-Geo eDiscovery](https://docs.microsoft.com/en-us/office365/enterprise/multi-geo-ediscovery-configuration)
* Content Source: [Enterprise/multi-geo-ediscovery-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/multi-geo-ediscovery-configuration.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by VLG17** [comment]
@scottclarke1 "The Region parameter specifies the satellite location for multi-geo tenants to conduct eDiscovery searches in." If you create Compliance Security Filter with NAM as the value for the -Region parameter, the users that you assign the search filter to will be allowed to search only in NAM.

If you don't use the "-Region" parameter in a multi-geo tenant, eDiscovery searches are performed in the central location.

**Comment by mypil** [comment]
@scottclarke1 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17 so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
