### ISSUE TITLE
Clarification on Hard Deletion

### ISSUE THREAD

**Issue by Mlavieri** [MicrosoftDocs/OfficeDocs-Enterprise#702]
When a hard deletion is complete and the blocks are available for re-use is there any process in place such as page zeroing on top of this data or do the encrypted chunks stay until they are written over?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cefde46c-31d4-54ad-8c5c-44f23d8509b7
* Version Independent ID: ae9d8dc1-dafc-7bb6-b9de-c5ddc049dadf
* Content: [Office 365 SharePoint Online Data Deletion](https://docs.microsoft.com/en-us/office365/enterprise/office-365-sharepoint-online-data-deletion#feedback)
* Content Source: [Enterprise/office-365-sharepoint-online-data-deletion.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-sharepoint-online-data-deletion.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by VLG17** [comment]
@Mlavieri According to the [public documentation](https://docs.microsoft.com/en-us/office365/Enterprise/office-365-exchange-online-data-deletion#page-zeroing), a page zeroing mechanism exists only for Exchange Online. For SharePoint this is not applicable. The data is written over the deleted chunks.

**Comment by Mlavieri** [comment]
@VLG17 thanks for the confirmation
