### ISSUE TITLE
Who are the members of the program

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-Enterprise#704]
Please provide information about the firms that are in this program

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e449ab57-b1c0-6ca5-7e77-a587eb7390a9
* Version Independent ID: 53932091-b65c-c7d8-1927-97afa11d1cf6
* Content: [Office 365 Networking Partner Program](https://docs.microsoft.com/en-us/Office365/Enterprise/office-365-networking-partner-program)
* Content Source: [Enterprise/office-365-networking-partner-program.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-networking-partner-program.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Can you please share your insights on this issue?


Thank you.


cc: @kenwith

**Comment by John712796** [comment]
You can find the list of partners in the program here: https://www.microsoft.com/microsoft-365/partners/O365networkingpartners

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by John712796 so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
