### ISSUE TITLE
Clarify need for global admin

### ISSUE THREAD

**Issue by V3ertigo83** [MicrosoftDocs/OfficeDocs-Enterprise#705]
Under the section 'Start a SharePoint site geo move for an Office 365 Group-connected site' it explicitly states 'the global administrator must' but leverages a cmdlet from the sharepoint-online module. Please clarify if this MUST be a global admin, or if a more least-privilege access level is sufficient (Such as SharePoint Administrator or Group Administrator). IF there is a requirement that this MUST be a global admin, please note more clearly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d451efa0-3ee4-2b8c-3aad-bff6a8e5257d
* Version Independent ID: 3a8471e3-4775-e6b4-7586-25dbe01fca33
* Content: [Move a SharePoint site to a different geo location](https://docs.microsoft.com/en-us/office365/enterprise/move-sharepoint-between-geo-locations#feedback)
* Content Source: [Enterprise/move-sharepoint-between-geo-locations.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/move-sharepoint-between-geo-locations.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by VLG17** [comment]
@V3ertigo83 It is stated in the article that "You must be a **Global Administrator or SharePoint Administrator** to move a site between geo locations."

I will create a PR and add "SharePoint Administrator" to the paragraph you mentioned.

**Comment by JoeDavies-MSFT** [comment]
@VLG17 @V3ertigo83 The article has been updated and published. Sorry about the long delay here. Thanks so much for letting us know.
