### ISSUE TITLE
Retired Content

### ISSUE THREAD

**Issue by DynamitePLF** [MicrosoftDocs/OfficeDocs-Enterprise#706]
This article sites the In-Place eDiscovery & Hold, which has been moved to O365 Compliance Center.  Blah-Blah-Blah!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39aa0813-6d11-cf85-b3d0-9f068c1ba5e7
* Version Independent ID: a92e5228-5ddf-84f2-d695-3076cee03159
* Content: [Recover deleted items in a user mailbox - Admin Help](https://docs.microsoft.com/en-us/office365/enterprise/recover-deleted-items-in-a-mailbox)
* Content Source: [Enterprise/recover-deleted-items-in-a-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/recover-deleted-items-in-a-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@DynamitePLF Thanks for the reminder. As you imply, admins won't be able to create new In-Place eDiscovery searches in the EAC after April 1, 2020, and should start using the search and export functionality in Content Search in the compliance center. We'll update this topic accordingly or retire it.
