### ISSUE TITLE
Including Microsoft Teams for Federation SRV record

### ISSUE THREAD

**Issue by NickElniff** [MicrosoftDocs/OfficeDocs-Enterprise#707]
Microsoft Teams needs to be included as well in the _SipFederationtls._tcp section

SRV
(Skype for Business Online)
Allows your Office 365 domain to share instant messaging (IM) features with external clients by enabling SIP federation. Read more about Office 365 URLs and IP address ranges.
Service: sipfederationtls
Protocol: TCP
Priority: 100
Weight: 1
Port: 5061
Target: sipfed.online.lync.com
Note: If the firewall or proxy server blocks SRV lookups on an external DNS, you should add this record to the internal DNS record.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e27e942-5c6d-591e-14c4-40d44d90422c
* Version Independent ID: 5e92f544-cae1-9d31-0c9a-253a7e76b73f
* Content: [External Domain Name System records for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/external-domain-name-system-records)
* Content Source: [Enterprise/external-domain-name-system-records.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/external-domain-name-system-records.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by VLG17** [comment]
@NickElniff As far as i know, that's not the case and external access in Microsoft Teams [is turned on by default.](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access). Did you see an issue with Teams that was solved by adding "sipfederationtls"?

Other than [the well known ports and URLs](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#skype-for-business-online-and-microsoft-teams) and [network requirements and optimization](https://docs.microsoft.com/en-us/microsoftteams/prepare-network) there is no other requirement to get external communication within Teams going.

**Comment by NickElniff** [comment]
Turning on External Access is only the settings to allow for federation communications, while the "SipFederationTLS" DNS SRV record is to allow other organizations to discover the federation route. Example if Customer A is TeamsOnly in O365 and Customer B is Skype for Business Server: Customer B would need to be able to resolve Customer A's SipFederationTLS DNS record in order to know where to send federation traffic. Enabling External Access in the portal is not enough.

**Comment by VLG17** [comment]
@NickElniff I understand what you mean. I could not find any official guidance around this topic. I will add a note in the article about this and hopefully it will get approved.

I guess we will have to wait for official guidance to come out close to the [Skype for Business Online retirement date](https://techcommunity.microsoft.com/t5/healthcare-and-life-sciences/skype-for-business-online-end-of-life-july-31-2021/ba-p/779137). Until then i think one should treat the DNS records as having Skype for Business instead of Teams.

**Comment by mypil** [comment]
@NickElniff - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/a69be96fab09ff9bb06ad8369caafe090061c011. 


Thank you for your contribution to make the docs better! Much appreciated!
