### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by jasonkatz424** [MicrosoftDocs/OfficeDocs-Enterprise#709]
The "h" in "THis includes:" should not be capitalized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57a412c8-b70e-bc0e-63da-0a0adbf301f8
* Version Independent ID: 11d9d5d3-6eea-91a4-b3fd-babc6069b2ea
* Content: [Office 365 Data Immutability](https://docs.microsoft.com/en-us/office365/enterprise/office-365-data-immutability#feedback)
* Content Source: [Enterprise/office-365-data-immutability.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-data-immutability.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@jasonkatz424 - Thank you for pointing this out.

I created PR #712 to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
