### ISSUE TITLE
CDN checked, while is not in use (powershell check).

### ISSUE THREAD

**Issue by danone1985** [MicrosoftDocs/OfficeDocs-Enterprise#710]
CDN check is green in Page Diagnostic for SharePoint, while Get-SPOTenantCDNEnabled is FALSE for both private and public.

will retry, however seems to be a bug.

**Comment by mypil** [comment]
@danone1985 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@danone1985 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. 

Thank you.
