### ISSUE TITLE
further request on #593

### ISSUE THREAD

**Issue by UKayo** [MicrosoftDocs/OfficeDocs-Enterprise#716]
Thanks for the additional note on "mailnickname" section.
However, my intention was to also add a note that any allowed character other than "-" would be replaced with "_" when the object is synced to AAD. This was found from my testing environment. Would you revisit this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c60ee789-fce6-6c95-150d-be4ae895730e
* Version Independent ID: d9e96954-3b85-bf8d-c7d3-916a4698fd77
* Content: [Prepare for directory synchronization to Office 365](https://docs.microsoft.com/en-us/office365/enterprise/prepare-for-directory-synchronization#feedback)
* Content Source: [Enterprise/prepare-for-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/prepare-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@UKayo  Thank you for the feedback. There is already a note on the document which talks about this

Underscores ("_") in the synchronized name indicates that the original value of this attribute contains invalid characters. The original value can contain letters, numbers, and the characters !, #, $, %, &, ', *, +, -, /, =, ?, ^, _, `, {, |, } and ~. For more information on this attribute, see Exchange alias attribute.

Let me know if you think this still needs a change.

Thanks
Sri

**Comment by mypil** [comment]
@UKayo - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
