### ISSUE TITLE
include:sharepointonline.com needs clarification

### ISSUE THREAD

**Issue by miss-tech** [MicrosoftDocs/OfficeDocs-Enterprise#717]
The "include:sharepointonline.com" isn't neccessary anymore from my understanding. This needs removal and / or clarification.

**Comment by mypil** [comment]
@miss-tech - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@miss-tech - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. 

Thank you.

**Comment by miss-tech** [comment]
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_shareon-mso_o365b/sharepointonlinecom-vs-protectionoutlookcom-spf/43cf1dc1-655b-4d28-a827-ea0a10f529c3

This answers post and the following articles all exclude sharepointonline.com from SPF records:
- https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing?view=o365-worldwide
- https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/how-office-365-uses-spf-to-prevent-spoofing?view=o365-worldwide#HowSPFWorks

**Comment by miss-tech** [comment]
Could you please reopen this issue?

**Comment by miss-tech** [comment]
The primary article referencing this:
https://support.office.com/en-us/article/information-about-changes-to-the-address-that-is-used-to-send-notification-email-messages-from-sharepoint-online-ae01f2a0-acca-499b-ab96-df0e996d367a

Starting in January 2016, there was a subtle change in the "From" email address that's used in notification messages that are sent by SharePoint Online. This change should reduce the risk of SharePoint notification mails being routed to the Junk Email folder and should cause no adverse effect. You may want to remove SharePoint's Sender Policy Framework (SPF) records from your domain's SPF records and also remove any exceptions for SharePoint Online that you might have added to your spam filters.

**Comment by msbemba** [comment]
@miss-tech  Thank you for your feedback. All the three documents that you have mentioned state there is no need to add the SharePoint's SPF records. Can you elaborate on what changes are required on the document(s)?

Thanks
Sri

**Comment by mypil** [comment]
@miss-tech - Can you please respond to the query of msbemba?

Thank you.

**Comment by miss-tech** [comment]
https://docs.microsoft.com/en-us/office365/enterprise/external-domain-name-system-records#choose-the-spf-record-structure-you-need

Section 3 states that include:sharepointonline.com is required if Sharepoint Online is in use. This is no longer the case so needs to be modified.

**Comment by msbemba** [comment]
@miss-tech  Thank you for your feedback. We have modified the document accordingly via PR https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/762

Thanks
Sri

**Comment by mypil** [comment]
@miss-tech - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/27a9e3912f0eada2be7c01daf609f1bd9eb288d2. 


Thank you for your contribution to make the docs better! Much appreciated!
