### ISSUE TITLE
preferreddatalocation cannot be modified

### ISSUE THREAD

**Issue by limjianan** [MicrosoftDocs/OfficeDocs-Enterprise#72]
Set-MsolUser -UserPrincipalName <UserPrincipalName> -PreferredDataLocation <GeoCode> will not work for sync users.

https://docs.microsoft.com/en-us/azure/active-directory/connect/active-directory-aadconnectsync-feature-preferreddatalocation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85937c83-35db-0882-e226-a4f2f732de73
* Version Independent ID: ac0b646b-0fbf-eb24-6768-07cfcd51076b
* Content: [Multi-Geo Capabilities in Exchange Online](https://docs.microsoft.com/en-us/office365/enterprise/multi-geo-capabilities-in-exchange-online)
* Content Source: [Enterprise/multi-geo-capabilities-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/multi-geo-capabilities-in-exchange-online.md)
* Service: **o365-solutions**
* Product: **unspecified**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@limjianan, in the **Notes** right after the Set-MsolUser procedure, it says:

As mentioned previously for synchronized user objects from on-premises Active Directory, you can't use this procedure. You need to change the **PreferredDataLocation** value using AAD Connect. For more information, see [Azure Active Directory Connect sync: Configure preferred data location for Office 365 resources](https://docs.microsoft.com/azure/active-directory/connect/active-directory-aadconnectsync-feature-preferreddatalocation).

That's what you're saying, right?

Thanks for the feedback.

**Comment by limjianan** [comment]
@chrisda you are right, my bad.

**Comment by adammodlin** [comment]
It's mentioned above "Microsoft needs to configure your Exchange Online tenant for Multi-Geo support. This one-time configuration process is triggered after you order Multi-Geo and the licenses show up in our tenant." but there is no link or direction on how to enable this for your tenant. Am I missing that information or is it not on the page?
