### ISSUE TITLE
Domain Restrictions 

### ISSUE THREAD

**Issue by stewalshy** [MicrosoftDocs/OfficeDocs-Enterprise#720]
Hi,

In the "Limit sharing by domain" section of the site-level, it states that the settings cannot be used to override restrictions at the Sharepoint Organization or Azure AD Level. This is clear and easy to understand.

However can you explain how the "Limit external sharing by domain" option at the Sharepoint Organization level works with collaboration restrictions at the Azure AD level?

Taking a whitelist approach with domain1.com allowed at Azure AD and domain2.com allowed at Sharepoint Org:
- Is this a valid configuration or do the Sharepoint Org settings have to match / be a subset of Azure AD level?
- If this is a valid configuration, does this mean that users can share sites and files with both domains? Or will Azure AD block domain2.com and Sharepoint Org settings block domain1.com?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bb31720-7494-ab3f-6a3d-5c395649e75d
* Version Independent ID: 81c36ae8-fbaa-c411-4bd2-a4db98e249e1
* Content: [Microsoft 365 guest sharing settings reference](https://docs.microsoft.com/en-ie/Office365/Enterprise/microsoft-365-guest-settings#see-also)
* Content Source: [Enterprise/microsoft-365-guest-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/microsoft-365-guest-settings.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@stewalshy  if the [SharePoint and OneDrive integration with Azure AD B2B preview](https://docs.microsoft.com/sharepoint/sharepoint-azureb2b-integration-preview) has been enabled, then SharePoint will respect the Azure AD domain restrictions. So if only domain1.com is allowed in Azure AD, then you can't allow domain2.com in SharePoint. Basically, anything that is allowed based on the Azure AD settings can be further limited at the SharePoint organization level. Anything allowed based on the SharePoint org settings can be further limited at the site level.

**Comment by mypil** [comment]
@stewalshy - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author MikePlumleyMSFT so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
