### ISSUE TITLE
Whitepaper link broken

### ISSUE THREAD

**Issue by JRVcr** [MicrosoftDocs/OfficeDocs-Enterprise#721]
Redirects to MS home page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57a412c8-b70e-bc0e-63da-0a0adbf301f8
* Version Independent ID: 11d9d5d3-6eea-91a4-b3fd-babc6069b2ea
* Content: [Office 365 Data Immutability](https://docs.microsoft.com/en-us/office365/Enterprise/office-365-data-immutability#feedback)
* Content Source: [Enterprise/office-365-data-immutability.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-data-immutability.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@JRVcr - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/90b8591b712c791e5ec0f71c9a84830fbb7f4f8c. 


Thank you for your contribution to make the docs better! Much appreciated!
