### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by apedder** [MicrosoftDocs/OfficeDocs-Enterprise#726]
Tooltips on sensitivity labels can only be 64 characters. Your examples are longer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69eee476-1c7a-06ef-ba3f-5ba33c907c5e
* Version Independent ID: 31cdfe07-a3f4-3c0e-519f-042b847b7237
* Content: [Create a secure guest sharing environment](https://docs.microsoft.com/en-us/Office365/Enterprise/create-a-secure-guest-sharing-environment#feedback)
* Content Source: [Enterprise/create-a-secure-guest-sharing-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/create-a-secure-guest-sharing-environment.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@apedder Thank you for the feedback. The Tooltips on sensitivity labels doesn't have a limit as such. I was able to create a sensitivity label with the example provided.

![image](https://user-images.githubusercontent.com/45987684/76837600-d77e2280-6858-11ea-9b59-b90e65e0b305.png)

Thanks
Sri

**Comment by mypil** [comment]
@apedder - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
