### ISSUE TITLE
Digital Signature 

### ISSUE THREAD

**Issue by ziggynemeth** [MicrosoftDocs/OfficeDocs-Enterprise#727]
The idfix.exe tool is not signed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c937e8be-1696-c315-a93b-88f083279644
* Version Independent ID: c0c3d253-4bfe-1750-58a1-4d8f4a1e68d6
* Content: [Download and run the Office 365 IdFix tool](https://docs.microsoft.com/en-us/office365/enterprise/install-and-run-idfix)
* Content Source: [Enterprise/install-and-run-idfix.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/install-and-run-idfix.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@ziggynemeth  Thank you for your feedback. We are looking into this and will get back to you shortly.

Thanks
Sri

**Comment by JoeDavies-MSFT** [comment]
@ziggynemeth Sorry for the delay. Please create a similar issue here: https://github.com/microsoft/idfix/issues The IdFix tool is now being maintained as an open source project and this team can help you with this request. Thanks.

**Comment by mypil** [comment]
@JoeDavies-MSFT - Thanks for your guidance.

@ziggynemeth - From our understanding, the issue you raised has been answered by the author-JoeDavies-MSFT  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
