### ISSUE TITLE
Viewing service health as a general user

### ISSUE THREAD

**Issue by BatmanAMA** [MicrosoftDocs/OfficeDocs-Enterprise#728]
Why is this limited to admins? These just wind up posted all over twitter and reddit anyway so it's not like they're sensitive data, why do I have to be in an administrative role to see service health advisories?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd2a834a-296b-1c7d-7358-6f6a19f8f3c3
* Version Independent ID: 9ab6adbe-c651-d833-f395-64b7cddb2dd2
* Content: [How to check Office 365 service health](https://docs.microsoft.com/en-us/office365/enterprise/view-service-health#feedback)
* Content Source: [Enterprise/view-service-health.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/view-service-health.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@BatmanAMA Thank you for your feedback. By design, the service health dashboard is accessible for only admins. I can check with @mypil  and see if we have a UserVoice option open for this request.

Thanks
Sri

**Comment by msbemba** [comment]
@BatmanAMA I found a UserVoice (Design request) for the same.

https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/14823009-be-able-to-provide-only-the-service-health-informa

You can Upvote it with your email address and Once Microsoft developers/Product group make this change you will be notified

Thanks
Sri

**Comment by mypil** [comment]
@BatmanAMA - Thank you for engaging with the community here for the docs.

As mentioned by msbemba, please submit this feature request via UserVoice. 


Thank you for your contribution to make the docs better! Much appreciated!
