### ISSUE TITLE
include:sharepointonline.com needs removal or clarification

### ISSUE THREAD

**Issue by miss-tech** [MicrosoftDocs/OfficeDocs-Enterprise#731]
The "include:sharepointonline.com" isn't neccessary anymore from my understanding. This needs removal and / or clarification.

The primary article referencing this:
https://support.office.com/en-us/article/information-about-changes-to-the-address-that-is-used-to-send-notification-email-messages-from-sharepoint-online-ae01f2a0-acca-499b-ab96-df0e996d367a

Additional Information:
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_shareon-mso_o365b/sharepointonlinecom-vs-protectionoutlookcom-spf/43cf1dc1-655b-4d28-a827-ea0a10f529c3

This answers post and the following articles all exclude sharepointonline.com from SPF records required for Office 365 to function:

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing?view=o365-worldwide
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/how-office-365-uses-spf-to-prevent-spoofing?view=o365-worldwide#HowSPFWorks

**Comment by mypil** [comment]
Closing this issue as it is a duplicate to #717
