### ISSUE TITLE
MFA for Administrators

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-Enterprise#732]
I appreciate that this is "general advice".  But this article specifically refers to constraining Global Administrator accounts, while another article (https://docs.microsoft.com/bs-latn-ba/azure/active-directory/conditional-access/howto-conditional-access-policy-admin-mfa) recommends constraining all administrator roles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96784dc6-991a-fb80-cd0c-ae8217c32f45
* Version Independent ID: 0532ace1-bf55-916f-708d-5444c49d77b1
* Content: [Protect your Office 365 global administrator accounts](https://docs.microsoft.com/en-us/office365/enterprise/protect-your-global-administrator-accounts)
* Content Source: [Enterprise/protect-your-global-administrator-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/protect-your-global-administrator-accounts.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@Air-Git Thank you for your feedback. This article is focused on global administrator accounts only. That's the reason you don't see constraints on all admin roles. We have added a note saying that 
"Although this article is focused on global administrator accounts, you should consider whether additional accounts with wide-ranging permissions to access the data in your subscription, such as eDiscovery administrator or security or compliance administrator accounts, should be protected in the same way."

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@Air-Git- Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by Air-Git** [comment]
Thanks, that works.
