### ISSUE TITLE
When it support for OneDrive on macOS?

### ISSUE THREAD

**Issue by kelvinwong927** [MicrosoftDocs/OfficeDocs-Enterprise#734]
When it support for OneDrive on macOS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8669577f-03c4-3521-b969-83667dfc75b2
* Version Independent ID: b4f17a99-6f21-0bdf-ef27-d6087e2f6370
* Content: [Office 365 Client App Support — Certificate-based Authentication](https://docs.microsoft.com/en-us/office365/enterprise/office-365-client-support-certificate-based-authentication)
* Content Source: [Enterprise/office-365-client-support-certificate-based-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-client-support-certificate-based-authentication.md)
* Service: **office 365 administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@kelvinwong927 - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@robmazz - Can you please share your insights on this issue?

Thank you.


cc: @kenwith

**Comment by identityiskey** [comment]
OneDrive on macOS does indeed work with Certificate Based Authentication. Besides the known prerequisite of a certificate that has both the E.K.U client authentication and the User UPN in the NT Principal Name SAN (Subject Alternative Name) set. The key here is that you use the set-identity preference setting in macOS (either trough GUI or command). The set identity preference has to be created on the issued user certificate in the user logon keychain and filled with the URL of the ADFS server of the organization (certauth.xxx) - wildcards are possible. See: 
https://support.apple.com/lv-lv/guide/keychain-access/kyca6343b6c9/mac

**Comment by mypil** [comment]
@kelvinwong927 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @identityiskey so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
