### ISSUE TITLE
Hang while accessing O365 IP Address URL

### ISSUE THREAD

**Issue by freedomofkeima** [MicrosoftDocs/OfficeDocs-Enterprise#735]
Hi,

I noticed this is not the first time this issue was mentioned (https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/689, https://github.com/PaloAltoNetworks/minemeld/issues/49#issuecomment-573369187 described similar problem). Currently, we are retrieving O365 IP Address periodically as it is **critical** to our service. This issue seemed to happen recently (not in the past).

We noticed that this problem occurs consistently on IP address basis as a single request URL can be stuck in 1 instance while it is working if we tried accessing it on local machines. Example URL:

- https://endpoints.office.com/endpoints/worldwide?ClientRequestId=0aab0177-4da9-46d4-a54b-29963abc4626

The error that we received on server instance:

> ReadTimeout: HTTPSConnectionPool(host='endpoints.office.com', port=443): Read timed out. (read timeout=60)

<img width="983" alt="Screen Shot 2020-03-03 at 17 47 01" src="https://user-images.githubusercontent.com/2115470/75758232-1bf8c100-5d77-11ea-88a8-3c892ffa1477.png">

<img width="318" alt="Screen Shot 2020-03-03 at 17 47 06" src="https://user-images.githubusercontent.com/2115470/75758238-1dc28480-5d77-11ea-9639-683918437640.png">

Example source IP address where it's failing:
- **52.192.58.79**

(It started failing persistently at one point and caused 189 errors in the past 5 hours)

Is there any way we can know why our request is hanging / failing?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7ebf92c-e478-0f65-0494-97042e974b46
* Version Independent ID: 7e1b9b91-d60d-8665-9a39-2ca77a46b4ce
* Content: [Office 365 IP Address and URL web service](https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service#feedback)
* Content Source: [Enterprise/office-365-ip-web-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by freedomofkeima** [comment]
To clarify, on normal cases, we're only accessing the endpoint every 15 minutes. Since the request is failing and reaching a timeout of 60 seconds, the worker will try it again the subsequent minute, therefore there were around 189 requests in 5 hours.

**Comment by mypil** [comment]
@freedomofkeima - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by freedomofkeima** [comment]
Hi,

Thanks for the response. We'll see what we can do in our side. In the past few days, it looks a bit better with lower number of failures (we still see some occasional failures but not as persistent as a week ago).

<img width="1265" alt="Screen Shot 2020-03-09 at 19 35 09" src="https://user-images.githubusercontent.com/2115470/76205415-84dfad80-623d-11ea-8ecc-b0b1a686b297.png">
