### ISSUE TITLE
Microsoft Whiteboard for Teams

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/OfficeDocs-Enterprise#736]
whiteboard.microsoft.com needs to be added to this list. If a customer doesn't have it whitelisted it will prevent it from loading when the app is enabled for use in Microsoft Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#skype-for-business-online-and-microsoft-teams)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by LauraWi** [comment]
@greganth1 Thank you. We're reaching out to engage that engineering team so they can contribute their info to the automated process that generates the info in this topic.

**Comment by greganth1** [comment]
Additional info from Whiteboard team.
Microsoft Whiteboard IP addresses to be whitelisted for Whiteboard:

52.190.28.19
52.155.173.190
52.157.250.241
51.143.111.143

TCP Ports 80 and 443 need to be enabled.

The domains are the following:
whiteboard.microsoft.com
wbd.ms
whiteboard.ms
