### ISSUE TITLE
Global Admin and Office License

### ISSUE THREAD

**Issue by adnantocode** [MicrosoftDocs/OfficeDocs-Enterprise#737]
Can you also put that Global Admin do not need any license and if they do what is the use 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96784dc6-991a-fb80-cd0c-ae8217c32f45
* Version Independent ID: 0532ace1-bf55-916f-708d-5444c49d77b1
* Content: [Protect your Office 365 global administrator accounts](https://docs.microsoft.com/en-us/office365/enterprise/protect-your-global-administrator-accounts#feedback)
* Content Source: [Enterprise/protect-your-global-administrator-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/protect-your-global-administrator-accounts.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@adnantocode Thank you for your feedback. We have added a note to the document via PR# https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/751

Thanks
Sri

**Comment by JoeDavies-MSFT** [comment]
PR 751 is merged and published.
