### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by darwinpou** [MicrosoftDocs/OfficeDocs-Enterprise#739]
I've spent all steps in this article with no sucess.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7df65c5-ea03-f39b-ea7f-14809c15abc1
* Version Independent ID: 7ed5fef7-51f8-1b6b-e220-49dcc59e98c2
* Content: [Collaborate with guests in a team](https://docs.microsoft.com/en-us/Office365/Enterprise/collaborate-as-a-team#feedback)
* Content Source: [Enterprise/collaborate-as-a-team.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/collaborate-as-a-team.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@darwinpou - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
