### ISSUE TITLE
Error at Step #6

### ISSUE THREAD

**Issue by balajimadgundi** [MicrosoftDocs/OfficeDocs-Enterprise#74]
Method invocation failed because
[Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext] does
not contain a method named 'AcquireToken'.
At C:\Balaji\ACS
Migration\spsaml11-master\scripts\MSGraphTokenLifetimePolicy.psm1:53 char:3
+   $Global:authenticationResult = $authContext.AcquireToken($resourceA ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

You cannot call a method on a null-valued expression.

**Comment by kaevans** [comment]
@balajimadgundi The easiest way to do this is to[ install Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/install-azurerm-ps?view=azurermps-6.1.0). Once installed, make sure to run the script exactly as demonstrated in the article:

`
Import-Module <file path of Initialize.ps1> 
$objectid = "<Application Object ID from Table 1>"
$saml2policyid = Get-PoliciesAssignedToServicePrincipal -servicePrincipalId $objectid | ?{$_.displayName -EQ "TokenIssuancePolicy"} | select objectId
Remove-PolicyFromServicePrincipal -policyId $saml2policyid -servicePrincipalId $objectid
$policy = Add-TokenIssuancePolicy -DisplayName SPSAML11 -SigningAlgorithm "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" -TokenResponseSigningPolicy TokenOnly -SamlTokenVersion "1.1"
Set-PolicyToServicePrincipal -policyId $policy.objectId -servicePrincipalId $objectid
`

**Comment by balajimadgundi** [comment]
Thanks Kirk for response. Now I am able to execute the "$saml2policyid = Get- ..." step successfully, issue was I had old version of PowerShellGet.

But I have received below error for the next line "Remove-PolicyFromServicePrincipal.." 

"(unsupported query ..)"

When I have replaced the variable $saml2policyid with actual value then it works (as pointed out in by the others on similar issue #60 https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/60).

Is there anything I am missing?

**Comment by kaevans** [comment]
Updated sample code and verified in lab. [PR 78](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/78)
