### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by darwinpou** [MicrosoftDocs/OfficeDocs-Enterprise#740]
After spent some hours configuring Guest Access with these steps, finally not working.
I think there must be another step not documented in this page.
Even, waiting recommended 24 hours for configuration refresh.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2296f91f-ac66-7d38-1aae-479bbcef9b87
* Version Independent ID: db8bfc32-701d-c245-08ea-ec864da86c9d
* Content: [Collaborate with guests in a site](https://docs.microsoft.com/en-us/office365/enterprise/collaborate-in-a-site)
* Content Source: [Enterprise/collaborate-in-a-site.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/collaborate-in-a-site.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@darwinpou - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
