### ISSUE TITLE
Response to #716 

### ISSUE THREAD

**Issue by UKayo** [MicrosoftDocs/OfficeDocs-Enterprise#742]
@msbemba 
Thank you for looking into this. My intention was to say that any allowed characters allowed to use other than "-" and "_" will result in getting synced as "_".  It says we can contain " !, #, $, %, &, ', *, +, -, /, =, ?, ^, _, `, {, |, } and ~" but it actually only allows "-" and "_" to be synced properly. Please test this and verify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c60ee789-fce6-6c95-150d-be4ae895730e
* Version Independent ID: d9e96954-3b85-bf8d-c7d3-916a4698fd77
* Content: [Prepare for directory synchronization to Office 365](https://docs.microsoft.com/en-us/office365/enterprise/prepare-for-directory-synchronization)
* Content Source: [Enterprise/prepare-for-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/prepare-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by UKayo** [comment]
Somehow, "_" (underscore) has been deleted from my text, so re-posting with clarifications.

Thank you for looking into this. My intention was to say that any allowed characters allowed to use other than "- (hyphen)" and "_ (underscore)" will result in getting synced as "_ (underscore)". It says we can contain " !, #, $, %, &, ', *, +, -, /, =, ?, ^, _ (underscore), `, {, |, } and ~" but it actually only allows "-" and "_ (underscore)" to be synced properly. Please test this and verify.

**Comment by msbemba** [comment]
@UKayo  Thank you for the feedback. We will test this and update shortly.

**Comment by msbemba** [comment]
@UKayo Thank you for your feedback.I was able to test this in multiple Instances and the document is upto date. I was able to sync the below characters without any issues

" !, #, $, %, &, ', *, +, -, /, =, ?, ^, _ , `, {, |, } and ~"

![image](https://user-images.githubusercontent.com/45987684/77300274-c5e2c200-6d13-11ea-9dd3-c19ef51abf23.png)

Thanks
Sri

**Comment by UKayo** [comment]
Than you so much for testing! However, my point only applies to "mailNickname." Please test with this attribute

**Comment by msbemba** [comment]
@UKayo  Thank you for the response. I see that there is a Uservoice for this particular attribute https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/39013438-fix-the-behavior-that-the-character-set-as-the-mai

We have updated the note on the document to reflect the same. Reference  PR #https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/768

Thanks
Sri
