### ISSUE TITLE
Different information about data location on different pages

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-Enterprise#743]
This document https://products.office.com/pl-pl/where-is-your-data-located#office-ContentAreaHeadingTemplate-bkjgypc states that for EU data is stored in Austria, Finland, Netherlands and Ireland. This documents adds France, Germany and UK. Which document is correct and should be considered authorative?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d4d59d-d7b1-81b1-aeaf-6d34f61ae18b
* Version Independent ID: 2b2620fa-7e4f-27ee-2655-47da2391296f
* Content: [Office 365 data locations](https://docs.microsoft.com/en-us/office365/enterprise/o365-data-locations#countryregion-specific-data-center-city-locations)
* Content Source: [Enterprise/o365-data-locations.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/o365-data-locations.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by LauraWi** [comment]
@Larryngolog  -- Reaching out to engineering on this.

**Comment by LauraWi** [comment]
This document is accurate. The link you copied is an older page that will redirect to this doc page starting on March 27.
