### ISSUE TITLE
EU data stored in UK and Brexit

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-Enterprise#744]
Now that Brexit is a fact, what is approach to EU data residency? This document states that for European Union data can be stored in United Kingdom. Is this still true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d4d59d-d7b1-81b1-aeaf-6d34f61ae18b
* Version Independent ID: 2b2620fa-7e4f-27ee-2655-47da2391296f
* Content: [Office 365 data locations](https://docs.microsoft.com/en-us/office365/enterprise/o365-data-locations#countryregion-specific-data-center-city-locations)
* Content Source: [Enterprise/o365-data-locations.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/o365-data-locations.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by LauraWi** [comment]
@Larryngolog Reaching out to engineering on this.

**Comment by LauraWi** [comment]
Hi, update from my engineering counterpart: "Tenants with a sign-up address located within the UK will have their data stored at rest within the UK. Learn more about our data residency commitments in the Online Services Terms (OST) [https://www.microsoftvolumelicensing.com/Downloader.aspx?documenttype=OST&lang=English]. If you wish to store user data at rest in different geos under a single tenant, learn more about our Multi-Geo offering [https://products.office.com/en-us/business/multi-geo-capabilities]

**Comment by Larryngolog** [comment]
Hello. I think You understood my comment the other way around. The document clearly states that UK customers will have their data in UK but this is not what worries me. I was asking if EU customer's data (for example customer from Italy, Spain o Poland) can be stored in UK. Document states currently that EU data is/can be stored in UK. This could have serious legal consequences now since UK is not part of EU.

**Comment by LauraWi** [comment]
Thanks for this clarification. Hope this helps. I think my engineering partner is assuming you are in the UK, which you are not. EU data should stay in the EU.

If the O365 tenant has a GB signup country associated with it then the tenant’s core workload data at rest could be in the EU or it could be in the UK, depending on the timing of the tenant creation and whether or not the tenant opted-in for migration.

If your core workloads show European Union in the M365 Admin Center today then that is where you will stay unless you request migration to the UK.

**Comment by Larryngolog** [comment]
Can you please correct the article then? It clearly states today that European customers will get their data stored in UK:

Country
European Union

City:
Austria, Finland, France, Germany, Ireland, Netherlands, United Kingdom
