### ISSUE TITLE
GCC tenants

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-Enterprise#747]
can express route be used with GCC or GCC High tenants?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 132cbf89-c6a0-cbe2-dd7e-5e449ce2f390
* Version Independent ID: 787afe5f-0111-a1f0-d33c-4ac4260b846b
* Content: [Azure ExpressRoute for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/azure-expressroute)
* Content Source: [Enterprise/azure-expressroute.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/azure-expressroute.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@DeanGross  Thank you for the feedback. Yes. Office 365 GCC service endpoints are reachable through the Azure US Government ExpressRoute. However, you first need to open a support ticket on the Azure portal to provide the prefixes you intend to advertise to Microsoft. Your connectivity to Office 365 GCC services will be established after the support ticket is resolved. We have added this question to the FAQ's 

https://docs.microsoft.com/en-us/azure/expressroute/expressroute-faqs#can-i-access-office-365-us-government-community-gcc-services-over-an-azure-us-government-expressroute-circuit

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@DeanGross  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
