### ISSUE TITLE
Use write-output

### ISSUE THREAD

**Issue by GavGavGavGav** [MicrosoftDocs/OfficeDocs-Enterprise#749]
It would be helpful if you used "write-output $_.UserPrincipalName" to list the users, so you can easily use the data from the command. For example counting the amount of users by enclosing the whole thing in parentheses and using .count. Using write-host means the data is only good for copying/pasting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cdc030a-0015-fe77-eac3-4c5070c0c5a3
* Version Independent ID: 24107b9c-1f13-571c-1303-6019ba64dcea
* Content: [View licensed and unlicensed users with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-licensed-and-unlicensed-users-with-office-365-powershell?source=docs#feedback)
* Content Source: [Enterprise/powershell/view-licensed-and-unlicensed-users-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/view-licensed-and-unlicensed-users-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@GavGavGavGav Thank you for the feedback  The  Azure Active Directory PowerShell for Graph module has been added with two  examples to use Write-output.

Hope this helps!
Thanks
Sri

**Comment by mypil** [comment]
@GavGavGavGav  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
