### ISSUE TITLE
Teams IPs seem incorrect

### ISSUE THREAD

**Issue by jnxxx** [MicrosoftDocs/OfficeDocs-Enterprise#750]
Are you sure 13.107.64.0/18, 52.112.0.0/14 is correct?
I see connections to 52.114.0.0 instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by jnxxx** [comment]
Never mind. It is included off course... :-)

**Comment by mypil** [comment]
@jnxxx - Thank you for submitting feedback.

From your last comment, it appears that your issue has been addressed so we will close this issue now. 

Please feel free to open a new issue if you find a specific area of the docs that we can improve on by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page.
