### ISSUE TITLE
Link from other page does not properly point to here

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/OfficeDocs-Enterprise#752]
The link "Manage Skype for Business Online with Office 365 PowerShell" from this URL  https://docs.microsoft.com/en-us/SkypeForBusiness/set-up-your-computer-for-windows-powershell/set-up-your-computer-for-windows-powershell?source=docs
appears like it should point here but instead goes to a GitHub formatted page. Please review and correct. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f318af5-7da8-daec-d038-7bca3d4cabf8
* Version Independent ID: 7cb9bf9d-5b01-7cbd-fa54-cb9847b61fc2
* Content: [Manage Skype for Business Online with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell)
* Content Source: [Enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@adrianwells The https://docs.microsoft.com/en-us/SkypeForBusiness/set-up-your-computer-for-windows-powershell/set-up-your-computer-for-windows-powershell?source=docs article as been updated to link to the correct page. Thanks for letting us know.
