### ISSUE TITLE
Access to SPO

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-Enterprise#753]
Hello
Removing license to SPO does not remove access to SPO nor OneDrive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6e1db9c-8440-9547-98ab-3bfca008bd86
* Version Independent ID: 17011d6e-4978-6312-274b-586bd9e857de
* Content: [Disable access to services while assigning user licenses](https://docs.microsoft.com/en-us/office365/enterprise/powershell/disable-access-to-services-while-assigning-user-licenses)
* Content Source: [Enterprise/powershell/disable-access-to-services-while-assigning-user-licenses.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/disable-access-to-services-while-assigning-user-licenses.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Larryngolog Taking this issue internal to Microsoft for discussion and investigation. Thanks for letting us know.
