### ISSUE TITLE
shared mailbox

### ISSUE THREAD

**Issue by gnerd** [MicrosoftDocs/OfficeDocs-Enterprise#754]
Are licenses required for shared mailboxes (normally, shared mailboxes do not require a license)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85937c83-35db-0882-e226-a4f2f732de73
* Version Independent ID: ac0b646b-0fbf-eb24-6768-07cfcd51076b
* Content: [Exchange Multi-Geo](https://docs.microsoft.com/en-us/office365/enterprise/multi-geo-capabilities-in-exchange-online)
* Content Source: [Enterprise/multi-geo-capabilities-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/multi-geo-capabilities-in-exchange-online.md)
* Service: **o365-solutions**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by VLG17** [comment]
@gnerd Yes, licenses are required for shared mailboxes in a Multi-Geo scenario, according to [this article](https://techcommunity.microsoft.com/t5/security-privacy-and-compliance/multi-geo-in-exchange-online-and-onedrive/ba-p/182710).

> Licensing
> 
> USD $2/user/month for users in Satellite Geos
> Resource mailboxes (Rooms/Equipment) and Shared mailboxes need to be licensed
> Office 365 Group Mailboxes moved to Satellite Geos will need not be licensed for Multi-Geo

Although you need to keep this in mind, which was mentioned in the comments of the mentioned article:

> "Legacy" Shared Mailboxes are essentially "Shared" mailboxes that are created from the EXO Admin Center. These aren't tied to a Modern Group in Office 365. PowerShell shows the value for "RecipientTypeDetails" as "SharedMailbox"
>  
> Shared mailboxes are "Groups"...this is where a Mailbox is tied to a Modern Office 365 Group. PowerShell shows the value for "RecipientTypeDetails" as "GroupMailbox".
>  
> From a Multi-Geo licensing perspective, the mailboxes with the value "SharedMailbox" need to be licensed. 
> 

![image](https://user-images.githubusercontent.com/41186174/78242711-309db580-74eb-11ea-9708-feab0647d05e.png)

**Comment by mypil** [comment]
@gnerd  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17 so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
