### ISSUE TITLE
Email being sent from unpublished IP ranges

### ISSUE THREAD

**Issue by jimjimbojimbob** [MicrosoftDocs/OfficeDocs-Enterprise#755]
The web service which publishes the Exchange Online Protection IP ranges found here:

https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service

Currently reports the latest worldwide version as 2020022800 which reports the following ranges for inbound connections on port 25.  I have firewalls configured based on this information.

...
{
    "id": 10,
    "serviceArea": "Exchange",
    "serviceAreaDisplayName": "Exchange Online",
    "urls": [
      "*.mail.protection.outlook.com"
    ],
    "ips": [
      "40.92.0.0/15",
      "40.107.0.0/16",
      "52.100.0.0/14",
      "104.47.0.0/17",
      "2a01:111:f400::/48",
      "2a01:111:f403::/48"
    ],
    "tcpPorts": "25",
    "expressRoute": true,
    "category": "Allow",
    "required": true
  }
...

On 19th March I found email being sent from an IP address not listed in the ranges above (I have anonymised the log message):

Mar 19 21:30:17 from=<user@senderdomain.com> relay=mail-am6eur05rlyn2067.outbound.protection.outlook.com [40.95.90.67]

Can someone confirm what I'm seeing and/or update the documentation, I have multiple customers reporting emails missing and/or not being received and they configure their firewalls based on the IP ranges published via the web service.

**Comment by LauraWi** [comment]
Adding @pandrew1

**Comment by pandrew1** [comment]
The web service referenced here is for configuring network perimeter devices for client machine outbound to Office 365 service filtering. It is not provided as a comprehensive list of all Office 365 IP Addresses.

**Comment by jimjimbojimbob** [comment]
Thanks for the reply. I've slightly mis-understood then.  And in which case where is the list of IP ranges or URIs that can be referenced in order to configure network perimeter devices for inbound connections from EOP on port 25?

**Comment by pandrew1** [comment]
You can run this command to get the current IP Addresses for inbound SMTP validation: nslookup -type=TXT spf.protection.outlook.com
Please review this article for more information on Sender Policy Framework: https://docs.microsoft.com/microsoft-365/security/office-365-security/how-office-365-uses-spf-to-prevent-spoofing

**Comment by jimjimbojimbob** [comment]
Well that does make perfect sense, thank you.  However that nslookup does return the exact same IP ranges as the web service.

Also it doesn't explain why on March 19th as per my original message, mail was reported by customers as missing or not received.  I investigated and could see connection attempts on port 25 from other unpublished IP addresses in the 40.95.x.x range.  Once unblocked the missing email was delivered.

My guess is this is some sort of overflow or capacity issue as a result of the recent additional load on Office365 (Teams etc)?

However now I don't know how to configure the network perimeter devices for fear of email being missed, delayed or even lost.

(Please note I am grateful for your responses, I fully appreciate you have answered my original question and this may now be outside the scope of the Office Docs Enterprise)

**Comment by pandrew1** [comment]
@jimjimbojimbob I got an answer for you. These IP Addresses should not be in the SPF detail.

These IPs are used to send very specific type of mail: outbound messages where sender domains do not belong to the customers who sent them. We cannot block that mail altogether because of some legit auto-forwarding scenarios, but we cannot make that mail look authenticated from the receivers’ POV because that opens up a cross-customer spoofing vulnerability.

**Comment by mypil** [comment]
@jimjimbojimbob - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by pandrew1 so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
