### ISSUE TITLE
Azure ExpressRoute for Office 365

### ISSUE THREAD

**Issue by tuanna106** [MicrosoftDocs/OfficeDocs-Enterprise#756]
Please explain detail all condition we need to use Office 365 over ExpressRoute. ( exp : numbers of subscribers, license,... )

**Comment by mypil** [comment]
@tuanna106 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by tuanna106** [comment]
![Capture](https://user-images.githubusercontent.com/62473405/77230721-c91d6700-6bc8-11ea-930d-a687602972b8.PNG)

This the document link I used :"https://docs.microsoft.com/en-us/office365/enterprise/azure-expressroute". So I must finish  "ExpressRoute for Office 365 Request Form to begin a Microsoft review". So I just finish Request Form then I can use ExpressRoute for Office 365 OR I need any condition for this . Please help me clearly that.

**Comment by msbemba** [comment]
@tuanna106  Thank you for the feedback. The prerequisites and checklist for implementing the Azure express route are outlined in the below document.

There are no specific limits on how many licenses or subscribers 

https://docs.microsoft.com/en-us/azure/expressroute/expressroute-prerequisites

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@tuanna106 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
