### ISSUE TITLE
New GEO CHE

### ISSUE THREAD

**Issue by NoahGo-us** [MicrosoftDocs/OfficeDocs-Enterprise#758]
List needs to be updated for new CHE Geo

**Comment by mypil** [comment]
@NoahGo-us - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by NoahGo-us** [comment]
https://docs.microsoft.com/en-us/office365/enterprise/office-365-multi-geo

**Comment by mypil** [comment]
@NoahGo-us - Thank you for submitting feedback.

Please check on PR #759 which may resolve your issue once the PR will be merged by the author.

**Comment by mypil** [comment]
@NoahGo-us - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/d449a011f9b45cecd5ef6a9a7ee17bdacfa025c7. 


Thank you for your contribution to make the docs better! Much appreciated!
