### ISSUE TITLE
How to check if SAML1.1 is already enabled or not

### ISSUE THREAD

**Issue by guptas-abhishek** [MicrosoftDocs/OfficeDocs-Enterprise#76]
Hi,
 I had enabled SAML1.1 in my environment but for some reason, had to delete the Enterprise application in Azure.  I am not sure what is the state of the protocol and how to update it as  I can see that you are using Object ID as a parameter in enabling the protocol.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by guptas-abhishek** [comment]
To Add, getting the below error while trying to remove the service principal (4th step in your sample)-- 

PS Z:\CGAS\Abhi\Client ID and Secret> Remove-PolicyFromServicePrincipal -policyId $saml2policyid -servicePrincipalId $objectid
AssignPolicyToEntity: Using graph endpoint: https://graph.windows.net entity: servicePrincipals entityId: 5cfd7af1-024c-438d-b49b-c26036a981ee
HTTP DELETE https://graph.windows.net/myorganization/servicePrincipals/5cfd7af1-024c-438d-b49b-c26036a981ee/$links/policies/@{objectId=4f676f53-586a-48d9-b586-39292abfa92
1}?api-version=1.6
Invoke-RestMethod : {"odata.error":{"code":"Request_UnsupportedQuery","message":{"lang":"en","value":"Unsupported referenced-object resource identifier for link 
property 'policies'."}}}
At Z:\CGAS\Abhi\Client ID and Secret\MSGraphTokenLifetimePolicy.psm1:339 char:15
+     $result = Invoke-RestMethod @parameters
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Any thoughts please?

**Comment by kaevans** [comment]
@guptas-abhishek You can use the PowerShell sample cmdlets as provided. These PowerShell commands are simply wrappers to call the Azure AD Graph API. I find it easier to go to the [Azure AD Graph Explorer](https://graphexplorer.azurewebsites.net/) and run queries directly. The [API to list policies assigned to a principal] is documented (https://msdn.microsoft.com/en-us/library/azure/ad/graph/api/policy-operations#list-policies-assigned-to-application-or-service-principal). 

As an example, I run a GET query in Azure AD Graph Explorer using the object ID of the application registration:

https://graph.windows.net/myorganization/servicePrincipals/a27fc4bb-b766-43e6-8791-7eb496267f08/policies

The result:

![image](https://user-images.githubusercontent.com/7107098/41049603-e78a321e-6976-11e8-85f6-df43763f2661.png)

You can use the output from the PowerShell commands to test running the same queries in the Azure AD Graph Explorer.

**Comment by MSFTTracyP** [comment]
If you’re still getting this error – I’m not sure from further responses – remove all the variable references and replace them with actual IDs. It sounds like either we’re calling on something that doesn’t exist, or something is missing, so let’s be explicit.

Thanks,
Tracy

________________________________

**Comment by moojjoo** [comment]
MSFTTracyP I found the following as a viable solution:

1. https://graphexplorer.azurewebsites.net/
2. Run the query 
`https://graph.windows.net/myorganization/policies`
3. Take note of the objectID - 
`{
    "odata.metadata": "https://graph.windows.net/myorganization/$metadata#directoryObjects/Microsoft.DirectoryServices.Policy",
    "value": [
        {
            "odata.type": "Microsoft.DirectoryServices.Policy",
            "objectType": "Policy",
            "objectId": "**dbb8ebb5-9a98-4c4b-b17c-XXXXXXXXX**",
            "deletionTimestamp": null,
            "alternativeIdentifier": null,
            "definition": [
                "{\"TokenIssuancePolicy\":{\"TokenResponseSigningPolicy\":\"TokenOnly\",\"SamlTokenVersion\":\"1.1\",\"SigningAlgorithm\":\"http://www.w3.org/2001/04/xmldsig-more#rsa-sha256\",\"Version\":1}}"
            ],
            "displayName": "SPSAML11",
            "isTenantDefault": false,
            "keyCredentials": [],
            "type": "TokenIssuancePolicy"
        }
    ]
}`

4. Try running the PowerShell Script, but replace $policy.objectID with the actual ID from above - 
`Import-Module <file path of Initialize.ps1> 
$objectid = "<Application Object ID from Table 1>"
$saml2policyid = Get-PoliciesAssignedToServicePrincipal -servicePrincipalId $objectid | ?{$_.displayName -EQ "TokenIssuancePolicy"} | select objectId
Remove-PolicyFromServicePrincipal -policyId $saml2policyid -servicePrincipalId $objectid
$policy = Add-TokenIssuancePolicy -DisplayName SPSAML11 -SigningAlgorithm "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" -TokenResponseSigningPolicy TokenOnly -SamlTokenVersion "1.1"
Set-PolicyToServicePrincipal -policyId "**dbb8ebb5-9a98-4c4b-b17c-XXXXXXXXX**" -servicePrincipalId $objectid`

Make sure you only have "1" Policy applied to your **myorganization**.  If you have more than one you need to make sure you use the Graph to DELETE them all and then start again.  That is what we had to do to get this working.

**Comment by MSFTTracyP** [comment]
Oh, that’s well done! Thank you for letting me know – very helpful!

**Comment by kaevans** [comment]
@moojjoo @MSFTTracyP any suggestions on making the PowerShell less error prone? There have been multiple issues raised about the code getting into a state where the SAML 2.0 policy was removed, a SAML 1.1 policy was added, and someone runs the script again and gets an error. Perhaps we just remove any existing SAML policy instead of querying for a SAML 2.0 policy? There have also been issues where using the variable doesn't work for some people and replacing the string literal fixes it.

**Comment by guptas-abhishek** [comment]
@kaevans 
Thanks for all your comments and yes  unfortunately it looks dead straight but still a lot of people are facing issues in removing / adding a new token etc etc

Coming back to this issue,  as  Is aid  i earlier had added SAML1.1  but the output on AzureAD graph Explorer . This doesn't give me any clues regarding SAML1.1 token as shown in your snippet...


![image](https://user-images.githubusercontent.com/35603214/41108620-8f08d1c4-6a64-11e8-9ff4-7275f0f1e244.png)

**Comment by kaevans** [comment]
@guptas-abhishek yes, it's ok to have that many policies in the organization. However, a single service principal can only have a single TokenIssuancePolicy assigned, and that can be either 1.1 or 2.0.

**Comment by kaevans** [comment]
Updated sample code to avoid errors and to include output text to make it easier to see what is happening.  [PR 78](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/78)
