### ISSUE TITLE
Should we be using using the AzureAz module?

### ISSUE THREAD

**Issue by swinster** [MicrosoftDocs/OfficeDocs-Enterprise#764]
As the subject? This is now release and preferred to Azure AD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by swinster** [comment]
I guess without the old AzureAD module installed, you wont be able to even run `Connect-MsolService`

So what does this mean? Do you need to run AzureAD and AzureAZ side-by-side? Is that even possible?

**Comment by swinster** [comment]
Ok the above is relate to #765 as you stated that "PS version 5.1 or higher" should be use, but PS 6/7 is not supported :(

Still, I guess Azure Az will be the future here?

**Comment by JoeDavies-MSFT** [comment]
Article updated to include installing the AzureAz module as an alternative to the separate Azure Active Directory PowerShell for Graph. Thanks for letting us know.
