### ISSUE TITLE
Connecting to `Connect-MsolService` using PS 7 fails - Could not load type 'System.Security.Cryptography.SHA256Cng' 

### ISSUE THREAD

**Issue by swinster** [MicrosoftDocs/OfficeDocs-Enterprise#765]
Attempting to connect with these old methods to O365 fails in PS7

```
Connect-MsolService: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-gb/office365/enterprise/powershell/connect-to-office-365-powershell)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by swinster** [comment]
The docs above state:
> You must use PowerShell version 5.1 or later.
Note: Not "Windows" PowerShell

But then go onto say:
>PowerShell Core does not support the Microsoft Azure Active Directory Module for Windows PowerShell module and cmdlets with Msol in their name. 

Will this be available to work for PS6/7?

**Comment by JoeDavies-MSFT** [comment]
Article updated to include information about PowerShell 7. Thanks for letting us know.
