### ISSUE TITLE
Dynamics 365

### ISSUE THREAD

**Issue by lubergst** [MicrosoftDocs/OfficeDocs-Enterprise#766]
Do we have a public facing architecture of Dynamics 365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 096f9573-ba23-b0a0-23dc-7b0eb57a17d8
* Version Independent ID: 45643fe7-700e-8eca-b7b9-563327472d6b
* Content: [Microsoft cloud IT architecture resources](https://docs.microsoft.com/en-us/office365/enterprise/microsoft-cloud-it-architecture-resources?source=docs#feedback)
* Content Source: [Enterprise/microsoft-cloud-it-architecture-resources.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/microsoft-cloud-it-architecture-resources.md)
* Service: **o365-solutions**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by JoeDavies-MSFT** [comment]
@lubergst Not at this time. I will forward this request to the Dynamics 365 team. Thanks for your question.
