### ISSUE TITLE
Need to allow business.bing.com?

### ISSUE THREAD

**Issue by taisino** [MicrosoftDocs/OfficeDocs-Enterprise#767]
When I use sharepoint online, I can see the traffic to business.bing.com from sharepoint page.
Should this FQDN be allowed, or optional?
Please give the explanation of this FQDN.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@taisino Taking this investigation and its discussion internal to Microsoft.
