### ISSUE TITLE
Error in this page

### ISSUE THREAD

**Issue by smashingly** [MicrosoftDocs/OfficeDocs-Enterprise#77]
Hi, the following text is incorrect:

"There are two choices for connectivity to Microsoft cloud platforms and services: your existing Internet pipe and ExpressRoute. Use an ExpressRoute connection if predictable performance is important. You can use one ExpressRoute connection to connect directly to Microsoft SaaS services (Office 365 and Dynamics 365), Azure PaaS services, and Azure PaaS services."

The last three words should read "Azure IaaS services".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e8c817-6a71-c857-23ea-1615d6f2c9cb
* Version Independent ID: bcce4f9e-41eb-3670-58d2-7a0a66c2ce6c
* Content: [Architecture of Microsoft hybrid cloud scenarios](https://docs.microsoft.com/en-us/office365/enterprise/architecture-of-microsoft-hybrid-cloud-scenarios)
* Content Source: [Enterprise/architecture-of-microsoft-hybrid-cloud-scenarios.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/architecture-of-microsoft-hybrid-cloud-scenarios.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@smashingly This has been corrected and published. Thanks for letting me know. Joe
