### ISSUE TITLE
Incorrect download link to old version

### ISSUE THREAD

**Issue by ziggynemeth** [MicrosoftDocs/OfficeDocs-Enterprise#772]
The download link on this page points to old v1.11.6579.29793. It should point to GitHub v2.1.2.0 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c937e8be-1696-c315-a93b-88f083279644
* Version Independent ID: c0c3d253-4bfe-1750-58a1-4d8f4a1e68d6
* Content: [Download and run the Office 365 IdFix tool](https://docs.microsoft.com/en-us/office365/enterprise/install-and-run-idfix#feedback)
* Content Source: [Enterprise/install-and-run-idfix.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/install-and-run-idfix.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@ziggynemeth Article is updated for the GitHub repository and with instructions to download. Thanks so much for letting us know.
