### ISSUE TITLE
Update required to script for checking MSOnline module version

### ISSUE THREAD

**Issue by Manaf-Ibrahim** [MicrosoftDocs/OfficeDocs-Enterprise#773]
The path for this script needs to be changed as the module files are no longer located in System32 but rather this path:

C:\Program Files\WindowsPowerShell\Modules\MSOnline\1.1.183.57\Microsoft.Online.Administration.Automation.PSModule.dll

The script in the current documentation returns this output:

Get-Item : Cannot find path 'C:\Program 
Files\WindowsPowerShell\Modules\MSOnline\Microsoft.Online.Administration.Automation.PSModule.dll' 
because it does not exist.
At line:1 char:2
+ (Get-Item "C:\Program Files\WindowsPowerShell\Modules\MSOnline\Micros ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...on.PSModule.dll:String) [Get-Item] 
   , ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell#feedback)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Manaf-Ibrahim  Added text for the error and how to check the version for more modern versions of the MSOnline module. Thanks so much for letting us know.
