### ISSUE TITLE
Teams client update version number

### ISSUE THREAD

**Issue by pratikdedhia1987** [MicrosoftDocs/OfficeDocs-Enterprise#779]
Can we document the version number of the update that will include the fix ?

A current requirement for this to work in 100% of scenarios is to also add the IP range 13.107.60.1/32. This should not be necessary very shortly due to an update in the latest Teams client due for release w/c March 30 2020.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83a36fa1-0345-87d0-7fea-cca68bfe1915
* Version Independent ID: 0eaabf4b-4c4d-06d5-b877-56a7657eceaf
* Content: [Implementing VPN split tunnelling for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/office-365-vpn-implement-split-tunnel#feedback)
* Content Source: [Enterprise/office-365-vpn-implement-split-tunnel.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-vpn-implement-split-tunnel.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by PaulCollinge** [comment]
We'll update the article with this information as soon as it's known which should be within the next week.

**Comment by optiimusprime** [comment]
This is really useful. Thank you. Any chance of getting a howto guide for Fortigate? Also, if we restrict selective split tunnelling say only for MS Teams (scenario 2), this means any O365 url other than MS Teams would still traverse the VPN and go out to the internet via the corporate proxy? Just wondering how the user experience might be in this case.

**Comment by kelleyvice-msft** [comment]
@optiimusprime - RE Fortigate guidance, we've been adding links to vendor-specific Office 365 split tunneling guidance as it becomes available. I don't think Fortinet has published guidance specific to Office 365, but they do offer general split-tunneling guidance on their website. 

The answer to your second question is yes, and user experience for such a configuration will depend on many variables and will be specific to your network. See https://docs.microsoft.com/en-us/Office365/Enterprise/office-365-vpn-implement-split-tunnel#testing for information on how to get performance information for your specific configuration. Generally speaking, Internet traffic over the VPN tunnel will always experience higher latency to some degree.

**Comment by optiimusprime** [comment]
@kelleyvice-msft - Thanks for that

**Comment by mypil** [comment]
@pratikdedhia1987 @optiimusprime - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @PaulCollinge and @kelleyvice-msft so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
