### ISSUE TITLE
time is usually expressed in time units ;-)

### ISSUE THREAD

**Issue by rafalfitt** [MicrosoftDocs/OfficeDocs-Enterprise#780]
Time to Impact (in bytes/sec)
IMHO it should be seconds

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8836f0de-d00c-e6c6-984b-581a120bef7c
* Version Independent ID: 885bdef5-4c1e-abf7-cfd6-1cee68a030a1
* Content: [Office 365 Core Principles of Defense Against Denial-of-Service Attacks](https://docs.microsoft.com/en-us/office365/enterprise/office-365-core-principles-of-defense-against-dos-attacks)
* Content Source: [Enterprise/office-365-core-principles-of-defense-against-dos-attacks.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-core-principles-of-defense-against-dos-attacks.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@rafalfitt Thank you for the feedback. We have modified the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/840

Thanks
Sri

**Comment by mypil** [comment]
@rafalfitt - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/bc9735cbd99b949cdecdfb25663cb15ecaece133. 


Thank you for your contribution to make the docs better! Much appreciated!
