### ISSUE TITLE
What about iPadOS? It's now separate from iOS so does it need to have its own bullet?

### ISSUE THREAD

**Issue by bingoglossy** [MicrosoftDocs/OfficeDocs-Enterprise#783]
What about iPadOS? It's now separate from iOS so does it need to have its own bullet?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c554e4c6-b078-134a-dd27-43310c93aa45
* Version Independent ID: a55042c0-f1f4-5750-5a03-fe9fad687367
* Content: [Office 365 Client App Support — Modern Authentication](https://docs.microsoft.com/en-us/office365/enterprise/office-365-client-support-modern-authentication#feedback)
* Content Source: [Enterprise/office-365-client-support-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-client-support-modern-authentication.md)
* Service: **office 365 administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@bingoglossy Thank you for the feedback. We have made changes to the doc via PR#https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/839

Thanks
Sri

**Comment by mypil** [comment]
@bingoglossy - Thank you for submitting feedback.

Please see the response from the author based on this https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/839#issuecomment-630316249 so we are going to close this issue.

Thank you for helping us improve the documentation!
