### ISSUE TITLE
Mising IP addresses

### ISSUE THREAD

**Issue by Clickbaitcake** [MicrosoftDocs/OfficeDocs-Enterprise#785]
IPs in 144 range are missing from this list. Microsoft teams communicates to these addresses.

52.114.119.85
52.114.144.88

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Clickbaitcake The address block starting with 52.114 is included in the 52.112.0.0/14 block that is listed. Thanks for you question.
