### ISSUE TITLE
Move Yammer bubble higher on the page

### ISSUE THREAD

**Issue by dab-ms** [MicrosoftDocs/OfficeDocs-Enterprise#786]
Hi team,

Can we request the Yammer Note bubble is moved to a more prominent position on the page i.e. underneath other Notes?

The page is quite long vertically so the Yammer note may go unnoticed as it did with a recent customer interaction I had. I am referring to

"Note For recommendations on Yammer IP addresses and URLs, see this blog post."

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?source=docs)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@dab-ms Based on our automated publishing system for the lists of endpoints, I can't insert the Skype note between the sections of lists. It needs to remain where it is. Thanks for your question.
