### ISSUE TITLE
The 

### ISSUE THREAD

**Issue by artproton33** [MicrosoftDocs/OfficeDocs-Enterprise#789]
[ป้อนคำติชมที่นี่]

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: c554e4c6-b078-134a-dd27-43310c93aa45
* Version Independent ID: a55042c0-f1f4-5750-5a03-fe9fad687367
* Content: [Office 365 Client App Support — Modern Authentication](https://docs.microsoft.com/th-th/office365/enterprise/office-365-client-support-modern-authentication)
* Content Source: [Enterprise/office-365-client-support-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-client-support-modern-authentication.md)
* Service: **office 365 administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@artproton33 - คุณช่วยกรุณาแบ่งปันปัญหาเฉพาะที่คุณมีกับเอกสารนี้หรือไม่

**Comment by mypil** [comment]
@artproton33 - เราขอขอบคุณข้อเสนอแนะใด ๆ ที่ปรับปรุงเนื้อหาในเอกสาร Microsoft แต่เราไม่ได้มีการตอบสนองใด ๆ จากคุณเพื่อให้เราจะปิดปัญหานี้

หากมีพื้นที่เฉพาะของเอกสารที่เราสามารถปรับปรุงได้โปรดเปิดประเด็นใหม่โดยคลิกที่ส่วนข้อเสนอแนะในเอกสาร Microsoft เฉพาะซึ่งพบที่ด้านล่างของหน้า ขอบคุณ

[We appreciate any suggestions for improving the content in the Microsoft documentation, but we do not have any response from you so we will close this issue.

If there is a specific area of the document that we can improve, please open a new issue by clicking on the feedback section on the specific Microsoft document found at the bottom of the page. Thank you.]
