### ISSUE TITLE
URL(s) for non-O365 recipients

### ISSUE THREAD

**Issue by felgar73** [MicrosoftDocs/OfficeDocs-Enterprise#790]
Can you provide more details on what is required from external, non-O365 recipients (Google, Exch on-prem, etc.) to decrypt or access the OME portal and request the OTP? Is there a specific URL or URLs that are needed to be allowed via firewall such as, "*outlook.office365.com/Encryption/", which is what I see in my testing, but is not exactly documented?
-Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@felgar73 Taking this issue up for internal Microsoft discussion. Thanks for letting us know.

**Comment by felgar73** [comment]
Thanks!

-Felix G.
