### ISSUE TITLE
Add Windows Native Mail Client to the List

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/OfficeDocs-Enterprise#795]
I can't seems to find Windows Native Mail Client in the list although for sure it is  one of the Windows Apps which does support modern authentication when we sign-in.

Could we get this document updated to add Add Windows Native Mail Client to the List.

This indeed would be helpful as many customer's are in process of evaluating their environment for clients and applications that supports modern auth in awake of basic auth to be disabled in future for exchange online.

**Comment by mypil** [comment]
@qaehtesh - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by qaehtesh** [comment]
I am referring to modern auth app doc below
Office 365 Client App Support - Modern Authentication
https://docs.microsoft.com/en-us/office365/enterprise/office-365-client-support-modern-authentication

**Comment by msbemba** [comment]
@qaehtesh Thank you for the feedback. This document pertains only to Office 365 Applications so the windows native app isn't added to the list.

Hope this helps!

Thanks
Sri

**Comment by qaehtesh** [comment]
Thank you Sri, is there a documentation referring to windows native apps with modern auth, I couldn't find one.

**Comment by msbemba** [comment]
@qaehtesh  I could not find one pertaining to Windows Mail Application. I was able to test and it supports Modern authentication.

Thanks
Sri

**Comment by qaehtesh** [comment]
Thanks Sri, yes it works and have confirmed that it is supported , it is just that there is no public documentation for it.
So it becomes reactive where customer opening a ticket to ask with support rather proactively finding a documentation themselves which do not exist, that's why i was trying to get this updated

**Comment by msbemba** [comment]
@qaehtesh We have requested the author of the below document to update about Modern auth support. You should see an update on it soon.

https://support.office.com/en-us/article/set-up-email-in-the-mail-app-for-windows-10-7ff79e8b-439b-4b47-8ff9-3f9a33166c60

Thanks
Sri

**Comment by mypil** [comment]
@qaehtesh - Thank you for submitting feedback.

This doc - https://support.office.com/en-us/article/set-up-email-in-the-mail-app-for-windows-10-7ff79e8b-439b-4b47-8ff9-3f9a33166c60 does not belong to the Enterprise repo. However, as mentioned by @msbemba, we have already engaged the author for that doc you wanted to be updated about this feedback. We will close this issue now.

Thank you for your contribution to make the docs better! Much appreciated!
