### ISSUE TITLE
Problems with Step 6

### ISSUE THREAD

**Issue by stevep4** [MicrosoftDocs/OfficeDocs-Enterprise#8]
Really excited to try and get this working, but I'm stuck on Step 6.
Get-PoliciesAssignedToServicePrincipal is giving "Request_ResourceNotFound" - "Resource 'defaultPolicy' does not exist...". The objectid is definitely correct.
Could you suggest other ways to achieve changing the issuance policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* [Content](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* [Content Source](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: o365-solutions

**Comment by stevep4** [comment]
Many thanks Kirk, that seems to have done the trick! :-)

Could you comment on licencing please?
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-acs-migration
Seems to indicate that what we've done in this article would require Azure AD Premium license? If so, that scuppers me as I only have AAD Basic. :-(

**Comment by kaevans** [comment]
From the article you referenced:  "This approach requires an Azure AD Premium license. If you are an Access Control customer and you require a premium license for setting up single-sign on for an application, contact us. We'll be happy to provide developer licenses for you to use." For more information on features in the various SKUs, see https://azure.microsoft.com/en-us/pricing/details/active-directory/.
