### ISSUE TITLE
Splendid documentation

### ISSUE THREAD

**Issue by gramosvishay** [MicrosoftDocs/OfficeDocs-Enterprise#80]
Superb, absolute gold.  Wonderfully documented, tremendously easy to follow and reproduce.  I am deeply appreciative for all the hard work that went into this effort.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 136007e4-4ddd-a1d8-a3ac-251da6bd5311
* Version Independent ID: 5c1ec643-ac23-cf7c-c787-3ffb1b4f9674
* Content: [Base Configuration dev/test environment](https://docs.microsoft.com/en-us/office365/enterprise/base-configuration-dev-test-environment)
* Content Source: [Enterprise/base-configuration-dev-test-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/base-configuration-dev-test-environment.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
Thanks very much for the feedback, gramosvishay!
