### ISSUE TITLE
Conditional Access - Based on Named Locations / Trusted IP

### ISSUE THREAD

**Issue by dneto82** [MicrosoftDocs/OfficeDocs-Enterprise#802]
Hi. Great news. But wasn't clear to me, how this will work with Conditional Access Ruled based on Named Locations / Trusted IPs source.

If select "Optimize" to split tunneling, how this will affect conditional access rules based on source IP/Named Locations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b1a1d14-d150-f90f-dce5-c2b2c12600f9
* Version Independent ID: 0966ffd4-9173-912e-9c8f-5f5928bb45ad
* Content: [Overview: VPN split tunnelling with Office 365](https://docs.microsoft.com/en-us/Office365/Enterprise/office-365-vpn-split-tunnel#feedback)
* Content Source: [Enterprise/office-365-vpn-split-tunnel.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-vpn-split-tunnel.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@dneto82 - Thank you for submitting feedback.  

PR #806 has been created by @MartinRinas to resolve this issue once the PR is merged.



Thank you and we appreciate your contribution to make the docs better!

**Comment by mypil** [comment]
@dneto82 - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/8e1778101ad791e4ad2872621aea621465795d18. 


Thank you for your contribution to make the docs better! Much appreciated!
