### ISSUE TITLE
 correct the word  "the latest cummulative " to "the latest cumulative "

### ISSUE THREAD

**Issue by musashiharuno** [MicrosoftDocs/OfficeDocs-Enterprise#803]
wrong spell, please correct the word  "the latest cummulative " to "the latest cumulative "

•	All Exchange servers must have the latest cumulative updates installed, see Upgrade Exchange to the latest Cumulative Updates to find and manage all available updates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626caf29-7e88-0b56-2013-5c5b7c2a5917
* Version Independent ID: 2376192f-793d-0166-46c7-870cd0c41abb
* Content: [Hybrid Modern Authentication overview and prerequisites for use with on-premises Skype for Business and Exchange servers](https://docs.microsoft.com/en-us/office365/enterprise/hybrid-modern-auth-overview#feedback)
* Content Source: [Enterprise/hybrid-modern-auth-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/hybrid-modern-auth-overview.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
Typo corrected. Thanks, @musashiharuno!
