### ISSUE TITLE
Could you add description/purposes for these lines?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-Enterprise#804]
Hi,
Is there any change that you could add a description to each of those lines? That would be much more informative for us. E.g. when smtp.office365.com TCP: 587 is really needed? Currently when looking for my Outlook's connection statuses it shows only "HTTP".
![image](https://user-images.githubusercontent.com/43988151/79312218-3e016980-7f07-11ea-8517-3e5aea226a29.png)

But still you have marked that port as "**Allow required**"? 

Could you please be a bit helpful and share that information for us.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Petri-X I will pass your suggestion to the product team. Currently, the automated process that creates these tables does not include this information.
