### ISSUE TITLE
Missing IDs?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-Enterprise#805]
Hi,
When looking for the list of the networks and hosts, you have the ID on the row. But quite fast you could see that there are missing IDs from the list: 4, 7, 20, 21, 23, etc...

Is there a reason for that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Petri-X The ID numbers are used for internal purposes. For example, a missing ID number can indicate a block of endpoints that are no longer being used. Thanks for your question.
