### ISSUE TITLE
04/15/2020 Feed Service is down, Internal Server Error

### ISSUE THREAD

**Issue by jdcoats** [MicrosoftDocs/OfficeDocs-Enterprise#807]
04/15/2020 Feed Service is down, Internal Server Error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7ebf92c-e478-0f65-0494-97042e974b46
* Version Independent ID: 7e1b9b91-d60d-8665-9a39-2ca77a46b4ce
* Content: [Office 365 IP Address and URL web service](https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service)
* Content Source: [Enterprise/office-365-ip-web-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
Confirmed. I will touch base with engineering and update this issue.

**Comment by kelleyvice-msft** [comment]
Engineering is working on the problem. I will reply to this issue when there is more information or the problem is resolved. Thanks for reporting the problem, @jdcoats!

**Comment by kelleyvice-msft** [comment]
The issue has been mitigated, and I have confirmed. Thank you for reporting this, @jdcoats.

**Comment by jdcoats** [comment]
this issue is recurring. The feed is still failing https://endpoints.office.com/endpoints/worldwide
It did work for a minute but I've noticed it not being consistent.

**Comment by jdcoats** [comment]
@kelleyvice-msft this issue is still happening intermittently.

**Comment by kelleyvice-msft** [comment]
Thanks @jdcoats - I will let engineering know. I know they are still working on resolving the root cause, but it sounds like the mitigation is not resilient.
