### ISSUE TITLE
Exchange V2 Module

### ISSUE THREAD

**Issue by RaghuramP** [MicrosoftDocs/OfficeDocs-Enterprise#808]
Update the document to promote use of Exchange V2 module, rather than V1 that uses legacy authentication.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c551eb1-7ac5-cb02-cd1b-d67ca3886d85
* Version Independent ID: fb690e2e-420e-f697-60f2-39520283d385
* Content: [Connect to all Office 365 services in a single Windows PowerShell window](https://docs.microsoft.com/en-gb/office365/enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window?redirectedfrom=MSDN#feedback)
* Content Source: [Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@RaghuramP The article has been updated to use the Exchange Online V2 module and commands. Thanks so much for the suggestion.
