### ISSUE TITLE
set usage location first.

### ISSUE THREAD

**Issue by jmthia** [MicrosoftDocs/OfficeDocs-Enterprise#809]
Hello, 
To avoid error and the error action, I first set the usage location and the assign the license.
Regards,
Jean Marie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6e1db9c-8440-9547-98ab-3bfca008bd86
* Version Independent ID: 17011d6e-4978-6312-274b-586bd9e857de
* Content: [Disable access to services while assigning user licenses](https://docs.microsoft.com/en-us/office365/enterprise/powershell/disable-access-to-services-while-assigning-user-licenses#feedback)
* Content Source: [Enterprise/powershell/disable-access-to-services-while-assigning-user-licenses.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/disable-access-to-services-while-assigning-user-licenses.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@jmthia Each of the command blocks set the location with the "$usageLocation=$user.UsageLocation" command. Can you tell me which block you are using and which error you are getting?

**Comment by jmthia** [comment]
HI @JoeDavies-MSFT, 
yes each block set the location after setting the licence
Set-MsolUserLicense -UserPrincipalName $userUpn -AddLicenses $accountSkuId -ErrorAction SilentlyContinue
Sleep -Seconds 5
Set-MsolUserLicense -UserPrincipalName $userUpn -LicenseOptions $licenseOptions -ErrorAction SilentlyContinue
Set-MsolUser -UserPrincipalName $userUpn -UsageLocation $usageLocation

but so using EA silently continue, you does  see the self explanatory error message...
running : Set-MsolUserLicense -UserPrincipalName $upn -AddLicenses $F1
i do have this error
Set-MsolUserLicense : You must provide a required property: Parameter name: UsageLocation
Au caractère E:\WorkDatas\Items\O365\PoSh\DemandesTeams\userLicense.ps1:90 : 9
+         Set-MsolUserLicense -UserPrincipalName $upn -AddLicenses $F1
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Set-MsolUserLicense], MicrosoftOnlineException
    + FullyQualifiedErrorId : Microsoft.Online.Administration.Automation.RequiredPropertyNotSetException, 
   Microsoft.Online.Administration.Automation.SetUserLicense
and of course another error when running the other part
Set-MsolUserLicense -UserPrincipalName $upn -LicenseOptions $F1licenseOptions
Set-MsolUserLicense : Unable to assign this license because the license options are invalid.
Au caractère E:\WorkDatas\Items\O365\PoSh\DemandesTeams\userLicense.ps1:93 : 9
+         Set-MsolUserLicense -UserPrincipalName $upn -LicenseOptions $ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Set-MsolUserLicense], MicrosoftOnlineException
    + FullyQualifiedErrorId : Microsoft.Online.Administration.Automation.InvalidUserLicenseOptionExceptio 
   n,Microsoft.Online.Administration.Automation.SetUserLicense
after setting the location, if you rerun the block, it will work.

So the good order of the command in the block is
        #set user location
        Set-MsolUser -UserPrincipalName $upn -UsageLocation 'FR'
        # set user license
        Set-MsolUserLicense -UserPrincipalName $upn -AddLicenses $F1 
        sleep -Seconds 4
        Set-MsolUserLicense -UserPrincipalName $upn -LicenseOptions $F1licenseOptions
        
I even removed the error action as the is no error, and if any we must catch it. I have not try setting a wrong licence or over subscribe to a licence.

Hope this helps,
Jean Marie

**Comment by JoeDavies-MSFT** [comment]
@jmthia I revised the code blocks to remove the use of usage location entirely. The Set-MsolUser command is not needed to set licensing configuration on a user account.
