### ISSUE TITLE
Missing service MSol

### ISSUE THREAD

**Issue by martensnico** [MicrosoftDocs/OfficeDocs-Enterprise#81]
Hi, great article. I used this to create my own personal auto-logging in feature using this article. However, I found I was missing the Msol cmdlets (for getting users / changing licenses etc).
Maybe you can add the Connect-MSolService in here as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c551eb1-7ac5-cb02-cd1b-d67ca3886d85
* Version Independent ID: fb690e2e-420e-f697-60f2-39520283d385
* Content: [Connect to all Office 365 services in a single Windows PowerShell window](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window)
* Content Source: [Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
Thank you for the feedback, martensnico! We are looking into this.

**Comment by JoeDavies-MSFT** [comment]
@martensnico,  Connecting with Msol-ConnectService added as an alternative throughout. Thanks for letting us know. Joe
