### ISSUE TITLE
Amount of users/seats minimum

### ISSUE THREAD

**Issue by jopgommans** [MicrosoftDocs/OfficeDocs-Enterprise#811]
This article states there is a requirement of 500 EA users, whereas the latest information and the paper on the MS site states a 250 minimum. You might want to update that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdf84db6-c7e8-9a68-0b60-eb0af2de593a
* Version Independent ID: bc0ed520-fccd-c390-b706-71ddfeab4085
* Content: [Office 365 Multi-Geo](https://docs.microsoft.com/en-us/office365/enterprise/office-365-multi-geo#feedback)
* Content Source: [Enterprise/office-365-multi-geo.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-multi-geo.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by cimares** [comment]
Just to support this, the O365 blog was released last Wed 15th April with the updated limits.. though the marketing pages still show 500 too!

https://techcommunity.microsoft.com/t5/blogs/blogarticleprintpage/blog-id/Office365Blog/article-id/2176

**Comment by msbemba** [comment]
@jopgommans  Thank you for your feedback. We corrected the minimum requirement on the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/850

Thanks
Sri

**Comment by mypil** [comment]
@jopgommans @cimares - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/e76970620c9d7f6858daa7676cee51828bb69f6a. 


Thank you for your contribution to make the docs better! Much appreciated!
