### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by jopgommans** [MicrosoftDocs/OfficeDocs-Enterprise#812]
Additionally: I am having a hard time finding pricing information. Putting a reference to pricing information would add to the quality of this article in my opinion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdf84db6-c7e8-9a68-0b60-eb0af2de593a
* Version Independent ID: bc0ed520-fccd-c390-b706-71ddfeab4085
* Content: [Office 365 Multi-Geo](https://docs.microsoft.com/en-us/office365/enterprise/office-365-multi-geo#feedback)
* Content Source: [Enterprise/office-365-multi-geo.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-multi-geo.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@jopgommans  Thank you for your feedback. We have added a note to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/850

Thanks
Sri
