### ISSUE TITLE
Data Move Eligibility

### ISSUE THREAD

**Issue by testtenant** [MicrosoftDocs/OfficeDocs-Enterprise#813]
Would it be possible for tenant / organization way back 2015 to be eligible and request for data move when it was created and the geo is not available before as an option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 186af886-1433-eb0d-030f-e828a03be906
* Version Independent ID: d5c4cc30-bd40-27ed-c3dc-81e54633b50a
* Content: [Data move general FAQ](https://docs.microsoft.com/en-us/office365/enterprise/data-move-faq#feedback)
* Content Source: [Enterprise/data-move-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/data-move-faq.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by andybergen** [comment]
Yes, if the tenant signup country is valid.
