### ISSUE TITLE
Remove All Licenses From All Users Command Not Working

### ISSUE THREAD

**Issue by lewislivingstone** [MicrosoftDocs/OfficeDocs-Enterprise#814]
Hey,

I had some issues with your command to remove licenses from all users. I kept getting errors which I sadly did not take a screenshot of but basically it wouldn't allow me to remove multiple licenses when separated by commas and also if some of your users have different licenses assigned, it can cause issues if you try and remove a license that doesn't exist for that user.

Therefore, I re-wrote the script to the following:
$users = Get-MsolUser -All | where {$_.isLicensed -eq $true}
foreach($user in $users)
{
$licenses = $user.Licenses.AccountSkuId
foreach ($lic in $licenses)
{
Set-MsolUserLicense -UserPrincipalName $user.UserPrincipalName -RemoveLicenses $lic
}
}

This has worked for me without fail on multiple tenancies.

Lewis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90144912-28c3-e215-7763-12beddc645c7
* Version Independent ID: c2aa496c-51d4-ffd9-9b06-e3a7097d027a
* Content: [Remove licenses from user accounts with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell#feedback)
* Content Source: [Enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@lewislivingstone The article has been updated with your code. Thanks so much for your effort.
