### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by fbrusa** [MicrosoftDocs/OfficeDocs-Enterprise#816]
Link on "choosing PHS" is broken, it gives a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bd2f66d-c853-21ff-7f74-ccb1359af4e1
* Version Independent ID: 807303e4-fbf8-ad2c-de8a-5ed65ad9216e
* Content: [Hybrid identity and directory synchronization for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/plan-for-directory-synchronization#feedback)
* Content Source: [Enterprise/plan-for-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/plan-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@fbrusa This has been corrected. Thanks so much for letting us know.
