### ISSUE TITLE
Firewall doesn't support URLs

### ISSUE THREAD

**Issue by ioshi13** [MicrosoftDocs/OfficeDocs-Enterprise#817]
What if the firewall doesn't support URLs, do you have the list of required IPs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by rickyrickuk** [comment]
IPs show in the tables as well as URLs.

**Comment by ioshi13** [comment]
Some of the URLs doesn't have the corresponding IPs like line 32, 33, 35, 36, etc. Is the IPs provided here enough?

**Comment by rickyrickuk** [comment]
I would hope so, but resolving one of them (e.g. g.live.com in line 36) to 52.142.114.176. This IP doesn't seem to be in the list.
Maybe someone from Microsoft can advise?

**Comment by JoeDavies-MSFT** [comment]
@ioshi13 Please see the blog post at https://techcommunity.microsoft.com/t5/Office-365-Networking/Why-are-some-Office-365-network-endpoints-provided-as-URLs-only/m-p/310490#M97 for information on why some URLs do not have their corresponding IP addresses listed. Thanks

**Comment by mypil** [comment]
@rickyrickuk @ioshi13 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author @JoeDavies-MSFT  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
