### ISSUE TITLE
Microsoft Teams Live Events IPs/URLs

### ISSUE THREAD

**Issue by rickyrickuk** [MicrosoftDocs/OfficeDocs-Enterprise#818]
Are the Teams Live Events IPs/URLs covered by the Teams IPs on this page?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-gb/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@rickyrickuk I have forwarded this request to the team that manages the published Teams endpoints for investigation and consideration. Thanks for you suggestion.
