### ISSUE TITLE
Obsolete Link

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-Enterprise#82]
The link to PowerShell for Office 365 group of the Office 365 Yammer Network points to yammer network that no longer exists, can it be removed to eliminate confusion?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 719de36a-fd95-7a77-9fc0-09044a7c6802
* Version Independent ID: eff65b2e-4340-09c5-e50b-00f374a574ab
* Content: [Office 365 PowerShell community resources](https://docs.microsoft.com/en-us/office365/enterprise/powershell/office-365-powershell-community-resources)
* Content Source: [Enterprise/powershell/office-365-powershell-community-resources.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/office-365-powershell-community-resources.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
Thanks, DeanGross, for the feedback. The article has been updated with a link to Office 365 Tech Communities. I hope this helps!
