### ISSUE TITLE
SharePoint Online Record no longer required

### ISSUE THREAD

**Issue by brianreidc7** [MicrosoftDocs/OfficeDocs-Enterprise#824]
In this page (under "Choose the SPF record structure you need") it says in the Note section and row 3 of the table that the SPF record should contain include:sharepointonline.com. But https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing?view=o365-worldwide says that this is no longer necessary. Both of these documents where last edited around the same time so can one of them be fixed to ensure the correct statement is covered please. I do not think include:sharepointonline.com is needed so this document should be tidied up.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e27e942-5c6d-591e-14c4-40d44d90422c
* Version Independent ID: 5e92f544-cae1-9d31-0c9a-253a7e76b73f
* Content: [External Domain Name System records for Office 365](https://docs.microsoft.com/en-gb/office365/enterprise/external-domain-name-system-records#feedback)
* Content Source: [Enterprise/external-domain-name-system-records.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/external-domain-name-system-records.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by get-itips** [comment]
Hello @brianreidc7 thanks for noticing and reporting.
I created a pull request to fix the article, if it gets approval, it will be reflected online.
Thank you

**Comment by mypil** [comment]
@brianreidc7 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/fadf1c75d1d1422ac7ba2d565fa447e173e70e2c. 


Thank you for your contribution to make the docs better! Much appreciated!
