### ISSUE TITLE
Tenant in common

### ISSUE THREAD

**Issue by JonScott46** [MicrosoftDocs/OfficeDocs-Enterprise#825]
We are two schools in different countries looking to create collaborative learning opportunities for students. Wondering if it is better to create a middle-ground Tenant which shares information with Tenants in each school, in order to ensure security of data. Or is it in fact better to have simple trust relationships between our two existing Tenants—if so what are the risks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41bcfce7-bfcf-f2da-f752-36ac0e497b78
* Version Independent ID: 880faa66-d243-6598-ae24-cf0e4d5a7c16
* Content: [Office 365 inter-tenant collaboration](https://docs.microsoft.com/en-us/office365/enterprise/office-365-inter-tenant-collaboration#feedback)
* Content Source: [Enterprise/office-365-inter-tenant-collaboration.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-inter-tenant-collaboration.md)
* Service: **o365-administration**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @JonScott46 
Thanks for your question. It sounds like you as looking for multi-geo planning consulting help.  This channel is for comments on documentation. I suggest you check out [Microsoft Tech Communities](https://techcommunity.microsoft.com/) and browse the communities there as a start.
