### ISSUE TITLE
Provide needed commands

### ISSUE THREAD

**Issue by mprentice22153** [MicrosoftDocs/OfficeDocs-Enterprise#826]
In this document you provide a lot of good steps and commands.  Can you please provide the needed commands for the last part of this section?  https://docs.microsoft.com/en-us/office365/enterprise/configure-exchange-server-for-hybrid-modern-authentication#verify-virtual-directories-are-properly-configured

What are the commands needed if the virtual directories are not enabled with OAuth?  In our case the ActiveSyncVirtualDirectory did not have any options listed.  What are the correct options to list?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba93584-38f6-bc46-9784-c14492de8f75
* Version Independent ID: 2fc5806d-bc80-9cc4-a051-1a9f16322c8d
* Content: [How to configure Exchange Server on-premises to use Hybrid Modern Authentication](https://docs.microsoft.com/en-us/office365/enterprise/configure-exchange-server-for-hybrid-modern-authentication)
* Content Source: [Enterprise/configure-exchange-server-for-hybrid-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/configure-exchange-server-for-hybrid-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by get-itips** [comment]
Hello @mprentice22153 Thanks for your feedback, created a pr to improve the article. If it gets approval, it will be reflected online.

**Comment by mypil** [comment]
@mprentice22153 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/565689211f542a9a1e6af803b2d7074f38915d56. 


Thank you for your contribution to make the docs better! Much appreciated!
