### ISSUE TITLE
Step 2 is broken

### ISSUE THREAD

**Issue by norrcom** [MicrosoftDocs/OfficeDocs-Enterprise#829]
Context:
Powershell v7.0.0 / Windows 10 Pro (v1809, OS Build 17763.1158)
Step 1 completes no errors.

Next:
Instructions state the following:

Step 2: Connect to Azure AD for your Office 365 subscription
To connect to Azure AD for your Office 365 subscription with an account name and password or with multi-factor authentication (MFA), run one of these commands.

However, running the prescribed command generates the following error:

Connect-AzureAD
Connect-AzureAD: The term 'Connect-AzureAD' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@norrcom Run the "Get-InstalledModule" PowerShell command and verify that you have the "Azure-AD" module name in the list. If not run the "Install-Module -Name AzureAD" command again.

**Comment by Manaf-Ibrahim** [comment]
Hi @Norrcom,

Not sure if this will help as it is a missing step from this article but try running "Import-Module AzureAD" - I think the issue is that the module is installed but not available in the current context of the session.

If that doesn't work then the contributor will have to step in here and review further.

**Comment by norrcom** [comment]
Get-InstalledModule`

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.0.2.76             AzureAD                             PSGallery            Azure Active Directory V2 General Availa…
1.1.183.57           MSOnline                            PSGallery            Microsoft Azure Active Directory Module …
1.3.3                NuGet                               PSGallery            Create Nuget repos, Register Repos, Mana…
2.2.3                PowerShellGet                       PSGallery            PowerShell module with commands for disc…

**Comment by norrcom** [comment]
Step missing from document:

Import-Module AzureAD
