### ISSUE TITLE
Is the management API supported in DoD tenants?

### ISSUE THREAD

**Issue by davidck-msft** [MicrosoftDocs/OfficeDocs-Enterprise#830]
*.manage.office.com and manage.office.com endpoints are listed in the Worldwide endpoints. And *.manage.office365.us and manage.office365.us are listed as GCC High endpoints.

But there are no endpoints for the Microsoft Office365 Management Activity API documented in this specific article, does this mean that the Management Activity API endpoints are not supported on DoD environments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58bf69f3-b268-a5e6-2db8-63c496137226
* Version Independent ID: d8449616-ae9c-1b7b-224b-9f3f12d8a669
* Content: [Office 365 U.S. Government DoD endpoints](https://docs.microsoft.com/en-us/office365/enterprise/office-365-u-s-government-dod-endpoints#feedback)
* Content Source: [Enterprise/office-365-u-s-government-dod-endpoints.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-u-s-government-dod-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by HGHodges** [comment]
Is there a DOD equivalent to manage.office365.us?

**Comment by HGHodges** [comment]
mange.protection.apps.mil

**Comment by msbemba** [comment]
@davidck-msft Thank you for the feedback.  manage.protection.apps.mil is the endpoint used for Management Activity API  and the same is covered in *.protection.apps.mil mentioned in the document.

https://docs.microsoft.com/en-us/office/office-365-management-api/troubleshooting-the-office-365-management-activity-api is another document which has this covered

Enterprise plan and GCC government plan: manage.office.com

GCC High government plan: manage.office365.us

DoD government plan: manage.protection.apps.mil

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @davidck-msft Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
