### ISSUE TITLE
Misspelling of tunneling

### ISSUE THREAD

**Issue by ndambrosio** [MicrosoftDocs/OfficeDocs-Enterprise#832]
Throughout this article we use tunnelling, the correct spelling is tunneling.  This is also an issue in "Overview: VPN split tunnelling for Office 365" https://docs.microsoft.com/en-us/office365/enterprise/office-365-vpn-split-tunnel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83a36fa1-0345-87d0-7fea-cca68bfe1915
* Version Independent ID: 0eaabf4b-4c4d-06d5-b877-56a7657eceaf
* Content: [Implementing VPN split tunnelling for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/office-365-vpn-implement-split-tunnel)
* Content Source: [Enterprise/office-365-vpn-implement-split-tunnel.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-vpn-implement-split-tunnel.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by PaulCollinge** [comment]
Both are correct, one is correct for US English (single l) and the other is more pervasively used elsewhere in the world and the presence of both is due to authors being from various locations. We'll correct to a standard form however, thanks for pointing it out.

**Comment by mypil** [comment]
@ndambrosio - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @PaulCollinge so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
