### ISSUE TITLE
Misspelling of tunneling

### ISSUE THREAD

**Issue by ndambrosio** [MicrosoftDocs/OfficeDocs-Enterprise#833]
Throughout this article we use tunnelling, the correct spelling is tunneling. This is also an issue in "Related topics
Implementing VPN split tunnelling for Office 365" https://docs.microsoft.com/en-us/office365/enterprise/office-365-vpn-implement-split-tunnel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b1a1d14-d150-f90f-dce5-c2b2c12600f9
* Version Independent ID: 0966ffd4-9173-912e-9c8f-5f5928bb45ad
* Content: [Overview: VPN split tunnelling with Office 365](https://docs.microsoft.com/en-us/office365/enterprise/office-365-vpn-split-tunnel)
* Content Source: [Enterprise/office-365-vpn-split-tunnel.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-vpn-split-tunnel.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by mypil** [comment]
@ndambrosio - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @PaulCollinge based on this similar https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/832#issuecomment-618371042 so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
