### ISSUE TITLE
IP address range missing for port 587

### ISSUE THREAD

**Issue by cbowen248** [MicrosoftDocs/OfficeDocs-Enterprise#834]
We are trying to allow network traffic through one of our Systems on Port 587 and we found that one of the ranges that it is using isn't listed here which is making it very difficult to get some of our systems working properly. When pinging smtp.office365.com we are getting an IP Address of 40.97.165.210. If we could get that updated so we know which ranges are being used please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@cbowen248 The 40.97.165.210 address is included in the 40.96.0.0/13 range in table ID 2. Does this answer your question?

**Comment by JoeDavies-MSFT** [comment]
@cbowen248 Hope this explanation closes this issue. Please reopen if you have additional questions.
