### ISSUE TITLE
maximum of four (not five) dedicated global administrators

### ISSUE THREAD

**Issue by JBines** [MicrosoftDocs/OfficeDocs-Enterprise#841]
needs to be changed to 4 inline with https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide
"maximum of five dedicated global administrator"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96784dc6-991a-fb80-cd0c-ae8217c32f45
* Version Independent ID: 0532ace1-bf55-916f-708d-5444c49d77b1
* Content: [Protect your Office 365 global administrator accounts](https://docs.microsoft.com/en-us/office365/enterprise/protect-your-global-administrator-accounts)
* Content Source: [Enterprise/protect-your-global-administrator-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/protect-your-global-administrator-accounts.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@JBines This has been corrected and published. Thanks so much for your suggestion.
