### ISSUE TITLE
Live Event attendee IPs or hijacked IP?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-Enterprise#842]
When joining to Live Event session I could see, my computer have lot of communication to server:
endpoint2-prdneucompsvc.streaming.mediaservices.windows.net
with IP: 152.199.19.160

But that IP address is not listed on this page? Is that a hijacked server? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Petri-X The endpoint2-prdneucompsvc.streaming.mediaservices.windows.net domain name is included in the *.streaming.mediaservices.windows.net FQDN (see ID 16). We don't list the IP addresses for default category endpoints. See https://techcommunity.microsoft.com/t5/office-365-networking/why-are-some-office-365-network-endpoints-provided-as-urls-only/m-p/310490#M97 for a detailed explanation. Thanks for your question.

**Comment by Petri-X** [comment]
Thank you @JoeDavies-MSFT 
This was helpful advice!
