### ISSUE TITLE
Better link to Categories

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-Enterprise#843]
Hi,
You have the following section:

> Category: Shows whether the endpoint set is categorized as "Optimize", "Allow", or "Default". You can read about these categories and guidance for management of them at https://aka.ms/pnc. 

Instead of having this short link, it would be more helpful for readers if you could use this URL instead: [New Office 365 endpoint categories](https://docs.microsoft.com/en-us/office365/enterprise/office-365-network-connectivity-principles#new-office-365-endpoint-categories)
I believe readers - like me :) - might get lost, so it would be better to have direct reference. And then perhaps Paul does not need to explain so often why not all IPs are listed there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?source=docs)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Petri-X This update has been made and published. Thanks for the helpful improvement.
