### ISSUE TITLE
How have access to the Service Health

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-Enterprise#846]
Hi,
Who have the access to the page? What role is required. And more important, can we open this page on company wide?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd2a834a-296b-1c7d-7358-6f6a19f8f3c3
* Version Independent ID: 9ab6adbe-c651-d833-f395-64b7cddb2dd2
* Content: [How to check Office 365 service health](https://docs.microsoft.com/en-us/office365/enterprise/view-service-health)
* Content Source: [Enterprise/view-service-health.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/view-service-health.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Petri-X Please see the Note after step 1 for information on required roles. Not sure what you mean about "company wide". The service health page is for the entire subscription. Can you clarify? Thanks

**Comment by Petri-X** [comment]
ehhh :)
Sorry.

But that means we are not able to allow regular users to read those pages?

**Comment by JoeDavies-MSFT** [comment]
@Petri-X Yes. That is correct.

**Comment by Petri-X** [comment]
:'(
