### ISSUE TITLE
How to combine multiple SPF1 with ~all and -all

### ISSUE THREAD

**Issue by LukeChung** [MicrosoftDocs/OfficeDocs-Enterprise#847]
We need to combine these:
"v=spf1 include:_spf.google.com include:mail.zendesk.com ~all"
"v=spf1 include:spf.protection.outlook.com -all"

Notice the difference in the ~all and -all. Not sure if that matters.

Does it become this or do the "all" parts also need to be combined in some way?
"v=spf1 include:_spf.google.com include:mail.zendesk.com ~all include:spf.protection.outlook.com -all"

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e27e942-5c6d-591e-14c4-40d44d90422c
* Version Independent ID: 5e92f544-cae1-9d31-0c9a-253a7e76b73f
* Content: [External Domain Name System records for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/external-domain-name-system-records#feedback)
* Content Source: [Enterprise/external-domain-name-system-records.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/external-domain-name-system-records.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@LukeChung  Thank you for your feedback. There can be only one SPF record and it is all about publishing a list of servers that are authorized to send on behalf of a domain.

By adding a prefix of “~” or “-“, the meaning of the mechanism is changed to be:

“softfail” in the case of “~”
“fail” in the case of “-“

In your case, you can use either -all or ~all depending on your requirement.

for example, it would be v=spf1 include:_spf.google.com include:mail.zendesk.com include:spf.protection.outlook.com -all or ~all

So there is no changes needed in the document as such.

Hope this helps!
Thanks
Sri

**Comment by LukeChung** [comment]
So when I combine it with the office 365 requirement, do I include two all terms or just one at the very end?

Luke

**Comment by msbemba** [comment]
@LukeChung  Thank you for your feedback. Yes, One at the very end.  It would be v=spf1 include:_spf.google.com include:mail.zendesk.com include:spf.protection.outlook.com -all if you want to hard fail.

Thanks
Sri

**Comment by LukeChung** [comment]
Thanks.

Is there a simple way to verify the settings are correct?

Luke

**Comment by msbemba** [comment]
@LukeChung  I'd recommend Contacting the Support team from your Office 365 tenant so that a technician will work with you to verify. Let me know if you need details on how to raise a support ticket.

Thanks
Sri

**Comment by mypil** [comment]
@LukeChung  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue. You can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP.

Thank you for your contribution to make the docs better! Much appreciated!
