### ISSUE TITLE
Office 365 IP Addresses and URL's Whitelist Query

### ISSUE THREAD

**Issue by exc877** [MicrosoftDocs/OfficeDocs-Enterprise#851]
Q1.If there are no Asia-Pacific related IP addresses for Office 365 services. Can you whitelist URL's alone and leave out public IP addresses from "Addresses" column on the article from this URL (Example: Exchange Online - outlook.office.com, smtp.office365.com, SharePoint - [tenant].sharepoint.com, [tenant]-my.sharepoint.com, Teams - *.lync.com, *.teams.microsoft.com, teams.microsoft.com). 

Q2.For the "Ports" column on this article , there is no clear information of ports that needs to be allowed bi-directional and ports that needs to be allowed uni-directional on the Firewall. Please clarify this so that we allow correct ports for each Office 365 services with correct direction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#feedback)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by get-itips** [comment]
Hello @exc877 How are you? 👍 

About Q.2: The article currently says:

> Endpoint data below lists requirements for connectivity **from a user's machine to Office 365**. **It does not include network connections from Microsoft into a customer network**, sometimes called hybrid or inbound network connections.

About Q.1: I would say that you can't leave out Public IP Addresses but I would like to check with @JoeDavies-MSFT to confirm.

Thanks

**Comment by JoeDavies-MSFT** [comment]
@exc877: @get-itips is correct. We can't leave out public IP addresses for Optimize and Allow category endpoints. You are free to just whitelist the FQDN and not whitelist the public IP addresses. Both must be provided to support different types of network edge devices. Thanks for your question.
