### ISSUE TITLE
Removing all licenses can generate errors

### ISSUE THREAD

**Issue by ipcejdiaz** [MicrosoftDocs/OfficeDocs-Enterprise#852]
When using the script in this document to remove licenses, I received an error that is a bit deceiving, since I am not assigning any licenses:

Set-MsolUserLicense : Unable to assign this license.
    + CategoryInfo          : OperationStopped: (:) [Set-MsolUserLicense], MicrosoftOnlineException
    + FullyQualifiedErrorId : Microsoft.Online.Administration.Automation.InvalidLicenseConfigurationException,Microsoft.Online.Administration.Automation.SetUserLicense 

I believe that if a license is not removed in the correct order, it generates this error. In order to fix this, instead of using a foreach loop, I passed an array to the removelicenses parameter.

$user=get-msoluser -UserPrincipalName "name@email.com"
Set-MsolUserLicense -UserPrincipalName "name@email.com" -RemoveLicenses $user.licenses.accountskuid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90144912-28c3-e215-7763-12beddc645c7
* Version Independent ID: c2aa496c-51d4-ffd9-9b06-e3a7097d027a
* Content: [Remove licenses from user accounts with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell#feedback)
* Content Source: [Enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@ipcejdiaz I reworked the PowerShell commands to use an array and a for-loop to remove the licenses on a per-user basis. Thanks for the suggestion and letting us know.

**Comment by ipcejdiaz** [comment]
Hi, I think this will result in the same error since the for loop will not take into account the order in which the licenses are removed. 

According to the [documentation for set-msoluserlicense](https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoluserlicense?view=azureadps-1.0), the removelicenses parameter accepts an array of strings as a value, so there would not be a need to create a loop and in this case the licenses are removed in the correct order.
