### ISSUE TITLE
Potentially dangerous PowerShell code

### ISSUE THREAD

**Issue by clerckjo** [MicrosoftDocs/OfficeDocs-Enterprise#855]
`$_.UserPrincipalName.Replace` might in some cases replace part of either the user part of the UPN (before the @), or partial subdomains (domain.contoso.local) that might exist in AD.
To prevent this, include the @ sign on the replace expression:
`$newUpn = $_.UserPrincipalName.Replace("@contoso.local","@contoso.com")`

Same accounts for the filter expression on `Get-ADUser`: use` -like '*@contoso.local' `to only return users with the exact UPN suffix.

NB: Get-ADUser's -Filter parameter is a string, so should be presented as a string instead of an expression (to avoid confusion when people try to use variables in the expression)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79589db3-4bf5-e940-0410-75d5f0ff97b8
* Version Independent ID: e7980b96-bab3-981e-2da8-6e1bdde9ba31
* Content: [Prepare a non-routable domain for directory synchronization](https://docs.microsoft.com/en-us/office365/enterprise/prepare-a-non-routable-domain-for-directory-synchronization#feedback)
* Content Source: [Enterprise/prepare-a-non-routable-domain-for-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/prepare-a-non-routable-domain-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@clerckjo Your suggested corrections have been made and published. Thanks for letting us know.
