### ISSUE TITLE
Missing Status descriptions

### ISSUE THREAD

**Issue by bzabber** [MicrosoftDocs/OfficeDocs-Enterprise#857]
Hi,

There's no definitions for the following status':

VerifyingService
ServiceOperational

Status description can be found[ here](https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-service-communications-api-reference#status-definitions).

**Comment by bzabber** [comment]
The following status also doesn't have a matching status on this [page](https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-service-communications-api-reference#status-definitions). 
Investigation suspended

**Comment by mypil** [comment]
@bzabber - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by bzabber** [comment]
@mypil 
Here's the link which lists a the status definitions for O365 via the Service Communications API: https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-service-communications-api-reference#status-definitions

The section then references "[How to check Office 365 service health](https://docs.microsoft.com/en-us/office365/enterprise/view-service-health#status-definitions)" which lists the status definitions which matches up for the most part but there are some others which don't appear on the previous webpage. 

It looks like some of the status' might not be customer facing or if they are they are rare it might be a good idea to call that out or provide a reason why they aren't listed.

Thank you in advance,
Bryan

**Comment by SheikhAbdulAlmamun** [comment]
What exactly are the requirements for a Shared or Room mailbox located in a Geo-location?    An F1, F3, E3 or E5 and then add a Multi-Geo to a Shared or Room mailbox?   Or is only a Multi-Geo license required for a Shared or Room mailbox?

BR//
Mamun

**Comment by msbemba** [comment]
@bzabber Thank you for your feedback. We are discussing this internally and will get back to you shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@SheikhAbdulAlmamun  Thank you for the questions. Since it does not relate to this document you may have to contact support team for the requirements.

@mypil  Can you provide the contact details for the Support team?

Thanks
Sri

**Comment by mypil** [comment]
@SheikhAbdulAlmamun - You can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so they can help resolve your technical issue. Thank you!

**Comment by bzabber** [comment]
> @bzabber Thank you for your feedback. We are discussing this internally and will get back to you shortly.
> 
> Thanks
> Sri

Thank you Sri! Feel free to ping me internally if you have any further questions.
