### ISSUE TITLE
Obsolete - Replaced by MS Graph reporting APIs

### ISSUE THREAD

**Issue by jadoming** [MicrosoftDocs/OfficeDocs-Enterprise#86]
This method is deprecated as of Jan 29th 2018.
O365 reporting services have been moved to the Graph and this document should be removed or updated with a pointer to the Graph API reference site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffbeccaa-efdd-de74-0b2c-5a74de5caac0
* Version Independent ID: 95d9f3d2-8664-32d0-2002-05252cfeacee
* Content: [Using Excel to Retrieve Office 365 Reporting Data](https://docs.microsoft.com/en-za/office365/enterprise/powershell/using-excel-to-retrieve-office-365-reporting-data#feedback)
* Content Source: [Enterprise/powershell/using-excel-to-retrieve-office-365-reporting-data.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/using-excel-to-retrieve-office-365-reporting-data.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
Hello jadoming, and thank you for letting us know about this. We will address ASAP.

**Comment by JoeDavies-MSFT** [comment]
Article removed.
