### ISSUE TITLE
NIST - Phone and SMS are a RESTRICTED authenticator

### ISSUE THREAD

**Issue by JBines** [MicrosoftDocs/OfficeDocs-Enterprise#860]
Should phone and sms also be removed from recommendations to align to NIST recommendations

https://pages.nist.gov/800-63-FAQ/#q-b01

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96784dc6-991a-fb80-cd0c-ae8217c32f45
* Version Independent ID: 0532ace1-bf55-916f-708d-5444c49d77b1
* Content: [Protect your Office 365 global administrator accounts](https://docs.microsoft.com/en-us/office365/enterprise/protect-your-global-administrator-accounts)
* Content Source: [Enterprise/protect-your-global-administrator-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/protect-your-global-administrator-accounts.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@JBines I added a note about the NIST restriction on second authentication methods. Thanks for letting us know.
