### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by sinhakislay** [MicrosoftDocs/OfficeDocs-Enterprise#862]
The link "top 10..." does not work please check
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f142840-ae30-a7e7-af06-f145d2102956
* Version Independent ID: f19fc938-d1fd-9868-78e3-45fd975a94a7
* Content: [Tune Office 365 performance](https://docs.microsoft.com/en-us/office365/enterprise/tune-office-365-performance)
* Content Source: [Enterprise/tune-office-365-performance.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/tune-office-365-performance.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by JoeDavies-MSFT** [comment]
@sinhakislay This has been corrected. Thanks so much for letting us know.
