### ISSUE TITLE
Isolation for Teams data

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-Enterprise#863]
Can we please also get information about chat and meeting content separation for Microsoft Teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3045ac0-ca41-436d-f23b-e26621b96c5a
* Version Independent ID: 99558152-41b2-c8c8-d6ee-a0d8a837a984
* Content: [Office 365 Isolation and Access Control in Office 365](https://docs.microsoft.com/en-us/office365/Enterprise/office-365-isolation-in-office-365)
* Content Source: [Enterprise/office-365-isolation-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-isolation-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@Larryngolog  Thank you for the feedback. We have made changes to the doc via PR# https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/909

Thanks
Sri

**Comment by mypil** [comment]
@Larryngolog - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/commit/6003ac436a277198ad58a46fd4fbeccf9cd94209. 


Thank you for your contribution to make the docs better! Much appreciated!
