### ISSUE TITLE
Connection Information

### ISSUE THREAD

**Issue by Dodge1350** [MicrosoftDocs/OfficeDocs-Enterprise#865]
Why does every powershell reference in Microsoft documentation omit the Connection command that must be used prior to the powershell script that is being referenced?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 719591af-cbcc-669e-a4c3-f36f223e7381
* Version Independent ID: d1c0f978-69e3-cbce-a993-3ffd3016ba6b
* Content: [Create SharePoint Online sites and add users with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/create-sharepoint-sites-and-add-users-with-powershell#feedback)
* Content Source: [Enterprise/powershell/create-sharepoint-sites-and-add-users-with-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/create-sharepoint-sites-and-add-users-with-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Dodge1350 The instructions to make the connection to SharePoint Online are linked to from the "Before you begin" section at the top of each article.
