### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by D4-AzIdentity** [MicrosoftDocs/OfficeDocs-Enterprise#869]
Choose Between MDM and Intune 
https://docs.microsoft.com/en-us/office365/securitycompliance/choose-between-mdm-and-intune

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23814c6c-d430-65bc-d84d-5e7975266578
* Version Independent ID: 7e0dd7ad-d299-36d4-073e-32c849a51f40
* Content: [Office 365 Client App Support — Conditional Access](https://docs.microsoft.com/en-us/office365/enterprise/office-365-client-support-conditional-access)
* Content Source: [Enterprise/office-365-client-support-conditional-access.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-client-support-conditional-access.md)
* Service: **office 365 administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by joinimran** [comment]
@D4-AzIdentity - Can you please confirm the document where the link is broken so that I can make necessary changes.

Thanks
Imran

**Comment by mypil** [comment]
@D4-AzIdentity - We would like to follow up. Can you please respond to the query of @joinimran?

Thank you.

**Comment by D4-AzIdentity** [comment]
My apologies I have been trying to find the original page from which I clicked to submit feedback but have been unable to find. I will submit another request if I come across it again. It doesn't appear that the feedback carry's leave a indication of where you came from when clicking the feedback button.
