### ISSUE TITLE
This does not work forme.

### ISSUE THREAD

**Issue by geekgalconsulting** [MicrosoftDocs/OfficeDocs-Enterprise#870]
I have been trying everything I know but this does NOT work for me.

Get-Content "c:\temp\account.txt" | ForEach { Set-MsolUserLicense -UserPrincipalName $_ -RemoveLicenses "acctname:STANDARDWOFFPACK_IW_STUDENT", "acctname:STANDARDWOFFPACK_STUDENT"}

It is NOT removing licenses.    I really do not want to remove licenses one by one on over 2000 people.   Any help available???  (yes I know the "acctname" is the name of our account.. just removed as I do not want that published).  TY

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90144912-28c3-e215-7763-12beddc645c7
* Version Independent ID: c2aa496c-51d4-ffd9-9b06-e3a7097d027a
* Content: [Remove licenses from user accounts with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell?redirectedfrom=MSDN#feedback)
* Content Source: [Enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@geekgalconsulting Please try this way of doing it:

$x=Get-Content c:\docs\LicenseTest.txt
for ($i=0; $i -lt $x.Count; $i++)
{
Set-MsolUserLicense -UserPrincipalName $x[$i] -RemoveLicenses "acctname:STANDARDWOFFPACK_IW_STUDENT","acctname:STANDARDWOFFPACK_STUDENT"
}

**Comment by JoeDavies-MSFT** [comment]
@geekgalconsulting I have tested the above new code and have updated the article. Please re-open this issue if it doesn't work for you. Thanks for letting us know.

**Comment by geekgalconsulting** [comment]
Oh, thank you!  I will try it next week.
