### ISSUE TITLE
Connection steps when using multi-factor authentication" $acctName=

### ISSUE THREAD

**Issue by eerstech** [MicrosoftDocs/OfficeDocs-Enterprise#872]
the first line of "Connection steps when using multi-factor authentication" $acctName=emailaddress.com gives an error ..is this normal ..I have tried all combination ( emailaddress.com was replaced for posting but give the same exact error with the real email )

ERROR 
The term 'emailaddress.com' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:12
+ $acctName= emailaddress.com
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (emailaddress.com) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c551eb1-7ac5-cb02-cd1b-d67ca3886d85
* Version Independent ID: fb690e2e-420e-f697-60f2-39520283d385
* Content: [Connect to all Office 365 services in a single Windows PowerShell window](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window#feedback)
* Content Source: [Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-all-office-365-services-in-a-single-windows-powershell-window.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@eerstech You need to put quotes around emailaddress.com ("$acctName= emailaddress.com"). PowerShell is interpreting emailaddress.com as a command rather than a string. Thanks for your question.
