### ISSUE TITLE
Set-AzureADUserLicense doesn't work as documented

### ISSUE THREAD

**Issue by chscott** [MicrosoftDocs/OfficeDocs-Enterprise#873]
If I pass in a list of licenses to remove, I get this:

Error occurred while executing SetUserLicenses: User does not have a corresponding license.

If I pass in a single license to remove, it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90144912-28c3-e215-7763-12beddc645c7
* Version Independent ID: c2aa496c-51d4-ffd9-9b06-e3a7097d027a
* Content: [Remove licenses from user accounts with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell#feedback)
* Content Source: [Enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by chscott** [comment]
Looks like the issue for me is that I just want to remove _any_ license a user might have without trying to figure out which license the user actually has assigned. I can work around this by getting the licenses and removing them one at a time, swallowing errors along the way. It would be nice to have a way to just unlicense a user. In other words, I don't care what licenses the user has now, I just want them to have no licenses after I run this command.

**Comment by chscott** [comment]
Well, I guess I can't swallow the errors since the cmdlet throws an exception if I try to remove a license that isn't assigned.

**Comment by JoeDavies-MSFT** [comment]
@chscott I added a new section to remove all the licenses from a specified user account. Thanks for your suggestion.
