### ISSUE TITLE
Do items are retained for 93 or 90 days In SharePoint Online ?

### ISSUE THREAD

**Issue by OrawanO** [MicrosoftDocs/OfficeDocs-Enterprise#875]
Do items are retained for 93 or 90 days In SharePoint Online ?

this link shows 93 days but this article shows 90 days
https://support.office.com/en-us/article/restore-deleted-items-from-the-site-collection-recycle-bin-5fa924ee-16d7-487b-9a0a-021b9062d14b

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4badd6ff-b44c-9df6-2d4e-b788cb37a5e1
* Version Independent ID: 416f1753-cc58-ff8a-11b6-528ed962986e
* Content: [Office 365 Malware and Ransomware Protection](https://docs.microsoft.com/en-us/office365/enterprise/office-365-malware-and-ransomware-protection)
* Content Source: [Enterprise/office-365-malware-and-ransomware-protection.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-malware-and-ransomware-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@OrawanO  Thank you for your feedback. We have made changes to the document to reflect it as 93 days. This can be tracked via PR# https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/905

**Comment by robmazz** [comment]
Merged
