### ISSUE TITLE
"City locations" shows states not cities, for Australia only

### ISSUE THREAD

**Issue by koolhand** [MicrosoftDocs/OfficeDocs-Enterprise#876]
> ## Country/Region specific Data Center city locations
> 
> |Country|City|
> |----|----|
> | ... | ... |
> |Australia|New South Wales, Victoria|
> | ... | etc |

Those are states - large ones - not cities. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d4d59d-d7b1-81b1-aeaf-6d34f61ae18b
* Version Independent ID: 2b2620fa-7e4f-27ee-2655-47da2391296f
* Content: [Office 365 data locations](https://docs.microsoft.com/en-us/office365/enterprise/o365-data-locations?geo=All)
* Content Source: [Enterprise/o365-data-locations.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/o365-data-locations.md)
* Service: **o365-solutions**
* GitHub Login: @dmwmsft
* Microsoft Alias: **deanw**

**Comment by msbemba** [comment]
@koolhand Thank you for the feedback.  The Australia Geo will consist of data centers in the Australia East Region (New South Wales) and the Australia Southeast Region (Victoria). That is why there is no city mentioned in the document. 

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@koolhand  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
