### ISSUE TITLE
Location of Shifts data?

### ISSUE THREAD

**Issue by Kressmark** [MicrosoftDocs/OfficeDocs-Enterprise#877]
I would be good to have the location of Shifts data in this page as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d4d59d-d7b1-81b1-aeaf-6d34f61ae18b
* Version Independent ID: 2b2620fa-7e4f-27ee-2655-47da2391296f
* Content: [Office 365 data locations](https://docs.microsoft.com/en-us/office365/enterprise/o365-data-locations?)
* Content Source: [Enterprise/o365-data-locations.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/o365-data-locations.md)
* Service: **o365-solutions**
* GitHub Login: @dmwmsft
* Microsoft Alias: **deanw**

**Comment by dmwmsft** [comment]
Shifts data is stored in one of 3 major regions: US, EMEA or Asia Pacific. . For more information regarding which data centers make up the major regions refer to https://docs.microsoft.com/en-us/office365/enterprise/o365-data-locations#data-center-locations

**Comment by mypil** [comment]
@Kressmark  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author @dmwmsft and @msbemba so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
