### ISSUE TITLE
IP adress updates

### ISSUE THREAD

**Issue by Shane-zhao** [MicrosoftDocs/OfficeDocs-Enterprise#878]
[Enter feedback here]
would you please update this IP address: 13.107.60.1/32  into https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Shane-zhao This IP address might be a Default category endpoint, which we don't explicitly list. Please see https://techcommunity.microsoft.com/t5/Office-365-Networking/Why-are-some-Office-365-network-endpoints-provided-as-URLs-only/m-p/310490#M97  for more information. Thanks for your comment.
