### ISSUE TITLE
What do you mean by "Custom-navigation provider"

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/OfficeDocs-Enterprise#879]
What are trying to tell by "Custom-navigation provider" for SharePoint Online? It's not possible, doesn't it? You can't add custom SiteMapProvider in any way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe686368-f607-9a7d-710b-d51c3f8f6c9a
* Version Independent ID: 01b5902a-6e23-62d9-f0a3-7c1e86194ef1
* Content: [Navigation options for SharePoint Online](https://docs.microsoft.com/en-us/office365/enterprise/navigation-options-for-sharepoint-online?redirectSourcePath=%252fen-us%252farticle%252fNavigation-options-for-SharePoint-Online-adb92b80-b342-4ecb-99a1-da2a2b4782eb#example-replace-the-out-of-the-box-navigation-code-in-a-master-page)
* Content Source: [Enterprise/navigation-options-for-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/navigation-options-for-sharepoint-online.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@VerdonTrigance  Thank you for the feedback. For a custom Navigation solution, you can refer to https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-navigation#using-a-custom-navigation-solution

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @VerdonTrigance Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
