### ISSUE TITLE
typo in script

### ISSUE THREAD

**Issue by Simon5886** [MicrosoftDocs/OfficeDocs-Enterprise#88]
In the multiple user script, there is a typo. 
line 3 shows variable $accountSkuId but in line 12 it is called as $AccountSkuId, which means code does not run correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6e1db9c-8440-9547-98ab-3bfca008bd86
* Version Independent ID: 17011d6e-4978-6312-274b-586bd9e857de
* Content: [Disable access to services while assigning user licenses](https://docs.microsoft.com/en-us/office365/enterprise/powershell/disable-access-to-services-while-assigning-user-licenses)
* Content Source: [Enterprise/powershell/disable-access-to-services-while-assigning-user-licenses.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/disable-access-to-services-while-assigning-user-licenses.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
Hello Simon5886, and thank you for letting us know about this. We'll fix it ASAP.
