### ISSUE TITLE
Reference to Office 2019

### ISSUE THREAD

**Issue by henascim** [MicrosoftDocs/OfficeDocs-Enterprise#880]
It would be nice to include a reference to Office 2019. I know the behavior should be identical to Office 2016, but I had a couple of customers asking for an explicit reference.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059ed9a7-ea75-0fa3-e246-4ad1f1b0c5bc
* Version Independent ID: d7598f96-3158-09ee-024a-6175599718cd
* Content: [How modern authentication works for Office 2013 and Office 2016 client apps](https://docs.microsoft.com/en-us/office365/enterprise/modern-auth-for-office-2013-and-2016?redirectSourcePath=%252farticle%252f776c0036-66fd-41cb-8928-5495c0f9168a)
* Content Source: [Enterprise/modern-auth-for-office-2013-and-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/modern-auth-for-office-2013-and-2016.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@henascim  Thank you for your feedback. We have made changes to the doc via PR# https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/908

Thanks
Sri

**Comment by msbemba** [comment]
@henascim  We have made the changes to the document. Thanks again for your feedback. @yogkumgit We can close this.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @henascim Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
