### ISSUE TITLE
IP missing in article for - Office 365 URLs and IP address ranges

### ISSUE THREAD

**Issue by rktiwari14** [MicrosoftDocs/OfficeDocs-Enterprise#882]
Hi Team, 

I have a customer who is service provider and provide teams service to there customer.  They have whitelisted all o365 IP's for Teams mentioned in given article but when their user is making teams to team call the user are being charged as one of the IP address is not listed in article , They he tracked to know what IP was sent to their DPI system and it was 13.89.219.246. Could you pls update the article with all other new IP's added recently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2#bkmk_teams)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@rktiwari14 Not all IP addresses are listed for Default category endpoints. Please see https://techcommunity.microsoft.com/t5/Office-365-Networking/Why-are-some-Office-365-network-endpoints-provided-as-URLs-only/m-p/310490#M97 for more information. Thanks for your question.
