### ISSUE TITLE
Explain the real purpose of IP range 13.107.60.1/32

### ISSUE THREAD

**Issue by SergGu** [MicrosoftDocs/OfficeDocs-Enterprise#885]
Dear Microsoft Documentation Team,

Can you please explain the real purpose of IP range 13.107.60.1/32? We checked our firewalls and there is not a single hit or session to this destination. Is this a real route for the traffic of some kind OR just a marker used by Teams to discover presence of the VPN solution?

Regards,
Serg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83a36fa1-0345-87d0-7fea-cca68bfe1915
* Version Independent ID: 0eaabf4b-4c4d-06d5-b877-56a7657eceaf
* Content: [Implementing VPN split tunneling for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/office-365-vpn-implement-split-tunnel#howto-guides-for-common-vpn-platforms)
* Content Source: [Enterprise/office-365-vpn-implement-split-tunnel.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-vpn-implement-split-tunnel.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@SergGu Thank you for the feedback. We have now removed the IP range added an important note to the doc as the teams update is made available.

Note:- To ensure Teams media traffic is routed via the desired method in all VPN scenarios, please ensure users are running Microsoft Teams client version **1.3.00.13565** or greater. This version includes improvements in how the client detects available network paths.

Thanks
Sri

**Comment by mypil** [comment]
@SergGu - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
