### ISSUE TITLE
Could Microsoft be blocking one of my IPs from using REST API on endpoints.office.com?

### ISSUE THREAD

**Issue by brazilianthunder** [MicrosoftDocs/OfficeDocs-Enterprise#886]
I run the Powershell script to check for any changes daily - that is once at day, at night. Since the 26th, I have been unable to pull anything using REST API coming from one specific IP address. 

Powershell errors out and gives the following error "Error The underlying connection was closed: An unexpected error occurred on a receive."

Manually browsing to the URL, like this one https://endpoints.office.com/version/Worldwide?clientRequestId=aeb3532d-0a70-41cc-8dde-d1a510a17f89 , using any browser just never loads. I can see the browser sending the request, but nothing is ever replied back to me. I've tried new GUIDs and still the same behavior. Using different servers in my environment that are using the same public IP, gives me the same results. Even just manually trying to go to https://endpoints.office.com/ never loads, it just keeps trying to load- sending a request but never getting anything back. 

Now, if I use a server that is behind the same firewall with exactly the same outbound rules ( no rules) with the exception that is using a different public IP, I'm able to successfully use the endpoints page.  Any insight would be greatly appreciated it.

**Comment by brazilianthunder** [comment]
Also, DNS translates endpoints.office.com to endpointssvcpreview1.westus.cloudapp.azure.com [138.91.80.132] on all my devices.

**Comment by mypil** [comment]
@brazilianthunder - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by brazilianthunder** [comment]
Well, inexplicably today,  it appears to be working again. Unfortunately I did not have the time to open the case with Microsoft, so I do not know why it happened. 
There have been no changes in our infrastructure before, during and after the issue. Thanks for the direction.
