### ISSUE TITLE
Microsoft Edge (chromium based) - Update requirement

### ISSUE THREAD

**Issue by ingd** [MicrosoftDocs/OfficeDocs-Enterprise#889]
Hello guys,

I am not sure about what kind of Microsoft Edge architecture the documentation talking about. Could someone update this requirement?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0adf74-b4de-678c-4213-cafe76476dd7
* Version Independent ID: d2cc6acf-7abc-0568-afd0-2b6e1fff380e
* Content: [Use lean popouts to reduce memory used when reading mail messages](https://docs.microsoft.com/en-us/office365/enterprise/use-lean-popouts-to-reduce-memory-used-when-reading-mail-messages?redirectSourcePath=%252farticle%252fa6d6ba01-2562-4c3d-a8f1-78748dd506cf)
* Content Source: [Enterprise/use-lean-popouts-to-reduce-memory-used-when-reading-mail-messages.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/use-lean-popouts-to-reduce-memory-used-when-reading-mail-messages.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@ingd  Thank you for your feedback. The lean pop outs options are available on all versions of Microsoft edge and can be configured within your Office 365 organization using Set-OrganizationConfig -LeanPopoutEnabled $true

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @ingd Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
