### ISSUE TITLE
In acurate information

### ISSUE THREAD

**Issue by earthengine** [MicrosoftDocs/OfficeDocs-Enterprise#89]
For all scripts, every occurance of "StandardLRS" should be replaced with "Standard_LRS".

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 136007e4-4ddd-a1d8-a3ac-251da6bd5311
* Version Independent ID: 5c1ec643-ac23-cf7c-c787-3ffb1b4f9674
* Content: [Base Configuration dev/test environment](https://docs.microsoft.com/en-gb/office365/enterprise/base-configuration-dev-test-environment)
* Content Source: [Enterprise/base-configuration-dev-test-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/base-configuration-dev-test-environment.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
Thank you for the feedback, earthengine! We'll take a look at this.

**Comment by ashunt677** [comment]
Yes Standard_LRS is definitely correct, was covered in the post titled 'Splendid documentation'.

**Comment by JoeDavies-MSFT** [comment]
I have updated the instances of StandardLRS to "Standard_LRS" in accordance with the examples in https://docs.microsoft.com/en-us/azure/virtual-machines/windows/attach-disk-ps and version 6.00 and later of the Azure PowerShell module.
