### ISSUE TITLE
Add link to 21Vianet reference

### ISSUE THREAD

**Issue by kerbos** [MicrosoftDocs/OfficeDocs-Enterprise#893]
Please add a link to the explanation of what 21Vianet is in the following note on this page.
**Note:** This CNAME only applies to Office 365 operated by 21Vianet.

Here's the link:
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-operated-by-21vianet

**Justification:** The MSOID is no longer needed for non-21Vianet but is harmless in Commercial Office 365 scenarios if present. However it adversely affects customers migrating to GCC High and DoD Office 365. If not removed it keeps them from accessing our services. It's challenging to explain this to customers. And when you search Bing with 'MSOID docs' this is the first article that comes up. Adding the link above may reduce confusion to quickly understand it is still only needed for 21Vianet. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e27e942-5c6d-591e-14c4-40d44d90422c
* Version Independent ID: 5e92f544-cae1-9d31-0c9a-253a7e76b73f
* Content: [External Domain Name System records for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/external-domain-name-system-records)
* Content Source: [Enterprise/external-domain-name-system-records.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/external-domain-name-system-records.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@kerbos Thank you for your feedback. We have added the link to the note via PR #https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/950

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @kerbos Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
