### ISSUE TITLE
New-AzureADUser Missing Attribute

### ISSUE THREAD

**Issue by ArthurEzenwanne** [MicrosoftDocs/OfficeDocs-Enterprise#895]
The "**_LicenseAssignment_**" attribute is not found for the New-AzureADUser command; running the command via PowerShell with the attribute added fails.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6320b861-3716-b7da-9068-6047ce728c73
* Version Independent ID: 0319c981-107f-05ba-f874-6a3907961fbd
* Content: [Create user accounts with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/create-user-accounts-with-office-365-powershell#use-the-microsoft-azure-active-directory-module-for-windows-powershell)
* Content Source: [Enterprise/powershell/create-user-accounts-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/create-user-accounts-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@ArthurEzenwanne The "LicenseAssignment" parameter is specific to the New-MsolUser cmdlet and is not supported by the New-AzureADUser cmdlet. To assign licenses to user accounts after they are created with New-AzureADUser, see https://docs.microsoft.com/en-us/office365/enterprise/powershell/assign-licenses-to-user-accounts-with-office-365-powershell. Thanks for your question.
