### ISSUE TITLE
Could you please list a move date for GER

### ISSUE THREAD

**Issue by newsgrep** [MicrosoftDocs/OfficeDocs-Enterprise#896]
Could you please decide on a move date for Germany. 
Or at least write when the option to apply to move will be open for Germany. 
A guess with 2. 3. or 4. quarter of the year would be a start to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 756e6a9b-289c-6ef9-bf79-e36e32e12a98
* Version Independent ID: 49e4602b-fe63-e5be-edeb-bd99249f4b8b
* Content: [How to request your data move](https://docs.microsoft.com/en-us/office365/enterprise/request-your-data-move)
* Content Source: [Enterprise/request-your-data-move.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/request-your-data-move.md)
* Service: **o365-administration**
* GitHub Login: @andybergen
* Microsoft Alias: **andyber**

**Comment by andybergen** [comment]
We cannot share tentative dates, sorry.  When the program timelines are firm for German tenants we will post guidance at this site and communicate directly to eligible tenants via Message Center.

**Comment by newsgrep** [comment]
The current docs say: "You'll also have a confirmation message in your message center. This confirms that you have successfully requested a move._"

So just add something like: 
"When the program timelines for tenants in your country are firm we will post this at this site and communicate also directly to eligible tenants via Message Center."

So that every one knows he/she will receive a msg when it is time to apply for the change. 

Sry for reopening, my fault. You can close issue if you like.
