### ISSUE TITLE
NO movement 2022 or 2020

### ISSUE THREAD

**Issue by newsgrep** [MicrosoftDocs/OfficeDocs-Enterprise#897]
Are you sure the Date in the table for Norway is 30 October 2022?
Also have a look at the screenshot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 756e6a9b-289c-6ef9-bf79-e36e32e12a98
* Version Independent ID: 49e4602b-fe63-e5be-edeb-bd99249f4b8b
* Content: [How to request your data move](https://docs.microsoft.com/en-us/office365/enterprise/request-your-data-move)
* Content Source: [Enterprise/request-your-data-move.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/request-your-data-move.md)
* Service: **o365-administration**
* GitHub Login: @andybergen
* Microsoft Alias: **andyber**

**Comment by andybergen** [comment]
Correct.  Eligible customers with a NO signup address can opt-in for migration through the end of October 2020.  Migrations for all eligible workloads will complete by the end of October, 2022.
