### ISSUE TITLE
when was my tenant created?

### ISSUE THREAD

**Issue by newsgrep** [MicrosoftDocs/OfficeDocs-Enterprise#898]
Please add an information how I can find out the creation date of my a tenant. 
So that I can find out if the informationen on this page applies to my tenant.

`The information on this page only applies to customers who had existing Microsoft 365 tenants before the new datacenters in their geo launched.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 756e6a9b-289c-6ef9-bf79-e36e32e12a98
* Version Independent ID: 49e4602b-fe63-e5be-edeb-bd99249f4b8b
* Content: [How to request your data move](https://docs.microsoft.com/en-us/office365/enterprise/request-your-data-move)
* Content Source: [Enterprise/request-your-data-move.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/request-your-data-move.md)
* Service: **o365-administration**
* GitHub Login: @andybergen
* Microsoft Alias: **andyber**

**Comment by andybergen** [comment]
Migration eligibility depends on the specific workload provisioning date, so tenant creation date may not always be the single date that matters.  The tenant could have been created with just Exchange and then added on OneDrive for Business and Teams later on.

Admins can see subscription info in Admin in Billing / Your Products.  

This all comes out in the wash via Data Location in Admin.  If the service you want to move from region to local shows in the region + your country is eligible + the opt-in period is open then it will move if the admin opts-in for migration.

**Comment by newsgrep** [comment]
please add this information to the documentation.
________________________________
Von: andybergen <notifications@github.com>
Gesendet: Montag, 8. Juni 2020 17:38
An: MicrosoftDocs/OfficeDocs-Enterprise <OfficeDocs-Enterprise@noreply.github.com>
Cc: newsgrep <newsgrep@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [MicrosoftDocs/OfficeDocs-Enterprise] when was my tenant created? (#898)


Migration eligibility depends on the specific workload provisioning date, so tenant creation date may not always be the single date that matters. The tenant could have been created with just Exchange and then added on OneDrive for Business and Teams later on.

Admins can see subscription info in Admin in Billing / Your Products.

This all comes out in the wash via Data Location in Admin. If the service you want to move from region to local shows in the region + your country is eligible + the opt-in period is open then it will move if the admin opts-in for migration.

**Comment by msbemba** [comment]
@newsgrep  Thank you for your feedback. As Andy suggested, Migration eligibility depends on the specific workload provisioning date, so tenant creation date may not always be the single date that matters. I have added that to the note via PR#https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/951

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @newsgrep Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
