### ISSUE TITLE
some cities are missing

### ISSUE THREAD

**Issue by newsgrep** [MicrosoftDocs/OfficeDocs-Enterprise#899]
Add the cities for Finland, Ireland, Netherlands, Austria in this table:

https://docs.microsoft.com/de-de/office365/enterprise/o365-data-locations#countryregion-specific-data-center-city-locations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d4d59d-d7b1-81b1-aeaf-6d34f61ae18b
* Version Independent ID: 2b2620fa-7e4f-27ee-2655-47da2391296f
* Content: [Office 365 data locations](https://docs.microsoft.com/en-us/office365/enterprise/o365-data-locations#countryregion-specific-data-center-city-locations)
* Content Source: [Enterprise/o365-data-locations.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/o365-data-locations.md)
* Service: **o365-solutions**
* GitHub Login: @dmwmsft
* Microsoft Alias: **deanw**

**Comment by dmwmsft** [comment]
Thank you for the input.  These updates have been made.

**Comment by mypil** [comment]
@newsgrep - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author @dmwmsft so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
