### ISSUE TITLE
Lacks visual appeal and flow

### ISSUE THREAD

**Issue by stefshap** [MicrosoftDocs/OfficeDocs-Enterprise#90]
As someone has been in multiple compromise situations, this document does not flow well. It needs screen shots and a greater visual appeal for all types of users. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04d540fc-67c0-86ea-7bcb-9a08cdc52e1b
* Version Independent ID: 022eebfd-370d-7b8b-1a26-81d0dfb0aae7
* Content: [Responding to a Compromised Email Account in Office 365](https://docs.microsoft.com/en-us/office365/enterprise/responding-to-a-compromised-email-account#feedback)
* Content Source: [Enterprise/responding-to-a-compromised-email-account.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/responding-to-a-compromised-email-account.md)
* Service: **o365-solutions**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Thanks for the feedback. There is a video embedded and given that this is a fast turn around topic for deflection, additional revisions will be considered later.
