### ISSUE TITLE
"South Korea" or "Korea"

### ISSUE THREAD

**Issue by newsgrep** [MicrosoftDocs/OfficeDocs-Enterprise#900]
please decide, for all the documentation, if you would like to call it "South Korea" or "Korea". 

As an example:
https://docs.microsoft.com/en-us/office365/enterprise/request-your-data-move

https://docs.microsoft.com/en-us/office365/enterprise/o365-data-locations#countryregion-specific-data-center-city-locations

I would recommend to call it "South Korea"
You may also have a look here:
https://www.nationsonline.org/oneworld/country_code_list.htm#K
https://www.cia.gov/library/publications/the-world-factbook/appendix/appendix-d.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d4d59d-d7b1-81b1-aeaf-6d34f61ae18b
* Version Independent ID: 2b2620fa-7e4f-27ee-2655-47da2391296f
* Content: [Office 365 data locations](https://docs.microsoft.com/en-us/office365/enterprise/o365-data-locations#countryregion-specific-data-center-city-locations)
* Content Source: [Enterprise/o365-data-locations.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/o365-data-locations.md)
* Service: **o365-solutions**
* GitHub Login: @dmwmsft
* Microsoft Alias: **deanw**

**Comment by dmwmsft** [comment]
Thank you for the input.  This has been updated.

**Comment by mypil** [comment]
@dmwmsft - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author @dmwmsft so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
