### ISSUE TITLE
https://aka.ms/o365networkconnectivity is a 404

### ISSUE THREAD

**Issue by mcc-ah** [MicrosoftDocs/OfficeDocs-Enterprise#904]
[Enter feedback here]

The link to https://aka.ms/o365networkconnectivity goes to a 404 page https://docs.microsoft.com/en-gb/office365/enterprise/network-connectivity?redirectSourcePath=%252fen-us%252farticle%252fNetwork-connectivity-to-Office-365-64b420ef-0218-48f6-8a34-74bb27633b10.
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bfcc4e9-0782-ba4b-929f-a77ec789bb33
* Version Independent ID: 0c38b2f3-970c-eb3a-7c70-2ed150fa9ba8
* Content: [Assessing Office 365 network connectivity](https://docs.microsoft.com/en-gb/office365/enterprise/assessing-network-connectivity#the-microsoft-365-connectivity-test)
* Content Source: [Enterprise/assessing-network-connectivity.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/assessing-network-connectivity.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by JoeDavies-MSFT** [comment]
@mcc-ah This has been corrected. Sorry for the delay. Thanks so much for letting us know.
