### ISSUE TITLE
URLs from ActiveSync/AutoDiscover Virtual Directories

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Enterprise#913]
Hello,

I've noticed that in the **Add on-premises web service URLs as SPNs in Azure AD** section, we get URLs from virtual directories: MAPI, EWS, OAB, _ActiveSync_.  But then later in the **Verify Virtual Directories are Properly Configured** section, we confirm OAuth settings in virtual directories MAPI, EWS, OAB, and _Autodiscover_.

I'm wondering, do we need to:

A) In the first step, also get our Autodiscover SCP URi's (i.e. Get-ClientAccessServer | fl Name, AutodiscoverServiceInternalUri), and make sure that URL is added to our Azure AD Service Principal's SPN's?

B) In the second step, is there anything we need to worry about with ActiveSync virtual directories' authentication settings?  I'm thinking no, because Outlook app won't use that, but then I wonder, did we really need to get the ActiveSync URL's in the first step at this rate?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba93584-38f6-bc46-9784-c14492de8f75
* Version Independent ID: 2fc5806d-bc80-9cc4-a051-1a9f16322c8d
* Content: [How to configure Exchange Server on-premises to use Hybrid Modern Authentication](https://docs.microsoft.com/en-us/office365/enterprise/configure-exchange-server-for-hybrid-modern-authentication)
* Content Source: [Enterprise/configure-exchange-server-for-hybrid-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/configure-exchange-server-for-hybrid-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@JeremyTBradshaw Thank you for the feedback. Agree with you, I have updated the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/957. Once the author verifies and approves this, the document will be updated.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @JeremyTBradshaw 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
