### ISSUE TITLE
About Office 365 URLs and IP address ranges

### ISSUE THREAD

**Issue by misuwama** [MicrosoftDocs/OfficeDocs-Enterprise#916]
Hi,

It seems like the information below is missing from the URL/IP address range. Is it possible to add this information?

------------------------------------------------
To get a video feed for an External app or device produced live event sent to Microsoft Stream from your encoder you'll need the following IP ranges and ports open in your network's firewall or proxy:

Domains: *.channel.media.azure.net
Ports: 1935/2935/1936/2936 (for RTMP and RTMPS)

https://docs.microsoft.com/en-us/stream/network-overview#endpoints-that-need-to-be-reachable-by-users-inside-your-network
------------------------------------------------

Regards, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#microsoft-365-common-and-office-online)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@misuwama The "*.channel.media.azure.net" domain name is included with the "*.media.azure.net" endpoint in ID 44 of the "Microsoft 365 Common and Office Online" section (https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#microsoft-365-common-and-office-online). Thanks for your question.

**Comment by misuwama** [comment]
@JoeDavies-MSFT Thank you for your reply. I confirmed that  ".media.azure.net" is on the list, but I could not find the "Ports: 1935/2935/1936/2936 (for RTMP and RTMPS)" information. Is this listed somewhere as well? 
Thank you,
