### ISSUE TITLE
Whether 13.107.42.23 should be in the SFB online & Teams IP range

### ISSUE THREAD

**Issue by Kurosawa-Dia** [MicrosoftDocs/OfficeDocs-Enterprise#917]
Hi team, could you please help to verify if 13.107.42.23 is within the range of SFB online and Teams? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Kurosawa-Dia This IP address could be for a Default category URL, in which case we do not list all of the corresponding IP addresses. Please see https://techcommunity.microsoft.com/t5/office-365-networking/why-are-some-office-365-network-endpoints-provided-as-urls-only/m-p/310490#M97 for more information. Thanks for your question.
