### ISSUE TITLE
onedrive.live.com is missing?

### ISSUE THREAD

**Issue by meitalna** [MicrosoftDocs/OfficeDocs-Enterprise#918]
Hi,

Why onedrive.live.com doesn't appear in O365 IP ranges / domains feed?

Thanks,
Meital

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@meitalna I have passed your question on to the product team who maintains these endpoints for their consideration in a future update. Thanks for your question.
