### ISSUE TITLE
Adding license when it should remove license?

### ISSUE THREAD

**Issue by p0shkar** [MicrosoftDocs/OfficeDocs-Enterprise#920]
> $userUPN="<user sign-in name (UPN)>"
> $planName="< license plan name from the list of license plans>"
> $license = New-Object -TypeName Microsoft.Open.AzureAD.Model.AssignedLicense
> $licenses = New-Object -TypeName Microsoft.Open.AzureAD.Model.AssignedLicenses
> $license.SkuId = (Get-AzureADSubscribedSku | Where-Object -Property SkuPartNumber -Value $planName -EQ).SkuID
> $licenses.AddLicenses = $license
> Set-AzureADUserLicense -ObjectId $userUPN -AssignedLicenses $licenses
> $Licenses.AddLicenses = @()
> $Licenses.RemoveLicenses =  (Get-AzureADSubscribedSku | Where-Object -Property SkuPartNumber -Value $planName -EQ).SkuID
> Set-AzureADUserLicense -ObjectId $userUPN -AssignedLicenses $licenses

This code seems to be unnecessarily long, and incorrect for the purpose of the article.
The Title is "Remove licenses from user accounts with Office 365 PowerShell", so why does the code first add the license and then removes it?

This code seems to add the license:
> $license = New-Object -TypeName Microsoft.Open.AzureAD.Model.AssignedLicense
> $licenses = New-Object -TypeName Microsoft.Open.AzureAD.Model.AssignedLicenses
> $license.SkuId = (Get-AzureADSubscribedSku | Where-Object -Property SkuPartNumber -Value $planName -EQ).SkuID
> $licenses.AddLicenses = $license
> Set-AzureADUserLicense -ObjectId $userUPN -AssignedLicenses $licenses

It seems to me that this would suffice:
> $userUPN="<user sign-in name (UPN)>"
> $planName="< license plan name from the list of license plans>"
> $license = New-Object -TypeName Microsoft.Open.AzureAD.Model.AssignedLicenses
> $License.RemoveLicenses =  (Get-AzureADSubscribedSku | Where-Object -Property SkuPartNumber -Value $planName -EQ).SkuID
> Set-AzureADUserLicense -ObjectId $userUPN -AssignedLicenses $license

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90144912-28c3-e215-7763-12beddc645c7
* Version Independent ID: c2aa496c-51d4-ffd9-9b06-e3a7097d027a
* Content: [Remove licenses from user accounts with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell)
* Content Source: [Enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/remove-licenses-from-user-accounts-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@p0shkar You are correct. I have validated your code and updated the article with it. Thanks so much for letting us know.
