### ISSUE TITLE
Microsoft Online Services Sign-in Assistant still required on modern operating systems?

### ISSUE THREAD

**Issue by amandeepmand** [MicrosoftDocs/OfficeDocs-Enterprise#922]
Under Install Required Software section, the first instruction asks to "Install the 64-bit version of the Microsoft Online Services Sign-in Assistant: Microsoft Online Services Sign-in Assistant for IT Professionals RTW."

Is this still required for modern Operating Systems (i.e. Windows 10)? It appears the PS Module works fine without installing this service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@amandeepmand I verified this on a Windows 10 machine and modified the content to ship the install of the Microsoft Online Services Sign-in Assistant module for Windows 10. Thanks for letting us know.
