### ISSUE TITLE
URLs for MCAS missing

### ISSUE THREAD

**Issue by jpawlowski** [MicrosoftDocs/OfficeDocs-Enterprise#923]
Hi team,

during our implementation of MCAS policies, we recognized that `*.cas.ms` is not mentioned here in any way. However, this info was required for us to successfully implement firewall policies and to prevent SSL deep inspection within our environment.

It also seems that the domain is not part of the JSON file provided by the Microsoft API.
Not sure this is intentionally but I think it is an important part missing here.

May I ask you to consider updating this documentation page and ask the network product group to discuss if the Office 365 Endpoints API should be updated for MCAS?

Thanks,
Julian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@jpawlowski I will forward this request on to the product teams for their consideration to add it to this article or an article that is focused on Azure services. Thanks for letting us know.
