### ISSUE TITLE
Please update ADFS

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-Enterprise#925]
Hi folks,

The proper terms is AD FS.  Note the space.  Can this page be updated please? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626caf29-7e88-0b56-2013-5c5b7c2a5917
* Version Independent ID: 2376192f-793d-0166-46c7-870cd0c41abb
* Content: [Hybrid Modern Authentication overview and prerequisites for use with on-premises Skype for Business and Exchange servers](https://docs.microsoft.com/en-us/office365/enterprise/hybrid-modern-auth-overview)
* Content Source: [Enterprise/hybrid-modern-auth-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/hybrid-modern-auth-overview.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@r-milne Thank you for your feedback. We have updated doc via PR#https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/946

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @r-milne Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
