### ISSUE TITLE
Yammer missing

### ISSUE THREAD

**Issue by TeodoraI** [MicrosoftDocs/OfficeDocs-Enterprise#926]
Yammer is missing from the list of services.

Here is what I believe needs to be added:
Yammer
Yammer created for the satellite location will use the end point located in the central location for the tenant. Yammer is not a Multi-Geo service.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194b008d-099c-583e-55fc-af47877ca8f9
* Version Independent ID: 129b03d5-c287-2dd4-01ed-c513eee91590
* Content: [Administering a multi-geo environment](https://docs.microsoft.com/en-CA/office365/enterprise/administering-a-multi-geo-environment)
* Content Source: [Enterprise/administering-a-multi-geo-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/administering-a-multi-geo-environment.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@TeodoraI Thank you for your feedback. We have made changes to the doc via PR#https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/947

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @TeodoraI Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
