### ISSUE TITLE
The compliance centre is replacing the one in the exchange admin centre by the end of the month

### ISSUE THREAD

**Issue by contactbrenton** [MicrosoftDocs/OfficeDocs-Enterprise#927]
The compliance centre is replacing the one in the exchange admin centre by the end of the month
https://compliance.microsoft.com/homepage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39aa0813-6d11-cf85-b3d0-9f068c1ba5e7
* Version Independent ID: a92e5228-5ddf-84f2-d695-3076cee03159
* Content: [Recover deleted items in a user mailbox - Admin Help](https://docs.microsoft.com/en-us/office365/enterprise/recover-deleted-items-in-a-mailbox)
* Content Source: [Enterprise/recover-deleted-items-in-a-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/recover-deleted-items-in-a-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@contactbrenton This has been added to the list of updates to make at the end of this month when the replacement takes place. Thanks for letting us know.
