### ISSUE TITLE
New IP ranges?

### ISSUE THREAD

**Issue by danielscott1709** [MicrosoftDocs/OfficeDocs-Enterprise#928]
Hi

It looks like there are new IPs ranges as our firewalls (cannot do URL filtering) is blocking Exchange 2016 to M365 EWS traffic using the IPs :

52.109.32.27
52.109.76.6
52.109.32.27
52.109.88.8
40.67.254.36

However, i cannot see these ranges in the article, so we cannot see the CIDR notation to cover the range.

Please can you update this ASAP?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
The addresses starting with 52.109 are included in the 52.108.0.0/14 range in ID 46. The 40.67.254.36 could be for a URL for which we don't list the IP addresses. See https://techcommunity.microsoft.com/t5/Office-365-Networking/Why-are-some-Office-365-network-endpoints-provided-as-URLs-only/m-p/310490#M97 for the details.

**Comment by JoeDavies-MSFT** [comment]
@danielscott1709 Adding your name. Please see previous comment. Thanks

**Comment by msbemba** [comment]
@danielscott1709 Thank you for your feedback. As Joe mentioned, The IP's staring with 52.109 are included in the 52.108.0.0/14 range in ID 46.

The 40.67.254.36 could be for a URL for which we don't list the IP addresses. Reference Document https://techcommunity.microsoft.com/t5/Office-365-Networking/Why-are-some-Office-365-network-endpoints-provided-as-URLs-only/m-p/310490#M97  for more details.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @danielscott1709 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
