### ISSUE TITLE
SfB Online uses 50000-59999 ports from client side to the service for ScreenSharing sessions. This information doesn't reflected in the documentation related to O365 IP Ranges and to identify that you need to go into Optimizing your network docs to find it. Why?

### ISSUE THREAD

**Issue by stasfeelin** [MicrosoftDocs/OfficeDocs-Enterprise#929]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@stasfeelin The endpoints listed in the article are only for server-side ports as the destination for outbound, initiated traffic by the client. These endpoints must be allowed by your edge devices for successful connectivity. The client-side 50000-59999 ports are dynamically assigned by the TCP/IP stack as a destination for inbound, return traffic to the client, and are therefore not listed in the article.

**Comment by stasfeelin** [comment]
If it should be inbound, return traffic to the client, **only** (I assume it from your answer and from that fact that these ports are not included into the document related to outbound traffic only) so why we see outbound traffic from the client to the MSFT server via this dynamic range? And actually our users were experiencing issues with ScreenSharing sessions long time while we tried to find different document where problematic ports are mentioned to open them...
![image](https://user-images.githubusercontent.com/33052570/87278365-f2059700-c4ec-11ea-8e8d-035f7deb2331.png)
