### ISSUE TITLE
Need more information for Office 365 Multi-Geo capabilities for SharePoint

### ISSUE THREAD

**Issue by dipesh-wadhwa** [MicrosoftDocs/OfficeDocs-Enterprise#931]
Is it possible to create sub-site in different GEO location?

For Ex: https://consto.sharepoint.com/ is our tenant located in India.
https://consto.sharepoint.com/sites/HR is site collection again located in India.
https://consto.sharepoint.com/sites/HR/subsitedemo => Can we create sub-site under HR site collection which is stored in United States (Other geo location)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f3a2c9-0399-218d-cf9a-eb0f16fcbbb0
* Version Independent ID: da6ada6e-ce41-f772-74b8-144cf540d423
* Content: [Multi-Geo Capabilities in OneDrive and SharePoint Online](https://docs.microsoft.com/en-us/office365/enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365)
* Content Source: [Enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-office-365.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dipesh-wadhwa** [comment]
@yogkumgit any update?

**Comment by msbemba** [comment]
@dipesh-wadhwa Thank you for your feedback. As of now, the Subsites will have to be located in the same geo as the site collection. 

We will update the document when the option of creating a subsite on different geo is available.

Hope this helps!

Thanks
Sri

**Comment by dipesh-wadhwa** [comment]
Thanks @msbemba
