### ISSUE TITLE
how do I view Office Licensing Service activation per user?

### ISSUE THREAD

**Issue by mars-wilson** [MicrosoftDocs/OfficeDocs-Enterprise#933]
I'm wondering how I can view a user's count of devices that they've actually installed Office on.

Is the Office Licensing Service status available through the MSOL suite?

(Trying to identify users that are not actually using their Office license)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f403603f-e17b-8b5b-cbd8-8e4c6f4e1728
* Version Independent ID: a93a3de1-25d3-4f7a-3e3e-3a6f25f88b75
* Content: [View account license and service details with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-account-license-and-service-details-with-office-365-powershell)
* Content Source: [Enterprise/powershell/view-account-license-and-service-details-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/view-account-license-and-service-details-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@mars-wilson Unfortunately, there is no way to display the number of devices on which a user has installed Office with PowerShell.
