### ISSUE TITLE
How long is "until-revoked"

### ISSUE THREAD

**Issue by adrwh** [MicrosoftDocs/OfficeDocs-Enterprise#934]
Hi does the following sentence imply that a user can maintain a valid access token "forever" as long as they remain active and the token is not revoked by an admin or password reset action?

"Refresh tokens are valid for 90 days, and with continuous use, they can be valid until revoked."

1. Is it technically possible to configure a token to never expire as long as there is ongoing activity?
2. Is it technically possible for a user to never have to login again as long as there is ongoing activity?

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @adrwh Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
