### ISSUE TITLE
"myaccount.microsoft.com" is required.

### ISSUE THREAD

**Issue by hmuchaku** [MicrosoftDocs/OfficeDocs-Enterprise#935]
"My Account" of Office365 URL has changed from "portal.office.com" to "myaccount.microsoft.com".
However, "myaccount.microsoft.com" is not listed in the following url and web services. 

https://docs.microsoft.com/ja-jp/office365/enterprise/urls-and-ip-address-ranges

"myaccount.microsoft.com" should be listed as "required : true".

**Comment by JoeDavies-MSFT** [comment]
@hmuchaku I have passed your request to the team that manages the Microsoft 365 Common and Office Online endpoints for their consideration in a future update. Thanks so much for letting us know.
