### ISSUE TITLE
DNS Required for Teams

### ISSUE THREAD

**Issue by ArneshAZAdmin** [MicrosoftDocs/OfficeDocs-Enterprise#936]
In the article you have mentioned this document applies for Hybrid Teams and Skype for Business Online?

What is Hybrid Teams?  When did Microsoft come up with a On-Prem solution?

Is this required for 1:1 Teams Chat between two teams only tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e27e942-5c6d-591e-14c4-40d44d90422c
* Version Independent ID: 5e92f544-cae1-9d31-0c9a-253a7e76b73f
* Content: [External Domain Name System records for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/external-domain-name-system-records)
* Content Source: [Enterprise/external-domain-name-system-records.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/external-domain-name-system-records.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@ArneshAZAdmin Thank you for your feedback. We have corrected the note to reflect Hybrid Teams and Skype For business on prem scenario. This can be tracked via PR# https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/948

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @ArneshAZAdmin 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
