### ISSUE TITLE
Procedure for CSP Partners (i.e. Delegated Access)?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Enterprise#94]
Hello,

I see there are procedures that have been added for Azure AD and Exchange Online PowerShell for CSP partners to connect to customers' tenants but I don't see anything for Skype for Business Online PowerShell.  Will this be added?

Thanks in advance.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f318af5-7da8-daec-d038-7bca3d4cabf8
* Version Independent ID: 7cb9bf9d-5b01-7cbd-fa54-cb9847b61fc2
* Content: [Manage Skype for Business Online with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell)
* Content Source: [Enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
@JeremyTBradshaw, good question. We're looking into this.

**Comment by kenwith** [comment]
@JeremyTBradshaw - thank you for reporting. We were able to get this added to our Product Backlog for Skype documentation and I will work to get this prioritized in an upcoming sprint. Thanks for taking the time to make the docs better!

**Comment by bchris999** [comment]
Almost 2 years later, any progress on this?

**Comment by JoeDavies-MSFT** [comment]
Assigning to kenwith for input.

**Comment by kenwith** [comment]
@bchris999 - I am looking into this question in regards to Teams. Doing some research I found this article: https://docs.microsoft.com/en-us/microsoft-365/admin/misc/add-partner?view=o365-worldwide and am discussing with @JoeDavies-MSFT and @Sirkkuw if we need more information for Teams specifically. Our initial thinking is that a partner with these permissions could do anything a global admin could do.. is this your understanding as well? Do you see anything you think should be called out for Teams and PowerShell around CSP Partners?
