### ISSUE TITLE
Generated PAC File sample is not updated

### ISSUE THREAD

**Issue by eeha0120** [MicrosoftDocs/OfficeDocs-Enterprise#940]
Hi.

The generated PAC File sample is missing several URLs required at least by Teams App.

The following URLs are still processed by a PROXY using the generated PAC Sample when attempting to login to Teams, resulting in really slow times or even being unable to login at all with Teams:

geo.prod.do.dsp.mp.microsoft.com
disc601.prod.do.dsp.mp.microsoft.com
settings-win.data.microsoft.com
v10.events.data.microsoft.com
kv601.prod.do.dsp.mp.microsoft.com
geover.prod.do.dsp.mp.microsoft.com
teams.events.data.microsoft.com
mobile.pipe.aria.microsoft.com
api.flightproxy.teams.microsoft.com
statics.teams.cdn.office.net
api.cc.skype.com
config.teams.microsoft.com
us-api.asm.skype.com
array612.prod.do.dsp.mp.microsoft.com
login.live.com
tsfe.trafficshaping.dsp.mp.microsoft.com
cp601.prod.do.dsp.mp.microsoft.com
watson.telemetry.microsoft.com

Is this the expected behavior ? 

It was just downloaded and tested.

Command line ran was:
Get-PacFile -Type 2 -Instance Worldwide -ClientRequestId b10c5ed1-bad1-445f-b386-b919946339a7

And it was also tested with the Tenant from a customer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8762d73c-32fc-a4f9-162a-b81ae4052ea3
* Version Independent ID: 554cc99d-b929-8db0-7ab7-0f666438e8cf
* Content: [Managing Office 365 endpoints](https://docs.microsoft.com/en-us/office365/enterprise/managing-office-365-endpoints#pacfiles)
* Content Source: [Enterprise/managing-office-365-endpoints.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/managing-office-365-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@eeha0120 Only network endpoints that are required for Office 365 functionality are published. There may be connections attempted by Office 365 clients to other FQDNs that are not required. To answer your question, yes, this is expected behavior. The  Get-PacFile script gets the latest set of published endpoints that are required for Office 365 functionality. Thanks for your question.
