### ISSUE TITLE
Looks like doc forgetting about AutoD and Anywhere URLs

### ISSUE THREAD

**Issue by Rodrigo30Horas** [MicrosoftDocs/OfficeDocs-Enterprise#942]
Although doc ask admin to add all URLs and provides the cmdlets for EWS, MAPIoverHTTP and so on, it fails to inform that admins will need to add autodiscover and Anywhere (RPCoverHTTP) as well in the step "Add on-premises web service URLs as SPNs in Azure AD"

Regards,
Rodrigo Dias

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba93584-38f6-bc46-9784-c14492de8f75
* Version Independent ID: 2fc5806d-bc80-9cc4-a051-1a9f16322c8d
* Content: [How to configure Exchange Server on-premises to use Hybrid Modern Authentication](https://docs.microsoft.com/en-us/office365/enterprise/configure-exchange-server-for-hybrid-modern-authentication)
* Content Source: [Enterprise/configure-exchange-server-for-hybrid-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/configure-exchange-server-for-hybrid-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@Rodrigo30Horas  Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/952

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @Rodrigo30Horas Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
