### ISSUE TITLE
Add New SPO Admin URL to Office 365 URLs Doc.

### ISSUE THREAD

**Issue by DanielOp** [MicrosoftDocs/OfficeDocs-Enterprise#943]
SPO ADMIN CENTER NEW URL
Current <tenant>.sharepoint.com
Change <tenant>-admin.sharepoint.com, <tenant>
Or 
Add *.sharepoint.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges#sharepoint-online-and-onedrive-for-business)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@DanielOp I have forwarded your request to the team that maintains these endpoints for investigation and inclusion in a future update. Thanks for letting us know.
