### ISSUE TITLE
Typo: there is a space missing in a sentence

### ISSUE THREAD

**Issue by cqueern** [MicrosoftDocs/OfficeDocs-Enterprise#945]
Hello Team.

> After you have updated the UPNs to use the verified domain,you are ready

is probably meant to read:

> After you have updated the UPNs to use the verified domain, you are ready

Thanks for your hard work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79589db3-4bf5-e940-0410-75d5f0ff97b8
* Version Independent ID: e7980b96-bab3-981e-2da8-6e1bdde9ba31
* Content: [Prepare a non-routable domain for directory synchronization](https://docs.microsoft.com/en-us/office365/enterprise/prepare-a-non-routable-domain-for-directory-synchronization)
* Content Source: [Enterprise/prepare-a-non-routable-domain-for-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/prepare-a-non-routable-domain-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@cqueern I have this fix in the publishing process and will close this issue when it is live. Thanks so much for letting us know.

**Comment by JoeDavies-MSFT** [comment]
@cqueern This has been corrected and published. Thanks again.
