### ISSUE TITLE
72 hours notation needed.

### ISSUE THREAD

**Issue by DJ-1701** [MicrosoftDocs/OfficeDocs-Enterprise#953]
I had to preform this command recently, and the article needs to clearly state that this command takes 72 hours before you can turn the service back on if you have to turn it off with this method. I contacted Microsoft Support and found this out after 36 hours of the service being in a `PendingDisabled` state (which you can find out using `(Get-MSOLCompanyInformation).DirectorySynchronizationStatus`) and when trying to start during this time it will refuse ironically stating `Set-MsolDirSyncEnabled : You cannot turn off Active Directory synchronization.`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b245b5d3-be8c-00a5-c373-05eb5d74ff7d
* Version Independent ID: d7020de2-b00a-6a9d-e062-c76052df17f7
* Content: [Turn off directory synchronization for Microsoft 365](https://docs.microsoft.com/en-us/office365/enterprise/turn-off-directory-synchronization)
* Content Source: [Enterprise/turn-off-directory-synchronization.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/turn-off-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@DJ-1701  Thank you for your feedback. The note to wait 72 hours has been added to the document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @DJ-1701 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
