### ISSUE TITLE
Additional detail for email notifications

### ISSUE THREAD

**Issue by dbird03** [MicrosoftDocs/OfficeDocs-Enterprise#954]
This documentation does not specify whether the email settings under **Preferences** are for the _entire tenant_ or _per user_. I tested this in my tenant with a coworker and confirmed it appears to be per user since he did not see my email settings after I saved them.

I would recommend this distinction be made clear in both this documentation and the Preferences menu in the product itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd2a834a-296b-1c7d-7358-6f6a19f8f3c3
* Version Independent ID: 9ab6adbe-c651-d833-f395-64b7cddb2dd2
* Content: [How to check Microsoft 365 service health](https://docs.microsoft.com/en-us/office365/enterprise/view-service-health)
* Content Source: [Enterprise/view-service-health.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/view-service-health.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@dbird03 Thank you for your feedback. That is correct as these settings are for each admin. For more information, please visit https://docs.microsoft.com/en-us/microsoft-365/admin/manage/message-center?view=o365-worldwide#preferences

I have made changes to the document via PR# https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/958

Thanks
Sri

**Comment by dbird03** [comment]
@msbemba Thank you! The link you provided does help clarify the preferences are per user.

I think it would be helpful if that link was added to the **See also** section of the documentation I opened this issue for. Can you add this as well?

**Comment by msbemba** [comment]
@dbird03  I have added that to the See also section via the same Pull request. Thank you for the feedback.

**Comment by dbird03** [comment]
@msbemba Thank you! I just saw your additional commit. I think you accidentally typed a "9" instead of the "(" in the URL. 🙂

**Comment by msbemba** [comment]
> @msbemba Thank you! I just saw your additional commit. I think you accidentally typed a "9" instead of the "(" in the URL. 🙂

Thank you @dbird03. I have made changes accordingly.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dbird03 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
