### ISSUE TITLE
Correct text in opening sentence on Managing Office 365 endpoints

### ISSUE THREAD

**Issue by cliffordkennedy** [MicrosoftDocs/OfficeDocs-Enterprise#955]
Referring to the first paragraph and sentence on the page there is an extra ""to need" that should be removed. Or alternatively re-worked. 

Original text: 
Most enterprise organizations that have multiple office locations and a connecting WAN will need **to need** configuration for Office...

Proposed update: 
Most enterprise organizations that have multiple office locations and a connecting WAN will need configuration for Office...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8762d73c-32fc-a4f9-162a-b81ae4052ea3
* Version Independent ID: 554cc99d-b929-8db0-7ab7-0f666438e8cf
* Content: [Managing Office 365 endpoints](https://docs.microsoft.com/en-us/office365/enterprise/managing-office-365-endpoints)
* Content Source: [Enterprise/managing-office-365-endpoints.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/managing-office-365-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@cliffordkennedy  Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/956

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @cliffordkennedy 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
