### ISSUE TITLE
Instructions incorrect for "Connect with the Microsoft Azure Active Directory Module for Windows PowerShell"

### ISSUE THREAD

**Issue by AMSDatabase** [MicrosoftDocs/OfficeDocs-Enterprise#96]
The instructions for  "Connect with the Microsoft Azure Active Directory Module for Windows PowerShell" are confusing/incorrect. Once the MSOnline Module is installed and you get to Step 2 the commands have to be run sequentially -- run the first command under Line 2:
$UserCredential = Get-Credential
Input your Office 365 credentials in the dialog box and click OK, then run the next command shown in Line 2:
Connect-MsolService -Credential $UserCredential

But this is covered in the next line, Line 3??
It would be much clearer to arrange as follows: install the module, then run $UserCredential = Get-Credential and input your Office 365 credentials and submit, then run the command  Connect-MsolService -Credential $UserCredential, then test using a simple command like Get-MsolUser 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@AMSDatabase You run the two commands together. The second command is run automatically by PowerShell after you enter your credentials. A third step and extra copy-past operation is not needed. Hope this helps.

**Comment by AMSDatabase** [comment]
Nope -- didn't work that way for me. Returned an error.

**Comment by JoeDavies-MSFT** [comment]
@amsdatabase I just tried this and it worked. You have to press Enter for the second command when copying from the code box. What error are you getting?

**Comment by JoeDavies-MSFT** [comment]
@AMSDatabase  The instructions have been rewritten to use only the Connect-MsolService command for both user name/PW and MFA sign-ins.
