### ISSUE TITLE
Dark fiber?

### ISSUE THREAD

**Issue by mattchiodi** [MicrosoftDocs/OfficeDocs-Enterprise#960]
[Enter feedback here]
Your document mentions "traffic is then routed internally to data and service endpoints over Microsoft's ultra-low latency high availability dark fiber." Dark fiber typically references fiber optic cable that has been laid but is not yet active. The wording of this sentence infers that customer traffic is going to be routed over a network that is not yet active. It should say, "high availability fiber."

Cheers!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9ebe7df-558d-69ab-f809-cb58fa50f9af
* Version Independent ID: a934d2cb-cb52-95a4-9d40-bdb796239b93
* Content: [Microsoft 365 Network Connectivity Overview](https://docs.microsoft.com/en-us/office365/enterprise/office-365-networking-overview)
* Content Source: [Enterprise/office-365-networking-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-networking-overview.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by JoeDavies-MSFT** [comment]
@mattchiodi The article has been corrected and published. Thanks so much for letting us know.
