### ISSUE TITLE
URL missing

### ISSUE THREAD

**Issue by kcsportal** [MicrosoftDocs/OfficeDocs-Enterprise#962]
[Enter feedback here]
It seems that my users are being directed to microsoftonline.us, but that site is not listed on this page. Is it a valid Microsoft page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@kcsportal I will pass this request to the team that manages the list of endpoints for their consideration and inclusion in a future update. Thanks so much for letting us know.
