### ISSUE TITLE
Why does the ID Fix tool report on X500 addresses in a Hybrid environment that were added by EX\EXO?

### ISSUE THREAD

**Issue by Patrick-Robbins** [MicrosoftDocs/OfficeDocs-Enterprise#963]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f88534d6-5018-dfdd-f433-be94408798a7
* Version Independent ID: 5450a7e9-250f-f368-069b-521f110f8738
* Content: [Prepare directory attributes for synchronization with Microsoft 365 by using the IdFix tool](https://docs.microsoft.com/en-us/office365/enterprise/prepare-directory-attributes-for-synch-with-idfix)
* Content Source: [Enterprise/prepare-directory-attributes-for-synch-with-idfix.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/prepare-directory-attributes-for-synch-with-idfix.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Patrick-Robbins Please submit this question as an issue here: https://github.com/microsoft/idfix/issues They should be able to help you. Thanks for your question.
