### ISSUE TITLE
Please create a paragraph exclusively for AADConnect

### ISSUE THREAD

**Issue by RobdeJong** [MicrosoftDocs/OfficeDocs-Enterprise#964]
I'm a PM in the Azure AD Connect team. We received earlier guidance from the Office team not to maintain our own documentation for URLs and IP address ranges but instead refer to this document, which is what we are now doing.

We have received feedback from several customers that the collection of URLs and IP address ranges is too broad for them. They want to know only the URLs and IP address ranges they need to open for Azure AD Connect.

My team can provide this information, is this something you can help us with?

Thanks,

Rob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077406d8-bff1-496e-3ea2-b38558fd9355
* Version Independent ID: 57db3dec-2250-2dee-fd1a-ec6656911798
* Content: [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2&source=docs)
* Content Source: [Enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@RobdeJong Taking this request internal to Microsoft with an email thread. Thanks for letting us know.
