### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by mikeparkie** [MicrosoftDocs/OfficeDocs-Enterprise#965]
https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-sharepoint-users-and-groups-with-powershell

Search for: "_replace replace everything within the quotes, including the < and > characters, with the correct names."

and remove the extra "replace"

**Comment by msbemba** [comment]
@mikeparkie Thank you for your feedback. We have fixed the typo in the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/966

Thanks
Sri
