### ISSUE TITLE
An organisation could have multiple domain names

### ISSUE THREAD

**Issue by chazwoza** [MicrosoftDocs/OfficeDocs-Enterprise#97]
You mention the domain name as being the identifying component of an organization... but a tenant may have multiple domain names for different organisations attached to it.

I also think we need a clearer explanation of how the Azure Enrollment, Accounts/Departments etc relate to the tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdf56d0-5b7a-f0df-86c2-14ce1c067514
* Version Independent ID: 76a8737d-8f21-56ae-93f5-5d7942813484
* Content: [Subscriptions, licenses, accounts, and tenants for Microsoft's cloud offerings](https://docs.microsoft.com/en-us/office365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings)
* Content Source: [Enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
@chazwoza, thank you for the feedback. We'll look into this.

**Comment by JoeDavies-MSFT** [comment]
The text has been revised to allow for multiple domain names. Thanks.
