### ISSUE TITLE
Module Name

### ISSUE THREAD

**Issue by JeffBrownTech** [MicrosoftDocs/OfficeDocs-Enterprise#99]
The code examples reference's the older "LyncOnlineConnector" module while the new PowerShell module's name is "SkypeOnlineConnector".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f318af5-7da8-daec-d038-7bca3d4cabf8
* Version Independent ID: 7cb9bf9d-5b01-7cbd-fa54-cb9847b61fc2
* Content: [Manage Skype for Business Online with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell)
* Content Source: [Enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/manage-skype-for-business-online-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
This has been corrected. Thanks for letting us know.
